openapi: 3.0.2
info:
  title: Acuris Entities API
tags:
  - name: entities
    description: Get list of entities
paths:
  /entities:
    get:
      tags:
        - entities
      summary: Get list of entities (with optional filters)
      description: >-
        Returns JSON containing entities matching given filtering criteria set
        (or top ten entities when no filters are provided).
  /entities/{id}:
    get:
      tags:
        - entityById
      summary: Get one entity by its ID
  /entities/hierarchy:
    get:
      tags:
        - entitiesHierarchy
      summary: Get entities hierarchy (with optional filters)
      description: >-
        Returns JSON containing entities matching given filtering criteria set
        (or top ten entities when no filters are 
