info:
  title: Assistant API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /understand/Assistants/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
      summary: Retrieve Assistant
    post:
      description: ''
      tags:
        - Assistants
      summary: Create Assistant
    delete:
      description: ''
      tags:
        - Assistants
      summary: Delete Assistant
  /understand/Assistants/{AssistantSid}/FallbackActions:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Actions
      summary: Retrieve Fallback Actions
    post:
      description: ''
      tags:
        - Actions
      summary: Create Fallback Actions
  /understand/Assistants/{AssistantSid}/InitiationActions:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Actions
      summary: Retrieve Initiation Actions
    post:
      description: ''
      tags:
        - Actions
      summary: Create Initiation Action
  /understand/Assistants/{AssistantSid}/Dialogues/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Dialogue
      summary: Retrieve Dialogue
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Fields/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Fields
      summary: Retrieve Task Field
    delete:
      description: ''
      tags:
        - Fields
      summary: Delete Task Fields
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Fields:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Fields
      summary: Retrieve Task Fields
    post:
      description: ''
      tags:
        - Fields
      summary: Create Task Field
  /understand/Assistants/{AssistantSid}/FieldTypes/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Field Types
      summary: Retrieve Task Field Type
    post:
      description: ''
      tags:
        - Field Types
      summary: Update Task Field Type
    delete:
      description: ''
      tags:
        - Field Types
      summary: Delete Task Field Type
  /understand/Assistants/{AssistantSid}/FieldTypes:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Field Types
      summary: Retrieve Task Field Types
    post:
      description: ''
      tags:
        - Field Types
      summary: Create Task Field Type
  /understand/Assistants/{AssistantSid}/FieldTypes/{FieldTypeSid}/FieldValues/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Field Values
      summary: Retrieve Field Value
    delete:
      description: ''
      tags:
        - Field Values
      summary: Delete Field Value
  /understand/Assistants/{AssistantSid}/FieldTypes/{FieldTypeSid}/FieldValues:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Field Values
      summary: Retrieve Field Values
    post:
      description: ''
      tags:
        - Field Values
      summary: Create Field Value
  /understand/Assistants/{AssistantSid}/ModelBuilds/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Model Build
      summary: Retrieve Model Build
    post:
      description: ''
      tags:
        - Model Build
      summary: Update Model Build
    delete:
      description: ''
      tags:
        - Model Build
      summary: Delete Model Build
  /understand/Assistants/{AssistantSid}/ModelBuilds:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Model Build
      summary: Retrieve Model Builds
    post:
      description: ''
      tags:
        - Model Build
      summary: Create Model Build
  /understand/Assistants/{AssistantSid}/Queries/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Queries
      summary: Retrieve Query
    post:
      description: ''
      tags:
        - Queries
      summary: Update Query
    delete:
      description: ''
      tags:
        - Queries
      summary: Delete Query
  /understand/Assistants/{AssistantSid}/Queries:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Queries
      summary: Retrieve Queries
    post:
      description: ''
      tags:
        - Queries
      summary: Create Query
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Samples/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Samples
      summary: Retrieve Task Sample
    post:
      description: ''
      tags:
        - Samples
      summary: Update Task Sample
    delete:
      description: ''
      tags:
        - Samples
      summary: Delete Task Sample
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Samples:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Samples
      summary: Retrieve Task Samples
    post:
      description: ''
      tags:
        - Samples
      summary: Create Task Sample
  /understand/Assistants/{AssistantSid}/StyleSheet:
    description: 'TODO: Resource-level docs'
    get:
      description: Returns Style sheet JSON object for this Assistant
      tags:
        - Style Sheets
      summary: Retrieve Style Sheet
    post:
      description: >-
        Updates the style sheet for an assistant identified by {AssistantSid} or
        {AssistantUniqueName}.
      tags:
        - Style Sheets
      summary: Create Style Sheet
  /understand/Assistants/{AssistantSid}/Tasks/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Tasks
      summary: Retrieve Task
    post:
      description: ''
      tags:
        - Tasks
      summary: Update Task
    delete:
      description: ''
      tags:
        - Tasks
      summary: Delete Task
  /understand/Assistants/{AssistantSid}/Tasks:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Tasks
      summary: Retrieve Tasks
    post:
      description: ''
      tags:
        - Tasks
      summary: Create Task
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Actions:
    description: 'TODO: Resource-level docs'
    get:
      description: Returns JSON actions for this Task.
      tags:
        - Task Actions
      summary: Retrieve Task Actions
    post:
      description: >-
        Updates the actions of an Task identified by {TaskSid} or
        {TaskUniqueName}.
      tags:
        - Task Actions
      summary: Create Task Action
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Statistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Task Statistics
      summary: Retrieve Task Statistics
tags:
  - name: Dialogue
  - name: Fields
  - name: Field Types
  - name: Field Values
  - name: Model Build
  - name: Queries
  - name: Samples
  - name: Style Sheets
  - name: Tasks
  - name: Task Actions
  - name: Task Statistics
x-maturity:
  - name: Preview
    description: >-
      PLEASE NOTE that this is a Preview product that is subject to change. Use
      it with caution. If you currently do not have developer preview access,
      please contact https://www.twilio.com/help/contact.
