info:
  title: Twilio Intelligence API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v2/Transcripts/{Sid}/Media:
    description: 'TODO: Resource-level docs'
    get:
      description: Get download URLs for media if possible
      tags:
        - Intelligence
        - Transcripts
        - Media
      summary: Retrieve Transcript Media
  /v2/Transcripts/{TranscriptSid}/OperatorResults:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of Operator Results for the given Transcript.
      tags:
        - Intelligence
        - Transcripts
        - Operators
      summary: Retrieve Transcript Operator Results
  /v2/Transcripts/{TranscriptSid}/OperatorResults/{OperatorSid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Operator Result for the given Transcript.
      tags:
        - Intelligence
        - Transcripts
        - Operators
      summary: Retrieve Transcript Operator Result
  /v2/Transcripts/{TranscriptSid}/Sentences:
    description: 'TODO: Resource-level docs'
    get:
      description: Get all Transcript Sentences by TranscriptSid
      tags:
        - Intelligence
        - Transcripts
        - Sentences
      summary: Retrieve Transcript Sentences
  /v2/Services:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Service for the given Account
      tags:
        - Intelligence
        - Services
      summary: Create Service
    get:
      description: Retrieves a list of all Services for an account.
      tags:
        - Intelligence
        - Services
      summary: Retrieve Services
  /v2/Services/{Sid}:
    description: 'TODO: Resource-level docs'
    delete:
      description: Delete a specific Service.
      tags:
        - Intelligence
        - Services
      summary: Delete Service
    get:
      description: Fetch a specific Service.
      tags:
        - Intelligence
        - Services
      summary: Retrieve Service
    post:
      description: Update a specific Service.
      tags:
        - Intelligence
        - Services
      summary: Update Service
  /v2/Transcripts:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Transcript for the service
      tags:
        - Intelligence
        - Transcripts
      summary: Create Transcript
    get:
      description: Retrieve a list of Transcripts for a given service.
      tags:
        - Intelligence
        - Transcripts
      summary: Retrieve Transcripts
  /v2/Transcripts/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Transcript.
      tags:
        - Intelligence
        - Transcripts
      summary: Retrieve Transcript
    delete:
      description: Delete a specific Transcript.
      tags:
        - Intelligence
        - Transcripts
      summary: Delete Transcript
tags:
  - name: Tag
  - name: Intelligence
    description: Needs a description.
  - name: Transcripts
    description: Needs a description.
  - name: Media
    description: Needs a description.
  - name: Operators
    description: Needs a description.
  - name: Sentences
    description: Needs a description.
  - name: Services
    description: Needs a description.
x-maturity:
  - name: Beta
    description: >-
      PLEASE NOTE that this is a Beta product that is subject to change. Use it
      with caution.
