info:
  title: Twilio IP Messaging API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v2/Services/{ServiceSid}/Bindings:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Bindings
      summary: Retrieve Service Bindings
  /v2/Services/{ServiceSid}/Bindings/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Bindings
      summary: Retrieve Service Binding
    delete:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Bindings
      summary: Delete Service Binding
  /v2/Services/{ServiceSid}/Channels/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
      summary: Retrieve Service Channel
    delete:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
      summary: Delete Service Channel
    post:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
      summary: Update Service Channel
  /v2/Services/{ServiceSid}/Channels:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
      summary: Create Service Channel
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
      summary: Retrieve Service Channels
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Webhooks:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Webhooks
      summary: Retrieve Service Channel Webhooks
    post:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Webhooks
      summary: Create Service Channel Webhook
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Webhooks/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Webhooks
      summary: Retrieve Service Channel Webhook
    post:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Webhooks
      summary: Update Service Channel Webhooks
    delete:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Webhooks
      summary: Delete Service Channel Webhook
  /v2/Credentials:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IP Messaging
        - Credentials
      summary: Retrieve Credentials
    post:
      description: ''
      tags:
        - IP Messaging
        - Credentials
      summary: Create Credential
  /v2/Credentials/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IP Messaging
        - Credentials
      summary: Retrieve Credential
    post:
      description: ''
      tags:
        - IP Messaging
        - Credentials
      summary: Update Credential
    delete:
      description: ''
      tags:
        - IP Messaging
        - Credentials
      summary: Delete Credential
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Invites/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Invites
      summary: Retrieve Service Channel Invite
    delete:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Invites
      summary: Delete Service Channel Invite
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Invites:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Invites
      summary: Create Service Channel Invite
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Invites
      summary: Retrieve Service Channel Invites
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Members/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Members
      summary: Retrieve Service Channel Member
    delete:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Members
      summary: Delete Service Channel Member
    post:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Members
      summary: Update Service Channel Member
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Members:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Members
      summary: Create Service Channel Member
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Members
      summary: Retrieve Service Channel Members
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Messages/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Messages
      summary: Retrieve Service Channel Message
    delete:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Messages
      summary: Delete Service Channel Message
    post:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Messages
      summary: Update Service Channel Message
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Messages:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Messages
      summary: Create Service Channel Message
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Messages
      summary: Retrieve Service Channel Messages
  /v2/Services/{ServiceSid}/Roles/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Roles
      summary: Retrieve Service Role
    delete:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Roles
      summary: Delete Service Role
    post:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Roles
      summary: Update Service Role
  /v2/Services/{ServiceSid}/Roles:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Roles
      summary: Create Service Role
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Channels
        - Roles
      summary: Retrieve Service Roles
  /v2/Services/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
      summary: Retrieve Service
    delete:
      description: ''
      tags:
        - IP Messaging
        - Services
      summary: Delete Service
    post:
      description: ''
      tags:
        - IP Messaging
        - Services
      summary: Update Service
  /v2/Services:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - IP Messaging
        - Services
      summary: Create Service
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
      summary: Retrieve Services
  /v2/Services/{ServiceSid}/Users/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Users
      summary: Retrieve Service User
    delete:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Users
      summary: Delete Service User
    post:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Users
      summary: Update Service User
  /v2/Services/{ServiceSid}/Users:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Users
      summary: Create Service User
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Users
      summary: Retrieve Service Users
  /v2/Services/{ServiceSid}/Users/{UserSid}/Bindings:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Users
        - Bindings
      summary: Retrieve Service User Bindings
  /v2/Services/{ServiceSid}/Users/{UserSid}/Bindings/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Users
        - Bindings
      summary: Retrieve Service User Binding
    delete:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Users
        - Bindings
      summary: Delete Service User Binding
  /v2/Services/{ServiceSid}/Users/{UserSid}/Channels:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Users
        - Channels
      summary: Retrieve Service User Channels
  /v2/Services/{ServiceSid}/Users/{UserSid}/Channels/{ChannelSid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Users
        - Channels
      summary: Retrieve Service User Channel
    delete:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Users
        - Channels
      summary: Delete Service User Channel
    post:
      description: ''
      tags:
        - IP Messaging
        - Services
        - Users
        - Channels
      summary: Update Service User Channel
tags:
  - name: IP Messaging
    description: Needs a description.
  - name: Services
    description: Needs a description.
  - name: Bindings
    description: Needs a description.
  - name: Channels
    description: Needs a description.
  - name: Webhooks
    description: Needs a description.
  - name: Cre
    description: Needs a description.
  - name: Credentials
    description: Needs a description.
  - name: Invites
    description: Needs a description.
  - name: Members
    description: Needs a description.
  - name: Message
    description: Needs a description.
  - name: Roles
    description: Needs a description.
  - name: Users
    description: Needs a description.
x-maturity:
  - name: GA
    description: This product is Generally Available.
