info:
  title: Twilio Marketplace API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /marketplace/AvailableAddOns/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch an instance of an Add-on currently available to be installed.
      tags:
        - PreviewMarketplaceAvailableAddOn
      summary: Retrieve Available Add-On
  /marketplace/AvailableAddOns:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of Add-ons currently available to be installed.
      tags:
        - PreviewMarketplaceAvailableAddOn
      summary: Retrieve Available Add-Ons
  /marketplace/AvailableAddOns/{AvailableAddOnSid}/Extensions/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch an instance of an Extension for the Available Add-on.
      tags:
        - PreviewMarketplaceAvailableAddOnExtension
      summary: Retrieve Available Add-On Extension
  /marketplace/AvailableAddOns/{AvailableAddOnSid}/Extensions:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of Extensions for the Available Add-on.
      tags:
        - PreviewMarketplaceAvailableAddOnExtension
      summary: Retrieve Available Add-On Extensions
  /marketplace/InstalledAddOns:
    description: 'TODO: Resource-level docs'
    post:
      description: Install an Add-on for the Account specified.
      tags:
        - PreviewMarketplaceInstalledAddOn
      summary: Create Installed Add-On
    get:
      description: Retrieve a list of Add-ons currently installed on this Account.
      tags:
        - PreviewMarketplaceInstalledAddOn
      summary: Retrieve Installed Add-Ons
  /marketplace/InstalledAddOns/{Sid}:
    description: 'TODO: Resource-level docs'
    delete:
      description: Remove an Add-on installation from your account
      tags:
        - PreviewMarketplaceInstalledAddOn
      summary: Delete Installed Add-On
    get:
      description: Fetch an instance of an Add-on currently installed on this Account.
      tags:
        - PreviewMarketplaceInstalledAddOn
      summary: Retrieve Installed Add-On
    post:
      description: Update an Add-on installation for the Account specified.
      tags:
        - PreviewMarketplaceInstalledAddOn
      summary: Update Installed Add-On
  /marketplace/InstalledAddOns/{InstalledAddOnSid}/Extensions/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch an instance of an Extension for the Installed Add-on.
      tags:
        - PreviewMarketplaceInstalledAddOnExtension
      summary: Retrieve Installed Add-On Extension
    post:
      description: Update an Extension for an Add-on installation.
      tags:
        - PreviewMarketplaceInstalledAddOnExtension
      summary: Create Installed Add-On Extension
  /marketplace/InstalledAddOns/{InstalledAddOnSid}/Extensions:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of Extensions for the Installed Add-on.
      tags:
        - PreviewMarketplaceInstalledAddOnExtension
      summary: Retrieve Installed Add-On Extensions
tags:
  - name: PreviewMarketplaceAvailableAddOn
  - name: PreviewMarketplaceAvailableAddOnExtension
  - name: PreviewMarketplaceInstalledAddOn
  - name: PreviewMarketplaceInstalledAddOnExtension
x-maturity:
  - name: Preview
    description: >-
      PLEASE NOTE that this is a Preview product that is subject to change. Use
      it with caution. If you currently do not have developer preview access,
      please contact https://www.twilio.com/help/contact.
