info:
  title: Twilio Messaging API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Services/{ServiceSid}/AlphaSenders:
    description: >-
      A Messaging Service resource to add, fetch or remove an Alpha Sender ID
      from a Messaging Service.
    post:
      description: ''
      tags:
        - Messaging
        - Services
        - Alpha
        - Senders
      summary: Create Service Alpha Sender
    get:
      description: ''
      tags:
        - Messaging
        - Services
        - Alpha
        - Senders
      summary: Retrieve Service Alpha Senders
  /v1/Services/{ServiceSid}/AlphaSenders/{Sid}:
    description: >-
      A Messaging Service resource to add, fetch or remove an Alpha Sender ID
      from a Messaging Service.
    get:
      description: ''
      tags:
        - Messaging
        - Services
        - Alpha
        - Senders
      summary: Retrieve Service Alpha Sender
    delete:
      description: ''
      tags:
        - Messaging
        - Services
        - Alpha
        - Senders
      summary: Delete Service Alpha Sender
  /v1/a2p/BrandRegistrations/{BrandRegistrationSid}/SmsOtp:
    description: >-
      A Messaging Service resource to retry OTP verification for Sole Proprietor
      Brand Registrations.
    post:
      description: ''
      tags:
        - Messaging
        - Brands
        - Registrations
        - SMS
      summary: Create Brand Registration SMS
  /v1/a2p/BrandRegistrations/{Sid}:
    description: A Messaging Service resource to add and fetch Brand Registrations.
    get:
      description: ''
      tags:
        - Messaging
        - Brands
        - Registrations
        - SMS
      summary: Retrieve Brand Registration
    post:
      description: ''
      tags:
        - Messaging
        - Brands
        - Registrations
        - SMS
      summary: Update Brand Registration
  /v1/a2p/BrandRegistrations:
    description: A Messaging Service resource to add and fetch Brand Registrations.
    get:
      description: ''
      tags:
        - Messaging
        - Brands
        - Registrations
      summary: Retrieve Brand Registrations
    post:
      description: ''
      tags:
        - Messaging
        - Brands
        - Registrations
      summary: Create Brand Registration
  /v1/a2p/BrandRegistrations/{BrandSid}/Vettings:
    description: A Messaging Service resource to add and get Brand Vettings.
    post:
      description: ''
      tags:
        - Messaging
        - Brands
        - Registrations
        - Vettings
      summary: Create Brand Registration Vetting
    get:
      description: ''
      tags:
        - Messaging
        - Brands
        - Registrations
        - Vettings
      summary: Retrieve Brand Registration Vettings
  /v1/a2p/BrandRegistrations/{BrandSid}/Vettings/{BrandVettingSid}:
    description: A Messaging Service resource to add and get Brand Vettings.
    get:
      description: ''
      tags:
        - Messaging
        - Brands
        - Registrations
        - Vettings
      summary: Retrieve Brand Registration Vetting
  /v1/Services/{MessagingServiceSid}/ChannelSenders:
    description: >-
      A Messaging Service resource to read, fetch all Channel Senders associated
      with a Messaging Service.
    get:
      description: ''
      tags:
        - Messaging
        - Services
        - Channels
        - Senders
      summary: Retrieve Service Channel Senders
  /v1/Services/{MessagingServiceSid}/ChannelSenders/{Sid}:
    description: >-
      A Messaging Service resource to read, fetch all Channel Senders associated
      with a Messaging Service.
    get:
      description: ''
      tags:
        - Messaging
        - Services
        - Channels
        - Senders
      summary: Retrieve Service Channel Sender
  /v1/Deactivations:
    description: >-
      A Deactivation resource to retrieve a list of United States phone numbers
      that have been deactivated by mobile carriers on a specific date.
    get:
      description: >-
        Fetch a list of all United States numbers that have been deactivated on
        a specific date.
      tags:
        - Messaging
        - Deactivations
      summary: Retrieve Deactivations
  /v1/LinkShortening/Domains/{DomainSid}/Certificate:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Messaging
        - Link Shortening
        - Domains
        - Certificates
      summary: Create Link Shortening Domain Certificate
    get:
      description: ''
      tags:
        - Messaging
        - Link Shortening
        - Domains
        - Certificates
      summary: Retrieve Link Shortening Domain Certificate
    delete:
      description: ''
      tags:
        - Messaging
        - Link Shortening
        - Domains
        - Certificates
      summary: Create Link Shortening Domain Certificate
  /v1/LinkShortening/Domains/{DomainSid}/Config:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Messaging
        - Link Shortening
        - Domains
        - Configurations
      summary: Create Link Shortening Domain Configuration
    get:
      description: ''
      tags:
        - Messaging
        - Link Shortening
        - Domains
        - Configurations
      summary: Retrieve Link Shortening Domain Configuration
  /v1/LinkShortening/MessagingService/{MessagingServiceSid}/DomainConfig:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Messaging
        - Link Shortening
        - Services
        - Domains
        - Configurations
      summary: Retrieve Link Shortening  Messaging Service Domain Configuration
  /v1/Services/PreregisteredUsa2p:
    description: Resource to associate preregistered campaign with Messaging Service.
    post:
      description: ''
      tags:
        - Messaging
        - Services
        - Pre-Registered
      summary: Create Service Pre-registered USA 2P
  /v1/LinkShortening/Domains/{DomainSid}/MessagingServices/{MessagingServiceSid}:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Messaging
        - Link Shortening
        - Services
        - Domains
      summary: Update Link Shortening Domain Message Service
    delete:
      description: ''
      tags:
        - Messaging
        - Link Shortening
        - Services
        - Domains
      summary: Delete Link Shortening Domain Message Service
  /v1/LinkShortening/MessagingServices/{MessagingServiceSid}/Domain:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Messaging
        - Link Shortening
        - Services
        - Domains
      summary: Retrieve Link Shortening Messaging Service Domain
  /v1/Services/{ServiceSid}/PhoneNumbers:
    description: >-
      A Messaging Service resource to add, fetch or remove phone numbers from a
      Messaging Service.
    post:
      description: ''
      tags:
        - Messaging
        - Services
        - Phone Number
        - Numbers
      summary: Create Service Phone Number
    get:
      description: ''
      tags:
        - Messaging
        - Services
        - Phone Number
        - Numbers
      summary: Retrieve Service Phone Numbers
  /v1/Services/{ServiceSid}/PhoneNumbers/{Sid}:
    description: >-
      A Messaging Service resource to add, fetch or remove phone numbers from a
      Messaging Service.
    delete:
      description: ''
      tags:
        - Messaging
        - Services
        - Phone Number
        - Numbers
      summary: Delete Service Phone Number
    get:
      description: ''
      tags:
        - Messaging
        - Services
        - Phone Number
        - Numbers
      summary: Retrieve Service Phone Numbers
  /v1/Services:
    description: >-
      A Messaging Service resource to create, fetch, update, delete or
      add/remove senders from Messaging Services.
    post:
      description: ''
      tags:
        - Messaging
        - Services
      summary: Create Service
    get:
      description: ''
      tags:
        - Messaging
        - Services
      summary: Retrieve Services
  /v1/Services/{Sid}:
    description: >-
      A Messaging Service resource to create, fetch, update, delete or
      add/remove senders from Messaging Services.
    post:
      description: ''
      tags:
        - Messaging
        - Services
      summary: Update Service
    get:
      description: ''
      tags:
        - Messaging
        - Services
      summary: Retrieve Service
    delete:
      description: ''
      tags:
        - Messaging
        - Services
      summary: Delete Service
  /v1/Services/{ServiceSid}/ShortCodes:
    description: >-
      A Messaging Service resource to add, fetch or remove short code numbers
      from a Messaging Service.
    post:
      description: ''
      tags:
        - Messaging
        - Services
        - Short Codes
      summary: Create Service Short Codes
    get:
      description: ''
      tags:
        - Messaging
        - Services
        - Short Codes
      summary: Retrieve Service Short Codes
  /v1/Services/{ServiceSid}/ShortCodes/{Sid}:
    description: >-
      A Messaging Service resource to add, fetch or remove short code numbers
      from a Messaging Service.
    delete:
      description: ''
      tags:
        - Messaging
        - Services
        - Short Codes
      summary: Delete Service Short Code
    get:
      description: ''
      tags:
        - Messaging
        - Services
        - Short Codes
      summary: Retrieve Service Short Code
  /v1/Tollfree/Verifications/{Sid}:
    description: A Messaging resource to add and fetch Tollfree Verifications.
    get:
      description: ''
      tags:
        - Messaging
        - Toll Free
        - Verifications
      summary: Retrieve Toll Free Verification
    post:
      description: ''
      tags:
        - Messaging
        - Toll Free
        - Verifications
      summary: Update Toll Free Verification
    delete:
      description: ''
      tags:
        - Messaging
        - Toll Free
        - Verifications
      summary: Delete Toll Free Verification
  /v1/Tollfree/Verifications:
    description: A Messaging resource to add and fetch Tollfree Verifications.
    get:
      description: ''
      tags:
        - Messaging
        - Toll Free
        - Verifications
      summary: Retrieve Toll Free Verifications
    post:
      description: ''
      tags:
        - Messaging
        - Toll Free
        - Verifications
      summary: Create Toll Free Verification
  /v1/Services/{MessagingServiceSid}/Compliance/Usa2p:
    description: A service for (fetch/create/delete) A2P Campaign for a Messaging Service
    post:
      description: ''
      tags:
        - Messaging
        - Services
        - Compliance
      summary: Create Service Compliance USA 2P
    get:
      description: ''
      tags:
        - Messaging
        - Services
        - Compliance
      summary: Retrieve Service Compliance USA 2Ps
  /v1/Services/{MessagingServiceSid}/Compliance/Usa2p/{Sid}:
    description: A service for (fetch/create/delete) A2P Campaign for a Messaging Service
    delete:
      description: ''
      tags:
        - Messaging
        - Services
        - Compliance
      summary: Delete Service Compliance USA 2P
    get:
      description: ''
      tags:
        - Messaging
        - Services
        - Compliance
      summary: Retrieve Service Compliance USA 2P
  /v1/Services/{MessagingServiceSid}/Compliance/Usa2p/Usecases:
    description: >-
      Messaging Service Use Case resource. Fetch possible use cases for service.
      The Use Cases API returns an empty list if there is an issue with the
      customer's A2P brand registration. This Brand cannot register any campaign
      use cases. Customers are requested to contact support with their A2P brand
      information.
    get:
      description: ''
      tags:
        - Messaging
        - Services
        - Compliance
        - Use Cases
      summary: Retrieve Service Compliance USA 2P Use Cases
  /v1/Services/Usecases:
    description: Use Case resource. Fetch possible use cases for a Messaging Service.
    get:
      description: ''
      tags:
        - Messaging
        - Services
        - Compliance
        - Use Cases
      summary: Retrieve Service Use Cases
tags:
  - name: Messaging
    description: Needs a description.
  - name: Services
    description: Needs a description.
  - name: Alpha
    description: Needs a description.
  - name: Senders
    description: Needs a description.
  - name: Brand
    description: Needs a description.
  - name: Registrations
    description: Needs a description.
  - name: SMS
    description: Needs a description.
  - name: Vettings
    description: Needs a description.
  - name: Channels
    description: Needs a description.
  - name: Deactivations
    description: Needs a description.
  - name: Link Shortening
    description: Needs a description.
  - name: Domains
    description: Needs a description.
  - name: Certificates
    description: Needs a description.
  - name: Configurations
    description: Needs a description.
  - name: Pre-Registered
    description: Needs a description.
  - name: USA
    description: Needs a description.
  - name: 2P
    description: Needs a description.
  - name: Phone Number
    description: Needs a description.
  - name: Numbers
    description: Needs a description.
  - name: Short Codes
    description: Needs a description.
  - name: Toll Free
    description: Needs a description.
  - name: Verification
    description: Needs a description.
  - name: Verifications
    description: Needs a description.
  - name: Compliance
    description: Needs a description.
  - name: Use Cases
    description: Needs a description.
x-maturity:
  - name: GA
    description: This product is Generally Available.
  - name: Beta
    description: >-
      PLEASE NOTE that this is a Beta product that is subject to change. Use it
      with caution.
