info:
  title: Twilio Microvisor API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Configs:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Configs for an Account.
      tags:
        - Microvisors
        - Accounts
        - Configurations
      summary: Retrieve Configurations
    post:
      description: Create a config for an Account.
      tags:
        - Microvisors
        - Accounts
        - Configurations
      summary: Create Configuration
  /v1/Configs/{Key}:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a Config for an Account.
      tags:
        - Microvisors
        - Accounts
        - Configurations
        - Keys
      summary: Retrieve Configuration
    post:
      description: Update a config for an Account.
      tags:
        - Microvisors
        - Accounts
        - Configurations
        - Keys
      summary: Update Configuration
    delete:
      description: Delete a config for an Account.
      tags:
        - Microvisors
        - Accounts
        - Configurations
        - Keys
      summary: Delete Configuration
  /v1/Secrets:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Secrets for an Account.
      tags:
        - Microvisors
        - Secrets
      summary: Retrieve Secrets
    post:
      description: Create a secret for an Account.
      tags:
        - Microvisors
        - Secrets
      summary: Create Secret
  /v1/Secrets/{Key}:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a Secret for an Account.
      tags:
        - Microvisors
        - Secrets
      summary: Retrieve Secret
    post:
      description: Update a secret for an Account.
      tags:
        - Microvisors
        - Secrets
      summary: Update Secret
    delete:
      description: Delete a secret for an Account.
      tags:
        - Microvisors
        - Secrets
      summary: Delete Secret
  /v1/Apps:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Apps for an Account.
      tags:
        - Microvisors
        - Applications
      summary: Retrieve Applications
  /v1/Apps/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific App.
      tags:
        - Microvisors
        - Applications
      summary: Retrieve Application
    delete:
      description: Delete a specific App.
      tags:
        - Microvisors
        - Applications
      summary: Delete Application
  /v1/Apps/{AppSid}/Manifest:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve the Manifest for an App.
      tags:
        - Microvisors
        - Applications
        - Manifests
      summary: Retrieve Application Manifest
  /v1/Devices:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Devices registered with the Account.
      tags:
        - Microvisors
        - Devices
      summary: Retrieve Devices
  /v1/Devices/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Device.
      tags:
        - Microvisors
        - Devices
      summary: Retrieve Device
    post:
      description: Update a specific Device.
      tags:
        - Microvisors
        - Devices
      summary: Update Device
  /v1/Devices/{DeviceSid}/Configs:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Configs for a Device.
      tags:
        - Microvisors
        - Devices
        - Configurations
      summary: Retrieve Device Configurations
    post:
      description: Create a config for a Microvisor Device.
      tags:
        - Microvisors
        - Devices
        - Configurations
      summary: Create Device Configuration
  /v1/Devices/{DeviceSid}/Configs/{Key}:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a Config for a Device.
      tags:
        - Microvisors
        - Devices
        - Configurations
        - Keys
      summary: Retrieve Device Configuration
    post:
      description: Update a config for a Microvisor Device.
      tags:
        - Microvisors
        - Devices
        - Configurations
        - Keys
      summary: Update Device Configuration
    delete:
      description: Delete a config for a Microvisor Device.
      tags:
        - Microvisors
        - Devices
        - Configurations
        - Keys
      summary: Delete Device Configuration
  /v1/Devices/{DeviceSid}/Secrets:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Secrets for a Device.
      tags:
        - Microvisors
        - Devices
        - Secrets
      summary: Retrieve Device Secrets
    post:
      description: Create a secret for a Microvisor Device.
      tags:
        - Microvisors
        - Devices
        - Secrets
      summary: Create Device Secret
  /v1/Devices/{DeviceSid}/Secrets/{Key}:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a Secret for a Device.
      tags:
        - Microvisors
        - Devices
        - Secrets
      summary: Retrieve Device Secret
    post:
      description: Update a secret for a Microvisor Device.
      tags:
        - Microvisors
        - Devices
        - Secrets
      summary: Update Device Secret
    delete:
      description: Delete a secret for a Microvisor Device.
      tags:
        - Microvisors
        - Devices
        - Secrets
      summary: Delete Device Secret
tags:
  - name: Test
  - name: Microvisors
    description: Needs a description.
  - name: Accounts
    description: Needs a description.
  - name: Configurations
    description: Needs a description.
  - name: Keys
    description: Needs a description.
  - name: Microvisor
    description: Needs a description.
  - name: Secrets
    description: Needs a description.
  - name: Applications
    description: Needs a description.
  - name: Manifests
    description: Needs a description.
  - name: Devices
    description: Needs a description.
x-maturity:
  - name: Preview
    description: >-
      PLEASE NOTE that this is a Preview product that is subject to change. Use
      it with caution. If you currently do not have developer preview access,
      please contact https://www.twilio.com/help/contact.
