info:
  title: Twilio Proxy API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Services/{ServiceSid}/Sessions/{SessionSid}/Interactions/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: >-
        Retrieve a list of Interactions for a given
        [Session](https://www.twilio.com/docs/proxy/api/session).
      tags:
        - Proxies
        - Services
        - Sessions
        - Interactions
      summary: Retrieve Service Session Interaction
    delete:
      description: Delete a specific Interaction.
      tags:
        - Proxies
        - Services
        - Sessions
        - Interactions
      summary: Delete Service Session Interaction
  /v1/Services/{ServiceSid}/Sessions/{SessionSid}/Interactions:
    description: 'TODO: Resource-level docs'
    get:
      description: >-
        Retrieve a list of all Interactions for a Session. A maximum of 100
        records will be returned per page.
      tags:
        - Proxies
        - Services
        - Sessions
        - Interactions
      summary: Retrieve Service Session Interactions
  /v1/Services/{ServiceSid}/Sessions/{SessionSid}/Participants/{ParticipantSid}/MessageInteractions:
    description: 'TODO: Resource-level docs'
    post:
      description: >-
        Create a new message Interaction to send directly from your system to
        one [Participant](https://www.twilio.com/docs/proxy/api/participant). 
        The `inbound` properties for the Interaction will always be empty.
      tags:
        - Proxies
        - Services
        - Sessions
        - Participants
        - Interactions
      summary: Create Service Session Participant Interaction
    get:
      description: ''
      tags:
        - Proxies
        - Services
        - Sessions
        - Participants
        - Interactions
      summary: Retrieve Service Session Participant Interaction
  /v1/Services/{ServiceSid}/Sessions/{SessionSid}/Participants/{ParticipantSid}/MessageInteractions/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Proxies
        - Services
        - Sessions
        - Participants
        - Interactions
      summary: Retrieve Service Session Participant Interactions
  /v1/Services/{ServiceSid}/Sessions/{SessionSid}/Participants/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Participant.
      tags:
        - Proxies
        - Services
        - Sessions
        - Participants
      summary: Retrieve Service Session Participant
    delete:
      description: >-
        Delete a specific Participant. This is a soft-delete. The participant
        remains associated with the session and cannot be re-added. Participants
        are only permanently deleted when the
        [Session](https://www.twilio.com/docs/proxy/api/session) is deleted.
      tags:
        - Proxies
        - Services
        - Sessions
        - Participants
      summary: Delete Service Session Participant
  /v1/Services/{ServiceSid}/Sessions/{SessionSid}/Participants:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Participants in a Session.
      tags:
        - Proxies
        - Services
        - Sessions
        - Participants
      summary: Retrieve Service Session Participants
    post:
      description: Add a new Participant to the Session
      tags:
        - Proxies
        - Services
        - Sessions
        - Participants
      summary: Create Service Session Participant
  /v1/Services/{ServiceSid}/PhoneNumbers:
    description: 'TODO: Resource-level docs'
    post:
      description: Add a Phone Number to a Service's Proxy Number Pool.
      tags:
        - Proxies
        - Services
        - Phone Numbers
        - Numbers
      summary: Create Service Phone Number
    get:
      description: >-
        Retrieve a list of all Phone Numbers in the Proxy Number Pool for a
        Service. A maximum of 100 records will be returned per page.
      tags:
        - Proxies
        - Services
        - Phone Numbers
        - Numbers
      summary: Retrieve Service Phone Numbers
  /v1/Services/{ServiceSid}/PhoneNumbers/{Sid}:
    description: 'TODO: Resource-level docs'
    delete:
      description: Delete a specific Phone Number from a Service.
      tags:
        - Proxies
        - Services
        - Phone Numbers
        - Numbers
      summary: Delete Service Phone Number
    get:
      description: Fetch a specific Phone Number.
      tags:
        - Proxies
        - Services
        - Phone Numbers
        - Numbers
      summary: Retrieve Service Phone Number
    post:
      description: Update a specific Proxy Number.
      tags:
        - Proxies
        - Services
        - Phone Numbers
        - Numbers
      summary: Update Service Phone Number
  /v1/Services/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Service.
      tags:
        - Proxies
        - Services
      summary: Retrieve Service
    delete:
      description: Delete a specific Service.
      tags:
        - Proxies
        - Services
      summary: Delete Service
    post:
      description: Update a specific Service.
      tags:
        - Proxies
        - Services
      summary: Update Service
  /v1/Services:
    description: 'TODO: Resource-level docs'
    get:
      description: >-
        Retrieve a list of all Services for Twilio Proxy. A maximum of 100
        records will be returned per page.
      tags:
        - Proxies
        - Services
      summary: Retrieve Services
    post:
      description: Create a new Service for Twilio Proxy
      tags:
        - Proxies
        - Services
      summary: Create Service
  /v1/Services/{ServiceSid}/Sessions/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Session.
      tags:
        - Proxies
        - Services
        - Sessions
      summary: Retrieve Service Session
    delete:
      description: Delete a specific Session.
      tags:
        - Proxies
        - Services
        - Sessions
      summary: Delete Service Session
    post:
      description: Update a specific Session.
      tags:
        - Proxies
        - Services
        - Sessions
      summary: Update Service Session
  /v1/Services/{ServiceSid}/Sessions:
    description: 'TODO: Resource-level docs'
    get:
      description: >-
        Retrieve a list of all Sessions for the Service. A maximum of 100
        records will be returned per page.
      tags:
        - Proxies
        - Services
        - Sessions
      summary: Retrieve Service Sessions
    post:
      description: Create a new Session
      tags:
        - Proxies
        - Services
        - Sessions
      summary: Create Service Session
  /v1/Services/{ServiceSid}/ShortCodes:
    description: 'TODO: Resource-level docs'
    post:
      description: Add a Short Code to the Proxy Number Pool for the Service.
      tags:
        - Proxies
        - Services
        - Short Codes
      summary: Create Service Short Code
    get:
      description: >-
        Retrieve a list of all Short Codes in the Proxy Number Pool for the
        Service. A maximum of 100 records will be returned per page.
      tags:
        - Proxies
        - Services
        - Short Codes
      summary: Retrieve Service Short Codes
  /v1/Services/{ServiceSid}/ShortCodes/{Sid}:
    description: 'TODO: Resource-level docs'
    delete:
      description: Delete a specific Short Code from a Service.
      tags:
        - Proxies
        - Services
        - Short Codes
      summary: Delete Service Short Code
    get:
      description: Fetch a specific Short Code.
      tags:
        - Proxies
        - Services
        - Short Codes
      summary: Retrieve Service Short Code
    post:
      description: Update a specific Short Code.
      tags:
        - Proxies
        - Services
        - Short Codes
      summary: Update Service Short Code
tags:
  - name: Tag
  - name: Proxies
    description: Needs a description.
  - name: Services
    description: Needs a description.
  - name: ''
    description: Needs a description.
  - name: Sessions
    description: Needs a description.
  - name: Interactions
    description: Needs a description.
  - name: Participants
    description: Needs a description.
  - name: Phone Numbers
    description: Needs a description.
  - name: Numbers
    description: Needs a description.
  - name: Short Codes
    description: Needs a description.
x-maturity:
  - name: Beta
    description: >-
      PLEASE NOTE that this is a Beta product that is subject to change. Use it
      with caution.
