info:
  title: Twilio Sync API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Services/{ServiceSid}/Documents/{Sid}:
    description: Sync Document objects
    get:
      description: ''
      tags:
        - Sync
        - Services
        - Documents
      summary: Retrieve Service Document
    delete:
      description: ''
      tags:
        - Sync
        - Services
        - Documents
      summary: Delete Service Document
    post:
      description: ''
      tags:
        - Sync
        - Services
        - Documents
      summary: Update Service Document
  /v1/Services/{ServiceSid}/Documents:
    description: Sync Document objects
    post:
      description: ''
      tags:
        - Sync
        - Services
        - Documents
      summary: Create Service Document
    get:
      description: ''
      tags:
        - Sync
        - Services
        - Documents
      summary: Retrieve Service Documents
  /v1/Services/{ServiceSid}/Documents/{DocumentSid}/Permissions/{Identity}:
    description: Sync document permissions
    get:
      description: Fetch a specific Sync Document Permission.
      tags:
        - Sync
        - Services
        - Documents
        - Permissions
      summary: Retrieve Service Document Permission
    delete:
      description: Delete a specific Sync Document Permission.
      tags:
        - Sync
        - Services
        - Documents
        - Permissions
      summary: Delete Service Document Permission
    post:
      description: Update an identity's access to a specific Sync Document.
      tags:
        - Sync
        - Services
        - Documents
        - Permissions
      summary: Update Service Document Permission
  /v1/Services/{ServiceSid}/Documents/{DocumentSid}/Permissions:
    description: Sync document permissions
    get:
      description: Retrieve a list of all Permissions applying to a Sync Document.
      tags:
        - Sync
        - Services
        - Documents
        - Permissions
      summary: Retrieve Service Document Permissions
  /v1/Services/{Sid}:
    description: Containers for sync objects
    get:
      description: ''
      tags:
        - Sync
        - Services
      summary: Retrieve Service
    delete:
      description: ''
      tags:
        - Sync
        - Services
      summary: Delete Service
    post:
      description: ''
      tags:
        - Sync
        - Services
      summary: Update Service
  /v1/Services:
    description: Containers for sync objects
    post:
      description: ''
      tags:
        - Sync
        - Services
      summary: Create Service
    get:
      description: ''
      tags:
        - Sync
        - Services
      summary: Retrieve Services
  /v1/Services/{ServiceSid}/Streams/{StreamSid}/Messages:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Stream Message.
      tags:
        - Sync
        - Services
        - Streams
        - Messages
      summary: Create Service Stream Message
  /v1/Services/{ServiceSid}/Lists/{Sid}:
    description: Sync list objects
    get:
      description: ''
      tags:
        - Sync
        - Services
        - Lists
      summary: Retrieve Service List
    delete:
      description: ''
      tags:
        - Sync
        - Services
        - Lists
      summary: Delete Service List
    post:
      description: ''
      tags:
        - Sync
        - Services
        - Lists
      summary: Update Service List
  /v1/Services/{ServiceSid}/Lists:
    description: Sync list objects
    post:
      description: ''
      tags:
        - Sync
        - Services
        - Lists
      summary: Create Service List
    get:
      description: ''
      tags:
        - Sync
        - Services
        - Lists
      summary: Retrieve Service Lists
  /v1/Services/{ServiceSid}/Lists/{ListSid}/Items/{Index}:
    description: Items in a sync list
    get:
      description: ''
      tags:
        - Sync
        - Services
        - Lists
        - Items
      summary: Retrieve Service List Item
    delete:
      description: ''
      tags:
        - Sync
        - Services
        - Lists
        - Items
      summary: Delete Service List Item
    post:
      description: ''
      tags:
        - Sync
        - Services
        - Lists
        - Items
      summary: Update Service List Item
  /v1/Services/{ServiceSid}/Lists/{ListSid}/Items:
    description: Items in a sync list
    post:
      description: ''
      tags:
        - Sync
        - Services
        - Lists
        - Items
      summary: Create Service List Item
    get:
      description: ''
      tags:
        - Sync
        - Services
        - Lists
        - Items
      summary: Retrieve Service List Item
  /v1/Services/{ServiceSid}/Lists/{ListSid}/Permissions/{Identity}:
    description: Permissions for Sync list items
    get:
      description: Fetch a specific Sync List Permission.
      tags:
        - Sync
        - Services
        - Lists
        - Permissions
      summary: Retrieve Service List Permission
    delete:
      description: Delete a specific Sync List Permission.
      tags:
        - Sync
        - Services
        - Lists
        - Permissions
      summary: Delete Service List Permission
    post:
      description: Update an identity's access to a specific Sync List.
      tags:
        - Sync
        - Services
        - Lists
        - Permissions
      summary: Update Service List Permission
  /v1/Services/{ServiceSid}/Lists/{ListSid}/Permissions:
    description: Permissions for Sync list items
    get:
      description: Retrieve a list of all Permissions applying to a Sync List.
      tags:
        - Sync
        - Services
        - Lists
        - Permissions
      summary: Retrieve Service List Permissions
  /v1/Services/{ServiceSid}/Maps/{Sid}:
    description: Sync map objects
    get:
      description: ''
      tags:
        - Sync
        - Services
        - Maps
      summary: Retrieve Service Map
    delete:
      description: ''
      tags:
        - Sync
        - Services
        - Maps
      summary: Delete Service Map
    post:
      description: ''
      tags:
        - Sync
        - Services
        - Maps
      summary: Update Service Map
  /v1/Services/{ServiceSid}/Maps:
    description: Sync map objects
    post:
      description: ''
      tags:
        - Sync
        - Services
        - Maps
      summary: Create Service Map
    get:
      description: ''
      tags:
        - Sync
        - Services
        - Maps
      summary: Retrieve Service Map
  /v1/Services/{ServiceSid}/Maps/{MapSid}/Items/{Key}:
    description: Keys in a sync map
    get:
      description: ''
      tags:
        - Sync
        - Services
        - Maps
        - Items
      summary: Retrieve Service Map Item
    delete:
      description: ''
      tags:
        - Sync
        - Services
        - Maps
        - Items
      summary: Delete Service Map Item
    post:
      description: ''
      tags:
        - Sync
        - Services
        - Maps
        - Items
      summary: Update Service Map Item
  /v1/Services/{ServiceSid}/Maps/{MapSid}/Items:
    description: Keys in a sync map
    post:
      description: ''
      tags:
        - Sync
        - Services
        - Maps
        - Items
      summary: Create Service Map Item
    get:
      description: ''
      tags:
        - Sync
        - Services
        - Maps
        - Items
      summary: Retrieve Service Map Item
  /v1/Services/{ServiceSid}/Maps/{MapSid}/Permissions/{Identity}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Sync Map Permission.
      tags:
        - Sync
        - Services
        - Maps
        - Permissions
      summary: Retrieve Service Map Permission
    delete:
      description: Delete a specific Sync Map Permission.
      tags:
        - Sync
        - Services
        - Maps
        - Permissions
      summary: Delete Service Map Permission
    post:
      description: Update an identity's access to a specific Sync Map.
      tags:
        - Sync
        - Services
        - Maps
        - Permissions
      summary: Update Service Map Permission
  /v1/Services/{ServiceSid}/Maps/{MapSid}/Permissions:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Permissions applying to a Sync Map.
      tags:
        - Sync
        - Services
        - Maps
        - Permissions
      summary: Retrieve Service Map Permissions
  /v1/Services/{ServiceSid}/Streams/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Stream.
      tags:
        - SyncV1SyncStream
      summary: Retrieve Service Stream
    delete:
      description: Delete a specific Stream.
      tags:
        - Sync
        - Services
        - Streams
      summary: Delete Service Stream
    post:
      description: Update a specific Stream.
      tags:
        - Sync
        - Services
        - Streams
      summary: Update Service Stream
  /v1/Services/{ServiceSid}/Streams:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Stream.
      tags:
        - Sync
        - Services
        - Streams
      summary: Create Service Stream
    get:
      description: Retrieve a list of all Streams in a Service Instance.
      tags:
        - Sync
        - Services
        - Streams
      summary: Retrieve Service Streams
tags:
  - name: Tag
  - name: Sync
    description: Needs a description.
  - name: Services
    description: Needs a description.
  - name: Documents
    description: Needs a description.
  - name: Permissions
    description: Needs a description.
  - name: Streams
    description: Needs a description.
  - name: Messages
    description: Needs a description.
  - name: Lists
    description: Needs a description.
  - name: Items
    description: Needs a description.
  - name: Maps
    description: Needs a description.
x-maturity:
  - name: GA
    description: This product is Generally Available.
