openapi: 3.0.0
info:
  title: Stripe Shipping Rates API
paths:
  /v1/shipping_rates:
    get:
      description: <p>Returns a list of your shipping rates.</p>
      summary: Retrieve Shipping Rates
      tags:
        - Shipping
        - Rates
    post:
      description: <p>Creates a new shipping rate object.</p>
      summary: Create Shipping Rate
      tags:
        - Shipping
        - Rates
  /v1/shipping_rates/{shipping_rate_token}:
    get:
      description: <p>Returns the shipping rate object with the given ID.</p>
      summary: Retrieve Shipping Rate Token
      tags:
        - Shipping
        - Rates
        - Tokens
    post:
      description: <p>Updates an existing shipping rate object.</p>
      summary: Update Shipping Rate Token
      tags:
        - Shipping
        - Rates
        - Tokens
tags:
  - name: Shipping
    description: Needs a description.
  - name: Rates
    description: Needs a description.
  - name: Tokens
    description: Needs a description.
