openapi: 3.0.0
info:
  title: Airline Routes
paths:
  /airline/destinations:
    get:
      summary: get airline destinations
      tags:
        - Get
        - Airline
        - Destinations
        - Airline
        - Destinations
      description: null
