openapi: 3.0.0
info:
  title: Airport Routes
paths:
  /airport/direct-destinations:
    get:
      summary: get airport direct routes
      tags:
        - Get
        - Airport
        - Direct
        - Routes
        - Airport
        - Direct
        - Destinations
      description: null
