openapi: 3.0.0
info:
  title: City Search
paths:
  /reference-data/locations/cities:
    get:
      summary: GET Cities by keyword
      tags:
        - Cities
        - By
        - Keyword
        - Reference
        - Data
        - Locations
        - Cities
      description: null
