openapi: 3.0.0
info:
  title: Flight Price Analysis API
paths:
  /analytics/itinerary-price-metrics:
    get:
      summary: GET itinerary price metric
      description: ''
      tags:
        - Itinerary
        - Prices
        - Metrics
        - Analytics
        - Itinerary
        - Prices
        - Metrics
    parameters: null
