openapi: 3.0.0
info:
  title: Hotel List
paths:
  /reference-data/locations/hotels/by-hotels:
    get:
      summary: Search Hotels using its unique Id
      tags:
        - Search
        - Hotels
        - Using
        - Items
        - Unique
        - Identifiers
        - References
        - Data
        - Locations
        - Hotels
        - By
      description: ''
  /reference-data/locations/hotels/by-city:
    get:
      summary: Search Hotels in a city
      tags:
        - Search
        - Hotels
        - In
        - Cities
        - References
        - Data
        - Locations
        - Hotels
        - By
        - Cities
      description: ''
  /reference-data/locations/hotels/by-geocode:
    get:
      summary: Search Hotels using Geocode
      tags:
        - Search
        - Hotels
        - Using
        - Geocode
        - References
        - Data
        - Locations
        - Hotels
        - By
        - Cities
        - Geocode
      description: ''
    parameters: null
