openapi: 3.0.0
info:
  title: Location Score
paths:
  /location/analytics/category-rated-areas:
    get:
      summary: GET category rated areas
      description: ''
      tags:
        - Categories
        - Rated
        - Areas
        - Locations
        - Analytics
        - Categories
        - Rated
        - Areas
    parameters: null
