openapi: 3.0.0
info:
  title: Location Score
paths:
  /location/analytics/category-rated-areas:
    get:
      summary: GET category rated areas
      description: ''
      tags:
        - - - - category-rated-areas
    parameters: []
tags: []
