openapi: 3.0.0
info:
  title: Travel Recommendations API
paths:
  /reference-data/recommended-locations:
    get:
      summary: GET recommended destinations
      tags:
        - Recommended
        - Destinations
        - References
        - Data
        - Recommended
        - Locations
      description: null
