openapi: 3.0.1
info:
  title: Zoom REST API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
externalDocs:
  description: Zoom REST API Documentation
  url: https://zoom.github.io/api
tags:
  - name: Users
    description: User operations
  - name: Meeting
    description: Meeting operations
  - name: Reports
    description: Report operations
  - name: Group
    description: Group operations
  - name: IM Group
    description: IM Group operations
  - name: Webinar
    description: Webinar operations
  - name: Dashboard
    description: Dashboard operations
  - name: Cloud Recording
    description: Cloud Recording operations
  - name: Archived Chat
    description: Archived Chat operations
  - name: Account
    description: Account operations
  - name: Devices
    description: Device operations
paths:
  /chat/get:
    post:
      tags:
        - Chat
      description: |+
        Get chat messages for a specified period.

  /chat/list:
    post:
      tags:
        - Chat
      description: |+
        Get chat history list for a specified time period.

  /group/create:
    post:
      tags:
        - Group
      description: |+
        Create a group on Zoom, return the new group info.

  /group/delete:
    post:
      tags:
        - Group
      description: |+
        Delete a group on Zoom, return the deleted group ID.

  /group/edit:
    post:
      tags:
        - Group
      description: |+
        Edit a group on Zoom, return the new group info.

  /group/get:
    post:
      tags:
        - Group
      description: |+
        Get a group on Zoom via ID, return the group info.

  /group/list:
    post:
      tags:
        - Group
      description: |+
        List all groups on your Zoom account.

  /group/member/add:
    post:
      tags:
        - Group
      description: |+
        Add members to a group on Zoom.

  /group/member/delete:
    post:
      tags:
        - Group
      description: |+
        Delete members of a group on Zoom.

  /group/member/list:
    post:
      tags:
        - Group
      description: |+
        Lists the members of a group on Zoom.

  /h323/device/create:
    post:
      tags:
        - Device
      description: |+
        Create a H.323/SIP Device on your Zoom account.

  /h323/device/delete:
    post:
      tags:
        - Device
      description: |+
        Delete a H.323/SIP Device on your Zoom account.

  /h323/device/list:
    post:
      tags:
        - Device
      description: |+
        List H.323/SIP Devices on your Zoom account.

  /h323/device/update:
    post:
      tags:
        - Device
      description: |+
        Update a H.323/SIP Device on your Zoom account.

  /im/group/create:
    post:
      tags:
        - IM Group
      description: |+
        Create a IM group on Zoom, return the new group info.

  /im/group/delete:
    post:
      tags:
        - IM Group
      description: |+
        Delete a IM group on Zoom, return the deleted group ID.

  /im/group/edit:
    post:
      tags:
        - IM Group
      description: |+
        Edit a IM group on Zoom, return the new group info.

  /im/group/get:
    post:
      tags:
        - IM Group
      description: |+
        Get a IM group on Zoom via ID, return the group info.

  /im/group/list:
    post:
      tags:
        - IM Group
      description: |+
        List all IM groups on your Zoom account.

  /im/group/member/delete:
    post:
      tags:
        - IM Group
      description: |+
        Delete members of a IM group on Zoom.

  /im/group/member/list:
    post:
      tags:
        - IM Group
      description: |+
        Lists the members of a IM group on Zoom.

  /ma/account/billing/update:
    post:
      tags:
        - Account
      description: >+
        Update Billing Information for a sub account of the master account on
        Zoom.

  /ma/account/create:
    post:
      tags:
        - Account
      description: >+
        Create a sub account of the master account on Zoom, return the created
        sub account id and owner id.


        <aside class="notice">Your account must be a master account and have
        this privilege to create sub account. Zoom only assign this privilege to
        trusted partner.</aside>


        <aside class="notice">User will not receive the confirmation
        email.</aside>

  /ma/account/delete:
    post:
      tags:
        - Account
      description: |+
        Delete the sub account.

  /ma/account/get:
    post:
      tags:
        - Account
      description: >+
        Get a sub account of the master account on Zoom, return the created sub
        account id and owner id.


        <aside class="notice">Your account must be a master account and have
        this privilege to get sub account. Zoom only assign this privilege to
        trusted partner.</aside>


        <aside class="notice">This API will let the master account owner to get
        sub account API key pair. This is a private feature and needs to be
        enabled by zoom support. If you need this function, please open a case
        with support to enable this API.</aside>

  /ma/account/list:
    post:
      tags:
        - Account
      description: |+
        List all the sub account under the master account.

  /ma/account/plan/add:
    post:
      tags:
        - Account
      description: >+
        Add a plan for a sub account of the master account on Zoom.


        <aside class="notice">Only for the sub account which is a paid account
        and paid by master account.</aside>


        <aside class="notice">Only add an Additional plan for a sub
        account.</aside>

  /ma/account/plan/get:
    post:
      tags:
        - Account
      description: |+
        Get plans information for a sub account of the master account on Zoom.

  /ma/account/plan/subscribe:
    post:
      tags:
        - Account
      description: |+
        Subscribe plans for a sub account of the master account on Zoom.

  /ma/account/plan/update:
    post:
      tags:
        - Account
      description: >+
        Update a plan for a sub account of the master account on Zoom.


        <aside class="notice">Only for the sub account which is a paid account
        and paid by master account.</aside>


        <aside class="notice">Could update a base plan or an additional
        plan.</aside>

  /ma/account/update:
    post:
      tags:
        - Account
      description: >+
        Update a sub account of the master account on Zoom, return the updated
        sub account id.

  /mc/recording/list:
    post:
      tags:
        - Cloud Recording
      description: |+
        Lists all the cloud recordings meetings on a Meeting Connector

  /meeting/create:
    post:
      tags:
        - Meeting
      description: |+
        Create a meeting on Zoom, return the created meeting URL

  /meeting/delete:
    post:
      tags:
        - Meeting
      description: |+
        Delete a meeting on Zoom, return the deleted meeting ID.

  /meeting/end:
    post:
      tags:
        - Meeting
      description: |+
        End a meeting on Zoom, return the deleted meeting ID.

  /meeting/get:
    post:
      tags:
        - Meeting
      description: |+
        Get a meeting on Zoom via meeting ID, return the meeting info.

  /meeting/list:
    post:
      tags:
        - Meeting
      description: |+
        List all the scheduled meetings on Zoom.

  /meeting/live:
    post:
      tags:
        - Meeting
      description: |+
        Lists the live meetings on Zoom.

  /meeting/register:
    post:
      tags:
        - Meeting
      description: |+
        Register for a meeting.

  /meeting/update:
    post:
      tags:
        - Meeting
      description: |+
        Update meeting info on Zoom via meeting ID.

  /metrics/crc:
    post:
      tags:
        - Dashboard
      description: |+
        Get CRC Port usage hour by hour for a specified time period.

  /metrics/im:
    post:
      tags:
        - Dashboard
      description: |+
        Get statistics of Zoom IM

  /metrics/meetingdetail:
    post:
      tags:
        - Dashboard
      description: |+
        Get live and past meeting details

  /metrics/meetings:
    post:
      tags:
        - Dashboard
      description: |+
        Get Live Meetings and past meetings for a specified period

  /metrics/qos:
    post:
      tags:
        - Dashboard
      description: |+
        Get the users quality of service in a Zoom Meeting

  /metrics/webinardetail:
    post:
      tags:
        - Dashboard
      description: |+
        Get live and past webinar details

  /metrics/webinars:
    post:
      tags:
        - Dashboard
      description: |+
        Get live webinars and past webinars for a specified period.

  /metrics/zoomroomdetail:
    post:
      tags:
        - Dashboard
      description: |+
        Get a Zoom Room on Zoom via Zoom ID, return the Zoom Room info.

  /metrics/zoomrooms:
    post:
      tags:
        - Dashboard
      description: |+
        List all Zoom Rooms on Zoom.

  /recording/delete:
    post:
      tags:
        - Cloud Recording
      description: |+
        Delete recorded meeting either on Zoom cloud or on-premise.

  /recording/get:
    post:
      tags:
        - Cloud Recording
      description: |+
        Get the recorded meeting on either Zoom cloud or on-prem.

  /recording/list:
    post:
      tags:
        - Cloud Recording
      description: |+
        List all the cloud recording meetings on Zoom.

  /report/getaccountreport:
    post:
      tags:
        - Report
      description: |+
        Get account report for a specified period.

  /report/getaudioreport:
    post:
      tags:
        - Report
      description: >+
        Get user report for a specified period.


        <aside class="notice">Toll Report API is provided for enabled 'Toll
        Report' option.</aside>


        <aside class="notice">We will report a maximum of one month. For
        example, if "from" is set to "2015-08-05" and "to" is "2015-10-10" we
        will adjust "from" to "2015-09-10"</aside>

  /report/getdailyreport:
    post:
      tags:
        - Report
      description: >+
        Get daily report for one month, can only get daily report for recent 3
        months.

  /report/getuserreport:
    post:
      tags:
        - Report
      description: |+
        Get user report for a specified period.

  /user/assistant/delete:
    post:
      tags:
        - User
      description: |+
        Delete a user's assistant.

  /user/assistant/set:
    post:
      tags:
        - User
      description: |+
        Set a user's assistant which can schedule meeting for him.

  /user/autocreate:
    post:
      tags:
        - User
      description: >+
        Create a user on Zoom, returns the created user ID.


        <aside class="notice">

        The API is provided for enterprise customer who has a managed domain

        </aside>


        <aside class="warning">

        This feature is disabled by default because of the security risk
        involved in creating a user who does not belong to your domain without
        notifying the user. You need to contact Zoom customer support if you
        want to use this API

        </aside>

  /user/checkemail:
    post:
      tags:
        - User
      description: |+
        Check if the user email exists.

  /user/checkzpk:
    post:
      tags:
        - User
      description: |+
        Check if the zpk is expired. The zpk is used to authenticate a user.

  /user/create:
    post:
      tags:
        - User
      description: >+
        Create a user on Zoom, returns the created user ID.


        <aside class="notice">

        Your account must have this privilege to provisioning user. Zoom only
        assigns this privilege to a trusted partner

        </aside>


        <aside class="notice">

        User will get an email sent from Zoom. There is a confirmation link in
        this email. User will then need to click this link to activate their
        account to the Zoom service. The user can set or change their password
        in Zoom.

        </aside>

  /user/custcreate:
    post:
      tags:
        - User
      description: >+
        Create a user on Zoom, returns the created user ID.


        <aside class="notice">

        The API is provided for API plan only

        </aside>


        <aside class="notice">

        User created in this way has no password and is not able to log into the
        Zoom web site or client

        </aside>

  /user/activate:
    post:
      tags:
        - User
      description: |+
        Activate a user on Zoom, return the user ID.

  /user/deactivate:
    post:
      tags:
        - User
      description: |+
        Deactivate a user on Zoom, return the user ID.

  /user/delete:
    post:
      tags:
        - User
      description: |+
        Delete a user on Zoom, return the deleted user ID.

  /user/get:
    post:
      tags:
        - User
      description: |+
        Get a user info on Zoom via user ID

  /user/getbyemail:
    post:
      tags:
        - User
      description: >+
        Get a user on Zoom via user email address and login type, return the
        user info.

  /user/list:
    post:
      tags:
        - User
      description: |+
        List all the users on Zoom

  /user/pending:
    post:
      tags:
        - User
      description: |+
        List all the pending users on Zoom

  /user/permanentdelete:
    post:
      tags:
        - User
      description: |+
        Delete a user from Zoom system permanently.

  /user/revoketoken:
    post:
      tags:
        - User
      description: |+
        Revoke a user's SSO token.

  /user/scheduleforhost/list:
    post:
      tags:
        - User
      description: |+
        List assigned schedule privilege for host users.

  /user/ssocreate:
    post:
      tags:
        - User
      description: >+
        Create a SSO user on Zoom, return the created user ID.


        <aside class="notice">The API is provided for enabled 'Pre-provisioning
        SSO User' option. User created in this way has no password. If it is not
        a basic user, will generate a Personal Vanity URL using user name (no
        domain) of the provisioning email. If user name or pmi is invalid or
        occupied, will use random number/random personal vanity URL.</aside>

  /user/update:
    post:
      tags:
        - User
      description: |+
        Update user info on Zoom via user ID.

  /user/updatepassword:
    post:
      tags:
        - User
      description: |+
        Upload and update user's profile picture on Zoom via user ID.

  /webinar/attendees/list:
    post:
      tags:
        - Webinar
      description: |+
        Get ended webinar attendees

  /webinar/create:
    post:
      tags:
        - Webinar
      description: |+
        Create a webinar on Zoom, return the created webinar start and join URL.

  /webinar/delete:
    post:
      tags:
        - Webinar
      description: |+
        Delete a webinar on Zoom, return the deleted webinar ID.

  /webinar/end:
    post:
      tags:
        - Webinar
      description: |+
        End a Webinar on Zoom, return the deleted Webinar ID

  /webinar/get:
    post:
      tags:
        - Webinar
      description: |+
        Get a Webinar on Zoom via Webinar ID, return the Webinar info

  /webinar/list:
    post:
      tags:
        - Webinar
      description: |+
        List all registrationless Webinars on Zoom

  /webinar/list/registration:
    post:
      tags:
        - Webinar
      description: |+
        List all the upcoming registration-based Webinars on Zoom

  /webinar/panelists:
    post:
      tags:
        - Webinar
      description: |+
        Get all the Webinar Panelists on Zoom

  /webinar/polls:
    post:
      tags:
        - Webinar
      description: |+
        Get Ended Webinar Polls

  /webinar/questions:
    post:
      tags:
        - Webinar
      description: |+
        Get Ended Webinar Q&A

  /webinar/register:
    post:
      tags:
        - Webinar
      description: |+
        Register for a webinar

  /webinar/registrants/approve:
    post:
      tags:
        - Webinar
      description: |+
        Approve pending registrants on Zoom Webinar.

  /webinar/registrants/list:
    post:
      tags:
        - Webinar
      description: >+
        List webinar registrants on Zoom, include pending approval registrants
        and approved registrants.

  /webinar/registration:
    post:
      tags:
        - Webinar
      description: |+
        Gather Webinar registrants info

  /webinar/registration/cancel:
    post:
      tags:
        - Webinar
      description: |+
        Cancel Webinar Registration

  /webinar/update:
    post:
      tags:
        - Webinar
      description: |+
        Update Webinar info on Zoom via Webinar ID

  /webinar/uuid/list:
    post:
      tags:
        - Webinar
      description: |
        Get ended webina
