---
openapi: 3.1.0
info:
  title: alexaforbusiness
  description: <p>Alexa for Business has been retired and is no longer supported.</p>
paths:
  /:
    POST:
      summary: UpdateSkillGroup
      description: <p>Updates skill group details by skill group ARN.</p>
---