---
openapi: 3.1.0
info:
  title: ec2
  description: >-
    <fullname>Amazon Elastic Compute Cloud</fullname> <p>Amazon Elastic Compute
    Cloud (Amazon EC2) provides resizable computing capacity in the Amazon Web
    Services (AWS) cloud. Using Amazon EC2 eliminates your need to invest in
    hardware up front, so you can develop and deploy applications faster.</p>
paths:
  /:
    POST:
      summary: WithdrawByoipCidr
      description: >-
        <p>Stops advertising an address range that is provisioned as an address
        pool.</p> <p>You can perform this operation at most once every 10
        seconds, even if you specify different address ranges each time.</p>
        <p>It can take a few minutes before traffic to the specified addresses
        stops routing to Amazon Web Services because of BGP propagation
        delays.</p>
---