openapi: 3.0.0
info:
  title: Stripe Apple Pay API
paths:
  /v1/apple_pay/domains:
    get:
      description: <p>List apple pay domains.</p>
      summary: Retrieve Apple Pay Domains
      tags:
        - Apple Pay
        - Domains
    post:
      description: <p>Create an apple pay domain.</p>
      summary: Create Apple Pay Domains
      tags:
        - Apple Pay
        - Domains
  /v1/apple_pay/domains/{domain}:
    delete:
      description: <p>Delete an apple pay domain.</p>
      summary: Delete Apple Pay Domain
      tags:
        - Apple Pay
        - Domains
    get:
      description: <p>Retrieve an apple pay domain.</p>
      summary: Retrieve Apple Pay Domain
      tags:
        - Apple Pay
        - Domains
tags:
  - name: Apple Pay
    description: Needs a description.
  - name: Domains
    description: Needs a description.
