openapi: 3.0.0
info:
  title: Stripe Apple Pay API
paths:
  /v1/apple_pay/domains:
    get:
      description: <p>List apple pay domains.</p>
    post:
      description: <p>Create an apple pay domain.</p>
  /v1/apple_pay/domains/{domain}:
    delete:
      description: <p>Delete an apple pay domain.</p>
    get:
      description: <p>Retrieve an apple pay dom
