openapi: 3.0.0
info:
  title: Stripe Application Secrets API
paths:
  /v1/apps/secrets:
    get:
      description: <p>List all secrets stored on the given scope.</p>
      summary: Retrieve Application Secrets
      tags:
        - Retrieve
        - Application
        - Secrets
        - V1
        - Apps
        - Secrets
    post:
      description: <p>Create or replace a secret in the secret store.</p>
      summary: Create Application Secret
      tags:
        - Create
        - Application
        - Secret
        - V1
        - Apps
        - Secrets
  /v1/apps/secrets/delete:
    post:
      description: <p>Deletes a secret from the secret store by name and scope.</p>
      summary: Delete Application Secret
      tags:
        - Delete
        - Application
        - Secret
        - V1
        - Apps
        - Secrets
        - Delete
  /v1/apps/secrets/find:
    get:
      description: <p>Finds a secret in the secret store by name and scope.</p>
      summary: Find Application Secret
      tags:
        - Find
        - Application
        - Secret
        - V1
        - Apps
        - Secrets
        - Delete
        - Find
tags:
  - name: Applications
    description: Needs a description.
  - name: Secrets
    description: Needs a descriptio
