openapi: 3.0.0
info:
  title: Stripe Billing API
paths:
  /v1/billing_portal/configurations:
    get:
      description: >-
        <p>Returns a list of configurations that describe the functionality of
        the customer portal.</p>
    post:
      description: >-
        <p>Creates a configuration that describes the functionality and behavior
        of a PortalSession</p>
  /v1/billing_portal/configurations/{configuration}:
    get:
      description: >-
        <p>Retrieves a configuration that describes the functionality of the
        customer portal.</p>
    post:
      description: >-
        <p>Updates a configuration that describes the functionality of the
        customer portal.</p>
  /v1/billing_portal/sessions:
    post:
      description: <p>Creates a session of the customer por
