openapi: 3.0.0
info:
  title: Stripe Billing API
paths:
  /v1/billing_portal/configurations:
    get:
      description: >-
        <p>Returns a list of configurations that describe the functionality of
        the customer portal.</p>
      summary: Retrieve Billing Portal Configurations
      tags:
        - Retrieve
        - Billing
        - Portal
        - Configurations
        - V1
        - Billing_portal
        - Configurations
    post:
      description: >-
        <p>Creates a configuration that describes the functionality and behavior
        of a PortalSession</p>
      summary: Create Billing Portal Configuration
      tags:
        - Create
        - Billing
        - Portal
        - Configuration
        - V1
        - Billing_portal
        - Configurations
  /v1/billing_portal/configurations/{configuration}:
    get:
      description: >-
        <p>Retrieves a configuration that describes the functionality of the
        customer portal.</p>
      summary: Retrieve Billing Portal Configuration
      tags:
        - Retrieve
        - Billing
        - Portal
        - Configuration
        - V1
        - Billing_portal
        - Configurations
        - Configuration
    post:
      description: >-
        <p>Updates a configuration that describes the functionality of the
        customer portal.</p>
      summary: Update Billing Portal Configuration
      tags:
        - Update
        - Billing
        - Portal
        - Configuration
        - V1
        - Billing_portal
        - Configurations
        - Configuration
  /v1/billing_portal/sessions:
    post:
      description: <p>Creates a session of the customer portal.</p>
      summary: Retrieve Billing Portal Session
      tags:
        - Retrieve
        - Billing
        - Portal
        - Session
        - V1
        - Billing_portal
        - Configurations
        - Configuration
        - Sessions
tags:
  - name: Billing
    description: Needs a description.
  - name: Portals
    description: Needs a description.
  - name: Configurations
    description: Needs a description.
  - name: Session
    description: Needs a descriptio
