openapi: 3.0.0
info:
  title: Stripe Ephemeral Keys API
paths:
  /v1/ephemeral_keys:
    post:
      description: <p>Creates a short-lived API key for a given resource.</p>
      summary: Create Ephemeral Key
      tags:
        - Ephemeral
        - Keys
  /v1/ephemeral_keys/{key}:
    delete:
      description: <p>Invalidates a short-lived API key for a given resource.</p>
      summary: Delete Ephemeral Key
      tags:
        - Ephemeral
        - Keys
tags:
  - name: Ephemeral
    description: Needs a description.
  - name: Keys
    description: Needs a description.
