openapi: 3.0.0
info:
  title: Stripe Ephemeral Keys API
paths:
  /v1/ephemeral_keys:
    post:
      description: <p>Creates a short-lived API key for a given resource.</p>
  /v1/ephemeral_keys/{key}:
    delete:
      description: <p>Invalidates a short-lived API key for a given resou
