openapi: 3.0.0
info:
  title: Stripe Financial Connections API
paths:
  /v1/financial_connections/accounts:
    get:
      description: >-
        <p>Returns a list of Financial Connections <code>Account</code>
        objects.</p>
  /v1/financial_connections/accounts/{account}:
    get:
      description: >-
        <p>Retrieves the details of an Financial Connections
        <code>Account</code>.</p>
  /v1/financial_connections/accounts/{account}/disconnect:
    post:
      description: >-
        <p>Disables your access to a Financial Connections <code>Account</code>.
        You will no longer be able to access data associated with the account
        (e.g. balances, transactions).</p>
  /v1/financial_connections/accounts/{account}/owners:
    get:
      description: <p>Lists all owners for a given <code>Account</code></p>
  /v1/financial_connections/accounts/{account}/refresh:
    post:
      description: >-
        <p>Refreshes the data associated with a Financial Connections
        <code>Account</code>.</p>
  /v1/financial_connections/accounts/{account}/subscribe:
    post:
      description: >-
        <p>Subscribes to periodic refreshes of data associated with a Financial
        Connections <code>Account</code>.</p>
  /v1/financial_connections/accounts/{account}/unsubscribe:
    post:
      description: >-
        <p>Unsubscribes from periodic refreshes of data associated with a
        Financial Connections <code>Account</code>.</p>
  /v1/financial_connections/sessions:
    post:
      description: >-
        <p>To launch the Financial Connections authorization flow, create a
        <code>Session</code>. The session’s <code>client_secret</code> can be
        used to launch the flow using Stripe.js.</p>
  /v1/financial_connections/sessions/{session}:
    get:
      description: >-
        <p>Retrieves the details of a Financial Connections
        <code>Session</code></p>
  /v1/financial_connections/transactions:
    get:
      description: >-
        <p>Returns a list of Financial Connections <code>Transaction</code>
        objects.</p>
  /v1/financial_connections/transactions/{transaction}:
    get:
      description: <p>Retrieves the details of a Financial Connections <code>Transaction</c
