openapi: 3.0.0
info:
  title: Stripe Payment Method API
paths:
  /v1/payment_method_configurations:
    get:
      description: <p>List payment method configurations</p>
      summary: Retrieve Payment Method Configurations
      tags:
        - Payments
        - Methods
        - Configurations
    post:
      description: <p>Creates a payment method configuration</p>
      summary: Create Payment Method Configuration
      tags:
        - Payments
        - Methods
        - Configurations
  /v1/payment_method_configurations/{configuration}:
    get:
      description: <p>Retrieve payment method configuration</p>
      summary: Retrieve Payment Method Configuration
      tags:
        - Payments
        - Methods
        - Configurations
    post:
      description: <p>Update payment method configuration</p>
      summary: Update Payment Method Configuration
      tags:
        - Payments
        - Methods
        - Configurations
  /v1/payment_method_domains:
    get:
      description: <p>Lists the details of existing payment method domains.</p>
      summary: Retrieve Payment Method Domains
      tags:
        - Payments
        - Methods
        - Domains
    post:
      description: <p>Creates a payment method domain.</p>
      summary: Create Payment Method Domain
      tags:
        - Payments
        - Methods
        - Domains
  /v1/payment_method_domains/{payment_method_domain}:
    get:
      description: <p>Retrieves the details of an existing payment method domain.</p>
      summary: Retrieve Payment Method Domain
      tags:
        - Payments
        - Methods
        - Domains
    post:
      description: <p>Updates an existing payment method domain.</p>
      summary: Update Payment Method Domain
      tags:
        - Payments
        - Methods
        - Domains
  /v1/payment_method_domains/{payment_method_domain}/validate:
    post:
      description: >-
        <p>Some payment methods such as Apple Pay require additional steps to
        verify a domain. If the requirements weren’t satisfied when the domain
        was created, the payment method will be inactive on the domain.

        The payment method doesn’t appear in Elements for this domain until it
        is active.</p>


        <p>To activate a payment method on an existing payment method domain,
        complete the required validation steps specific to the payment method,
        and then validate the payment method domain with this endpoint.</p>


        <p>Related guides: <a
        href="/docs/payments/payment-methods/pmd-registration">Payment method
        domains</a>.</p>
      summary: Validate Payment Method Domain
      tags:
        - Validate
        - Payments
        - Methods
        - Domains
  /v1/payment_methods:
    get:
      description: >-
        <p>Returns a list of PaymentMethods for Treasury flows. If you want to
        list the PaymentMethods attached to a Customer for payments, you should
        use the <a href="/docs/api/payment_methods/customer_list">List a
        Customer’s PaymentMethods</a> API instead.</p>
      summary: Retrieve Payment Methods
      tags:
        - Payments
        - Methods
    post:
      description: >-
        <p>Creates a PaymentMethod object. Read the <a
        href="/docs/stripe-js/reference#stripe-create-payment-method">Stripe.js
        reference</a> to learn how to create PaymentMethods via Stripe.js.</p>


        <p>Instead of creating a PaymentMethod directly, we recommend using the
        <a href="/docs/payments/accept-a-payment">PaymentIntents</a> API to
        accept a payment immediately or the <a
        href="/docs/payments/save-and-reuse">SetupIntent</a> API to collect
        payment method details ahead of a future payment.</p>
      summary: Create Payment Method
      tags:
        - Payments
        - Methods
  /v1/payment_methods/{payment_method}:
    get:
      description: >-
        <p>Retrieves a PaymentMethod object attached to the StripeAccount. To
        retrieve a payment method attached to a Customer, you should use <a
        href="/docs/api/payment_methods/customer">Retrieve a Customer’s
        PaymentMethods</a></p>
      summary: Retrieve Payment Method
      tags:
        - Payments
        - Methods
    post:
      description: >-
        <p>Updates a PaymentMethod object. A PaymentMethod must be attached a
        customer to be updated.</p>
      summary: Update Payment Method
      tags:
        - Payments
        - Methods
  /v1/payment_methods/{payment_method}/attach:
    post:
      description: >-
        <p>Attaches a PaymentMethod object to a Customer.</p>


        <p>To attach a new PaymentMethod to a customer for future payments, we
        recommend you use a <a href="/docs/api/setup_intents">SetupIntent</a>

        or a PaymentIntent with <a
        href="/docs/api/payment_intents/create#create_payment_intent-setup_future_usage">setup_future_usage</a>.

        These approaches will perform any necessary steps to set up the
        PaymentMethod for future payments. Using the
        <code>/v1/payment_methods/:id/attach</code>

        endpoint without first using a SetupIntent or PaymentIntent with
        <code>setup_future_usage</code> does not optimize the PaymentMethod for

        future use, which makes later declines and payment friction more likely.

        See <a href="/docs/payments/payment-intents#future-usage">Optimizing
        cards for future payments</a> for more information about setting up

        future payments.</p>


        <p>To use this PaymentMethod as the default for invoice or subscription
        payments,

        set <a
        href="/docs/api/customers/update#update_customer-invoice_settings-default_payment_method"><code>invoice_settings.default_payment_method</code></a>,

        on the Customer to the PaymentMethod’s ID.</p>
      summary: Attach Payment Method
      tags:
        - Attach
        - Payments
        - Methods
  /v1/payment_methods/{payment_method}/detach:
    post:
      description: >-
        <p>Detaches a PaymentMethod object from a Customer. After a
        PaymentMethod is detached, it can no longer be used for a payment or
        re-attached to a Customer.</p>
      summary: Detach Payment Method
      tags:
        - Detach
        - Payments
        - Methods
tags:
  - name: Payments
    description: Needs a description.
  - name: Methods
    description: Needs a description.
  - name: Configurations
    description: Needs a description.
  - name: Domains
    description: Needs a description.
  - name: Validate
    description: Needs a description.
  - name: Attach
    description: Needs a description.
  - name: Detach
    description: Needs a description.
