openapi: 3.0.0
info:
  title: Stripe Payment Links API
paths:
  /v1/payment_links:
    get:
      description: <p>Returns a list of your payment links.</p>
      summary: Retrieve Payment Links
      tags:
        - Payments
        - Links
    post:
      description: <p>Creates a payment link.</p>
      summary: Create Payment Link
      tags:
        - Payments
        - Links
  /v1/payment_links/{payment_link}:
    get:
      description: <p>Retrieve a payment link.</p>
      summary: Retrieve Payment Link
      tags:
        - Payments
        - Links
    post:
      description: <p>Updates a payment link.</p>
      summary: Update Payment Link
      tags:
        - Payments
        - Links
  /v1/payment_links/{payment_link}/line_items:
    get:
      description: >-
        <p>When retrieving a payment link, there is an includable
        <strong>line_items</strong> property containing the first handful of
        those items. There is also a URL where you can retrieve the full
        (paginated) list of line items.</p>
      summary: Retrieve Payment Link Line Items
      tags:
        - Payments
        - Links
        - Lines
        - Items
tags:
  - name: Payments
    description: Needs a description.
  - name: Links
    description: Needs a description.
  - name: Lines
    description: Needs a description.
  - name: Items
    description: Needs a description.
