openapi: 3.0.0
info:
  title: Stripe Plans API
paths:
  /v1/plans:
    get:
      description: <p>Returns a list of your plans.</p>
    post:
      description: >-
        <p>You can now model subscriptions more flexibly using the <a
        href="#prices">Prices API</a>. It replaces the Plans API and is
        backwards compatible to simplify your migration.</p>
  /v1/plans/{plan}:
    delete:
      description: >-
        <p>Deleting plans means new subscribers can’t be added. Existing
        subscribers aren’t affected.</p>
    get:
      description: <p>Retrieves the plan with the given ID.</p>
    post:
      description: >-
        <p>Updates the specified plan by setting the values of the parameters
        passed. Any parameters not provided are left unchanged. By design, you
        cannot change a plan’s ID, amount, currency, or billing cy
