openapi: 3.0.0
info:
  title: Stripe Products API
paths:
  /v1/products:
    get:
      description: >-
        <p>Returns a list of your products. The products are returned sorted by
        creation date, with the most recently created products appearing
        first.</p>
      summary: Retrieve Products
      tags:
        - Retrieve
        - Products
        - V1
        - Products
    post:
      description: <p>Creates a new product object.</p>
      summary: Create Product
      tags:
        - Create
        - Product
        - V1
        - Products
  /v1/products/search:
    get:
      description: >-
        <p>Search for products you’ve previously created using Stripe’s <a
        href="/docs/search#search-query-language">Search Query Language</a>.

        Don’t use search in read-after-write flows where strict consistency is
        necessary. Under normal operating

        conditions, data is searchable in less than a minute. Occasionally,
        propagation of new or updated data can be up

        to an hour behind during outages. Search functionality is not available
        to merchants in India.</p>
      summary: Search Products
      tags:
        - Search
        - Products
        - V1
        - Products
        - Search
  /v1/products/{id}:
    delete:
      description: >-
        <p>Delete a product. Deleting a product is only possible if it has no
        prices associated with it. Additionally, deleting a product with
        <code>type=good</code> is only possible if it has no SKUs associated
        with it.</p>
      summary: Delete Product
      tags:
        - Delete
        - Product
        - V1
        - Products
        - Search
        - Id
    get:
      description: >-
        <p>Retrieves the details of an existing product. Supply the unique
        product ID from either a product creation request or the product list,
        and Stripe will return the corresponding product information.</p>
      summary: Retrieve Product
      tags:
        - Retrieve
        - Product
        - V1
        - Products
        - Search
        - Id
    post:
      description: >-
        <p>Updates the specific product by setting the values of the parameters
        passed. Any parameters not provided will be left unchanged.</p>
      summary: Update Product
      tags:
        - Update
        - Product
        - V1
        - Products
        - Search
        - Id
tags:
  - name: Products
    description: Needs a description.
  - name: Search
    description: Needs a descriptio
