openapi: 3.0.0
info:
  title: Stripe Radar API
paths:
  /v1/radar/early_fraud_warnings:
    get:
      description: <p>Returns a list of early fraud warnings.</p>
      summary: Retrieve Early Fraud Warnings
      tags:
        - Retrieve
        - Early
        - Fraud
        - Warnings
        - V1
        - Radar
        - Early_fraud_warnings
  /v1/radar/early_fraud_warnings/{early_fraud_warning}:
    get:
      description: >-
        <p>Retrieves the details of an early fraud warning that has previously
        been created. </p>


        <p>Please refer to the <a href="#early_fraud_warning_object">early fraud
        warning</a> object reference for more details.</p>
      summary: Retrieve Early Fraud Warning
      tags:
        - Retrieve
        - Early
        - Fraud
        - Warning
        - V1
        - Radar
        - Early_fraud_warnings
        - Early_fraud_warning
  /v1/radar/value_list_items:
    get:
      description: >-
        <p>Returns a list of <code>ValueListItem</code> objects. The objects are
        sorted in descending order by creation date, with the most recently
        created object appearing first.</p>
      summary: Retrieve Value List Items
      tags:
        - Retrieve
        - Value
        - List
        - Items
        - V1
        - Radar
        - Early_fraud_warnings
        - Early_fraud_warning
        - Value_list_items
    post:
      description: >-
        <p>Creates a new <code>ValueListItem</code> object, which is added to
        the specified parent value list.</p>
      summary: Create Value List Items
      tags:
        - Create
        - Value
        - List
        - Items
        - V1
        - Radar
        - Early_fraud_warnings
        - Early_fraud_warning
        - Value_list_items
  /v1/radar/value_list_items/{item}:
    delete:
      description: >-
        <p>Deletes a <code>ValueListItem</code> object, removing it from its
        parent value list.</p>
      summary: Delete Value List Item
      tags:
        - Delete
        - Value
        - List
        - Item
        - V1
        - Radar
        - Early_fraud_warnings
        - Early_fraud_warning
        - Value_list_items
        - Item
    get:
      description: <p>Retrieves a <code>ValueListItem</code> object.</p>
      summary: Retrieve Value List Item
      tags:
        - Retrieve
        - Value
        - List
        - Item
        - V1
        - Radar
        - Early_fraud_warnings
        - Early_fraud_warning
        - Value_list_items
        - Item
  /v1/radar/value_lists:
    get:
      description: >-
        <p>Returns a list of <code>ValueList</code> objects. The objects are
        sorted in descending order by creation date, with the most recently
        created object appearing first.</p>
      summary: Retrieve Value Lists
      tags:
        - Retrieve
        - Value
        - Lists
        - V1
        - Radar
        - Early_fraud_warnings
        - Early_fraud_warning
        - Value_list_items
        - Item
        - Value_lists
    post:
      description: >-
        <p>Creates a new <code>ValueList</code> object, which can then be
        referenced in rules.</p>
      summary: Create Value List
      tags:
        - Create
        - Value
        - List
        - V1
        - Radar
        - Early_fraud_warnings
        - Early_fraud_warning
        - Value_list_items
        - Item
        - Value_lists
  /v1/radar/value_lists/{value_list}:
    delete:
      description: >-
        <p>Deletes a <code>ValueList</code> object, also deleting any items
        contained within the value list. To be deleted, a value list must not be
        referenced in any rules.</p>
      summary: Delete Value List
      tags:
        - Delete
        - Value
        - List
        - V1
        - Radar
        - Early_fraud_warnings
        - Early_fraud_warning
        - Value_list_items
        - Item
        - Value_lists
        - Value_list
    get:
      description: <p>Retrieves a <code>ValueList</code> object.</p>
      summary: Retrieve Value List
      tags:
        - Retrieve
        - Value
        - List
        - V1
        - Radar
        - Early_fraud_warnings
        - Early_fraud_warning
        - Value_list_items
        - Item
        - Value_lists
        - Value_list
    post:
      description: >-
        <p>Updates a <code>ValueList</code> object by setting the values of the
        parameters passed. Any parameters not provided will be left unchanged.
        Note that <code>item_type</code> is immutable.</p>
      summary: Update Value List
      tags:
        - Update
        - Value
        - List
        - V1
        - Radar
        - Early_fraud_warnings
        - Early_fraud_warning
        - Value_list_items
        - Item
        - Value_lists
        - Value_list
tags:
  - name: Radar
    description: Needs a description.
  - name: Early
    description: Needs a description.
  - name: Fraud
    description: Needs a description.
  - name: Warnings
    description: Needs a description.
  - name: Values
    description: Needs a description.
  - name: Lists
    description: Needs a description.
  - name: Items
    description: Needs a descriptio
