openapi: 3.0.0
info:
  title: Stripe Sigma API
paths:
  /v1/sigma/scheduled_query_runs:
    get:
      description: <p>Returns a list of scheduled query runs.</p>
      summary: Retrieve Scheduled Query Runs
      tags:
        - Scheduled
        - Query
        - Runs
        - Sigma
  /v1/sigma/scheduled_query_runs/{scheduled_query_run}:
    get:
      description: <p>Retrieves the details of an scheduled query run.</p>
      summary: Retrieve Scheduled Query Run
      tags:
        - Scheduled
        - Query
        - Runs
        - Sigma
tags:
  - name: Scheduled
    description: Needs a description.
  - name: Query
    description: Needs a description.
  - name: Runs
    description: Needs a description.
  - name: ' '
    description: Needs a description.
  - name: Sigma
    description: Needs a description.
