openapi: 3.0.0
info:
  title: Stripe Treasury API
paths:
  /v1/treasury/credit_reversals:
    get:
      description: <p>Returns a list of CreditReversals.</p>
      summary: Retrieve Credit Reversals
      tags:
        - Retrieve
        - Credit
        - Reversals
        - V1
        - Treasury
        - Credit_reversals
    post:
      description: <p>Reverses a ReceivedCredit and creates a CreditReversal object.</p>
      summary: Create Credit Reversal
      tags:
        - Create
        - Credit
        - Reversal
        - V1
        - Treasury
        - Credit_reversals
  /v1/treasury/credit_reversals/{credit_reversal}:
    get:
      description: >-
        <p>Retrieves the details of an existing CreditReversal by passing the
        unique CreditReversal ID from either the CreditReversal creation request
        or CreditReversal list</p>
      summary: Retrieve Credit Reversal
      tags:
        - Retrieve
        - Credit
        - Reversal
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
  /v1/treasury/debit_reversals:
    get:
      description: <p>Returns a list of DebitReversals.</p>
      summary: Retrieve Debit Reversals
      tags:
        - Retrieve
        - Debit
        - Reversals
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
    post:
      description: <p>Reverses a ReceivedDebit and creates a DebitReversal object.</p>
      summary: Create Debit Reversal
      tags:
        - Create
        - Debit
        - Reversal
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
  /v1/treasury/debit_reversals/{debit_reversal}:
    get:
      description: <p>Retrieves a DebitReversal object.</p>
      summary: Retrieve Debit Reversal
      tags:
        - Retrieve
        - Debit
        - Reversal
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
  /v1/treasury/financial_accounts:
    get:
      description: <p>Returns a list of FinancialAccounts.</p>
      summary: Retrieve Financial Accounts
      tags:
        - Retrieve
        - Financial
        - Accounts
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
    post:
      description: >-
        <p>Creates a new FinancialAccount. For now, each connected account can
        only have one FinancialAccount.</p>
      summary: Create Financial Account
      tags:
        - Create
        - Financial
        - Account
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
  /v1/treasury/financial_accounts/{financial_account}:
    get:
      description: <p>Retrieves the details of a FinancialAccount.</p>
      summary: Retrieve Financial Account
      tags:
        - Retrieve
        - Financial
        - Account
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
    post:
      description: <p>Updates the details of a FinancialAccount.</p>
      summary: Update Financial Account
      tags:
        - Update
        - Financial
        - Account
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
  /v1/treasury/financial_accounts/{financial_account}/features:
    get:
      description: >-
        <p>Retrieves Features information associated with the
        FinancialAccount.</p>
      summary: Retrieve Financial Account Features
      tags:
        - Retrieve
        - Financial
        - Account
        - Features
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
    post:
      description: <p>Updates the Features associated with a FinancialAccount.</p>
      summary: Update Financial Account Feature
      tags:
        - Update
        - Financial
        - Account
        - Feature
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
  /v1/treasury/inbound_transfers:
    get:
      description: >-
        <p>Returns a list of InboundTransfers sent from the specified
        FinancialAccount.</p>
      summary: Retrieve Inbound Transfers
      tags:
        - Retrieve
        - Inbound
        - Transfers
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
    post:
      description: <p>Creates an InboundTransfer.</p>
      summary: Create Inbound Transfer
      tags:
        - Create
        - Inbound
        - Transfer
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
  /v1/treasury/inbound_transfers/{id}:
    get:
      description: <p>Retrieves the details of an existing InboundTransfer.</p>
      summary: Retrieve Inbound Transfer
      tags:
        - Retrieve
        - Inbound
        - Transfer
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
  /v1/treasury/inbound_transfers/{inbound_transfer}/cancel:
    post:
      description: <p>Cancels an InboundTransfer.</p>
      summary: Cancel Inbound Transfer
      tags:
        - Cancel
        - Inbound
        - Transfer
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
  /v1/treasury/outbound_payments:
    get:
      description: >-
        <p>Returns a list of OutboundPayments sent from the specified
        FinancialAccount.</p>
      summary: Retrieve Outbound Payments
      tags:
        - Retrieve
        - Outbound
        - Payments
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
    post:
      description: <p>Creates an OutboundPayment.</p>
      summary: Create Outbound Payment
      tags:
        - Create
        - Outbound
        - Payment
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
  /v1/treasury/outbound_payments/{id}:
    get:
      description: >-
        <p>Retrieves the details of an existing OutboundPayment by passing the
        unique OutboundPayment ID from either the OutboundPayment creation
        request or OutboundPayment list.</p>
      summary: Retrieve Outbound Payment
      tags:
        - Retrieve
        - Outbound
        - Payment
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
  /v1/treasury/outbound_payments/{id}/cancel:
    post:
      description: <p>Cancel an OutboundPayment.</p>
      summary: Cacel Outbound Payment
      tags:
        - Cacel
        - Outbound
        - Payment
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
  /v1/treasury/outbound_transfers:
    get:
      description: >-
        <p>Returns a list of OutboundTransfers sent from the specified
        FinancialAccount.</p>
      summary: Retrieve Outbound Transfers
      tags:
        - Retrieve
        - Outbound
        - Transfers
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
    post:
      description: <p>Creates an OutboundTransfer.</p>
      summary: Create Outbound Transfer
      tags:
        - Create
        - Outbound
        - Transfer
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
  /v1/treasury/outbound_transfers/{outbound_transfer}:
    get:
      description: >-
        <p>Retrieves the details of an existing OutboundTransfer by passing the
        unique OutboundTransfer ID from either the OutboundTransfer creation
        request or OutboundTransfer list.</p>
      summary: Retrieve Outbound Transfer
      tags:
        - Retrieve
        - Outbound
        - Transfer
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
        - Outbound_transfer
  /v1/treasury/outbound_transfers/{outbound_transfer}/cancel:
    post:
      description: >-
        <p>An OutboundTransfer can be canceled if the funds have not yet been
        paid out.</p>
      summary: Cancel Outbound Transfer
      tags:
        - Cancel
        - Outbound
        - Transfer
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
        - Outbound_transfer
  /v1/treasury/received_credits:
    get:
      description: <p>Returns a list of ReceivedCredits.</p>
      summary: Retrieve Received Credits
      tags:
        - Retrieve
        - Received
        - Credits
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
        - Outbound_transfer
        - Received_credits
  /v1/treasury/received_credits/{id}:
    get:
      description: >-
        <p>Retrieves the details of an existing ReceivedCredit by passing the
        unique ReceivedCredit ID from the ReceivedCredit list.</p>
      summary: Retrieve Received Credit
      tags:
        - Retrieve
        - Received
        - Credit
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
        - Outbound_transfer
        - Received_credits
  /v1/treasury/received_debits:
    get:
      description: <p>Returns a list of ReceivedDebits.</p>
      summary: Retrieve Received Debits
      tags:
        - Retrieve
        - Received
        - Debits
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
        - Outbound_transfer
        - Received_credits
        - Received_debits
  /v1/treasury/received_debits/{id}:
    get:
      description: >-
        <p>Retrieves the details of an existing ReceivedDebit by passing the
        unique ReceivedDebit ID from the ReceivedDebit list</p>
      summary: Retrieve Received Debit
      tags:
        - Retrieve
        - Received
        - Debit
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
        - Outbound_transfer
        - Received_credits
        - Received_debits
  /v1/treasury/transaction_entries:
    get:
      description: <p>Retrieves a list of TransactionEntry objects.</p>
      summary: Retrieve Transaction Entries
      tags:
        - Retrieve
        - Transaction
        - Entries
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
        - Outbound_transfer
        - Received_credits
        - Received_debits
        - Transaction_entries
  /v1/treasury/transaction_entries/{id}:
    get:
      description: <p>Retrieves a TransactionEntry object.</p>
      summary: Retrieve Transaction Entry
      tags:
        - Retrieve
        - Transaction
        - Entry
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
        - Outbound_transfer
        - Received_credits
        - Received_debits
        - Transaction_entries
  /v1/treasury/transactions:
    get:
      description: <p>Retrieves a list of Transaction objects.</p>
      summary: Retrieve Transactions
      tags:
        - Retrieve
        - Transactions
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
        - Outbound_transfer
        - Received_credits
        - Received_debits
        - Transaction_entries
        - Transactions
  /v1/treasury/transactions/{id}:
    get:
      description: <p>Retrieves the details of an existing Transaction.</p>
      summary: Retrieve Transaction
      tags:
        - Retrieve
        - Transaction
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
        - Outbound_transfer
        - Received_credits
        - Received_debits
        - Transaction_entries
        - Transactions
tags:
  - name: Treasury
    description: Needs a description.
  - name: Credits
    description: Needs a description.
  - name: Reversals
    description: Needs a description.
  - name: Debit
    description: Needs a description.
  - name: Financial
    description: Needs a description.
  - name: Accounts
    description: Needs a description.
  - name: Features
    description: Needs a description.
  - name: Inbound
    description: Needs a description.
  - name: Transfers
    description: Needs a description.
  - name: Cancel
    description: Needs a description.
  - name: Outbound
    description: Needs a description.
  - name: Payments
    description: Needs a description.
  - name: Received
    description: Needs a description.
  - name: Debits
    description: Needs a description.
  - name: Transactiosn
    description: Needs a description.
  - name: Entries
    description: Needs a description.
  - name: Transactions
    description: Needs a descriptio
