openapi: 3.1.0
info:
  title: amplifyuibuilder
paths:
  /app/{appId}/environment/{environmentName}/components:
    GET:
      summary: ListComponents
      description: >-
        <p>Retrieves a list of components for a specified Amplify app and
        backend environment.</p>
  /app/{appId}/environment/{environmentName}/forms:
    GET:
      summary: ListForms
      description: >-
        <p>Retrieves a list of forms for a specified Amplify app and backend
        environment.</p>
  /app/{appId}/environment/{environmentName}/themes:
    GET:
      summary: ListThemes
      description: >-
        <p>Retrieves a list of themes for a specified Amplify app and backend
        environment.</p>
  /app/{appId}/environment/{environmentName}/components/{id}:
    PATCH:
      summary: UpdateComponent
      description: <p>Updates an existing component.</p>
  /app/{appId}/environment/{environmentName}/forms/{id}:
    PATCH:
      summary: UpdateForm
      description: <p>Updates an existing form.</p>
  /app/{appId}/environment/{environmentName}/themes/{id}:
    PATCH:
      summary: UpdateTheme
      description: <p>Updates an existing theme.</p>
  /tokens/{provider}:
    POST:
      summary: ExchangeCodeForToken
      description: >-
        <note> <p>This is for internal use.</p> </note> <p>Amplify uses this
        action to exchange an access code for a token.</p>
  /export/app/{appId}/environment/{environmentName}/components:
    GET:
      summary: ExportComponents
      description: >-
        <p>Exports component configurations to code that is ready to integrate
        into an Amplify app.</p>
  /export/app/{appId}/environment/{environmentName}/forms:
    GET:
      summary: ExportForms
      description: >-
        <p>Exports form configurations to code that is ready to integrate into
        an Amplify app.</p>
  /export/app/{appId}/environment/{environmentName}/themes:
    GET:
      summary: ExportThemes
      description: >-
        <p>Exports theme configurations to code that is ready to integrate into
        an Amplify app.</p>
  /app/{appId}/environment/{environmentName}/codegen-jobs/{id}:
    GET:
      summary: GetCodegenJob
      description: <p>Returns an existing code generation job.</p>
  /app/{appId}/environment/{environmentName}/metadata:
    GET:
      summary: GetMetadata
      description: <p>Returns existing metadata for an Amplify app.</p>
  /app/{appId}/environment/{environmentName}/codegen-jobs:
    POST:
      summary: StartCodegenJob
      description: >-
        <p>Starts a code generation job for a specified Amplify app and backend
        environment.</p>
  /app/{appId}/environment/{environmentName}/metadata/features/{featureName}:
    PUT:
      summary: PutMetadataFlag
      description: <p>Stores the metadata information about a feature on a form.</p>
  /tokens/{provider}/refresh:
    POST:
      summary: RefreshToken
      description: >-
        <note> <p>This is for internal use.</p> </note> <p>Amplify uses this
        action to refresh a previously issued access token that might have expi
