openapi: 3.1.0
info:
  title: amplifyuibuilder
paths:
  /app/{appId}/environment/{environmentName}/components:
    GET:
      summary: ListComponents
      description: >-
        <p>Retrieves a list of components for a specified Amplify app and
        backend environment.</p>
      tags:
        - List
        - Components
        - Id
        - Environment
        - Name
        - Components
  /app/{appId}/environment/{environmentName}/forms:
    GET:
      summary: ListForms
      description: >-
        <p>Retrieves a list of forms for a specified Amplify app and backend
        environment.</p>
      tags:
        - List
        - Forms
        - Id
        - Environment
        - Name
        - Components
        - Forms
  /app/{appId}/environment/{environmentName}/themes:
    GET:
      summary: ListThemes
      description: >-
        <p>Retrieves a list of themes for a specified Amplify app and backend
        environment.</p>
      tags:
        - List
        - Themes
        - Id
        - Environment
        - Name
        - Components
        - Forms
        - Themes
  /app/{appId}/environment/{environmentName}/components/{id}:
    PATCH:
      summary: UpdateComponent
      description: <p>Updates an existing component.</p>
      tags:
        - Update
        - Component
        - Id
        - Environment
        - Name
        - Components
        - Forms
        - Themes
  /app/{appId}/environment/{environmentName}/forms/{id}:
    PATCH:
      summary: UpdateForm
      description: <p>Updates an existing form.</p>
      tags:
        - Update
        - Form
        - Id
        - Environment
        - Name
        - Components
        - Forms
        - Themes
  /app/{appId}/environment/{environmentName}/themes/{id}:
    PATCH:
      summary: UpdateTheme
      description: <p>Updates an existing theme.</p>
      tags:
        - Update
        - Theme
        - Id
        - Environment
        - Name
        - Components
        - Forms
        - Themes
  /tokens/{provider}:
    POST:
      summary: ExchangeCodeForToken
      description: >-
        <note> <p>This is for internal use.</p> </note> <p>Amplify uses this
        action to exchange an access code for a token.</p>
      tags:
        - Exchange
        - Code
        - For
        - Token
        - Id
        - Environment
        - Name
        - Components
        - Forms
        - Themes
        - Tokens
        - Provider
  /export/app/{appId}/environment/{environmentName}/components:
    GET:
      summary: ExportComponents
      description: >-
        <p>Exports component configurations to code that is ready to integrate
        into an Amplify app.</p>
      tags:
        - Export
        - Components
        - Id
        - Environment
        - Name
        - Components
        - Forms
        - Themes
        - Tokens
        - Provider
  /export/app/{appId}/environment/{environmentName}/forms:
    GET:
      summary: ExportForms
      description: >-
        <p>Exports form configurations to code that is ready to integrate into
        an Amplify app.</p>
      tags:
        - Export
        - Forms
        - Id
        - Environment
        - Name
        - Components
        - Forms
        - Themes
        - Tokens
        - Provider
  /export/app/{appId}/environment/{environmentName}/themes:
    GET:
      summary: ExportThemes
      description: >-
        <p>Exports theme configurations to code that is ready to integrate into
        an Amplify app.</p>
      tags:
        - Export
        - Themes
        - Id
        - Environment
        - Name
        - Components
        - Forms
        - Themes
        - Tokens
        - Provider
  /app/{appId}/environment/{environmentName}/codegen-jobs/{id}:
    GET:
      summary: GetCodegenJob
      description: <p>Returns an existing code generation job.</p>
      tags:
        - Get
        - Codegen
        - Job
        - Id
        - Environment
        - Name
        - Components
        - Forms
        - Themes
        - Tokens
        - Provider
        - Codegen
        - Jobs
  /app/{appId}/environment/{environmentName}/metadata:
    GET:
      summary: GetMetadata
      description: <p>Returns existing metadata for an Amplify app.</p>
      tags:
        - Get
        - Metadata
        - Id
        - Environment
        - Name
        - Components
        - Forms
        - Themes
        - Tokens
        - Provider
        - Codegen
        - Jobs
        - Metadata
  /app/{appId}/environment/{environmentName}/codegen-jobs:
    POST:
      summary: StartCodegenJob
      description: >-
        <p>Starts a code generation job for a specified Amplify app and backend
        environment.</p>
      tags:
        - Start
        - Codegen
        - Job
        - Id
        - Environment
        - Name
        - Components
        - Forms
        - Themes
        - Tokens
        - Provider
        - Codegen
        - Jobs
        - Metadata
  /app/{appId}/environment/{environmentName}/metadata/features/{featureName}:
    PUT:
      summary: PutMetadataFlag
      description: <p>Stores the metadata information about a feature on a form.</p>
      tags:
        - Put
        - Metadata
        - Flag
        - Id
        - Environment
        - Name
        - Components
        - Forms
        - Themes
        - Tokens
        - Provider
        - Codegen
        - Jobs
        - Metadata
        - Features
        - Feature
  /tokens/{provider}/refresh:
    POST:
      summary: RefreshToken
      description: >-
        <note> <p>This is for internal use.</p> </note> <p>Amplify uses this
        action to refresh a previously issued access token that might have
        expired.</
      tags:
        - Refresh
        - Token
        - Id
        - Environment
        - Name
        - Components
        - Forms
        - Themes
        - Tokens
        - Provider
        - Codegen
        - Jobs
        - Metadata
        - Features
        - Feature
        - R
