openapi: 3.1.0
info:
  title: amplifybackend
paths:
  /backend/{appId}/environments/{backendEnvironmentName}/clone:
    POST:
      summary: CloneBackend
      description: <p>This operation clones an existing backend.</p>
      tags:
        - Clone
        - Backend
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
  /backend:
    POST:
      summary: CreateBackend
      description: >-
        <p>This operation creates a backend for an Amplify app. Backends are
        automatically created at the time of app creation.</p>
      tags:
        - Create
        - Backend
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
  /backend/{appId}/api:
    POST:
      summary: CreateBackendAPI
      description: <p>Creates a new backend API resource.</p>
      tags:
        - Create
        - Backend
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
  /backend/{appId}/auth:
    POST:
      summary: CreateBackendAuth
      description: <p>Creates a new backend authentication resource.</p>
      tags:
        - Create
        - Backend
        - Auth
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
  /backend/{appId}/config:
    POST:
      summary: CreateBackendConfig
      description: <p>Creates a config object for a backend.</p>
      tags:
        - Create
        - Backend
        - Config
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
  /backend/{appId}/storage:
    POST:
      summary: CreateBackendStorage
      description: <p>Creates a backend storage resource.</p>
      tags:
        - Create
        - Backend
        - Storage
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
  /backend/{appId}/challenge:
    POST:
      summary: CreateToken
      description: >-
        <p>Generates a one-time challenge code to authenticate a user into your
        Amplify Admin UI.</p>
      tags:
        - Create
        - Token
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
  /backend/{appId}/environments/{backendEnvironmentName}/remove:
    POST:
      summary: DeleteBackend
      description: <p>Removes an existing environment from your Amplify project.</p>
      tags:
        - Delete
        - Backend
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
  /backend/{appId}/api/{backendEnvironmentName}/remove:
    POST:
      summary: DeleteBackendAPI
      description: <p>Deletes an existing backend API resource.</p>
      tags:
        - Delete
        - Backend
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
  /backend/{appId}/auth/{backendEnvironmentName}/remove:
    POST:
      summary: DeleteBackendAuth
      description: <p>Deletes an existing backend authentication resource.</p>
      tags:
        - Delete
        - Backend
        - Auth
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
  /backend/{appId}/storage/{backendEnvironmentName}/remove:
    POST:
      summary: DeleteBackendStorage
      description: <p>Removes the specified backend storage resource.</p>
      tags:
        - Delete
        - Backend
        - Storage
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
  /backend/{appId}/challenge/{sessionId}/remove:
    POST:
      summary: DeleteToken
      description: >-
        <p>Deletes the challenge token based on the given appId and
        sessionId.</p>
      tags:
        - Delete
        - Token
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
        - Session
  /backend/{appId}/api/{backendEnvironmentName}/generateModels:
    POST:
      summary: GenerateBackendAPIModels
      description: <p>Generates a model schema for an existing backend API resource.</p>
      tags:
        - Generate
        - Backend
        - Models
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
        - Session
        - Generate
        - Models
  /backend/{appId}/details:
    POST:
      summary: GetBackend
      description: <p>Provides project-level details for your Amplify UI project.</p>
      tags:
        - Get
        - Backend
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
        - Session
        - Generate
        - Models
        - Details
  /backend/{appId}/api/{backendEnvironmentName}/details:
    POST:
      summary: GetBackendAPI
      description: <p>Gets the details for a backend API.</p>
      tags:
        - Get
        - Backend
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
        - Session
        - Generate
        - Models
        - Details
  /backend/{appId}/api/{backendEnvironmentName}/getModels:
    POST:
      summary: GetBackendAPIModels
      description: >-
        <p>Gets a model introspection schema for an existing backend API
        resource.</p>
      tags:
        - Get
        - Backend
        - Models
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
        - Session
        - Generate
        - Models
        - Details
        - Get
  /backend/{appId}/auth/{backendEnvironmentName}/details:
    POST:
      summary: GetBackendAuth
      description: <p>Gets a backend auth details.</p>
      tags:
        - Get
        - Backend
        - Auth
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
        - Session
        - Generate
        - Models
        - Details
        - Get
  /backend/{appId}/job/{backendEnvironmentName}/{jobId}:
    POST:
      summary: UpdateBackendJob
      description: <p>Updates a specific job.</p>
      tags:
        - Update
        - Backend
        - Job
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
        - Session
        - Generate
        - Models
        - Details
        - Get
        - Job
  /backend/{appId}/storage/{backendEnvironmentName}/details:
    POST:
      summary: GetBackendStorage
      description: <p>Gets details for a backend storage resource.</p>
      tags:
        - Get
        - Backend
        - Storage
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
        - Session
        - Generate
        - Models
        - Details
        - Get
        - Job
  /backend/{appId}/challenge/{sessionId}:
    GET:
      summary: GetToken
      description: <p>Gets the challenge token based on the given appId and sessionId.</p>
      tags:
        - Get
        - Token
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
        - Session
        - Generate
        - Models
        - Details
        - Get
        - Job
  /backend/{appId}/auth/{backendEnvironmentName}/import:
    POST:
      summary: ImportBackendAuth
      description: <p>Imports an existing backend authentication resource.</p>
      tags:
        - Import
        - Backend
        - Auth
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
        - Session
        - Generate
        - Models
        - Details
        - Get
        - Job
        - Import
  /backend/{appId}/storage/{backendEnvironmentName}/import:
    POST:
      summary: ImportBackendStorage
      description: <p>Imports an existing backend storage resource.</p>
      tags:
        - Import
        - Backend
        - Storage
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
        - Session
        - Generate
        - Models
        - Details
        - Get
        - Job
        - Import
  /backend/{appId}/job/{backendEnvironmentName}:
    POST:
      summary: ListBackendJobs
      description: <p>Lists the jobs for the backend of an Amplify app.</p>
      tags:
        - List
        - Backend
        - Jobs
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
        - Session
        - Generate
        - Models
        - Details
        - Get
        - Job
        - Import
  /s3Buckets:
    POST:
      summary: ListS3Buckets
      description: <p>The list of S3 buckets in your account.</p>
      tags:
        - List
        - S3
        - Buckets
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
        - Session
        - Generate
        - Models
        - Details
        - Get
        - Job
        - Import
        - Buckets
  /backend/{appId}/remove:
    POST:
      summary: RemoveAllBackends
      description: <p>Removes all backend environments from your Amplify project.</p>
      tags:
        - Remove
        - All
        - Backends
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
        - Session
        - Generate
        - Models
        - Details
        - Get
        - Job
        - Import
        - Buckets
  /backend/{appId}/config/remove:
    POST:
      summary: RemoveBackendConfig
      description: >-
        <p>Removes the AWS resources required to access the Amplify Admin
        UI.</p>
      tags:
        - Remove
        - Backend
        - Config
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
        - Session
        - Generate
        - Models
        - Details
        - Get
        - Job
        - Import
        - Buckets
  /backend/{appId}/api/{backendEnvironmentName}:
    POST:
      summary: UpdateBackendAPI
      description: <p>Updates an existing backend API resource.</p>
      tags:
        - Update
        - Backend
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
        - Session
        - Generate
        - Models
        - Details
        - Get
        - Job
        - Import
        - Buckets
  /backend/{appId}/auth/{backendEnvironmentName}:
    POST:
      summary: UpdateBackendAuth
      description: <p>Updates an existing backend authentication resource.</p>
      tags:
        - Update
        - Backend
        - Auth
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
        - Session
        - Generate
        - Models
        - Details
        - Get
        - Job
        - Import
        - Buckets
  /backend/{appId}/config/update:
    POST:
      summary: UpdateBackendConfig
      description: >-
        <p>Updates the AWS resources required to access the Amplify Admin
        UI.</p>
      tags:
        - Update
        - Backend
        - Config
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
        - Session
        - Generate
        - Models
        - Details
        - Get
        - Job
        - Import
        - Buckets
        - Update
  /backend/{appId}/storage/{backendEnvironmentName}:
    POST:
      summary: UpdateBackendStorage
      description: <p>Updates an existing backend storage res
      tags:
        - Update
        - Backend
        - Storage
        - Id
        - Environments
        - Backend
        - Environment
        - Name
        - Clone
        - Api
        - Auth
        - Config
        - Storage
        - Challenge
        - Remove
        - Session
        - Generate
        - Models
        - Details
        - Get
        - Job
        - Import
        - Buckets
        - Upda
