openapi: 3.1.0
info:
  title: apigatewaymanagementapi
paths:
  /@connections/{connectionId}:
    POST:
      summary: PostToConnection
      description: <p>Sends the provided data to the specified connection.</
      tags:
        - Post
        - To
        - Connection
        - Id
