openapi: 3.1.0
info:
  title: appconfig
paths:
  /applications:
    GET:
      summary: ListApplications
      description: <p>Lists all applications in your Amazon Web Services account.</p>
  /applications/{ApplicationId}/configurationprofiles:
    GET:
      summary: ListConfigurationProfiles
      description: <p>Lists the configuration profiles for an application.</p>
  /deploymentstrategies:
    GET:
      summary: ListDeploymentStrategies
      description: <p>Lists deployment strategies.</p>
  /applications/{ApplicationId}/environments:
    GET:
      summary: ListEnvironments
      description: <p>Lists the environments for an application.</p>
  /extensions:
    GET:
      summary: ListExtensions
      description: >-
        <p>Lists all custom and Amazon Web Services authored AppConfig
        extensions in the account. For more information about extensions, see <a
        href="https://docs.aws.amazon.com/appconfig/latest/userguide/working-with-appconfig-extensions.html">Working
        with AppConfig extensions</a> in the <i>AppConfig User Guide</i>.</p>
  /extensionassociations:
    GET:
      summary: ListExtensionAssociations
      description: >-
        <p>Lists all AppConfig extension associations in the account. For more
        information about extensions and associations, see <a
        href="https://docs.aws.amazon.com/appconfig/latest/userguide/working-with-appconfig-extensions.html">Working
        with AppConfig extensions</a> in the <i>AppConfig User Guide</i>.</p>
  /applications/{ApplicationId}/configurationprofiles/{ConfigurationProfileId}/hostedconfigurationversions:
    GET:
      summary: ListHostedConfigurationVersions
      description: >-
        <p>Lists configurations stored in the AppConfig hosted configuration
        store by version.</p>
  /applications/{ApplicationId}:
    PATCH:
      summary: UpdateApplication
      description: <p>Updates an application.</p>
  /applications/{ApplicationId}/configurationprofiles/{ConfigurationProfileId}:
    PATCH:
      summary: UpdateConfigurationProfile
      description: <p>Updates a configuration profile.</p>
  /deployementstrategies/{DeploymentStrategyId}:
    DELETE:
      summary: DeleteDeploymentStrategy
      description: >-
        <p>Deletes a deployment strategy. Deleting a deployment strategy does
        not delete a configuration from a host.</p>
  /applications/{ApplicationId}/environments/{EnvironmentId}:
    PATCH:
      summary: UpdateEnvironment
      description: <p>Updates an environment.</p>
  /extensions/{ExtensionIdentifier}:
    PATCH:
      summary: UpdateExtension
      description: >-
        <p>Updates an AppConfig extension. For more information about
        extensions, see <a
        href="https://docs.aws.amazon.com/appconfig/latest/userguide/working-with-appconfig-extensions.html">Working
        with AppConfig extensions</a> in the <i>AppConfig User Guide</i>.</p>
  /extensionassociations/{ExtensionAssociationId}:
    PATCH:
      summary: UpdateExtensionAssociation
      description: >-
        <p>Updates an association. For more information about extensions and
        associations, see <a
        href="https://docs.aws.amazon.com/appconfig/latest/userguide/working-with-appconfig-extensions.html">Working
        with AppConfig extensions</a> in the <i>AppConfig User Guide</i>.</p>
  /applications/{ApplicationId}/configurationprofiles/{ConfigurationProfileId}/hostedconfigurationversions/{VersionNumber}:
    GET:
      summary: GetHostedConfigurationVersion
      description: <p>Retrieves information about a specific configuration version.</p>
  /applications/{Application}/environments/{Environment}/configurations/{Configuration}:
    GET:
      summary: GetConfiguration
      description: >-
        <p>(Deprecated) Retrieves the latest deployed configuration.</p>
        <important> <p>Note the following important information.</p> <ul> <li>
        <p>This API action is deprecated. Calls to receive configuration data
        should use the <a
        href="https://docs.aws.amazon.com/appconfig/2019-10-09/APIReference/API_appconfigdata_StartConfigurationSession.html">StartConfigurationSession</a>
        and <a
        href="https://docs.aws.amazon.com/appconfig/2019-10-09/APIReference/API_appconfigdata_GetLatestConfiguration.html">GetLatestConfiguration</a>
        APIs instead. </p> </li> <li> <p> <code>GetConfiguration</code> is a
        priced call. For more information, see <a
        href="https://aws.amazon.com/systems-manager/pricing/">Pricing</a>.</p>
        </li> </ul> </important>
  /applications/{ApplicationId}/environments/{EnvironmentId}/deployments/{DeploymentNumber}:
    DELETE:
      summary: StopDeployment
      description: >-
        <p>Stops a deployment. This API action works only on deployments that
        have a status of <code>DEPLOYING</code>. This action moves the
        deployment to a status of <code>ROLLED_BACK</code>.</p>
  /deploymentstrategies/{DeploymentStrategyId}:
    PATCH:
      summary: UpdateDeploymentStrategy
      description: <p>Updates a deployment strategy.</p>
  /applications/{ApplicationId}/environments/{EnvironmentId}/deployments:
    POST:
      summary: StartDeployment
      description: <p>Starts a deployment.</p>
  /tags/{ResourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Deletes a tag key and value from an AppConfig resource.</p>
  /applications/{ApplicationId}/configurationprofiles/{ConfigurationProfileId}/validators:
    POST:
      summary: ValidateConfiguration
      description: >-
        <p>Uses the validators in a configuration profile to validate a
        configurat
