openapi: 3.1.0
info:
  title: appintegrations
paths:
  /applications:
    GET:
      summary: ListApplications
      description: >-
        <p>This API is in preview release and subject to change.</p> <p>Lists
        applications in the account.</p>
  /dataIntegrations:
    GET:
      summary: ListDataIntegrations
      description: >-
        <p>Returns a paginated list of DataIntegrations in the account.</p>
        <note> <p>You cannot create a DataIntegration association for a
        DataIntegration that has been previously associated. Use a different
        DataIntegration, or recreate the DataIntegration using the <a
        href="https://docs.aws.amazon.com/appintegrations/latest/APIReference/API_CreateDataIntegration.html">CreateDataIntegration</a>
        API.</p> </note>
  /eventIntegrations:
    GET:
      summary: ListEventIntegrations
      description: <p>Returns a paginated list of event integrations in the account.</p>
  /applications/{ApplicationIdentifier}:
    PATCH:
      summary: UpdateApplication
      description: >-
        <p>This API is in preview release and subject to change.</p> <p>Updates
        and persists an Application resource.</p>
  /dataIntegrations/{Identifier}:
    PATCH:
      summary: UpdateDataIntegration
      description: >-
        <p>Updates the description of a DataIntegration.</p> <note> <p>You
        cannot create a DataIntegration association for a DataIntegration that
        has been previously associated. Use a different DataIntegration, or
        recreate the DataIntegration using the <a
        href="https://docs.aws.amazon.com/appintegrations/latest/APIReference/API_CreateDataIntegration.html">CreateDataIntegration</a>
        API.</p> </note>
  /eventIntegrations/{Name}:
    PATCH:
      summary: UpdateEventIntegration
      description: <p>Updates the description of an event integration.</p>
  /applications/{ApplicationIdentifier}/associations:
    GET:
      summary: ListApplicationAssociations
      description: >-
        <p>Returns a paginated list of application associations for an
        application.</p>
  /dataIntegrations/{Identifier}/associations:
    GET:
      summary: ListDataIntegrationAssociations
      description: >-
        <p>Returns a paginated list of DataIntegration associations in the
        account.</p> <note> <p>You cannot create a DataIntegration association
        for a DataIntegration that has been previously associated. Use a
        different DataIntegration, or recreate the DataIntegration using the <a
        href="https://docs.aws.amazon.com/appintegrations/latest/APIReference/API_CreateDataIntegration.html">CreateDataIntegration</a>
        API.</p> </note>
  /eventIntegrations/{Name}/associations:
    GET:
      summary: ListEventIntegrationAssociations
      description: >-
        <p>Returns a paginated list of event integration associations in the
        account. </p>
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Removes the specified tags from the specified resou
