openapi: 3.1.0
info:
  title: appintegrations
paths:
  /applications:
    GET:
      summary: ListApplications
      description: >-
        <p>This API is in preview release and subject to change.</p> <p>Lists
        applications in the account.</p>
      tags:
        - List
        - Applications
        - Applications
  /dataIntegrations:
    GET:
      summary: ListDataIntegrations
      description: >-
        <p>Returns a paginated list of DataIntegrations in the account.</p>
        <note> <p>You cannot create a DataIntegration association for a
        DataIntegration that has been previously associated. Use a different
        DataIntegration, or recreate the DataIntegration using the <a
        href="https://docs.aws.amazon.com/appintegrations/latest/APIReference/API_CreateDataIntegration.html">CreateDataIntegration</a>
        API.</p> </note>
      tags:
        - List
        - Data
        - Integrations
        - Applications
        - Integrations
  /eventIntegrations:
    GET:
      summary: ListEventIntegrations
      description: <p>Returns a paginated list of event integrations in the account.</p>
      tags:
        - List
        - Event
        - Integrations
        - Applications
        - Integrations
  /applications/{ApplicationIdentifier}:
    PATCH:
      summary: UpdateApplication
      description: >-
        <p>This API is in preview release and subject to change.</p> <p>Updates
        and persists an Application resource.</p>
      tags:
        - Update
        - Application
        - Applications
        - Integrations
        - Application
        - Identifier
  /dataIntegrations/{Identifier}:
    PATCH:
      summary: UpdateDataIntegration
      description: >-
        <p>Updates the description of a DataIntegration.</p> <note> <p>You
        cannot create a DataIntegration association for a DataIntegration that
        has been previously associated. Use a different DataIntegration, or
        recreate the DataIntegration using the <a
        href="https://docs.aws.amazon.com/appintegrations/latest/APIReference/API_CreateDataIntegration.html">CreateDataIntegration</a>
        API.</p> </note>
      tags:
        - Update
        - Data
        - Integration
        - Applications
        - Integrations
        - Application
        - Identifier
  /eventIntegrations/{Name}:
    PATCH:
      summary: UpdateEventIntegration
      description: <p>Updates the description of an event integration.</p>
      tags:
        - Update
        - Event
        - Integration
        - Applications
        - Integrations
        - Application
        - Identifier
        - Name
  /applications/{ApplicationIdentifier}/associations:
    GET:
      summary: ListApplicationAssociations
      description: >-
        <p>Returns a paginated list of application associations for an
        application.</p>
      tags:
        - List
        - Application
        - Associations
        - Applications
        - Integrations
        - Application
        - Identifier
        - Name
        - Associations
  /dataIntegrations/{Identifier}/associations:
    GET:
      summary: ListDataIntegrationAssociations
      description: >-
        <p>Returns a paginated list of DataIntegration associations in the
        account.</p> <note> <p>You cannot create a DataIntegration association
        for a DataIntegration that has been previously associated. Use a
        different DataIntegration, or recreate the DataIntegration using the <a
        href="https://docs.aws.amazon.com/appintegrations/latest/APIReference/API_CreateDataIntegration.html">CreateDataIntegration</a>
        API.</p> </note>
      tags:
        - List
        - Data
        - Integration
        - Associations
        - Applications
        - Integrations
        - Application
        - Identifier
        - Name
        - Associations
  /eventIntegrations/{Name}/associations:
    GET:
      summary: ListEventIntegrationAssociations
      description: >-
        <p>Returns a paginated list of event integration associations in the
        account. </p>
      tags:
        - List
        - Event
        - Integration
        - Associations
        - Applications
        - Integrations
        - Application
        - Identifier
        - Name
        - Associations
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Removes the specified tags from the specified resource.</
      tags:
        - Untag
        - Resource
        - Applications
        - Integrations
        - Application
        - Identifier
        - Name
        - Associations
        - Arn
