openapi: 3.1.0
info:
  title: bedrock
paths:
  /model-customization-jobs:
    GET:
      summary: ListModelCustomizationJobs
      description: >-
        <p>Returns a list of model customization jobs that you have submitted.
        You can filter the jobs to return based on one or more criteria.</p>
        <p>For more information, see <a
        href="https://docs.aws.amazon.com/bedrock/latest/userguide/custom-models.html">Custom
        models</a> in the Bedrock User Guide.</p>
      tags:
        - List
        - Model
        - Customization
        - Jobs
        - Model
        - Customization
        - Jobs
  /provisioned-model-throughput:
    POST:
      summary: CreateProvisionedModelThroughput
      description: >-
        <p>Creates a provisioned throughput with dedicated capacity for a
        foundation model or a fine-tuned model.</p> <p>For more information, see
        <a
        href="https://docs.aws.amazon.com/bedrock/latest/userguide/what-is-service.html">Provisioned
        throughput</a> in the Bedrock User Guide.</p>
      tags:
        - Create
        - Provisioned
        - Model
        - Throughput
        - Model
        - Customization
        - Jobs
        - Provisioned
        - Throughput
  /custom-models/{modelIdentifier}:
    GET:
      summary: GetCustomModel
      description: >-
        <p>Get the properties associated with a Amazon Bedrock custom model that
        you have created.For more information, see <a
        href="https://docs.aws.amazon.com/bedrock/latest/userguide/custom-models.html">Custom
        models</a> in the Bedrock User Guide.</p>
      tags:
        - Get
        - Custom
        - Model
        - Model
        - Customization
        - Jobs
        - Provisioned
        - Throughput
        - Identifier
  /logging/modelinvocations:
    PUT:
      summary: PutModelInvocationLoggingConfiguration
      description: <p>Set the configuration values for model invocation logging.</p>
      tags:
        - Put
        - Model
        - Invocation
        - Logging
        - Configuration
        - Model
        - Customization
        - Jobs
        - Provisioned
        - Throughput
        - Identifier
        - Logging
        - Modelinvocations
  /provisioned-model-throughput/{provisionedModelId}:
    PATCH:
      summary: UpdateProvisionedModelThroughput
      description: >-
        <p>Update a provisioned throughput. For more information, see <a
        href="https://docs.aws.amazon.com/bedrock/latest/userguide/what-is-service.html">Provisioned
        throughput</a> in the Bedrock User Guide.</p>
      tags:
        - Update
        - Provisioned
        - Model
        - Throughput
        - Model
        - Customization
        - Jobs
        - Provisioned
        - Throughput
        - Identifier
        - Logging
        - Modelinvocations
        - Id
  /foundation-models/{modelIdentifier}:
    GET:
      summary: GetFoundationModel
      description: <p>Get details about a Amazon Bedrock foundation model.</p>
      tags:
        - Get
        - Foundation
        - Model
        - Model
        - Customization
        - Jobs
        - Provisioned
        - Throughput
        - Identifier
        - Logging
        - Modelinvocations
        - Id
  /model-customization-jobs/{jobIdentifier}:
    GET:
      summary: GetModelCustomizationJob
      description: >-
        <p>Retrieves the properties associated with a model-customization job,
        including the status of the job. For more information, see <a
        href="https://docs.aws.amazon.com/bedrock/latest/userguide/custom-models.html">Custom
        models</a> in the Bedrock User Guide.</p>
      tags:
        - Get
        - Model
        - Customization
        - Job
        - Model
        - Customization
        - Jobs
        - Provisioned
        - Throughput
        - Identifier
        - Logging
        - Modelinvocations
        - Id
  /custom-models:
    GET:
      summary: ListCustomModels
      description: >-
        <p>Returns a list of the custom models that you have created with the
        <code>CreateModelCustomizationJob</code> operation.</p> <p>For more
        information, see <a
        href="https://docs.aws.amazon.com/bedrock/latest/userguide/custom-models.html">Custom
        models</a> in the Bedrock User Guide.</p>
      tags:
        - List
        - Custom
        - Models
        - Model
        - Customization
        - Jobs
        - Provisioned
        - Throughput
        - Identifier
        - Logging
        - Modelinvocations
        - Id
        - Custom
        - Models
  /foundation-models:
    GET:
      summary: ListFoundationModels
      description: >-
        <p>List of Amazon Bedrock foundation models that you can use. For more
        information, see <a
        href="https://docs.aws.amazon.com/bedrock/latest/userguide/foundation-models.html">Foundation
        models</a> in the Bedrock User Guide.</p>
      tags:
        - List
        - Foundation
        - Models
        - Model
        - Customization
        - Jobs
        - Provisioned
        - Throughput
        - Identifier
        - Logging
        - Modelinvocations
        - Id
        - Custom
        - Models
        - Foundation
  /provisioned-model-throughputs:
    GET:
      summary: ListProvisionedModelThroughputs
      description: >-
        <p>List the provisioned capacities. For more information, see <a
        href="https://docs.aws.amazon.com/bedrock/latest/userguide/what-is-service.html">Provisioned
        throughput</a> in the Bedrock User Guide.</p>
      tags:
        - List
        - Provisioned
        - Model
        - Throughputs
        - Model
        - Customization
        - Jobs
        - Provisioned
        - Throughput
        - Identifier
        - Logging
        - Modelinvocations
        - Id
        - Custom
        - Models
        - Foundation
        - Throughputs
  /listTagsForResource:
    POST:
      summary: ListTagsForResource
      description: >-
        <p>List the tags associated with the specified resource.</p> <p>For more
        information, see <a
        href="https://docs.aws.amazon.com/bedrock/latest/userguide/what-is-service.html">Tagging
        resources</a> in the Bedrock User Guide.</p>
      tags:
        - List
        - Tags
        - For
        - Resource
        - Model
        - Customization
        - Jobs
        - Provisioned
        - Throughput
        - Identifier
        - Logging
        - Modelinvocations
        - Id
        - Custom
        - Models
        - Foundation
        - Throughputs
        - Tags
        - For
        - Resource
  /model-customization-jobs/{jobIdentifier}/stop:
    POST:
      summary: StopModelCustomizationJob
      description: >-
        <p>Stops an active model customization job. For more information, see <a
        href="https://docs.aws.amazon.com/bedrock/latest/userguide/custom-models.html">Custom
        models</a> in the Bedrock User Guide.</p>
      tags:
        - Stop
        - Model
        - Customization
        - Job
        - Model
        - Customization
        - Jobs
        - Provisioned
        - Throughput
        - Identifier
        - Logging
        - Modelinvocations
        - Id
        - Custom
        - Models
        - Foundation
        - Throughputs
        - Tags
        - For
        - Resource
        - Stop
  /tagResource:
    POST:
      summary: TagResource
      description: >-
        <p>Associate tags with a resource. For more information, see <a
        href="https://docs.aws.amazon.com/bedrock/latest/userguide/what-is-service.html">Tagging
        resources</a> in the Bedrock User Guide.</p>
      tags:
        - Tag
        - Resource
        - Model
        - Customization
        - Jobs
        - Provisioned
        - Throughput
        - Identifier
        - Logging
        - Modelinvocations
        - Id
        - Custom
        - Models
        - Foundation
        - Throughputs
        - Tags
        - For
        - Resource
        - Stop
  /untagResource:
    POST:
      summary: UntagResource
      description: >-
        <p>Remove one or more tags from a resource. For more information, see <a
        href="https://docs.aws.amazon.com/bedrock/latest/userguide/what-is-service.html">Tagging
        resources</a> in the Bedrock User 
      tags:
        - Untag
        - Resource
        - Model
        - Customization
        - Jobs
        - Provisioned
        - Throughput
        - Identifier
        - Logging
        - Modelinvocations
        - Id
        - Custom
        - Models
        - Foundation
        - Throughputs
        - Tags
        - For
        - Resource
        - St
