openapi: 3.1.0
info:
  title: bedrock-agent
paths:
  /agents/{agentId}/agentversions/{agentVersion}/knowledgebases/:
    POST:
      summary: ListAgentKnowledgeBases
      description: >-
        <p>List of Knowledge Bases associated to an existing Amazon Bedrock
        Agent Version</p>
      tags:
        - List
        - Agent
        - Knowledge
        - Bases
        - Id
        - Agentversions
        - Agent
        - Version
        - Knowledgebases
  /agents/:
    POST:
      summary: ListAgents
      description: <p>Lists Agents</p>
      tags:
        - List
        - Agents
        - Id
        - Agentversions
        - Agent
        - Version
        - Knowledgebases
        - Agents
  /agents/{agentId}/agentversions/{agentVersion}/actiongroups/:
    POST:
      summary: ListAgentActionGroups
      description: <p>Lists an Action Group for existing Amazon Bedrock Agent Version</p>
      tags:
        - List
        - Agent
        - Action
        - Groups
        - Id
        - Agentversions
        - Agent
        - Version
        - Knowledgebases
        - Agents
        - Actiongroups
  /agents/{agentId}/agentaliases/:
    POST:
      summary: ListAgentAliases
      description: <p>Lists all the Aliases for an Amazon Bedrock Agent</p>
      tags:
        - List
        - Agent
        - Aliases
        - Id
        - Agentversions
        - Agent
        - Version
        - Knowledgebases
        - Agents
        - Actiongroups
        - Agentaliases
  /knowledgebases/{knowledgeBaseId}/datasources/:
    POST:
      summary: ListDataSources
      description: <p>List data sources</p>
      tags:
        - List
        - Data
        - Sources
        - Id
        - Agentversions
        - Agent
        - Version
        - Knowledgebases
        - Agents
        - Actiongroups
        - Agentaliases
        - Base
        - Datasources
  /knowledgebases/:
    POST:
      summary: ListKnowledgeBases
      description: <p>List Knowledge Bases</p>
      tags:
        - List
        - Knowledge
        - Bases
        - Id
        - Agentversions
        - Agent
        - Version
        - Knowledgebases
        - Agents
        - Actiongroups
        - Agentaliases
        - Base
        - Datasources
  /agents/{agentId}/:
    PUT:
      summary: UpdateAgent
      description: <p>Updates an existing Amazon Bedrock Agent</p>
      tags:
        - Update
        - Agent
        - Id
        - Agentversions
        - Agent
        - Version
        - Knowledgebases
        - Agents
        - Actiongroups
        - Agentaliases
        - Base
        - Datasources
  /agents/{agentId}/agentversions/{agentVersion}/actiongroups/{actionGroupId}/:
    PUT:
      summary: UpdateAgentActionGroup
      description: <p>Updates an existing Action Group for Amazon Bedrock Agent</p>
      tags:
        - Update
        - Agent
        - Action
        - Group
        - Id
        - Agentversions
        - Agent
        - Version
        - Knowledgebases
        - Agents
        - Actiongroups
        - Agentaliases
        - Base
        - Datasources
        - Action
        - Group
  /agents/{agentId}/agentaliases/{agentAliasId}/:
    PUT:
      summary: UpdateAgentAlias
      description: <p>Updates an existing Alias for an Amazon Bedrock Agent</p>
      tags:
        - Update
        - Agent
        - Alias
        - Id
        - Agentversions
        - Agent
        - Version
        - Knowledgebases
        - Agents
        - Actiongroups
        - Agentaliases
        - Base
        - Datasources
        - Action
        - Group
        - Alias
  /agents/{agentId}/agentversions/{agentVersion}/:
    GET:
      summary: GetAgentVersion
      description: <p>Gets an Agent version for existing Amazon Bedrock Agent</p>
      tags:
        - Get
        - Agent
        - Version
        - Id
        - Agentversions
        - Agent
        - Version
        - Knowledgebases
        - Agents
        - Actiongroups
        - Agentaliases
        - Base
        - Datasources
        - Action
        - Group
        - Alias
  /knowledgebases/{knowledgeBaseId}/datasources/{dataSourceId}:
    PUT:
      summary: UpdateDataSource
      description: <p>Update an existing data source</p>
      tags:
        - Update
        - Data
        - Source
        - Id
        - Agentversions
        - Agent
        - Version
        - Knowledgebases
        - Agents
        - Actiongroups
        - Agentaliases
        - Base
        - Datasources
        - Action
        - Group
        - Alias
        - Data
        - Source
  /knowledgebases/{knowledgeBaseId}:
    PUT:
      summary: UpdateKnowledgeBase
      description: <p>Update an existing knowledge base</p>
      tags:
        - Update
        - Knowledge
        - Base
        - Id
        - Agentversions
        - Agent
        - Version
        - Knowledgebases
        - Agents
        - Actiongroups
        - Agentaliases
        - Base
        - Datasources
        - Action
        - Group
        - Alias
        - Data
        - Source
  /agents/{agentId}/agentversions/{agentVersion}/knowledgebases/{knowledgeBaseId}/:
    PUT:
      summary: UpdateAgentKnowledgeBase
      description: >-
        <p>Updates an existing Knowledge Base associated to an Amazon Bedrock
        Agent</p>
      tags:
        - Update
        - Agent
        - Knowledge
        - Base
        - Id
        - Agentversions
        - Agent
        - Version
        - Knowledgebases
        - Agents
        - Actiongroups
        - Agentaliases
        - Base
        - Datasources
        - Action
        - Group
        - Alias
        - Data
        - Source
        - Knowledge
  /knowledgebases/{knowledgeBaseId}/datasources/{dataSourceId}/ingestionjobs/{ingestionJobId}:
    GET:
      summary: GetIngestionJob
      description: <p>Get an ingestion job</p>
      tags:
        - Get
        - Ingestion
        - Job
        - Id
        - Agentversions
        - Agent
        - Version
        - Knowledgebases
        - Agents
        - Actiongroups
        - Agentaliases
        - Base
        - Datasources
        - Action
        - Group
        - Alias
        - Data
        - Source
        - Knowledge
        - Ingestionjobs
        - Ingestion
        - Job
  /agents/{agentId}/agentversions/:
    POST:
      summary: ListAgentVersions
      description: <p>Lists Agent Versions</p>
      tags:
        - List
        - Agent
        - Versions
        - Id
        - Agentversions
        - Agent
        - Version
        - Knowledgebases
        - Agents
        - Actiongroups
        - Agentaliases
        - Base
        - Datasources
        - Action
        - Group
        - Alias
        - Data
        - Source
        - Knowledge
        - Ingestionjobs
        - Ingestion
        - Job
  /knowledgebases/{knowledgeBaseId}/datasources/{dataSourceId}/ingestionjobs/:
    PUT:
      summary: StartIngestionJob
      description: <p>Start a new ingestion job</p>
      tags:
        - Start
        - Ingestion
        - Job
        - Id
        - Agentversions
        - Agent
        - Version
        - Knowledgebases
        - Agents
        - Actiongroups
        - Agentaliases
        - Base
        - Datasources
        - Action
        - Group
        - Alias
        - Data
        - Source
        - Knowledge
        - Ingestionjobs
        - Ingestion
        - Job
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Untag a resource</
      tags:
        - Untag
        - Resource
        - Id
        - Agentversions
        - Agent
        - Version
        - Knowledgebases
        - Agents
        - Actiongroups
        - Agentaliases
        - Base
        - Datasources
        - Action
        - Group
        - Alias
        - Data
        - Source
        - Knowledge
        - Ingestionjobs
        - Ingestion
        - Job
        - nu
