openapi: 3.1.0
info:
  title: bedrock-agent-runtime
paths:
  /agents/{agentId}/agentAliases/{agentAliasId}/sessions/{sessionId}/text:
    POST:
      summary: InvokeAgent
      description: >-
        <p>Invokes the specified Bedrock model to run inference using the input
        provided in the request body.</p>
      tags:
        - Invoke
        - Agent
        - Id
        - Agent
        - Aliases
        - Alias
        - Sessions
        - Session
        - Text
  /knowledgebases/{knowledgeBaseId}/retrieve:
    POST:
      summary: Retrieve
      description: <p>Retrieve from knowledge base.</p>
      tags:
        - Retrieve
        - Id
        - Agent
        - Aliases
        - Alias
        - Sessions
        - Session
        - Text
        - Base
        - Retrieve
  /retrieveAndGenerate:
    POST:
      summary: RetrieveAndGenerate
      description: <p>RetrieveAndGenerate API</
      tags:
        - Retrieve
        - And
        - Generate
        - Id
        - Agent
        - Aliases
        - Alias
        - Sessions
        - Session
        - Text
        - Base
        - Retrieve
        - And
        - Ge
