openapi: 3.1.0
info:
  title: cleanroomsml
paths:
  /audience-model:
    GET:
      summary: ListAudienceModels
      description: <p>Returns a list of audience models.</p>
  /configured-audience-model:
    GET:
      summary: ListConfiguredAudienceModels
      description: <p>Returns a list of the configured audience models.</p>
  /training-dataset:
    GET:
      summary: ListTrainingDatasets
      description: <p>Returns a list of training datasets.</p>
  /audience-generation-job/{audienceGenerationJobArn}:
    GET:
      summary: GetAudienceGenerationJob
      description: <p>Returns information about an audience generation job.</p>
  /audience-model/{audienceModelArn}:
    GET:
      summary: GetAudienceModel
      description: <p>Returns information about an audience model</p>
  /configured-audience-model/{configuredAudienceModelArn}:
    PATCH:
      summary: UpdateConfiguredAudienceModel
      description: >-
        <p>Provides the information necessary to update a configured audience
        model. Updates that impact audience generation jobs take effect when a
        new job starts, but do not impact currently running jobs.</p>
  /configured-audience-model/{configuredAudienceModelArn}/policy:
    PUT:
      summary: PutConfiguredAudienceModelPolicy
      description: >-
        <p>Create or update the resource policy for a configured audience
        model.</p>
  /training-dataset/{trainingDatasetArn}:
    GET:
      summary: GetTrainingDataset
      description: <p>Returns information about a training dataset.</p>
  /audience-export-job:
    POST:
      summary: StartAudienceExportJob
      description: >-
        <p>Export an audience of a specified size after you have generated an
        audience.</p>
  /audience-generation-job:
    POST:
      summary: StartAudienceGenerationJob
      description: <p>Information necessary to start the audience generation job.</p>
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Removes metadata tags from a specified resou
