openapi: 3.1.0
info:
  title: cleanroomsml
paths:
  /audience-model:
    GET:
      summary: ListAudienceModels
      description: <p>Returns a list of audience models.</p>
      tags:
        - List
        - Audience
        - Models
        - Audience
        - Model
  /configured-audience-model:
    GET:
      summary: ListConfiguredAudienceModels
      description: <p>Returns a list of the configured audience models.</p>
      tags:
        - List
        - Configured
        - Audience
        - Models
        - Audience
        - Model
        - Configured
  /training-dataset:
    GET:
      summary: ListTrainingDatasets
      description: <p>Returns a list of training datasets.</p>
      tags:
        - List
        - Training
        - Datasets
        - Audience
        - Model
        - Configured
        - Training
        - Dataset
  /audience-generation-job/{audienceGenerationJobArn}:
    GET:
      summary: GetAudienceGenerationJob
      description: <p>Returns information about an audience generation job.</p>
      tags:
        - Get
        - Audience
        - Generation
        - Job
        - Audience
        - Model
        - Configured
        - Training
        - Dataset
        - Generation
        - Job
        - Arn
  /audience-model/{audienceModelArn}:
    GET:
      summary: GetAudienceModel
      description: <p>Returns information about an audience model</p>
      tags:
        - Get
        - Audience
        - Model
        - Audience
        - Model
        - Configured
        - Training
        - Dataset
        - Generation
        - Job
        - Arn
  /configured-audience-model/{configuredAudienceModelArn}:
    PATCH:
      summary: UpdateConfiguredAudienceModel
      description: >-
        <p>Provides the information necessary to update a configured audience
        model. Updates that impact audience generation jobs take effect when a
        new job starts, but do not impact currently running jobs.</p>
      tags:
        - Update
        - Configured
        - Audience
        - Model
        - Audience
        - Model
        - Configured
        - Training
        - Dataset
        - Generation
        - Job
        - Arn
  /configured-audience-model/{configuredAudienceModelArn}/policy:
    PUT:
      summary: PutConfiguredAudienceModelPolicy
      description: >-
        <p>Create or update the resource policy for a configured audience
        model.</p>
      tags:
        - Put
        - Configured
        - Audience
        - Model
        - Policy
        - Audience
        - Model
        - Configured
        - Training
        - Dataset
        - Generation
        - Job
        - Arn
        - Policy
  /training-dataset/{trainingDatasetArn}:
    GET:
      summary: GetTrainingDataset
      description: <p>Returns information about a training dataset.</p>
      tags:
        - Get
        - Training
        - Dataset
        - Audience
        - Model
        - Configured
        - Training
        - Dataset
        - Generation
        - Job
        - Arn
        - Policy
  /audience-export-job:
    POST:
      summary: StartAudienceExportJob
      description: >-
        <p>Export an audience of a specified size after you have generated an
        audience.</p>
      tags:
        - Start
        - Audience
        - Export
        - Job
        - Audience
        - Model
        - Configured
        - Training
        - Dataset
        - Generation
        - Job
        - Arn
        - Policy
        - Export
  /audience-generation-job:
    POST:
      summary: StartAudienceGenerationJob
      description: <p>Information necessary to start the audience generation job.</p>
      tags:
        - Start
        - Audience
        - Generation
        - Job
        - Audience
        - Model
        - Configured
        - Training
        - Dataset
        - Generation
        - Job
        - Arn
        - Policy
        - Export
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Removes metadata tags from a specified res
      tags:
        - Untag
        - Resource
        - Audience
        - Model
        - Configured
        - Training
        - Dataset
        - Generation
        - Job
        - Arn
        - Policy
        - Expo
