openapi: 3.1.0
info:
  title: codestar-connections
paths:
  /:
    POST:
      summary: UpdateSyncConfiguration
      description: >-
        <p>Updates the sync configuration for your connection and a specified
        external Git reposit
