openapi: 3.1.0
info:
  title: connectcampaigns
paths:
  /campaigns:
    PUT:
      summary: CreateCampaign
      description: >-
        <p>Creates a campaign for the specified Amazon Connect account. This API
        is idempotent.</p>
      tags:
        - Create
        - Campaign
        - Campaigns
  /campaigns/{id}:
    GET:
      summary: DescribeCampaign
      description: <p>Describes the specific campaign.</p>
      tags:
        - Describe
        - Campaign
        - Campaigns
        - Id
  /connect-instance/{connectInstanceId}/config:
    GET:
      summary: GetConnectInstanceConfig
      description: <p>Get the specific Connect instance config.</p>
      tags:
        - Get
        - Connect
        - Instance
        - Config
        - Campaigns
        - Id
        - Instance
        - Config
  /connect-instance/{connectInstanceId}/onboarding:
    PUT:
      summary: StartInstanceOnboardingJob
      description: >-
        <p>Onboard the specific Amazon Connect instance to Connect
        Campaigns.</p>
      tags:
        - Start
        - Instance
        - Onboarding
        - Job
        - Campaigns
        - Id
        - Instance
        - Config
        - Onboarding
  /campaigns/{id}/state:
    GET:
      summary: GetCampaignState
      description: <p>Get state of a campaign for the specified Amazon Connect account.</p>
      tags:
        - Get
        - Campaign
        - State
        - Campaigns
        - Id
        - Instance
        - Config
        - Onboarding
        - State
  /campaigns-state:
    POST:
      summary: GetCampaignStateBatch
      description: <p>Get state of campaigns for the specified Amazon Connect account.</p>
      tags:
        - Get
        - Campaign
        - State
        - Batch
        - Campaigns
        - Id
        - Instance
        - Config
        - Onboarding
        - State
  /campaigns-summary:
    POST:
      summary: ListCampaigns
      description: >-
        <p>Provides summary information about the campaigns under the specified
        Amazon Connect account.</p>
      tags:
        - List
        - Campaigns
        - Campaigns
        - Id
        - Instance
        - Config
        - Onboarding
        - State
        - Summary
  /tags/{arn}:
    DELETE:
      summary: UntagResource
      description: <p>Untag a resource.</p>
      tags:
        - Untag
        - Resource
        - Campaigns
        - Id
        - Instance
        - Config
        - Onboarding
        - State
        - Summary
        - Tags
        - Arn
  /campaigns/{id}/pause:
    POST:
      summary: PauseCampaign
      description: <p>Pauses a campaign for the specified Amazon Connect account.</p>
      tags:
        - Pause
        - Campaign
        - Campaigns
        - Id
        - Instance
        - Config
        - Onboarding
        - State
        - Summary
        - Tags
        - Arn
        - Pause
  /campaigns/{id}/dial-requests:
    PUT:
      summary: PutDialRequestBatch
      description: >-
        <p>Creates dials requests for the specified campaign Amazon Connect
        account. This API is idempotent.</p>
      tags:
        - Put
        - Dial
        - Request
        - Batch
        - Campaigns
        - Id
        - Instance
        - Config
        - Onboarding
        - State
        - Summary
        - Tags
        - Arn
        - Pause
        - Dial
        - Requests
  /campaigns/{id}/resume:
    POST:
      summary: ResumeCampaign
      description: <p>Stops a campaign for the specified Amazon Connect account.</p>
      tags:
        - Resume
        - Campaign
        - Campaigns
        - Id
        - Instance
        - Config
        - Onboarding
        - State
        - Summary
        - Tags
        - Arn
        - Pause
        - Dial
        - Requests
        - Resume
  /campaigns/{id}/start:
    POST:
      summary: StartCampaign
      description: <p>Starts a campaign for the specified Amazon Connect account.</p>
      tags:
        - Start
        - Campaign
        - Campaigns
        - Id
        - Instance
        - Config
        - Onboarding
        - State
        - Summary
        - Tags
        - Arn
        - Pause
        - Dial
        - Requests
        - Resume
        - Start
  /campaigns/{id}/stop:
    POST:
      summary: StopCampaign
      description: <p>Stops a campaign for the specified Amazon Connect account.</p>
      tags:
        - Stop
        - Campaign
        - Campaigns
        - Id
        - Instance
        - Config
        - Onboarding
        - State
        - Summary
        - Tags
        - Arn
        - Pause
        - Dial
        - Requests
        - Resume
        - Start
        - Stop
  /campaigns/{id}/dialer-config:
    POST:
      summary: UpdateCampaignDialerConfig
      description: <p>Updates the dialer config of a campaign. This API is idempotent.</p>
      tags:
        - Update
        - Campaign
        - Dialer
        - Config
        - Campaigns
        - Id
        - Instance
        - Config
        - Onboarding
        - State
        - Summary
        - Tags
        - Arn
        - Pause
        - Dial
        - Requests
        - Resume
        - Start
        - Stop
        - Dialer
  /campaigns/{id}/name:
    POST:
      summary: UpdateCampaignName
      description: <p>Updates the name of a campaign. This API is idempotent.</p>
      tags:
        - Update
        - Campaign
        - Name
        - Campaigns
        - Id
        - Instance
        - Config
        - Onboarding
        - State
        - Summary
        - Tags
        - Arn
        - Pause
        - Dial
        - Requests
        - Resume
        - Start
        - Stop
        - Dialer
        - Name
  /campaigns/{id}/outbound-call-config:
    POST:
      summary: UpdateCampaignOutboundCallConfig
      description: >-
        <p>Updates the outbound call config of a campaign. This API is
        idempotent.</
      tags:
        - Update
        - Campaign
        - Outbound
        - Call
        - Config
        - Campaigns
        - Id
        - Instance
        - Config
        - Onboarding
        - State
        - Summary
        - Tags
        - Arn
        - Pause
        - Dial
        - Requests
        - Resume
        - Start
        - Stop
        - Dialer
        - Name
        - Outbound
        - nu
