openapi: 3.1.0
info:
  title: connect-contact-lens
paths:
  /realtime-contact-analysis/analysis-segments:
    POST:
      summary: ListRealtimeContactAnalysisSegments
      description: <p>Provides a list of analysis segments for a real-time analysis sess
