openapi: 3.1.0
info:
  title: dataexchange
paths:
  /v1/jobs/{JobId}:
    PATCH:
      summary: StartJob
      description: <p>This operation starts a job.</p>
      tags:
        - Start
        - Job
        - Job
        - Id
  /v1/data-sets:
    GET:
      summary: ListDataSets
      description: >-
        <p>This operation lists your data sets. When listing by origin OWNED,
        results are sorted by CreatedAt in descending order. When listing by
        origin ENTITLED, there is no order and the maxResults parameter is
        ignored.</p>
      tags:
        - List
        - Data
        - Sets
        - Job
        - Id
        - V1
        - Data
        - Sets
  /v1/event-actions:
    GET:
      summary: ListEventActions
      description: <p>This operation lists your event actions.</p>
      tags:
        - List
        - Event
        - Actions
        - Job
        - Id
        - V1
        - Data
        - Sets
        - Event
        - Actions
  /v1/jobs:
    GET:
      summary: ListJobs
      description: >-
        <p>This operation lists your jobs sorted by CreatedAt in descending
        order.</p>
      tags:
        - List
        - Jobs
        - Job
        - Id
        - V1
        - Data
        - Sets
        - Event
        - Actions
        - Jobs
  /v1/data-sets/{DataSetId}/revisions:
    GET:
      summary: ListDataSetRevisions
      description: >-
        <p>This operation lists a data set's revisions sorted by CreatedAt in
        descending order.</p>
      tags:
        - List
        - Data
        - Set
        - Revisions
        - Job
        - Id
        - V1
        - Data
        - Sets
        - Event
        - Actions
        - Jobs
        - Set
        - Revisions
  /v1/data-sets/{DataSetId}/revisions/{RevisionId}/assets/{AssetId}:
    PATCH:
      summary: UpdateAsset
      description: <p>This operation updates an asset.</p>
      tags:
        - Update
        - Asset
        - Job
        - Id
        - V1
        - Data
        - Sets
        - Event
        - Actions
        - Jobs
        - Set
        - Revisions
        - Revision
        - Assets
        - Asset
  /v1/data-sets/{DataSetId}:
    PATCH:
      summary: UpdateDataSet
      description: <p>This operation updates a data set.</p>
      tags:
        - Update
        - Data
        - Set
        - Job
        - Id
        - V1
        - Data
        - Sets
        - Event
        - Actions
        - Jobs
        - Set
        - Revisions
        - Revision
        - Assets
        - Asset
  /v1/event-actions/{EventActionId}:
    PATCH:
      summary: UpdateEventAction
      description: <p>This operation updates the event action.</p>
      tags:
        - Update
        - Event
        - Action
        - Job
        - Id
        - V1
        - Data
        - Sets
        - Event
        - Actions
        - Jobs
        - Set
        - Revisions
        - Revision
        - Assets
        - Asset
        - Action
  /v1/data-sets/{DataSetId}/revisions/{RevisionId}:
    PATCH:
      summary: UpdateRevision
      description: <p>This operation updates a revision.</p>
      tags:
        - Update
        - Revision
        - Job
        - Id
        - V1
        - Data
        - Sets
        - Event
        - Actions
        - Jobs
        - Set
        - Revisions
        - Revision
        - Assets
        - Asset
        - Action
  /v1/data-sets/{DataSetId}/revisions/{RevisionId}/assets:
    GET:
      summary: ListRevisionAssets
      description: >-
        <p>This operation lists a revision's assets sorted alphabetically in
        descending order.</p>
      tags:
        - List
        - Revision
        - Assets
        - Job
        - Id
        - V1
        - Data
        - Sets
        - Event
        - Actions
        - Jobs
        - Set
        - Revisions
        - Revision
        - Assets
        - Asset
        - Action
  /tags/{ResourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>This operation removes one or more tags from a resource.</p>
      tags:
        - Untag
        - Resource
        - Job
        - Id
        - V1
        - Data
        - Sets
        - Event
        - Actions
        - Jobs
        - Set
        - Revisions
        - Revision
        - Assets
        - Asset
        - Action
        - Resource
        - Arn
  /v1/data-sets/{DataSetId}/revisions/{RevisionId}/revoke:
    POST:
      summary: RevokeRevision
      description: <p>This operation revokes subscribers' access to a revision.</p>
      tags:
        - Revoke
        - Revision
        - Job
        - Id
        - V1
        - Data
        - Sets
        - Event
        - Actions
        - Jobs
        - Set
        - Revisions
        - Revision
        - Assets
        - Asset
        - Action
        - Resource
        - Arn
        - Revoke
  /v1:
    POST:
      summary: SendApiAsset
      description: >-
        <p>This operation invokes an API Gateway API asset. The request is
        proxied to the provider’s API Gateway API.</p>
      tags:
        - Send
        - Api
        - Asset
        - Job
        - Id
        - V1
        - Data
        - Sets
        - Event
        - Actions
        - Jobs
        - Set
        - Revisions
        - Revision
        - Assets
        - Asset
        - Action
        - Resource
        - Arn
        - Revoke
  /v1/data-sets/{DataSetId}/notification:
    POST:
      summary: SendDataSetNotification
      description: <p>The type of event associated with the data set.</
      tags:
        - Send
        - Data
        - Set
        - Notification
        - Job
        - Id
        - V1
        - Data
        - Sets
        - Event
        - Actions
        - Jobs
        - Set
        - Revisions
        - Revision
        - Assets
        - Asset
        - Action
        - Resource
        - Arn
        - Revoke
        - Notification
