openapi: 3.1.0
info:
  title: datapipeline
paths:
  /:
    POST:
      summary: ValidatePipelineDefinition
      description: >-
        <p>Validates the specified pipeline definition to ensure that it is well
        formed and can be run without error.</
      tags:
        - Validate
        - Pipeline
        - Definition
