openapi: 3.1.0
info:
  title: databrew
paths:
  /recipes/{name}/batchDeleteRecipeVersion:
    POST:
      summary: BatchDeleteRecipeVersion
      description: >-
        <p>Deletes one or more versions of a recipe at a time.</p> <p>The entire
        request will be rejected if:</p> <ul> <li> <p>The recipe does not
        exist.</p> </li> <li> <p>There is an invalid version identifier in the
        list of versions.</p> </li> <li> <p>The version list is empty.</p> </li>
        <li> <p>The version list size exceeds 50.</p> </li> <li> <p>The version
        list contains duplicate entries.</p> </li> </ul> <p>The request will
        complete successfully, but with partial failures, if:</p> <ul> <li> <p>A
        version does not exist.</p> </li> <li> <p>A version is being used by a
        job.</p> </li> <li> <p>You specify <code>LATEST_WORKING</code>, but it's
        being used by a project.</p> </li> <li> <p>The version fails to be
        deleted.</p> </li> </ul> <p>The <code>LATEST_WORKING</code> version will
        only be deleted if the recipe has no other versions. If you try to
        delete <code>LATEST_WORKING</code> while other versions exist (or if
        they can't be deleted), then <code>LATEST_WORKING</code> will be listed
        as partial failure in the response.</p>
      tags:
        - Batch
        - Delete
        - Recipe
        - Version
        - Delete
        - Recipe
        - Version
  /datasets:
    GET:
      summary: ListDatasets
      description: <p>Lists all of the DataBrew datasets.</p>
      tags:
        - List
        - Datasets
        - Delete
        - Recipe
        - Version
        - Datasets
  /profileJobs:
    POST:
      summary: CreateProfileJob
      description: >-
        <p>Creates a new job to analyze a dataset and create its data
        profile.</p>
      tags:
        - Create
        - Profile
        - Job
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
  /projects:
    GET:
      summary: ListProjects
      description: <p>Lists all of the DataBrew projects that are defined.</p>
      tags:
        - List
        - Projects
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
  /recipes:
    GET:
      summary: ListRecipes
      description: <p>Lists all of the DataBrew recipes that are defined.</p>
      tags:
        - List
        - Recipes
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
  /recipeJobs:
    POST:
      summary: CreateRecipeJob
      description: >-
        <p>Creates a new job to transform input data, using steps defined in an
        existing Glue DataBrew recipe</p>
      tags:
        - Create
        - Recipe
        - Job
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
  /rulesets:
    GET:
      summary: ListRulesets
      description: >-
        <p>List all rulesets available in the current account or rulesets
        associated with a specific resource (dataset).</p>
      tags:
        - List
        - Rulesets
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
        - Rulesets
  /schedules:
    GET:
      summary: ListSchedules
      description: <p>Lists the DataBrew schedules that are defined.</p>
      tags:
        - List
        - Schedules
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
        - Rulesets
        - Schedules
  /datasets/{name}:
    PUT:
      summary: UpdateDataset
      description: <p>Modifies the definition of an existing DataBrew dataset.</p>
      tags:
        - Update
        - Dataset
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
        - Rulesets
        - Schedules
        - Name
  /jobs/{name}:
    GET:
      summary: DescribeJob
      description: <p>Returns the definition of a specific DataBrew job.</p>
      tags:
        - Describe
        - Job
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
        - Rulesets
        - Schedules
        - Name
  /projects/{name}:
    PUT:
      summary: UpdateProject
      description: <p>Modifies the definition of an existing DataBrew project.</p>
      tags:
        - Update
        - Project
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
        - Rulesets
        - Schedules
        - Name
  /recipes/{name}/recipeVersion/{recipeVersion}:
    DELETE:
      summary: DeleteRecipeVersion
      description: <p>Deletes a single version of a DataBrew recipe.</p>
      tags:
        - Delete
        - Recipe
        - Version
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
        - Rulesets
        - Schedules
        - Name
  /rulesets/{name}:
    PUT:
      summary: UpdateRuleset
      description: <p>Updates specified ruleset.</p>
      tags:
        - Update
        - Ruleset
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
        - Rulesets
        - Schedules
        - Name
  /schedules/{name}:
    PUT:
      summary: UpdateSchedule
      description: <p>Modifies the definition of an existing DataBrew schedule.</p>
      tags:
        - Update
        - Schedule
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
        - Rulesets
        - Schedules
        - Name
  /jobs/{name}/jobRun/{runId}:
    GET:
      summary: DescribeJobRun
      description: <p>Represents one run of a DataBrew job.</p>
      tags:
        - Describe
        - Job
        - Run
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
        - Rulesets
        - Schedules
        - Name
        - Run
        - Id
  /recipes/{name}:
    PUT:
      summary: UpdateRecipe
      description: >-
        <p>Modifies the definition of the <code>LATEST_WORKING</code> version of
        a DataBrew recipe.</p>
      tags:
        - Update
        - Recipe
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
        - Rulesets
        - Schedules
        - Name
        - Run
        - Id
  /jobs/{name}/jobRuns:
    GET:
      summary: ListJobRuns
      description: <p>Lists all of the previous runs of a particular DataBrew job.</p>
      tags:
        - List
        - Job
        - Runs
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
        - Rulesets
        - Schedules
        - Name
        - Run
        - Id
        - Runs
  /jobs:
    GET:
      summary: ListJobs
      description: <p>Lists all of the DataBrew jobs that are defined.</p>
      tags:
        - List
        - Jobs
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
        - Rulesets
        - Schedules
        - Name
        - Run
        - Id
        - Runs
  /recipeVersions:
    GET:
      summary: ListRecipeVersions
      description: >-
        <p>Lists the versions of a particular DataBrew recipe, except for
        <code>LATEST_WORKING</code>.</p>
      tags:
        - List
        - Recipe
        - Versions
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
        - Rulesets
        - Schedules
        - Name
        - Run
        - Id
        - Runs
        - Versions
  /tags/{ResourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Removes metadata tags from a DataBrew resource.</p>
      tags:
        - Untag
        - Resource
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
        - Rulesets
        - Schedules
        - Name
        - Run
        - Id
        - Runs
        - Versions
        - Resource
        - Arn
  /recipes/{name}/publishRecipe:
    POST:
      summary: PublishRecipe
      description: <p>Publishes a new version of a DataBrew recipe.</p>
      tags:
        - Publish
        - Recipe
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
        - Rulesets
        - Schedules
        - Name
        - Run
        - Id
        - Runs
        - Versions
        - Resource
        - Arn
  /projects/{name}/sendProjectSessionAction:
    PUT:
      summary: SendProjectSessionAction
      description: >-
        <p>Performs a recipe step within an interactive DataBrew session that's
        currently open.</p>
      tags:
        - Send
        - Project
        - Session
        - Action
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
        - Rulesets
        - Schedules
        - Name
        - Run
        - Id
        - Runs
        - Versions
        - Resource
        - Arn
        - Project
        - Session
        - Action
  /jobs/{name}/startJobRun:
    POST:
      summary: StartJobRun
      description: <p>Runs a DataBrew job.</p>
      tags:
        - Start
        - Job
        - Run
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
        - Rulesets
        - Schedules
        - Name
        - Run
        - Id
        - Runs
        - Versions
        - Resource
        - Arn
        - Project
        - Session
        - Action
        - Job
  /projects/{name}/startProjectSession:
    PUT:
      summary: StartProjectSession
      description: >-
        <p>Creates an interactive session, enabling you to manipulate data in a
        DataBrew project.</p>
      tags:
        - Start
        - Project
        - Session
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
        - Rulesets
        - Schedules
        - Name
        - Run
        - Id
        - Runs
        - Versions
        - Resource
        - Arn
        - Project
        - Session
        - Action
        - Job
  /jobs/{name}/jobRun/{runId}/stopJobRun:
    POST:
      summary: StopJobRun
      description: <p>Stops a particular run of a job.</p>
      tags:
        - Stop
        - Job
        - Run
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
        - Rulesets
        - Schedules
        - Name
        - Run
        - Id
        - Runs
        - Versions
        - Resource
        - Arn
        - Project
        - Session
        - Action
        - Job
        - Stop
  /profileJobs/{name}:
    PUT:
      summary: UpdateProfileJob
      description: <p>Modifies the definition of an existing profile job.</p>
      tags:
        - Update
        - Profile
        - Job
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
        - Rulesets
        - Schedules
        - Name
        - Run
        - Id
        - Runs
        - Versions
        - Resource
        - Arn
        - Project
        - Session
        - Action
        - Job
        - Stop
  /recipeJobs/{name}:
    PUT:
      summary: UpdateRecipeJob
      description: <p>Modifies the definition of an existing DataBrew recipe job.</
      tags:
        - Update
        - Recipe
        - Job
        - Delete
        - Recipe
        - Version
        - Datasets
        - Jobs
        - Projects
        - Recipes
        - Rulesets
        - Schedules
        - Name
        - Run
        - Id
        - Runs
        - Versions
        - Resource
        - Arn
        - Project
        - Session
        - Action
        - Job
        - nu
