openapi: 3.1.0
info:
  title: discovery
paths:
  /:
    POST:
      summary: UpdateApplication
      description: <p>Updates metadata about an application.</
      tags:
        - Update
        - Appli
