openapi: 3.1.0
info:
  title: finspace-data
paths:
  /permission-group/{permissionGroupId}/users/{userId}:
    DELETE:
      summary: DisassociateUserFromPermissionGroup
      description: <p>Removes a user from a permission group.</p>
      tags:
        - Disassociate
        - User
        - From
        - Permission
        - Group
        - Group
        - Id
        - Users
        - User
  /datasets/{datasetId}/changesetsv2:
    GET:
      summary: ListChangesets
      description: <p>Lists the FinSpace Changesets for a Dataset.</p>
      tags:
        - List
        - Changesets
        - Group
        - Id
        - Users
        - User
        - Changesetsv2
  /datasets/{datasetId}/dataviewsv2:
    GET:
      summary: ListDataViews
      description: <p>Lists all available Dataviews for a Dataset.</p>
      tags:
        - List
        - Data
        - Views
        - Group
        - Id
        - Users
        - User
        - Changesetsv2
        - Dataviewsv2
  /datasetsv2:
    GET:
      summary: ListDatasets
      description: <p>Lists all of the active Datasets that a user has access to.</p>
      tags:
        - List
        - Datasets
        - Group
        - Id
        - Users
        - User
        - Changesetsv2
        - Dataviewsv2
        - Datasetsv2
  /permission-group:
    GET:
      summary: ListPermissionGroups
      description: <p>Lists all available permission groups in FinSpace.</p>
      tags:
        - List
        - Permission
        - Groups
        - Group
        - Id
        - Users
        - User
        - Changesetsv2
        - Dataviewsv2
        - Datasetsv2
        - Permission
  /user:
    GET:
      summary: ListUsers
      description: <p>Lists all available users in FinSpace.</p>
      tags:
        - List
        - Users
        - Group
        - Id
        - Users
        - User
        - Changesetsv2
        - Dataviewsv2
        - Datasetsv2
        - Permission
  /datasetsv2/{datasetId}:
    PUT:
      summary: UpdateDataset
      description: <p>Updates a FinSpace Dataset.</p>
      tags:
        - Update
        - Dataset
        - Group
        - Id
        - Users
        - User
        - Changesetsv2
        - Dataviewsv2
        - Datasetsv2
        - Permission
  /permission-group/{permissionGroupId}:
    PUT:
      summary: UpdatePermissionGroup
      description: >-
        <p>Modifies the details of a permission group. You cannot modify a
        <code>permissionGroupID</code>.</p>
      tags:
        - Update
        - Permission
        - Group
        - Group
        - Id
        - Users
        - User
        - Changesetsv2
        - Dataviewsv2
        - Datasetsv2
        - Permission
  /user/{userId}/disable:
    POST:
      summary: DisableUser
      description: >-
        <p>Denies access to the FinSpace web application and API for the
        specified user.</p>
      tags:
        - Disable
        - User
        - Group
        - Id
        - Users
        - User
        - Changesetsv2
        - Dataviewsv2
        - Datasetsv2
        - Permission
        - Disable
  /user/{userId}/enable:
    POST:
      summary: EnableUser
      description: >-
        <p> Allows the specified user to access the FinSpace web application and
        API.</p>
      tags:
        - Enable
        - User
        - Group
        - Id
        - Users
        - User
        - Changesetsv2
        - Dataviewsv2
        - Datasetsv2
        - Permission
        - Disable
        - Enable
  /datasets/{datasetId}/changesetsv2/{changesetId}:
    PUT:
      summary: UpdateChangeset
      description: <p>Updates a FinSpace Changeset.</p>
      tags:
        - Update
        - Changeset
        - Group
        - Id
        - Users
        - User
        - Changesetsv2
        - Dataviewsv2
        - Datasetsv2
        - Permission
        - Disable
        - Enable
        - Changeset
  /datasets/{datasetId}/dataviewsv2/{dataviewId}:
    GET:
      summary: GetDataView
      description: <p>Gets information about a Dataview.</p>
      tags:
        - Get
        - Data
        - View
        - Group
        - Id
        - Users
        - User
        - Changesetsv2
        - Dataviewsv2
        - Datasetsv2
        - Permission
        - Disable
        - Enable
        - Changeset
        - Dataview
  /datasets/{datasetId}/dataviewsv2/{dataviewId}/external-access-details:
    POST:
      summary: GetExternalDataViewAccessDetails
      description: >-
        <p>Returns the credentials to access the external Dataview from an S3
        location. To call this API:</p> <ul> <li> <p>You must retrieve the
        programmatic credentials.</p> </li> <li> <p>You must be a member of a
        FinSpace user group, where the dataset that you want to access has
        <code>Read Dataset Data</code> permissions.</p> </li> </ul>
      tags:
        - Get
        - External
        - Data
        - View
        - Access
        - Details
        - Group
        - Id
        - Users
        - User
        - Changesetsv2
        - Dataviewsv2
        - Datasetsv2
        - Permission
        - Disable
        - Enable
        - Changeset
        - Dataview
        - External
        - Access
        - Details
  /credentials/programmatic:
    GET:
      summary: GetProgrammaticAccessCredentials
      description: >-
        <p>Request programmatic credentials to use with FinSpace SDK. For more
        information, see <a
        href="https://docs.aws.amazon.com/finspace/latest/data-api/fs-using-the-finspace-api.html#accessing-credentials">Step
        2. Access credentials programmatically using IAM access key id and
        secret access key</a>.</p>
      tags:
        - Get
        - Programmatic
        - Access
        - Credentials
        - Group
        - Id
        - Users
        - User
        - Changesetsv2
        - Dataviewsv2
        - Datasetsv2
        - Permission
        - Disable
        - Enable
        - Changeset
        - Dataview
        - External
        - Access
        - Details
        - Credentials
        - Programmatic
  /user/{userId}:
    PUT:
      summary: UpdateUser
      description: >-
        <p>Modifies the details of the specified user. You cannot update the
        <code>userId</code> for a user.</p>
      tags:
        - Update
        - User
        - Group
        - Id
        - Users
        - User
        - Changesetsv2
        - Dataviewsv2
        - Datasetsv2
        - Permission
        - Disable
        - Enable
        - Changeset
        - Dataview
        - External
        - Access
        - Details
        - Credentials
        - Programmatic
  /workingLocationV1:
    POST:
      summary: GetWorkingLocation
      description: >-
        <p>A temporary Amazon S3 location, where you can copy your files from a
        source location to stage or use as a scratch space in FinSpace
        notebook.</p>
      tags:
        - Get
        - Working
        - Location
        - Group
        - Id
        - Users
        - User
        - Changesetsv2
        - Dataviewsv2
        - Datasetsv2
        - Permission
        - Disable
        - Enable
        - Changeset
        - Dataview
        - External
        - Access
        - Details
        - Credentials
        - Programmatic
        - Location
        - V1
  /user/{userId}/permission-groups:
    GET:
      summary: ListPermissionGroupsByUser
      description: >-
        <p>Lists all the permission groups that are associated with a specific
        user.</p>
      tags:
        - List
        - Permission
        - Groups
        - By
        - User
        - Group
        - Id
        - Users
        - User
        - Changesetsv2
        - Dataviewsv2
        - Datasetsv2
        - Permission
        - Disable
        - Enable
        - Changeset
        - Dataview
        - External
        - Access
        - Details
        - Credentials
        - Programmatic
        - Location
        - V1
        - Groups
  /permission-group/{permissionGroupId}/users:
    GET:
      summary: ListUsersByPermissionGroup
      description: <p>Lists details of all the users in a specific permission group.</p>
      tags:
        - List
        - Users
        - By
        - Permission
        - Group
        - Group
        - Id
        - Users
        - User
        - Changesetsv2
        - Dataviewsv2
        - Datasetsv2
        - Permission
        - Disable
        - Enable
        - Changeset
        - Dataview
        - External
        - Access
        - Details
        - Credentials
        - Programmatic
        - Location
        - V1
        - Groups
  /user/{userId}/password:
    POST:
      summary: ResetUserPassword
      description: >-
        <p>Resets the password for a specified user ID and generates a temporary
        one. Only a superuser can reset password for other users. Resetting the
        password immediately invalidates the previous password associated with
        the
      tags:
        - Reset
        - User
        - Password
        - Group
        - Id
        - Users
        - User
        - Changesetsv2
        - Dataviewsv2
        - Datasetsv2
        - Permission
        - Disable
        - Enable
        - Changeset
        - Dataview
        - External
        - Access
        - Details
        - Credentials
        - Programmatic
        - Location
        - V1
        - Groups
        - Passwo
