openapi: 3.1.0
info:
  title: fis
paths:
  /experimentTemplates:
    GET:
      summary: ListExperimentTemplates
      description: <p>Lists your experiment templates.</p>
      tags:
        - List
        - Experiment
        - Templates
        - Templates
  /experimentTemplates/{id}/targetAccountConfigurations/{accountId}:
    PATCH:
      summary: UpdateTargetAccountConfiguration
      description: >-
        <p>Updates the target account configuration for the specified experiment
        template.</p>
      tags:
        - Update
        - Target
        - Account
        - Configuration
        - Templates
        - Id
        - Target
        - Account
        - Configurations
  /experimentTemplates/{id}:
    PATCH:
      summary: UpdateExperimentTemplate
      description: <p>Updates the specified experiment template.</p>
      tags:
        - Update
        - Experiment
        - Template
        - Templates
        - Id
        - Target
        - Account
        - Configurations
  /actions/{id}:
    GET:
      summary: GetAction
      description: <p>Gets information about the specified FIS action.</p>
      tags:
        - Get
        - Action
        - Templates
        - Id
        - Target
        - Account
        - Configurations
        - Actions
  /experiments/{id}:
    DELETE:
      summary: StopExperiment
      description: <p>Stops the specified experiment.</p>
      tags:
        - Stop
        - Experiment
        - Templates
        - Id
        - Target
        - Account
        - Configurations
        - Actions
        - Experiments
  /experiments/{id}/targetAccountConfigurations/{accountId}:
    GET:
      summary: GetExperimentTargetAccountConfiguration
      description: >-
        <p>Gets information about the specified target account configuration of
        the experiment.</p>
      tags:
        - Get
        - Experiment
        - Target
        - Account
        - Configuration
        - Templates
        - Id
        - Target
        - Account
        - Configurations
        - Actions
        - Experiments
  /targetResourceTypes/{resourceType}:
    GET:
      summary: GetTargetResourceType
      description: <p>Gets information about the specified resource type.</p>
      tags:
        - Get
        - Target
        - Resource
        - Type
        - Templates
        - Id
        - Target
        - Account
        - Configurations
        - Actions
        - Experiments
        - Resource
        - Types
        - Type
  /actions:
    GET:
      summary: ListActions
      description: <p>Lists the available FIS actions.</p>
      tags:
        - List
        - Actions
        - Templates
        - Id
        - Target
        - Account
        - Configurations
        - Actions
        - Experiments
        - Resource
        - Types
        - Type
  /experiments/{id}/resolvedTargets:
    GET:
      summary: ListExperimentResolvedTargets
      description: >-
        <p>Lists the resolved targets information of the specified
        experiment.</p>
      tags:
        - List
        - Experiment
        - Resolved
        - Targets
        - Templates
        - Id
        - Target
        - Account
        - Configurations
        - Actions
        - Experiments
        - Resource
        - Types
        - Type
        - Targets
  /experiments/{id}/targetAccountConfigurations:
    GET:
      summary: ListExperimentTargetAccountConfigurations
      description: >-
        <p>Lists the target account configurations of the specified
        experiment.</p>
      tags:
        - List
        - Experiment
        - Target
        - Account
        - Configurations
        - Templates
        - Id
        - Target
        - Account
        - Configurations
        - Actions
        - Experiments
        - Resource
        - Types
        - Type
        - Targets
  /experiments:
    POST:
      summary: StartExperiment
      description: >-
        <p>Starts running an experiment from the specified experiment
        template.</p>
      tags:
        - Start
        - Experiment
        - Templates
        - Id
        - Target
        - Account
        - Configurations
        - Actions
        - Experiments
        - Resource
        - Types
        - Type
        - Targets
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Removes the specified tags from the specified resource.</p>
      tags:
        - Untag
        - Resource
        - Templates
        - Id
        - Target
        - Account
        - Configurations
        - Actions
        - Experiments
        - Resource
        - Types
        - Type
        - Targets
        - Arn
  /experimentTemplates/{id}/targetAccountConfigurations:
    GET:
      summary: ListTargetAccountConfigurations
      description: >-
        <p>Lists the target account configurations of the specified experiment
        template.</p>
      tags:
        - List
        - Target
        - Account
        - Configurations
        - Templates
        - Id
        - Target
        - Account
        - Configurations
        - Actions
        - Experiments
        - Resource
        - Types
        - Type
        - Targets
        - Arn
  /targetResourceTypes:
    GET:
      summary: ListTargetResourceTypes
      description: <p>Lists the target resource types.</
      tags:
        - List
        - Target
        - Resource
        - Types
        - Templates
        - Id
        - Target
        - Account
        - Configurations
        - Actions
        - Experiments
        - Resource
        - Types
        - Type
        - Targets
        - Arn
