openapi: 3.1.0
info:
  title: forecastquery
paths:
  /:
    POST:
      summary: QueryWhatIfForecast
      description: <p>Retrieves a what-if for
      tags:
        - Query
        - What
        - If
        - Foreca
