openapi: 3.1.0
info:
  title: identitystore
paths:
  /:
    POST:
      summary: UpdateUser
      description: >-
        <p>For the specified user in the specified identity store, updates the
        user metadata and attributes.</
      tags:
        - Update
        - nu
