openapi: 3.1.0
info:
  title: iot-jobs-data
paths:
  /things/{thingName}/jobs/{jobId}:
    POST:
      summary: UpdateJobExecution
      description: <p>Updates the status of a job execution.</p>
  /things/{thingName}/jobs:
    GET:
      summary: GetPendingJobExecutions
      description: >-
        <p>Gets the list of all jobs for a thing that are not in a terminal
        status.</p>
  /things/{thingName}/jobs/$next:
    PUT:
      summary: StartNextPendingJobExecution
      description: >-
        <p>Gets and starts the next pending (status IN_PROGRESS or QUEUED) job
        execution for a th
