openapi: 3.1.0
info:
  title: iot-roborunner
paths:
  /createDestination:
    POST:
      summary: CreateDestination
      description: <p>Grants permission to create a destination</p>
      tags:
        - Create
        - Destination
        - Destination
  /createSite:
    POST:
      summary: CreateSite
      description: <p>Grants permission to create a site</p>
      tags:
        - Create
        - Site
        - Destination
        - Site
  /createWorker:
    POST:
      summary: CreateWorker
      description: <p>Grants permission to create a worker</p>
      tags:
        - Create
        - Worker
        - Destination
        - Site
        - Worker
  /createWorkerFleet:
    POST:
      summary: CreateWorkerFleet
      description: <p>Grants permission to create a worker fleet</p>
      tags:
        - Create
        - Worker
        - Fleet
        - Destination
        - Site
        - Worker
        - Fleet
  /deleteDestination:
    POST:
      summary: DeleteDestination
      description: <p>Grants permission to delete a destination</p>
      tags:
        - Delete
        - Destination
        - Destination
        - Site
        - Worker
        - Fleet
  /deleteSite:
    POST:
      summary: DeleteSite
      description: <p>Grants permission to delete a site</p>
      tags:
        - Delete
        - Site
        - Destination
        - Site
        - Worker
        - Fleet
  /deleteWorker:
    POST:
      summary: DeleteWorker
      description: <p>Grants permission to delete a worker</p>
      tags:
        - Delete
        - Worker
        - Destination
        - Site
        - Worker
        - Fleet
  /deleteWorkerFleet:
    POST:
      summary: DeleteWorkerFleet
      description: <p>Grants permission to delete a worker fleet</p>
      tags:
        - Delete
        - Worker
        - Fleet
        - Destination
        - Site
        - Worker
        - Fleet
  /getDestination:
    GET:
      summary: GetDestination
      description: <p>Grants permission to get a destination</p>
      tags:
        - Get
        - Destination
        - Destination
        - Site
        - Worker
        - Fleet
  /getSite:
    GET:
      summary: GetSite
      description: <p>Grants permission to get a site</p>
      tags:
        - Get
        - Site
        - Destination
        - Site
        - Worker
        - Fleet
  /getWorker:
    GET:
      summary: GetWorker
      description: <p>Grants permission to get a worker</p>
      tags:
        - Get
        - Worker
        - Destination
        - Site
        - Worker
        - Fleet
  /getWorkerFleet:
    GET:
      summary: GetWorkerFleet
      description: <p>Grants permission to get a worker fleet</p>
      tags:
        - Get
        - Worker
        - Fleet
        - Destination
        - Site
        - Worker
        - Fleet
  /listDestinations:
    GET:
      summary: ListDestinations
      description: <p>Grants permission to list destinations</p>
      tags:
        - List
        - Destinations
        - Destination
        - Site
        - Worker
        - Fleet
        - Destinations
  /listSites:
    GET:
      summary: ListSites
      description: <p>Grants permission to list sites</p>
      tags:
        - List
        - Sites
        - Destination
        - Site
        - Worker
        - Fleet
        - Destinations
        - Sites
  /listWorkerFleets:
    GET:
      summary: ListWorkerFleets
      description: <p>Grants permission to list worker fleets</p>
      tags:
        - List
        - Worker
        - Fleets
        - Destination
        - Site
        - Worker
        - Fleet
        - Destinations
        - Sites
        - Fleets
  /listWorkers:
    GET:
      summary: ListWorkers
      description: <p>Grants permission to list workers</p>
      tags:
        - List
        - Workers
        - Destination
        - Site
        - Worker
        - Fleet
        - Destinations
        - Sites
        - Fleets
        - Workers
  /updateDestination:
    POST:
      summary: UpdateDestination
      description: <p>Grants permission to update a destination</p>
      tags:
        - Update
        - Destination
        - Destination
        - Site
        - Worker
        - Fleet
        - Destinations
        - Sites
        - Fleets
        - Workers
  /updateSite:
    POST:
      summary: UpdateSite
      description: <p>Grants permission to update a site</p>
      tags:
        - Update
        - Site
        - Destination
        - Site
        - Worker
        - Fleet
        - Destinations
        - Sites
        - Fleets
        - Workers
  /updateWorker:
    POST:
      summary: UpdateWorker
      description: <p>Grants permission to update a worker</p>
      tags:
        - Update
        - Worker
        - Destination
        - Site
        - Worker
        - Fleet
        - Destinations
        - Sites
        - Fleets
        - Workers
  /updateWorkerFleet:
    POST:
      summary: UpdateWorkerFleet
      description: <p>Grants permission to update a worker
      tags:
        - Update
        - Worker
        - Fleet
        - Destination
        - Site
        - Worker
        - Fleet
        - Destinations
        - Sites
        - Fleets
        - Worke
