openapi: 3.1.0
info:
  title: iotdeviceadvisor
paths:
  /suiteDefinitions:
    GET:
      summary: ListSuiteDefinitions
      description: >-
        <p>Lists the Device Advisor test suites you have created.</p>
        <p>Requires permission to access the <a
        href="https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiot.html#awsiot-actions-as-permissions">ListSuiteDefinitions</a>
        action.</p>
      tags:
        - List
        - Suite
        - Definitions
        - Definitions
  /suiteDefinitions/{suiteDefinitionId}:
    PATCH:
      summary: UpdateSuiteDefinition
      description: >-
        <p>Updates a Device Advisor test suite.</p> <p>Requires permission to
        access the <a
        href="https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiot.html#awsiot-actions-as-permissions">UpdateSuiteDefinition</a>
        action.</p>
      tags:
        - Update
        - Suite
        - Definition
        - Definitions
        - Suite
        - Definition
        - Id
  /endpoint:
    GET:
      summary: GetEndpoint
      description: <p>Gets information about an Device Advisor endpoint.</p>
      tags:
        - Get
        - Endpoint
        - Definitions
        - Suite
        - Definition
        - Id
        - Endpoint
  /suiteDefinitions/{suiteDefinitionId}/suiteRuns/{suiteRunId}:
    GET:
      summary: GetSuiteRun
      description: >-
        <p>Gets information about a Device Advisor test suite run.</p>
        <p>Requires permission to access the <a
        href="https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiot.html#awsiot-actions-as-permissions">GetSuiteRun</a>
        action.</p>
      tags:
        - Get
        - Suite
        - Run
        - Definitions
        - Suite
        - Definition
        - Id
        - Endpoint
        - Runs
        - Run
  /suiteDefinitions/{suiteDefinitionId}/suiteRuns/{suiteRunId}/report:
    GET:
      summary: GetSuiteRunReport
      description: >-
        <p>Gets a report download link for a successful Device Advisor
        qualifying test suite run.</p> <p>Requires permission to access the <a
        href="https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiot.html#awsiot-actions-as-permissions">GetSuiteRunReport</a>
        action.</p>
      tags:
        - Get
        - Suite
        - Run
        - Report
        - Definitions
        - Suite
        - Definition
        - Id
        - Endpoint
        - Runs
        - Run
        - Report
  /suiteRuns:
    GET:
      summary: ListSuiteRuns
      description: >-
        <p>Lists runs of the specified Device Advisor test suite. You can list
        all runs of the test suite, or the runs of a specific version of the
        test suite.</p> <p>Requires permission to access the <a
        href="https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiot.html#awsiot-actions-as-permissions">ListSuiteRuns</a>
        action.</p>
      tags:
        - List
        - Suite
        - Runs
        - Definitions
        - Suite
        - Definition
        - Id
        - Endpoint
        - Runs
        - Run
        - Report
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: >-
        <p>Removes tags from an IoT Device Advisor resource.</p> <p>Requires
        permission to access the <a
        href="https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiot.html#awsiot-actions-as-permissions">UntagResource</a>
        action.</p>
      tags:
        - Untag
        - Resource
        - Definitions
        - Suite
        - Definition
        - Id
        - Endpoint
        - Runs
        - Run
        - Report
        - Arn
  /suiteDefinitions/{suiteDefinitionId}/suiteRuns:
    POST:
      summary: StartSuiteRun
      description: >-
        <p>Starts a Device Advisor test suite run.</p> <p>Requires permission to
        access the <a
        href="https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiot.html#awsiot-actions-as-permissions">StartSuiteRun</a>
        action.</p>
      tags:
        - Start
        - Suite
        - Run
        - Definitions
        - Suite
        - Definition
        - Id
        - Endpoint
        - Runs
        - Run
        - Report
        - Arn
  /suiteDefinitions/{suiteDefinitionId}/suiteRuns/{suiteRunId}/stop:
    POST:
      summary: StopSuiteRun
      description: >-
        <p>Stops a Device Advisor test suite run that is currently running.</p>
        <p>Requires permission to access the <a
        href="https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiot.html#awsiot-actions-as-permissions">StopSuiteRun</a>
        action.</
      tags:
        - Stop
        - Suite
        - Run
        - Definitions
        - Suite
        - Definition
        - Id
        - Endpoint
        - Runs
        - Run
        - Report
        - Arn
        - Stop
