openapi: 3.1.0
info:
  title: iotsecuretunneling
paths:
  /:
    POST:
      summary: UntagResource
      description: <p>Removes a tag from a resource.</
      tags:
        - Untag
        - Resource
