openapi: 3.1.0
info:
  title: iottwinmaker
paths:
  /workspaces/{workspaceId}/entity-properties:
    POST:
      summary: BatchPutPropertyValues
      description: <p>Sets values for multiple time series properties.</p>
      tags:
        - Batch
        - Put
        - Property
        - Values
        - Id
        - Entity
        - Properties
  /metadata-transfer-jobs/{metadataTransferJobId}/cancel:
    PUT:
      summary: CancelMetadataTransferJob
      description: <p>Cancels the metadata transfer job.</p>
      tags:
        - Cancel
        - Metadata
        - Transfer
        - Job
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
  /workspaces/{workspaceId}/component-types/{componentTypeId}:
    PUT:
      summary: UpdateComponentType
      description: <p>Updates information in a component type.</p>
      tags:
        - Update
        - Component
        - Type
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
  /workspaces/{workspaceId}/entities:
    POST:
      summary: CreateEntity
      description: <p>Creates an entity.</p>
      tags:
        - Create
        - Entity
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
  /metadata-transfer-jobs:
    POST:
      summary: CreateMetadataTransferJob
      description: <p>Creates a new metadata transfer job.</p>
      tags:
        - Create
        - Metadata
        - Transfer
        - Job
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
  /workspaces/{workspaceId}/scenes:
    POST:
      summary: CreateScene
      description: <p>Creates a scene.</p>
      tags:
        - Create
        - Scene
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
  /workspaces/{workspaceId}/sync-jobs/{syncSource}:
    DELETE:
      summary: DeleteSyncJob
      description: <p>Delete the SyncJob.</p>
      tags:
        - Delete
        - Sync
        - Job
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
        - Sync
        - Source
  /workspaces/{workspaceId}:
    PUT:
      summary: UpdateWorkspace
      description: <p>Updates a workspace.</p>
      tags:
        - Update
        - Workspace
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
        - Sync
        - Source
  /workspaces/{workspaceId}/entities/{entityId}:
    PUT:
      summary: UpdateEntity
      description: <p>Updates an entity.</p>
      tags:
        - Update
        - Entity
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
        - Sync
        - Source
  /workspaces/{workspaceId}/scenes/{sceneId}:
    PUT:
      summary: UpdateScene
      description: <p>Updates a scene.</p>
      tags:
        - Update
        - Scene
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
        - Sync
        - Source
        - Scene
  /queries/execution:
    POST:
      summary: ExecuteQuery
      description: >-
        <p>Run queries to access information from your knowledge graph of
        entities within individual workspaces.</p> <note> <p>The ExecuteQuery
        action only works with <a
        href="https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/home.html">Amazon
        Web Services Java SDK2</a>. ExecuteQuery will not work with any Amazon
        Web Services Java SDK version &lt; 2.x.</p> </note>
      tags:
        - Execute
        - Query
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
        - Sync
        - Source
        - Scene
        - Queries
        - Execution
  /metadata-transfer-jobs/{metadataTransferJobId}:
    GET:
      summary: GetMetadataTransferJob
      description: <p>Gets a nmetadata transfer job.</p>
      tags:
        - Get
        - Metadata
        - Transfer
        - Job
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
        - Sync
        - Source
        - Scene
        - Queries
        - Execution
  /pricingplan:
    POST:
      summary: UpdatePricingPlan
      description: <p>Update the pricing plan.</p>
      tags:
        - Update
        - Pricing
        - Plan
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
        - Sync
        - Source
        - Scene
        - Queries
        - Execution
        - Pricingplan
  /workspaces/{workspaceId}/entity-properties/value:
    POST:
      summary: GetPropertyValue
      description: >-
        <p>Gets the property values for a component, component type, entity, or
        workspace.</p> <p>You must specify a value for either
        <code>componentName</code>, <code>componentTypeId</code>,
        <code>entityId</code>, or <code>workspaceId</code>.</p>
      tags:
        - Get
        - Property
        - Value
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
        - Sync
        - Source
        - Scene
        - Queries
        - Execution
        - Pricingplan
        - Value
  /workspaces/{workspaceId}/entity-properties/history:
    POST:
      summary: GetPropertyValueHistory
      description: >-
        <p>Retrieves information about the history of a time series property
        value for a component, component type, entity, or workspace.</p> <p>You
        must specify a value for <code>workspaceId</code>. For entity-specific
        queries, specify values for <code>componentName</code> and
        <code>entityId</code>. For cross-entity quries, specify a value for
        <code>componentTypeId</code>.</p>
      tags:
        - Get
        - Property
        - Value
        - History
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
        - Sync
        - Source
        - Scene
        - Queries
        - Execution
        - Pricingplan
        - Value
        - History
  /sync-jobs/{syncSource}:
    GET:
      summary: GetSyncJob
      description: <p>Gets the SyncJob.</p>
      tags:
        - Get
        - Sync
        - Job
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
        - Sync
        - Source
        - Scene
        - Queries
        - Execution
        - Pricingplan
        - Value
        - History
  /workspaces/{workspaceId}/component-types-list:
    POST:
      summary: ListComponentTypes
      description: <p>Lists all component types in a workspace.</p>
      tags:
        - List
        - Component
        - Types
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
        - Sync
        - Source
        - Scene
        - Queries
        - Execution
        - Pricingplan
        - Value
        - History
        - List
  /workspaces/{workspaceId}/entities/{entityId}/components-list:
    POST:
      summary: ListComponents
      description: <p>This API lists the components of an entity.</p>
      tags:
        - List
        - Components
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
        - Sync
        - Source
        - Scene
        - Queries
        - Execution
        - Pricingplan
        - Value
        - History
        - List
        - Components
  /workspaces/{workspaceId}/entities-list:
    POST:
      summary: ListEntities
      description: <p>Lists all entities in a workspace.</p>
      tags:
        - List
        - Entities
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
        - Sync
        - Source
        - Scene
        - Queries
        - Execution
        - Pricingplan
        - Value
        - History
        - List
        - Components
  /metadata-transfer-jobs-list:
    POST:
      summary: ListMetadataTransferJobs
      description: <p>Lists the metadata transfer jobs.</p>
      tags:
        - List
        - Metadata
        - Transfer
        - Jobs
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
        - Sync
        - Source
        - Scene
        - Queries
        - Execution
        - Pricingplan
        - Value
        - History
        - List
        - Components
  /workspaces/{workspaceId}/properties-list:
    POST:
      summary: ListProperties
      description: <p>This API lists the properties of a component.</p>
      tags:
        - List
        - Properties
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
        - Sync
        - Source
        - Scene
        - Queries
        - Execution
        - Pricingplan
        - Value
        - History
        - List
        - Components
  /workspaces/{workspaceId}/scenes-list:
    POST:
      summary: ListScenes
      description: <p>Lists all scenes in a workspace.</p>
      tags:
        - List
        - Scenes
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
        - Sync
        - Source
        - Scene
        - Queries
        - Execution
        - Pricingplan
        - Value
        - History
        - List
        - Components
  /workspaces/{workspaceId}/sync-jobs-list:
    POST:
      summary: ListSyncJobs
      description: <p>List all SyncJobs.</p>
      tags:
        - List
        - Sync
        - Jobs
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
        - Sync
        - Source
        - Scene
        - Queries
        - Execution
        - Pricingplan
        - Value
        - History
        - List
        - Components
  /workspaces/{workspaceId}/sync-jobs/{syncSource}/resources-list:
    POST:
      summary: ListSyncResources
      description: <p>Lists the sync resources.</p>
      tags:
        - List
        - Sync
        - Resources
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
        - Sync
        - Source
        - Scene
        - Queries
        - Execution
        - Pricingplan
        - Value
        - History
        - List
        - Components
        - Resources
  /tags-list:
    POST:
      summary: ListTagsForResource
      description: <p>Lists all tags associated with a resource.</p>
      tags:
        - List
        - Tags
        - For
        - Resource
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
        - Sync
        - Source
        - Scene
        - Queries
        - Execution
        - Pricingplan
        - Value
        - History
        - List
        - Components
        - Resources
        - Tags
  /workspaces-list:
    POST:
      summary: ListWorkspaces
      description: <p>Retrieves information about workspaces in the current account.</p>
      tags:
        - List
        - Workspaces
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
        - Sync
        - Source
        - Scene
        - Queries
        - Execution
        - Pricingplan
        - Value
        - History
        - List
        - Components
        - Resources
        - Tags
        - Workspaces
  /tags:
    DELETE:
      summary: UntagResource
      description: <p>Removes tags from a resource.</
      tags:
        - Untag
        - Resource
        - Id
        - Entity
        - Properties
        - Transfer
        - Job
        - Cancel
        - Component
        - Types
        - Type
        - Entities
        - Metadata
        - Jobs
        - Scenes
        - Sync
        - Source
        - Scene
        - Queries
        - Execution
        - Pricingplan
        - Value
        - History
        - List
        - Components
        - Resources
        - Tags
        - Work
