openapi: 3.1.0
info:
  title: ivs-realtime
paths:
  /CreateEncoderConfiguration:
    POST:
      summary: CreateEncoderConfiguration
      description: <p>Creates an EncoderConfiguration object.</p>
  /CreateParticipantToken:
    POST:
      summary: CreateParticipantToken
      description: >-
        <p>Creates an additional token for a specified stage. This can be done
        after stage creation or when tokens expire. Tokens always are scoped to
        the stage for which they are created.</p> <p>Encryption keys are owned
        by Amazon IVS and never used directly by your application.</p>
  /CreateStage:
    POST:
      summary: CreateStage
      description: <p>Creates a new stage (and optionally participant tokens).</p>
  /CreateStorageConfiguration:
    POST:
      summary: CreateStorageConfiguration
      description: >-
        <p>Creates a new storage configuration, used to enable recording to
        Amazon S3. When a StorageConfiguration is created, IVS will modify the
        S3 bucketPolicy of the provided bucket. This will ensure that IVS has
        sufficient permissions to write content to the provided bucket.</p>
  /DeleteEncoderConfiguration:
    POST:
      summary: DeleteEncoderConfiguration
      description: >-
        <p>Deletes an EncoderConfiguration resource. Ensures that no
        Compositions are using this template; otherwise, returns an error.</p>
  /DeleteStage:
    POST:
      summary: DeleteStage
      description: >-
        <p>Shuts down and deletes the specified stage (disconnecting all
        participants).</p>
  /DeleteStorageConfiguration:
    POST:
      summary: DeleteStorageConfiguration
      description: >-
        <p>Deletes the storage configuration for the specified ARN.</p> <p>If
        you try to delete a storage configuration that is used by a Composition,
        you will get an error (409 ConflictException). To avoid this, for all
        Compositions that reference the storage configuration, first use
        <a>StopComposition</a> and wait for it to complete, then use
        DeleteStorageConfiguration.</p>
  /DisconnectParticipant:
    POST:
      summary: DisconnectParticipant
      description: >-
        <p>Disconnects a specified participant and revokes the participant
        permanently from a specified stage.</p>
  /GetComposition:
    POST:
      summary: GetComposition
      description: <p>Get information about the specified Composition resource.</p>
  /GetEncoderConfiguration:
    POST:
      summary: GetEncoderConfiguration
      description: >-
        <p>Gets information about the specified EncoderConfiguration resource.
        </p>
  /GetParticipant:
    POST:
      summary: GetParticipant
      description: <p>Gets information about the specified participant token.</p>
  /GetStage:
    POST:
      summary: GetStage
      description: <p>Gets information for the specified stage.</p>
  /GetStageSession:
    POST:
      summary: GetStageSession
      description: <p>Gets information for the specified stage session.</p>
  /GetStorageConfiguration:
    POST:
      summary: GetStorageConfiguration
      description: <p>Gets the storage configuration for the specified ARN.</p>
  /ListCompositions:
    POST:
      summary: ListCompositions
      description: >-
        <p>Gets summary information about all Compositions in your account, in
        the AWS region where the API request is processed. </p>
  /ListEncoderConfigurations:
    POST:
      summary: ListEncoderConfigurations
      description: >-
        <p>Gets summary information about all EncoderConfigurations in your
        account, in the AWS region where the API request is processed.</p>
  /ListParticipantEvents:
    POST:
      summary: ListParticipantEvents
      description: >-
        <p>Lists events for a specified participant that occurred during a
        specified stage session.</p>
  /ListParticipants:
    POST:
      summary: ListParticipants
      description: <p>Lists all participants in a specified stage session.</p>
  /ListStageSessions:
    POST:
      summary: ListStageSessions
      description: <p>Gets all sessions for a specified stage.</p>
  /ListStages:
    POST:
      summary: ListStages
      description: >-
        <p>Gets summary information about all stages in your account, in the AWS
        region where the API request is processed.</p>
  /ListStorageConfigurations:
    POST:
      summary: ListStorageConfigurations
      description: >-
        <p>Gets summary information about all storage configurations in your
        account, in the AWS region where the API request is processed.</p>
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Removes tags from the resource with the specified ARN.</p>
  /StartComposition:
    POST:
      summary: StartComposition
      description: >-
        <p>Starts a Composition from a stage based on the configuration provided
        in the request.</p> <p>A Composition is an ephemeral resource that
        exists after this endpoint returns successfully. Composition stops and
        the resource is deleted:</p> <ul> <li> <p>When <a>StopComposition</a> is
        called.</p> </li> <li> <p>After a 1-minute timeout, when all
        participants are disconnected from the stage.</p> </li> <li> <p>After a
        1-minute timeout, if there are no participants in the stage when
        StartComposition is called.</p> </li> <li> <p>When broadcasting to the
        IVS channel fails and all retries are exhausted.</p> </li> <li> <p>When
        broadcasting is disconnected and all attempts to reconnect are
        exhausted.</p> </li> </ul>
  /StopComposition:
    POST:
      summary: StopComposition
      description: >-
        <p>Stops and deletes a Composition resource. Any broadcast from the
        Composition resource is stopped.</p>
  /UpdateStage:
    POST:
      summary: UpdateStage
      description: <p>Updates a stage’s configurat
