openapi: 3.1.0
info:
  title: launch-wizard
paths:
  /createDeployment:
    POST:
      summary: CreateDeployment
      description: >-
        <p>Creates a deployment for the given workload. Deployments created by
        this operation are not available in the Launch Wizard console to use the
        <code>Clone deployment</code> action on.</p>
      tags:
        - Create
        - Deployment
        - Deployment
  /deleteDeployment:
    POST:
      summary: DeleteDeployment
      description: <p>Deletes a deployment.</p>
      tags:
        - Delete
        - Deployment
        - Deployment
  /getDeployment:
    POST:
      summary: GetDeployment
      description: <p>Returns information about the deployment.</p>
      tags:
        - Get
        - Deployment
        - Deployment
  /getWorkload:
    POST:
      summary: GetWorkload
      description: <p>Returns information about a workload.</p>
      tags:
        - Get
        - Workload
        - Deployment
        - Workload
  /listDeploymentEvents:
    POST:
      summary: ListDeploymentEvents
      description: <p>Lists the events of a deployment.</p>
      tags:
        - List
        - Deployment
        - Events
        - Deployment
        - Workload
        - Events
  /listDeployments:
    POST:
      summary: ListDeployments
      description: <p>Lists the deployments that have been created.</p>
      tags:
        - List
        - Deployments
        - Deployment
        - Workload
        - Events
        - Deployments
  /listWorkloadDeploymentPatterns:
    POST:
      summary: ListWorkloadDeploymentPatterns
      description: <p>Lists the workload deployment patterns.</p>
      tags:
        - List
        - Workload
        - Deployment
        - Patterns
        - Deployment
        - Workload
        - Events
        - Deployments
        - Patterns
  /listWorkloads:
    POST:
      summary: ListWorkloads
      description: <p>Lists the workloads.</
      tags:
        - List
        - Workloads
        - Deployment
        - Workload
        - Events
        - Deployments
        - Patterns
        - Workloads
