openapi: 3.1.0
info:
  title: license-manager-linux-subscriptions
paths:
  /subscription/GetServiceSettings:
    POST:
      summary: GetServiceSettings
      description: <p>Lists the Linux subscriptions service settings.</p>
      tags:
        - Get
        - Service
        - Settings
        - Get
        - Service
        - Settings
  /subscription/ListLinuxSubscriptionInstances:
    POST:
      summary: ListLinuxSubscriptionInstances
      description: >-
        <p>Lists the running Amazon EC2 instances that were discovered with
        commercial Linux subscriptions.</p>
      tags:
        - List
        - Linux
        - Subscription
        - Instances
        - Get
        - Service
        - Settings
        - List
        - Linux
        - Subscription
        - Instances
  /subscription/ListLinuxSubscriptions:
    POST:
      summary: ListLinuxSubscriptions
      description: >-
        <p>Lists the Linux subscriptions that have been discovered. If you have
        linked your organization, the returned results will include data
        aggregated across your accounts in Organizations.</p>
      tags:
        - List
        - Linux
        - Subscriptions
        - Get
        - Service
        - Settings
        - List
        - Linux
        - Subscription
        - Instances
        - Subscriptions
  /subscription/UpdateServiceSettings:
    POST:
      summary: UpdateServiceSettings
      description: <p>Updates the service settings for Linux subscriptions.</
      tags:
        - Update
        - Service
        - Settings
        - Get
        - Service
        - Settings
        - List
        - Linux
        - Subscription
        - Instances
        - Subscriptions
        - null
