openapi: 3.1.0
info:
  title: license-manager-user-subscriptions
paths:
  /user/AssociateUser:
    POST:
      summary: AssociateUser
      description: >-
        <p>Associates the user to an EC2 instance to utilize user-based
        subscriptions.</p> <note> <p>Your estimated bill for charges on the
        number of users and related costs will take 48 hours to appear for
        billing periods that haven't closed (marked as <b>Pending</b> billing
        status) in Amazon Web Services Billing. For more information, see <a
        href="https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/invoice.html">Viewing
        your monthly charges</a> in the <i>Amazon Web Services Billing User
        Guide</i>.</p> </note>
      tags:
        - Associate
        - User
        - Associate
        - User
  /identity-provider/DeregisterIdentityProvider:
    POST:
      summary: DeregisterIdentityProvider
      description: >-
        <p>Deregisters the identity provider from providing user-based
        subscriptions.</p>
      tags:
        - Deregister
        - Identity
        - Provider
        - Associate
        - User
        - Deregister
        - Identity
        - Provider
  /user/DisassociateUser:
    POST:
      summary: DisassociateUser
      description: >-
        <p>Disassociates the user from an EC2 instance providing user-based
        subscriptions.</p>
      tags:
        - Disassociate
        - User
        - Associate
        - User
        - Deregister
        - Identity
        - Provider
        - Disassociate
  /identity-provider/ListIdentityProviders:
    POST:
      summary: ListIdentityProviders
      description: <p>Lists the identity providers for user-based subscriptions.</p>
      tags:
        - List
        - Identity
        - Providers
        - Associate
        - User
        - Deregister
        - Identity
        - Provider
        - Disassociate
        - List
        - Providers
  /instance/ListInstances:
    POST:
      summary: ListInstances
      description: <p>Lists the EC2 instances providing user-based subscriptions.</p>
      tags:
        - List
        - Instances
        - Associate
        - User
        - Deregister
        - Identity
        - Provider
        - Disassociate
        - List
        - Providers
        - Instances
  /user/ListProductSubscriptions:
    POST:
      summary: ListProductSubscriptions
      description: >-
        <p>Lists the user-based subscription products available from an identity
        provider.</p>
      tags:
        - List
        - Product
        - Subscriptions
        - Associate
        - User
        - Deregister
        - Identity
        - Provider
        - Disassociate
        - List
        - Providers
        - Instances
        - Product
        - Subscriptions
  /user/ListUserAssociations:
    POST:
      summary: ListUserAssociations
      description: <p>Lists user associations for an identity provider.</p>
      tags:
        - List
        - User
        - Associations
        - Associate
        - User
        - Deregister
        - Identity
        - Provider
        - Disassociate
        - List
        - Providers
        - Instances
        - Product
        - Subscriptions
        - Associations
  /identity-provider/RegisterIdentityProvider:
    POST:
      summary: RegisterIdentityProvider
      description: <p>Registers an identity provider for user-based subscriptions.</p>
      tags:
        - Register
        - Identity
        - Provider
        - Associate
        - User
        - Deregister
        - Identity
        - Provider
        - Disassociate
        - List
        - Providers
        - Instances
        - Product
        - Subscriptions
        - Associations
        - Register
  /user/StartProductSubscription:
    POST:
      summary: StartProductSubscription
      description: >-
        <p>Starts a product subscription for a user with the specified identity
        provider.</p> <note> <p>Your estimated bill for charges on the number of
        users and related costs will take 48 hours to appear for billing periods
        that haven't closed (marked as <b>Pending</b> billing status) in Amazon
        Web Services Billing. For more information, see <a
        href="https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/invoice.html">Viewing
        your monthly charges</a> in the <i>Amazon Web Services Billing User
        Guide</i>.</p> </note>
      tags:
        - Start
        - Product
        - Subscription
        - Associate
        - User
        - Deregister
        - Identity
        - Provider
        - Disassociate
        - List
        - Providers
        - Instances
        - Product
        - Subscriptions
        - Associations
        - Register
        - Start
        - Subscription
  /user/StopProductSubscription:
    POST:
      summary: StopProductSubscription
      description: >-
        <p>Stops a product subscription for a user with the specified identity
        provider.</p>
      tags:
        - Stop
        - Product
        - Subscription
        - Associate
        - User
        - Deregister
        - Identity
        - Provider
        - Disassociate
        - List
        - Providers
        - Instances
        - Product
        - Subscriptions
        - Associations
        - Register
        - Start
        - Subscription
        - Stop
  /identity-provider/UpdateIdentityProviderSettings:
    POST:
      summary: UpdateIdentityProviderSettings
      description: >-
        <p>Updates additional product configuration settings for the registered
        identity provider.</
      tags:
        - Update
        - Identity
        - Provider
        - Settings
        - Associate
        - User
        - Deregister
        - Identity
        - Provider
        - Disassociate
        - List
        - Providers
        - Instances
        - Product
        - Subscriptions
        - Associations
        - Register
        - Start
        - Subscription
        - Stop
        - Update
        - Settings
