openapi: 3.1.0
info:
  title: logs
paths:
  /:
    POST:
      summary: UpdateLogAnomalyDetector
      description: <p>Updates an existing log anomaly detector.</
      tags:
        - Update
        - Log
        - Anomaly
        - De
