openapi: 3.1.0
info:
  title: lookoutmetrics
paths:
  /ActivateAnomalyDetector:
    POST:
      summary: ActivateAnomalyDetector
      description: <p>Activates an anomaly detector.</p>
      tags:
        - Activate
        - Anomaly
        - Detector
        - Activate
        - Anomaly
        - Detector
  /BackTestAnomalyDetector:
    POST:
      summary: BackTestAnomalyDetector
      description: <p>Runs a backtest for anomaly detection for the specified resource.</p>
      tags:
        - Back
        - Test
        - Anomaly
        - Detector
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
  /CreateAlert:
    POST:
      summary: CreateAlert
      description: <p>Creates an alert for an anomaly detector.</p>
      tags:
        - Create
        - Alert
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
  /CreateAnomalyDetector:
    POST:
      summary: CreateAnomalyDetector
      description: <p>Creates an anomaly detector.</p>
      tags:
        - Create
        - Anomaly
        - Detector
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
  /CreateMetricSet:
    POST:
      summary: CreateMetricSet
      description: <p>Creates a dataset.</p>
      tags:
        - Create
        - Metric
        - Set
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
  /DeactivateAnomalyDetector:
    POST:
      summary: DeactivateAnomalyDetector
      description: <p>Deactivates an anomaly detector.</p>
      tags:
        - Deactivate
        - Anomaly
        - Detector
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
  /DeleteAlert:
    POST:
      summary: DeleteAlert
      description: <p>Deletes an alert.</p>
      tags:
        - Delete
        - Alert
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
  /DeleteAnomalyDetector:
    POST:
      summary: DeleteAnomalyDetector
      description: >-
        <p>Deletes a detector. Deleting an anomaly detector will delete all of
        its corresponding resources including any configured datasets and
        alerts.</p>
      tags:
        - Delete
        - Anomaly
        - Detector
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
  /DescribeAlert:
    POST:
      summary: DescribeAlert
      description: >-
        <p>Describes an alert.</p> <p>Amazon Lookout for Metrics API actions are
        eventually consistent. If you do a read operation on a resource
        immediately after creating or modifying it, use retries to allow time
        for the write operation to complete.</p>
      tags:
        - Describe
        - Alert
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
        - Describe
  /DescribeAnomalyDetectionExecutions:
    POST:
      summary: DescribeAnomalyDetectionExecutions
      description: >-
        <p>Returns information about the status of the specified anomaly
        detection jobs.</p>
      tags:
        - Describe
        - Anomaly
        - Detection
        - Executions
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
        - Describe
        - Detection
        - Executions
  /DescribeAnomalyDetector:
    POST:
      summary: DescribeAnomalyDetector
      description: >-
        <p>Describes a detector.</p> <p>Amazon Lookout for Metrics API actions
        are eventually consistent. If you do a read operation on a resource
        immediately after creating or modifying it, use retries to allow time
        for the write operation to complete.</p>
      tags:
        - Describe
        - Anomaly
        - Detector
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
        - Describe
        - Detection
        - Executions
  /DescribeMetricSet:
    POST:
      summary: DescribeMetricSet
      description: >-
        <p>Describes a dataset.</p> <p>Amazon Lookout for Metrics API actions
        are eventually consistent. If you do a read operation on a resource
        immediately after creating or modifying it, use retries to allow time
        for the write operation to complete.</p>
      tags:
        - Describe
        - Metric
        - Set
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
        - Describe
        - Detection
        - Executions
  /DetectMetricSetConfig:
    POST:
      summary: DetectMetricSetConfig
      description: <p>Detects an Amazon S3 dataset's file format, interval, and offset.</p>
      tags:
        - Detect
        - Metric
        - Set
        - Config
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
        - Describe
        - Detection
        - Executions
        - Detect
        - Config
  /GetAnomalyGroup:
    POST:
      summary: GetAnomalyGroup
      description: <p>Returns details about a group of anomalous metrics.</p>
      tags:
        - Get
        - Anomaly
        - Group
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
        - Describe
        - Detection
        - Executions
        - Detect
        - Config
        - Get
        - Group
  /GetDataQualityMetrics:
    POST:
      summary: GetDataQualityMetrics
      description: <p>Returns details about the requested data quality metrics.</p>
      tags:
        - Get
        - Data
        - Quality
        - Metrics
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
        - Describe
        - Detection
        - Executions
        - Detect
        - Config
        - Get
        - Group
        - Data
        - Quality
        - Metrics
  /GetFeedback:
    POST:
      summary: GetFeedback
      description: <p>Get feedback for an anomaly group.</p>
      tags:
        - Get
        - Feedback
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
        - Describe
        - Detection
        - Executions
        - Detect
        - Config
        - Get
        - Group
        - Data
        - Quality
        - Metrics
        - Feedback
  /GetSampleData:
    POST:
      summary: GetSampleData
      description: >-
        <p>Returns a selection of sample records from an Amazon S3
        datasource.</p>
      tags:
        - Get
        - Sample
        - Data
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
        - Describe
        - Detection
        - Executions
        - Detect
        - Config
        - Get
        - Group
        - Data
        - Quality
        - Metrics
        - Feedback
        - Sample
  /ListAlerts:
    POST:
      summary: ListAlerts
      description: >-
        <p>Lists the alerts attached to a detector.</p> <p>Amazon Lookout for
        Metrics API actions are eventually consistent. If you do a read
        operation on a resource immediately after creating or modifying it, use
        retries to allow time for the write operation to complete.</p>
      tags:
        - List
        - Alerts
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
        - Describe
        - Detection
        - Executions
        - Detect
        - Config
        - Get
        - Group
        - Data
        - Quality
        - Metrics
        - Feedback
        - Sample
        - List
        - Alerts
  /ListAnomalyDetectors:
    POST:
      summary: ListAnomalyDetectors
      description: >-
        <p>Lists the detectors in the current AWS Region.</p> <p>Amazon Lookout
        for Metrics API actions are eventually consistent. If you do a read
        operation on a resource immediately after creating or modifying it, use
        retries to allow time for the write operation to complete.</p>
      tags:
        - List
        - Anomaly
        - Detectors
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
        - Describe
        - Detection
        - Executions
        - Detect
        - Config
        - Get
        - Group
        - Data
        - Quality
        - Metrics
        - Feedback
        - Sample
        - List
        - Alerts
        - Detectors
  /ListAnomalyGroupRelatedMetrics:
    POST:
      summary: ListAnomalyGroupRelatedMetrics
      description: >-
        <p>Returns a list of measures that are potential causes or effects of an
        anomaly group.</p>
      tags:
        - List
        - Anomaly
        - Group
        - Related
        - Metrics
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
        - Describe
        - Detection
        - Executions
        - Detect
        - Config
        - Get
        - Group
        - Data
        - Quality
        - Metrics
        - Feedback
        - Sample
        - List
        - Alerts
        - Detectors
        - Related
  /ListAnomalyGroupSummaries:
    POST:
      summary: ListAnomalyGroupSummaries
      description: <p>Returns a list of anomaly groups.</p>
      tags:
        - List
        - Anomaly
        - Group
        - Summaries
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
        - Describe
        - Detection
        - Executions
        - Detect
        - Config
        - Get
        - Group
        - Data
        - Quality
        - Metrics
        - Feedback
        - Sample
        - List
        - Alerts
        - Detectors
        - Related
        - Summaries
  /ListAnomalyGroupTimeSeries:
    POST:
      summary: ListAnomalyGroupTimeSeries
      description: >-
        <p>Gets a list of anomalous metrics for a measure in an anomaly
        group.</p>
      tags:
        - List
        - Anomaly
        - Group
        - Time
        - Series
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
        - Describe
        - Detection
        - Executions
        - Detect
        - Config
        - Get
        - Group
        - Data
        - Quality
        - Metrics
        - Feedback
        - Sample
        - List
        - Alerts
        - Detectors
        - Related
        - Summaries
        - Time
        - Series
  /ListMetricSets:
    POST:
      summary: ListMetricSets
      description: >-
        <p>Lists the datasets in the current AWS Region.</p> <p>Amazon Lookout
        for Metrics API actions are eventually consistent. If you do a read
        operation on a resource immediately after creating or modifying it, use
        retries to allow time for the write operation to complete.</p>
      tags:
        - List
        - Metric
        - Sets
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
        - Describe
        - Detection
        - Executions
        - Detect
        - Config
        - Get
        - Group
        - Data
        - Quality
        - Metrics
        - Feedback
        - Sample
        - List
        - Alerts
        - Detectors
        - Related
        - Summaries
        - Time
        - Series
        - Sets
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: >-
        <p>Removes <a
        href="https://docs.aws.amazon.com/lookoutmetrics/latest/dev/detectors-tags.html">tags</a>
        from a detector, dataset, or alert.</p>
      tags:
        - Untag
        - Resource
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
        - Describe
        - Detection
        - Executions
        - Detect
        - Config
        - Get
        - Group
        - Data
        - Quality
        - Metrics
        - Feedback
        - Sample
        - List
        - Alerts
        - Detectors
        - Related
        - Summaries
        - Time
        - Series
        - Sets
        - Arn
  /PutFeedback:
    POST:
      summary: PutFeedback
      description: <p>Add feedback for an anomalous metric.</p>
      tags:
        - Put
        - Feedback
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
        - Describe
        - Detection
        - Executions
        - Detect
        - Config
        - Get
        - Group
        - Data
        - Quality
        - Metrics
        - Feedback
        - Sample
        - List
        - Alerts
        - Detectors
        - Related
        - Summaries
        - Time
        - Series
        - Sets
        - Arn
        - Put
  /UpdateAlert:
    POST:
      summary: UpdateAlert
      description: <p>Make changes to an existing alert.</p>
      tags:
        - Update
        - Alert
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
        - Describe
        - Detection
        - Executions
        - Detect
        - Config
        - Get
        - Group
        - Data
        - Quality
        - Metrics
        - Feedback
        - Sample
        - List
        - Alerts
        - Detectors
        - Related
        - Summaries
        - Time
        - Series
        - Sets
        - Arn
        - Put
        - Update
  /UpdateAnomalyDetector:
    POST:
      summary: UpdateAnomalyDetector
      description: >-
        <p>Updates a detector. After activation, you can only change a
        detector's ingestion delay and description.</p>
      tags:
        - Update
        - Anomaly
        - Detector
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
        - Describe
        - Detection
        - Executions
        - Detect
        - Config
        - Get
        - Group
        - Data
        - Quality
        - Metrics
        - Feedback
        - Sample
        - List
        - Alerts
        - Detectors
        - Related
        - Summaries
        - Time
        - Series
        - Sets
        - Arn
        - Put
        - Update
  /UpdateMetricSet:
    POST:
      summary: UpdateMetricSet
      description: <p>Updates a dataset.</
      tags:
        - Update
        - Metric
        - Set
        - Activate
        - Anomaly
        - Detector
        - Back
        - Test
        - Create
        - Alert
        - Metric
        - Set
        - Deactivate
        - Delete
        - Describe
        - Detection
        - Executions
        - Detect
        - Config
        - Get
        - Group
        - Data
        - Quality
        - Metrics
        - Feedback
        - Sample
        - List
        - Alerts
        - Detectors
        - Related
        - Summaries
        - Time
        - Series
        - Sets
        - Arn
        - Put
        - null
