openapi: 3.1.0
info:
  title: managedblockchain
paths:
  /accessors:
    GET:
      summary: ListAccessors
      description: >-
        <p>Returns a list of the accessors and their properties. Accessor
        objects are containers that have the information required for token
        based access to your Ethereum nodes.</p>
      tags:
        - List
        - Accessors
        - Accessors
  /networks/{networkId}/members:
    GET:
      summary: ListMembers
      description: >-
        <p>Returns a list of the members in a network and properties of their
        configurations.</p> <p>Applies only to Hyperledger Fabric.</p>
      tags:
        - List
        - Members
        - Accessors
        - Id
        - Members
  /networks:
    GET:
      summary: ListNetworks
      description: >-
        <p>Returns information about the networks in which the current Amazon
        Web Services account participates.</p> <p>Applies to Hyperledger Fabric
        and Ethereum.</p>
      tags:
        - List
        - Networks
        - Accessors
        - Id
        - Members
        - Networks
  /networks/{networkId}/nodes:
    GET:
      summary: ListNodes
      description: >-
        <p>Returns information about the nodes within a network.</p> <p>Applies
        to Hyperledger Fabric and Ethereum.</p>
      tags:
        - List
        - Nodes
        - Accessors
        - Id
        - Members
        - Networks
        - Nodes
  /networks/{networkId}/proposals:
    GET:
      summary: ListProposals
      description: >-
        <p>Returns a list of proposals for the network.</p> <p>Applies only to
        Hyperledger Fabric.</p>
      tags:
        - List
        - Proposals
        - Accessors
        - Id
        - Members
        - Networks
        - Nodes
        - Proposals
  /accessors/{AccessorId}:
    GET:
      summary: GetAccessor
      description: >-
        <p>Returns detailed information about an accessor. An accessor object is
        a container that has the information required for token based access to
        your Ethereum nodes.</p>
      tags:
        - Get
        - Accessor
        - Accessors
        - Id
        - Members
        - Networks
        - Nodes
        - Proposals
        - Accessor
  /networks/{networkId}/members/{memberId}:
    PATCH:
      summary: UpdateMember
      description: >-
        <p>Updates a member configuration with new parameters.</p> <p>Applies
        only to Hyperledger Fabric.</p>
      tags:
        - Update
        - Member
        - Accessors
        - Id
        - Members
        - Networks
        - Nodes
        - Proposals
        - Accessor
        - Member
  /networks/{networkId}/nodes/{nodeId}:
    PATCH:
      summary: UpdateNode
      description: >-
        <p>Updates a node configuration with new parameters.</p> <p>Applies only
        to Hyperledger Fabric.</p>
      tags:
        - Update
        - Node
        - Accessors
        - Id
        - Members
        - Networks
        - Nodes
        - Proposals
        - Accessor
        - Member
        - Node
  /networks/{networkId}:
    GET:
      summary: GetNetwork
      description: >-
        <p>Returns detailed information about a network.</p> <p>Applies to
        Hyperledger Fabric and Ethereum.</p>
      tags:
        - Get
        - Network
        - Accessors
        - Id
        - Members
        - Networks
        - Nodes
        - Proposals
        - Accessor
        - Member
        - Node
  /networks/{networkId}/proposals/{proposalId}:
    GET:
      summary: GetProposal
      description: >-
        <p>Returns detailed information about a proposal.</p> <p>Applies only to
        Hyperledger Fabric.</p>
      tags:
        - Get
        - Proposal
        - Accessors
        - Id
        - Members
        - Networks
        - Nodes
        - Proposals
        - Accessor
        - Member
        - Node
        - Proposal
  /invitations:
    GET:
      summary: ListInvitations
      description: >-
        <p>Returns a list of all invitations for the current Amazon Web Services
        account.</p> <p>Applies only to Hyperledger Fabric.</p>
      tags:
        - List
        - Invitations
        - Accessors
        - Id
        - Members
        - Networks
        - Nodes
        - Proposals
        - Accessor
        - Member
        - Node
        - Proposal
        - Invitations
  /networks/{networkId}/proposals/{proposalId}/votes:
    POST:
      summary: VoteOnProposal
      description: >-
        <p>Casts a vote for a specified <code>ProposalId</code> on behalf of a
        member. The member to vote as, specified by <code>VoterMemberId</code>,
        must be in the same Amazon Web Services account as the principal that
        calls the action.</p> <p>Applies only to Hyperledger Fabric.</p>
      tags:
        - Vote
        - 'On'
        - Proposal
        - Accessors
        - Id
        - Members
        - Networks
        - Nodes
        - Proposals
        - Accessor
        - Member
        - Node
        - Proposal
        - Invitations
        - Votes
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: >-
        <p>Removes the specified tags from the Amazon Managed Blockchain
        resource.</p> <p>For more information about tags, see <a
        href="https://docs.aws.amazon.com/managed-blockchain/latest/ethereum-dev/tagging-resources.html">Tagging
        Resources</a> in the <i>Amazon Managed Blockchain Ethereum Developer
        Guide</i>, or <a
        href="https://docs.aws.amazon.com/managed-blockchain/latest/hyperledger-fabric-dev/tagging-resources.html">Tagging
        Resources</a> in the <i>Amazon Managed Blockchain Hyperledger Fabric
        Developer Guide</i>.</p>
      tags:
        - Untag
        - Resource
        - Accessors
        - Id
        - Members
        - Networks
        - Nodes
        - Proposals
        - Accessor
        - Member
        - Node
        - Proposal
        - Invitations
        - Votes
        - Arn
  /invitations/{invitationId}:
    DELETE:
      summary: RejectInvitation
      description: >-
        <p>Rejects an invitation to join a network. This action can be called by
        a principal in an Amazon Web Services account that has received an
        invitation to create a member and join a network.</p> <p>Applies only to
        Hyperledger Fabric.</
      tags:
        - Reject
        - Invitation
        - Accessors
        - Id
        - Members
        - Networks
        - Nodes
        - Proposals
        - Accessor
        - Member
        - Node
        - Proposal
        - Invitations
        - Votes
        - Arn
