openapi: 3.1.0
info:
  title: mediapackage-vod
paths:
  /packaging_groups/{id}/configure_logs:
    PUT:
      summary: ConfigureLogs
      description: Changes the packaging group's properities to configure log subscription
      tags:
        - Configure
        - Logs
        - Packaging_groups
        - Id
        - Configure_logs
  /assets:
    GET:
      summary: ListAssets
      description: Returns a collection of MediaPackage VOD Asset resources.
      tags:
        - List
        - Assets
        - Packaging_groups
        - Id
        - Configure_logs
        - Assets
  /packaging_configurations:
    GET:
      summary: ListPackagingConfigurations
      description: >-
        Returns a collection of MediaPackage VOD PackagingConfiguration
        resources.
      tags:
        - List
        - Packaging
        - Configurations
        - Packaging_groups
        - Id
        - Configure_logs
        - Assets
        - Packaging_configurations
  /packaging_groups:
    GET:
      summary: ListPackagingGroups
      description: Returns a collection of MediaPackage VOD PackagingGroup resources.
      tags:
        - List
        - Packaging
        - Groups
        - Packaging_groups
        - Id
        - Configure_logs
        - Assets
        - Packaging_configurations
  /assets/{id}:
    GET:
      summary: DescribeAsset
      description: Returns a description of a MediaPackage VOD Asset resource.
      tags:
        - Describe
        - Asset
        - Packaging_groups
        - Id
        - Configure_logs
        - Assets
        - Packaging_configurations
  /packaging_configurations/{id}:
    GET:
      summary: DescribePackagingConfiguration
      description: >-
        Returns a description of a MediaPackage VOD PackagingConfiguration
        resource.
      tags:
        - Describe
        - Packaging
        - Configuration
        - Packaging_groups
        - Id
        - Configure_logs
        - Assets
        - Packaging_configurations
  /packaging_groups/{id}:
    PUT:
      summary: UpdatePackagingGroup
      description: >-
        Updates a specific packaging group. You can't change the id attribute or
        any other system-generated attributes.
      tags:
        - Update
        - Packaging
        - Group
        - Packaging_groups
        - Id
        - Configure_logs
        - Assets
        - Packaging_configurations
  /tags/{resource-arn}:
    DELETE:
      summary: UntagResource
      description: >-
        Removes tags from the specified resource. You can specify one or more
        tags 
      tags:
        - Untag
        - Resource
        - Packaging_groups
        - Id
        - Configure_logs
        - Assets
        - Packaging_configurations
        - Tags
        - Resource
        - A
