openapi: 3.1.0
info:
  title: medical-imaging
paths:
  /datastore/{datastoreId}/imageSet/{sourceImageSetId}/copyImageSet:
    POST:
      summary: CopyImageSet
      description: <p>Copy an image set.</p>
      tags:
        - Copy
        - Image
        - Set
        - Id
        - Image
        - Set
        - Source
        - Copy
  /datastore:
    GET:
      summary: ListDatastores
      description: <p>List data stores.</p>
      tags:
        - List
        - Datastores
        - Id
        - Image
        - Set
        - Source
        - Copy
        - Datastore
  /datastore/{datastoreId}:
    GET:
      summary: GetDatastore
      description: <p>Get data store properties.</p>
      tags:
        - Get
        - Datastore
        - Id
        - Image
        - Set
        - Source
        - Copy
        - Datastore
  /datastore/{datastoreId}/imageSet/{imageSetId}/deleteImageSet:
    POST:
      summary: DeleteImageSet
      description: <p>Delete an image set.</p>
      tags:
        - Delete
        - Image
        - Set
        - Id
        - Image
        - Set
        - Source
        - Copy
        - Datastore
        - Delete
  /getDICOMImportJob/datastore/{datastoreId}/job/{jobId}:
    GET:
      summary: GetDICOMImportJob
      description: >-
        <p>Get the import job properties to learn more about the job or job
        progress.</p>
      tags:
        - Get
        - Import
        - Job
        - Id
        - Image
        - Set
        - Source
        - Copy
        - Datastore
        - Delete
        - Import
        - Job
  /datastore/{datastoreId}/imageSet/{imageSetId}/getImageFrame:
    POST:
      summary: GetImageFrame
      description: <p>Get an image frame (pixel data) for an image set.</p>
      tags:
        - Get
        - Image
        - Frame
        - Id
        - Image
        - Set
        - Source
        - Copy
        - Datastore
        - Delete
        - Import
        - Job
        - Get
        - Frame
  /datastore/{datastoreId}/imageSet/{imageSetId}/getImageSet:
    POST:
      summary: GetImageSet
      description: <p>Get image set properties.</p>
      tags:
        - Get
        - Image
        - Set
        - Id
        - Image
        - Set
        - Source
        - Copy
        - Datastore
        - Delete
        - Import
        - Job
        - Get
        - Frame
  /datastore/{datastoreId}/imageSet/{imageSetId}/getImageSetMetadata:
    POST:
      summary: GetImageSetMetadata
      description: <p>Get metadata attributes for an image set.</p>
      tags:
        - Get
        - Image
        - Set
        - Metadata
        - Id
        - Image
        - Set
        - Source
        - Copy
        - Datastore
        - Delete
        - Import
        - Job
        - Get
        - Frame
        - Metadata
  /listDICOMImportJobs/datastore/{datastoreId}:
    GET:
      summary: ListDICOMImportJobs
      description: <p>List import jobs created for a specific data store.</p>
      tags:
        - List
        - Import
        - Jobs
        - Id
        - Image
        - Set
        - Source
        - Copy
        - Datastore
        - Delete
        - Import
        - Job
        - Get
        - Frame
        - Metadata
        - Jobs
  /datastore/{datastoreId}/imageSet/{imageSetId}/listImageSetVersions:
    POST:
      summary: ListImageSetVersions
      description: <p>List image set versions.</p>
      tags:
        - List
        - Image
        - Set
        - Versions
        - Id
        - Image
        - Set
        - Source
        - Copy
        - Datastore
        - Delete
        - Import
        - Job
        - Get
        - Frame
        - Metadata
        - Jobs
        - List
        - Versions
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Removes tags from a medical imaging resource.</p>
      tags:
        - Untag
        - Resource
        - Id
        - Image
        - Set
        - Source
        - Copy
        - Datastore
        - Delete
        - Import
        - Job
        - Get
        - Frame
        - Metadata
        - Jobs
        - List
        - Versions
        - Arn
  /datastore/{datastoreId}/searchImageSets:
    POST:
      summary: SearchImageSets
      description: >-
        <p>Search image sets based on defined input attributes.</p> <note> <p>
        <code>SearchImageSets</code> accepts a single search query parameter and
        returns a paginated response of all image sets that have the matching
        criteria. All range queries must be input as <code>(lowerBound,
        upperBound)</code>.</p> <p> <code>SearchImageSets</code> uses the
        <code>updatedAt</code> field for sorting in decreasing order from latest
        to oldest.</p> </note>
      tags:
        - Search
        - Image
        - Sets
        - Id
        - Image
        - Set
        - Source
        - Copy
        - Datastore
        - Delete
        - Import
        - Job
        - Get
        - Frame
        - Metadata
        - Jobs
        - List
        - Versions
        - Arn
        - Search
        - Sets
  /startDICOMImportJob/datastore/{datastoreId}:
    POST:
      summary: StartDICOMImportJob
      description: >-
        <p>Start importing bulk data into an <code>ACTIVE</code> data store. The
        import job imports DICOM P10 files found in the S3 prefix specified by
        the <code>inputS3Uri</code> parameter. The import job stores processing
        results in the file specified by the <code>outputS3Uri</code>
        parameter.</p>
      tags:
        - Start
        - Import
        - Job
        - Id
        - Image
        - Set
        - Source
        - Copy
        - Datastore
        - Delete
        - Import
        - Job
        - Get
        - Frame
        - Metadata
        - Jobs
        - List
        - Versions
        - Arn
        - Search
        - Sets
  /datastore/{datastoreId}/imageSet/{imageSetId}/updateImageSetMetadata:
    POST:
      summary: UpdateImageSetMetadata
      description: <p>Update image set metadata attri
      tags:
        - Update
        - Image
        - Set
        - Metadata
        - Id
        - Image
        - Set
        - Source
        - Copy
        - Datastore
        - Delete
        - Import
        - Job
        - Get
        - Frame
        - Metadata
        - Jobs
        - List
        - Versions
        - Arn
        - Search
        - Sets
        - Upda
