openapi: 3.1.0
info:
  title: mediastore
paths:
  /:
    POST:
      summary: UntagResource
      description: >-
        <p>Removes tags from the specified container. You can specify one or
        more tags to remove. </
      tags:
        - Untag
        - Resource
