openapi: 3.1.0
info:
  title: mediastore-data
paths:
  /{Path+}:
    PUT:
      summary: PutObject
      description: >-
        <p>Uploads an object to the specified path. Object sizes are limited to
        25 MB for standard upload availability and 10 MB for streaming upload
        availability.</p>
      tags:
        - Put
        - Object
        - Path+
  /:
    GET:
      summary: ListItems
      description: >-
        <p>Provides a list of metadata entries about folders and objects in the
        specified folder.</
      tags:
        - List
        - Items
        - Path+
