openapi: 3.1.0
info:
  title: mediapackage
paths:
  /channels/{id}/configure_logs:
    PUT:
      summary: ConfigureLogs
      description: Changes the Channel's properities to configure log subscription
      tags:
        - Configure
        - Logs
        - Channels
        - Id
        - Configure_logs
  /channels:
    GET:
      summary: ListChannels
      description: Returns a collection of Channels.
      tags:
        - List
        - Channels
        - Channels
        - Id
        - Configure_logs
  /harvest_jobs:
    GET:
      summary: ListHarvestJobs
      description: Returns a collection of HarvestJob records.
      tags:
        - List
        - Harvest
        - Jobs
        - Channels
        - Id
        - Configure_logs
        - Harvest_jobs
  /origin_endpoints:
    GET:
      summary: ListOriginEndpoints
      description: Returns a collection of OriginEndpoint records.
      tags:
        - List
        - Origin
        - Endpoints
        - Channels
        - Id
        - Configure_logs
        - Harvest_jobs
        - Origin_endpoints
  /channels/{id}:
    PUT:
      summary: UpdateChannel
      description: Updates an existing Channel.
      tags:
        - Update
        - Channel
        - Channels
        - Id
        - Configure_logs
        - Harvest_jobs
        - Origin_endpoints
  /origin_endpoints/{id}:
    PUT:
      summary: UpdateOriginEndpoint
      description: Updates an existing OriginEndpoint.
      tags:
        - Update
        - Origin
        - Endpoint
        - Channels
        - Id
        - Configure_logs
        - Harvest_jobs
        - Origin_endpoints
  /harvest_jobs/{id}:
    GET:
      summary: DescribeHarvestJob
      description: Gets details about an existing HarvestJob.
      tags:
        - Describe
        - Harvest
        - Job
        - Channels
        - Id
        - Configure_logs
        - Harvest_jobs
        - Origin_endpoints
  /tags/{resource-arn}:
    DELETE:
      summary: UntagResource
      description: null
      tags:
        - Untag
        - Resource
        - Channels
        - Id
        - Configure_logs
        - Harvest_jobs
        - Origin_endpoints
        - Tags
        - Resource
        - Arn
  /channels/{id}/credentials:
    PUT:
      summary: RotateChannelCredentials
      description: >-
        Changes the Channel's first IngestEndpoint's username and password.
        WARNING - This API is deprecated. Please use
        RotateIngestEndpointCredentials instead
      tags:
        - Rotate
        - Channel
        - Credentials
        - Channels
        - Id
        - Configure_logs
        - Harvest_jobs
        - Origin_endpoints
        - Tags
        - Resource
        - Arn
        - Credentials
  /channels/{id}/ingest_endpoints/{ingest_endpoint_id}/credentials:
    PUT:
      summary: RotateIngestEndpointCredentials
      description: >-
        Rotate the IngestEndpoint's username and password, as specified by the
        IngestEndpoint's i
      tags:
        - Rotate
        - Ingest
        - Endpoint
        - Credentials
        - Channels
        - Id
        - Configure_logs
        - Harvest_jobs
        - Origin_endpoints
        - Tags
        - Resource
        - Arn
        - Credentials
        - Ingest_endpoints
        - Ingest_endpoint_id
