openapi: 3.1.0
info:
  title: mediapackagev2
paths:
  /channelGroup/{ChannelGroupName}/channel:
    GET:
      summary: ListChannels
      description: >-
        <p>Retrieves all channels in a specific channel group that are
        configured in AWS Elemental MediaPackage, including the origin endpoints
        that are associated with it.</p>
      tags:
        - List
        - Channels
        - Group
        - Channel
        - Name
  /channelGroup:
    GET:
      summary: ListChannelGroups
      description: >-
        <p>Retrieves all channel groups that are configured in AWS Elemental
        MediaPackage, including the channels and origin endpoints that are
        associated with it.</p>
      tags:
        - List
        - Channel
        - Groups
        - Group
        - Channel
        - Name
  /channelGroup/{ChannelGroupName}/channel/{ChannelName}/originEndpoint:
    GET:
      summary: ListOriginEndpoints
      description: >-
        <p>Retrieves all origin endpoints in a specific channel that are
        configured in AWS Elemental MediaPackage.</p>
      tags:
        - List
        - Origin
        - Endpoints
        - Group
        - Channel
        - Name
        - Origin
        - Endpoint
  /channelGroup/{ChannelGroupName}/channel/{ChannelName}/:
    PUT:
      summary: UpdateChannel
      description: >-
        <p>Update the specified channel. You can edit if MediaPackage sends
        ingest or egress access logs to the CloudWatch log group, if content
        will be encrypted, the description on a channel, and your channel's
        policy settings. You can't edit the name of the channel or CloudFront
        distribution details.</p> <p>Any edits you make that impact the video
        output may not be reflected for a few minutes.</p>
      tags:
        - Update
        - Channel
        - Group
        - Channel
        - Name
        - Origin
        - Endpoint
  /channelGroup/{ChannelGroupName}:
    PUT:
      summary: UpdateChannelGroup
      description: >-
        <p>Update the specified channel group. You can edit the description on a
        channel group for easier identification later from the AWS Elemental
        MediaPackage console. You can't edit the name of the channel group.</p>
        <p>Any edits you make that impact the video output may not be reflected
        for a few minutes.</p>
      tags:
        - Update
        - Channel
        - Group
        - Group
        - Channel
        - Name
        - Origin
        - Endpoint
  /channelGroup/{ChannelGroupName}/channel/{ChannelName}/policy:
    PUT:
      summary: PutChannelPolicy
      description: >-
        <p>Attaches an IAM policy to the specified channel. With policies, you
        can specify who has access to AWS resources and what actions they can
        perform on those resources. You can attach only one policy with each
        request.</p>
      tags:
        - Put
        - Channel
        - Policy
        - Group
        - Channel
        - Name
        - Origin
        - Endpoint
        - Policy
  /channelGroup/{ChannelGroupName}/channel/{ChannelName}/originEndpoint/{OriginEndpointName}:
    PUT:
      summary: UpdateOriginEndpoint
      description: >-
        <p>Update the specified origin endpoint. Edit the packaging preferences
        on an endpoint to optimize the viewing experience. You can't edit the
        name of the endpoint.</p> <p>Any edits you make that impact the video
        output may not be reflected for a few minutes.</p>
      tags:
        - Update
        - Origin
        - Endpoint
        - Group
        - Channel
        - Name
        - Origin
        - Endpoint
        - Policy
  /channelGroup/{ChannelGroupName}/channel/{ChannelName}/originEndpoint/{OriginEndpointName}/policy:
    POST:
      summary: PutOriginEndpointPolicy
      description: >-
        <p>Attaches an IAM policy to the specified origin endpoint. You can
        attach only one policy with each request.</p>
      tags:
        - Put
        - Origin
        - Endpoint
        - Policy
        - Group
        - Channel
        - Name
        - Origin
        - Endpoint
        - Policy
  /tags/{ResourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Removes one or more tags from the specified resource.</
      tags:
        - Untag
        - Resource
        - Group
        - Channel
        - Name
        - Origin
        - Endpoint
        - Policy
        - Resource
        - Arn
