openapi: 3.1.0
info:
  title: memorydb
paths:
  /:
    POST:
      summary: UpdateUser
      description: <p>Changes user password(s) and/or access string.</
      tags:
        - Update
        - User
