openapi: 3.1.0
info:
  title: mobile
paths:
  /projects:
    GET:
      summary: ListProjects
      description: <p> Lists projects in AWS Mobile Hub. </p>
      tags:
        - List
        - Projects
        - Projects
  /projects/{projectId}:
    DELETE:
      summary: DeleteProject
      description: <p> Delets a project in AWS Mobile Hub. </p>
      tags:
        - Delete
        - Project
        - Projects
        - Id
  /bundles/{bundleId}:
    POST:
      summary: ExportBundle
      description: >-
        <p> Generates customized software development kit (SDK) and or tool
        packages used to integrate mobile web or mobile app clients with backend
        AWS resources. </p>
      tags:
        - Export
        - Bundle
        - Projects
        - Id
  /project:
    GET:
      summary: DescribeProject
      description: <p> Gets details about a project in AWS Mobile Hub. </p>
      tags:
        - Describe
        - Project
        - Projects
        - Id
        - Project
  /exports/{projectId}:
    POST:
      summary: ExportProject
      description: >-
        <p> Exports project configuration to a snapshot which can be downloaded
        and shared. Note that mobile app push credentials are encrypted in
        exported projects, so they can only be shared successfully within the
        same AWS account. </p>
      tags:
        - Export
        - Project
        - Projects
        - Id
        - Project
  /bundles:
    GET:
      summary: ListBundles
      description: <p> List all available bundles. </p>
      tags:
        - List
        - Bundles
        - Projects
        - Id
        - Project
        - Bundles
  /update:
    POST:
      summary: UpdateProject
      description: <p> Update an existing project. </
      tags:
        - Update
        - Project
        - Projects
        - Id
        - Project
        - Bundles
        - Update
