openapi: 3.1.0
info:
  title: mq
paths:
  /v1/brokers:
    GET:
      summary: ListBrokers
      description: <p>Returns a list of all brokers.</p>
      tags:
        - List
        - Brokers
        - V1
        - Brokers
  /v1/configurations:
    GET:
      summary: ListConfigurations
      description: <p>Returns a list of all configurations.</p>
      tags:
        - List
        - Configurations
        - V1
        - Brokers
        - Configurations
  /v1/tags/{resource-arn}:
    GET:
      summary: ListTags
      description: <p>Lists tags for a resource.</p>
      tags:
        - List
        - Tags
        - V1
        - Brokers
        - Configurations
        - Tags
        - Resource
        - Arn
  /v1/brokers/{broker-id}/users/{username}:
    PUT:
      summary: UpdateUser
      description: <p>Updates the information for an ActiveMQ user.</p>
      tags:
        - Update
        - User
        - V1
        - Brokers
        - Configurations
        - Tags
        - Resource
        - Arn
        - Broker
        - Id
        - Users
        - Username
  /v1/brokers/{broker-id}:
    PUT:
      summary: UpdateBroker
      description: <p>Adds a pending configuration change to a broker.</p>
      tags:
        - Update
        - Broker
        - V1
        - Brokers
        - Configurations
        - Tags
        - Resource
        - Arn
        - Broker
        - Id
        - Users
        - Username
  /v1/broker-engine-types:
    GET:
      summary: DescribeBrokerEngineTypes
      description: <p>Describe available engine types and versions.</p>
      tags:
        - Describe
        - Broker
        - Engine
        - Types
        - V1
        - Brokers
        - Configurations
        - Tags
        - Resource
        - Arn
        - Broker
        - Id
        - Users
        - Username
        - Engine
        - Types
  /v1/broker-instance-options:
    GET:
      summary: DescribeBrokerInstanceOptions
      description: <p>Describe available broker instance options.</p>
      tags:
        - Describe
        - Broker
        - Instance
        - Options
        - V1
        - Brokers
        - Configurations
        - Tags
        - Resource
        - Arn
        - Broker
        - Id
        - Users
        - Username
        - Engine
        - Types
        - Instance
        - Options
  /v1/configurations/{configuration-id}:
    PUT:
      summary: UpdateConfiguration
      description: <p>Updates the specified configuration.</p>
      tags:
        - Update
        - Configuration
        - V1
        - Brokers
        - Configurations
        - Tags
        - Resource
        - Arn
        - Broker
        - Id
        - Users
        - Username
        - Engine
        - Types
        - Instance
        - Options
        - Configuration
  /v1/configurations/{configuration-id}/revisions/{configuration-revision}:
    GET:
      summary: DescribeConfigurationRevision
      description: >-
        <p>Returns the specified configuration revision for the specified
        configuration.</p>
      tags:
        - Describe
        - Configuration
        - Revision
        - V1
        - Brokers
        - Configurations
        - Tags
        - Resource
        - Arn
        - Broker
        - Id
        - Users
        - Username
        - Engine
        - Types
        - Instance
        - Options
        - Configuration
        - Revisions
        - Revision
  /v1/configurations/{configuration-id}/revisions:
    GET:
      summary: ListConfigurationRevisions
      description: <p>Returns a list of all revisions for the specified configuration.</p>
      tags:
        - List
        - Configuration
        - Revisions
        - V1
        - Brokers
        - Configurations
        - Tags
        - Resource
        - Arn
        - Broker
        - Id
        - Users
        - Username
        - Engine
        - Types
        - Instance
        - Options
        - Configuration
        - Revisions
        - Revision
  /v1/brokers/{broker-id}/users:
    GET:
      summary: ListUsers
      description: <p>Returns a list of all ActiveMQ users.</p>
      tags:
        - List
        - Users
        - V1
        - Brokers
        - Configurations
        - Tags
        - Resource
        - Arn
        - Broker
        - Id
        - Users
        - Username
        - Engine
        - Types
        - Instance
        - Options
        - Configuration
        - Revisions
        - Revision
  /v1/brokers/{broker-id}/promote:
    POST:
      summary: Promote
      description: >-
        <p>Promotes a data replication replica broker to the primary broker
        role.</p>
      tags:
        - Promote
        - V1
        - Brokers
        - Configurations
        - Tags
        - Resource
        - Arn
        - Broker
        - Id
        - Users
        - Username
        - Engine
        - Types
        - Instance
        - Options
        - Configuration
        - Revisions
        - Revision
        - Promote
  /v1/brokers/{broker-id}/reboot:
    POST:
      summary: RebootBroker
      description: Reboots a brok
      tags:
        - Reboot
        - Broker
        - V1
        - Brokers
        - Configurations
        - Tags
        - Resource
        - Arn
        - Broker
        - Id
        - Users
        - Username
        - Engine
        - Types
        - Instance
        - Options
        - Configuration
        - Revisions
        - Revision
        - Promote
        - null
