openapi: 3.1.0
info:
  title: neptune-graph
paths:
  /importtasks/{taskIdentifier}:
    GET:
      summary: GetImportTask
      description: <p>Retrieves a specified import task.</p>
      tags:
        - Get
        - Import
        - Task
        - Identifier
  /queries/{queryId}:
    GET:
      summary: GetQuery
      description: >-
        <p>Retrieves the status of a specified query.</p> <note> <p> When
        invoking this operation in a Neptune Analytics cluster, the IAM user or
        role making the request must have the
        <code>neptune-graph:GetQueryStatus</code> IAM action attached. </p>
        </note>
      tags:
        - Get
        - Query
        - Identifier
        - Id
  /graphs:
    GET:
      summary: ListGraphs
      description: <p>Lists available Neptune Analytics graphs.</p>
      tags:
        - List
        - Graphs
        - Identifier
        - Id
        - Graphs
  /snapshots:
    GET:
      summary: ListGraphSnapshots
      description: <p>Lists available snapshots of a specified Neptune Analytics graph.</p>
      tags:
        - List
        - Graph
        - Snapshots
        - Identifier
        - Id
        - Graphs
        - Snapshots
  /importtasks:
    GET:
      summary: ListImportTasks
      description: <p>Lists import tasks.</p>
      tags:
        - List
        - Import
        - Tasks
        - Identifier
        - Id
        - Graphs
        - Snapshots
        - Importtasks
  /graphs/{graphIdentifier}/endpoints/:
    GET:
      summary: ListPrivateGraphEndpoints
      description: <p>Lists private endpoints for a specified Neptune Analytics graph.</p>
      tags:
        - List
        - Private
        - Graph
        - Endpoints
        - Identifier
        - Id
        - Graphs
        - Snapshots
        - Importtasks
        - Endpoints
  /graphs/{graphIdentifier}:
    PATCH:
      summary: UpdateGraph
      description: <p>Updates the configuration of a specified Neptune Analytics graph</p>
      tags:
        - Update
        - Graph
        - Identifier
        - Id
        - Graphs
        - Snapshots
        - Importtasks
        - Endpoints
  /snapshots/{snapshotIdentifier}:
    GET:
      summary: GetGraphSnapshot
      description: <p>Retrieves a specified graph snapshot.</p>
      tags:
        - Get
        - Graph
        - Snapshot
        - Identifier
        - Id
        - Graphs
        - Snapshots
        - Importtasks
        - Endpoints
  /graphs/{graphIdentifier}/endpoints/{vpcId}:
    GET:
      summary: GetPrivateGraphEndpoint
      description: <p>Retrieves information about a specified private endpoint.</p>
      tags:
        - Get
        - Private
        - Graph
        - Endpoint
        - Identifier
        - Id
        - Graphs
        - Snapshots
        - Importtasks
        - Endpoints
        - Vpc
  /queries:
    GET:
      summary: ListQueries
      description: <p>Lists active openCypher queries.</p>
      tags:
        - List
        - Queries
        - Identifier
        - Id
        - Graphs
        - Snapshots
        - Importtasks
        - Endpoints
        - Vpc
        - Queries
  /summary:
    GET:
      summary: GetGraphSummary
      description: <p>Gets a graph summary for a property graph.</p>
      tags:
        - Get
        - Graph
        - Summary
        - Identifier
        - Id
        - Graphs
        - Snapshots
        - Importtasks
        - Endpoints
        - Vpc
        - Queries
        - Summary
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Removes the specified tags from the specified resource.</p>
      tags:
        - Untag
        - Resource
        - Identifier
        - Id
        - Graphs
        - Snapshots
        - Importtasks
        - Endpoints
        - Vpc
        - Queries
        - Summary
        - Arn
  /snapshots/{snapshotIdentifier}/restore:
    POST:
      summary: RestoreGraphFromSnapshot
      description: <p>Restores a graph from a snapshot.</
      tags:
        - Restore
        - Graph
        - From
        - Snapshot
        - Identifier
        - Id
        - Graphs
        - Snapshots
        - Importtasks
        - Endpoints
        - Vpc
        - Queries
        - Summary
        - Arn
        - R
