openapi: 3.1.0
info:
  title: networkmonitor
paths:
  /monitors:
    GET:
      summary: ListMonitors
      description: <p>Returns a list of all of your monitors.</p>
      tags:
        - List
        - Monitors
        - Monitors
  /monitors/{monitorName}/probes:
    POST:
      summary: CreateProbe
      description: >-
        <p>Create a probe within a monitor. Once you create a probe, and it
        begins monitoring your network traffic, you'll incur billing charges for
        that probe. </p>
      tags:
        - Create
        - Probe
        - Monitors
        - Name
        - Probes
  /monitors/{monitorName}:
    PATCH:
      summary: UpdateMonitor
      description: >-
        <p>Updates the <code>aggregationPeriod</code> for a monitor. Monitors
        support an <code>aggregationPeriod</code> of either <code>30</code> or
        <code>60</code> seconds.</p>
      tags:
        - Update
        - Monitor
        - Monitors
        - Name
        - Probes
  /monitors/{monitorName}/probes/{probeId}:
    PATCH:
      summary: UpdateProbe
      description: >-
        <p>Updates a monitor probe. This action requires both the
        <code>monitorName</code> and <code>probeId</code> parameters. Run
        <code>ListMonitors</code> to get a list of monitor names. Run
        <code>GetMonitor</code> to get a list of probes and probe IDs. </p>
      tags:
        - Update
        - Probe
        - Monitors
        - Name
        - Probes
        - Probe
        - Id
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Removes a key-value pair from a monitor or probe.</
      tags:
        - Untag
        - Resource
        - Monitors
        - Name
        - Probes
        - Probe
        - Id
        - Arn
