openapi: 3.1.0
info:
  title: osis
paths:
  /2022-01-01/osis/createPipeline:
    POST:
      summary: CreatePipeline
      description: >-
        <p>Creates an OpenSearch Ingestion pipeline. For more information, see
        <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/creating-pipeline.html">Creating
        Amazon OpenSearch Ingestion pipelines</a>.</p>
      tags:
        - Create
        - Pipeline
        - Pipeline
  /2022-01-01/osis/deletePipeline/{PipelineName}:
    DELETE:
      summary: DeletePipeline
      description: >-
        <p>Deletes an OpenSearch Ingestion pipeline. For more information, see
        <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/delete-pipeline.html">Deleting
        Amazon OpenSearch Ingestion pipelines</a>.</p>
      tags:
        - Delete
        - Pipeline
        - Pipeline
        - Name
  /2022-01-01/osis/getPipeline/{PipelineName}:
    GET:
      summary: GetPipeline
      description: <p>Retrieves information about an OpenSearch Ingestion pipeline.</p>
      tags:
        - Get
        - Pipeline
        - Pipeline
        - Name
  /2022-01-01/osis/getPipelineBlueprint/{BlueprintName}:
    GET:
      summary: GetPipelineBlueprint
      description: >-
        <p>Retrieves information about a specific blueprint for OpenSearch
        Ingestion. Blueprints are templates for the configuration needed for a
        <code>CreatePipeline</code> request. For more information, see <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/creating-pipeline.html#pipeline-blueprint">Using
        blueprints to create a pipeline</a>.</p>
      tags:
        - Get
        - Pipeline
        - Blueprint
        - Pipeline
        - Name
        - Blueprint
  /2022-01-01/osis/getPipelineChangeProgress/{PipelineName}:
    GET:
      summary: GetPipelineChangeProgress
      description: >-
        <p>Returns progress information for the current change happening on an
        OpenSearch Ingestion pipeline. Currently, this operation only returns
        information when a pipeline is being created.</p> <p>For more
        information, see <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/creating-pipeline.html#get-pipeline-progress">Tracking
        the status of pipeline creation</a>.</p>
      tags:
        - Get
        - Pipeline
        - Change
        - Progress
        - Pipeline
        - Name
        - Blueprint
        - Change
        - Progress
  /2022-01-01/osis/listPipelineBlueprints:
    POST:
      summary: ListPipelineBlueprints
      description: >-
        <p>Retrieves a list of all available blueprints for Data Prepper. For
        more information, see <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/creating-pipeline.html#pipeline-blueprint">Using
        blueprints to create a pipeline</a>.</p>
      tags:
        - List
        - Pipeline
        - Blueprints
        - Pipeline
        - Name
        - Blueprint
        - Change
        - Progress
        - Blueprints
  /2022-01-01/osis/listPipelines:
    GET:
      summary: ListPipelines
      description: >-
        <p>Lists all OpenSearch Ingestion pipelines in the current Amazon Web
        Services account and Region. For more information, see <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/list-pipeline.html">Viewing
        Amazon OpenSearch Ingestion pipelines</a>.</p>
      tags:
        - List
        - Pipelines
        - Pipeline
        - Name
        - Blueprint
        - Change
        - Progress
        - Blueprints
        - Pipelines
  /2022-01-01/osis/listTagsForResource/:
    GET:
      summary: ListTagsForResource
      description: >-
        <p>Lists all resource tags associated with an OpenSearch Ingestion
        pipeline. For more information, see <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/tag-pipeline.html">Tagging
        Amazon OpenSearch Ingestion pipelines</a>.</p>
      tags:
        - List
        - Tags
        - For
        - Resource
        - Pipeline
        - Name
        - Blueprint
        - Change
        - Progress
        - Blueprints
        - Pipelines
        - Tags
        - For
        - Resource
  /2022-01-01/osis/startPipeline/{PipelineName}:
    PUT:
      summary: StartPipeline
      description: >-
        <p>Starts an OpenSearch Ingestion pipeline. For more information, see <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/pipeline--stop-start.html#pipeline--start">Starting
        an OpenSearch Ingestion pipeline</a>.</p>
      tags:
        - Start
        - Pipeline
        - Pipeline
        - Name
        - Blueprint
        - Change
        - Progress
        - Blueprints
        - Pipelines
        - Tags
        - For
        - Resource
  /2022-01-01/osis/stopPipeline/{PipelineName}:
    PUT:
      summary: StopPipeline
      description: >-
        <p>Stops an OpenSearch Ingestion pipeline. For more information, see <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/pipeline--stop-start.html#pipeline--stop">Stopping
        an OpenSearch Ingestion pipeline</a>.</p>
      tags:
        - Stop
        - Pipeline
        - Pipeline
        - Name
        - Blueprint
        - Change
        - Progress
        - Blueprints
        - Pipelines
        - Tags
        - For
        - Resource
  /2022-01-01/osis/tagResource/:
    POST:
      summary: TagResource
      description: >-
        <p>Tags an OpenSearch Ingestion pipeline. For more information, see <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/tag-pipeline.html">Tagging
        Amazon OpenSearch Ingestion pipelines</a>.</p>
      tags:
        - Tag
        - Resource
        - Pipeline
        - Name
        - Blueprint
        - Change
        - Progress
        - Blueprints
        - Pipelines
        - Tags
        - For
        - Resource
  /2022-01-01/osis/untagResource/:
    POST:
      summary: UntagResource
      description: >-
        <p>Removes one or more tags from an OpenSearch Ingestion pipeline. For
        more information, see <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/tag-pipeline.html">Tagging
        Amazon OpenSearch Ingestion pipelines</a>.</p>
      tags:
        - Untag
        - Resource
        - Pipeline
        - Name
        - Blueprint
        - Change
        - Progress
        - Blueprints
        - Pipelines
        - Tags
        - For
        - Resource
  /2022-01-01/osis/updatePipeline/{PipelineName}:
    PUT:
      summary: UpdatePipeline
      description: >-
        <p>Updates an OpenSearch Ingestion pipeline. For more information, see
        <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/update-pipeline.html">Updating
        Amazon OpenSearch Ingestion pipelines</a>.</p>
      tags:
        - Update
        - Pipeline
        - Pipeline
        - Name
        - Blueprint
        - Change
        - Progress
        - Blueprints
        - Pipelines
        - Tags
        - For
        - Resource
  /2022-01-01/osis/validatePipeline:
    POST:
      summary: ValidatePipeline
      description: >-
        <p>Checks whether an OpenSearch Ingestion pipeline configuration is
        valid prior to creation. For more information, see <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/creating-pipeline.html">Creating
        Amazon OpenSearch Ingestion pipelines</a>.</
      tags:
        - Validate
        - Pipeline
        - Pipeline
        - Name
        - Blueprint
        - Change
        - Progress
        - Blueprints
        - Pipelines
        - Tags
        - For
        - Re
