openapi: 3.1.0
info:
  title: redshift
paths:
  /:
    POST:
      summary: UpdatePartnerStatus
      description: <p>Updates the status of a partner integration.</
      tags:
        - Update
        - Partner
        - Status
