openapi: 3.1.0
info:
  title: repostspace
paths:
  /spaces:
    GET:
      summary: ListSpaces
      description: >-
        <p>Returns a list of AWS re:Post Private private re:Posts in the account
        with some information about each private re:Post.</p>
      tags:
        - List
        - Spaces
        - Spaces
  /spaces/{spaceId}:
    PUT:
      summary: UpdateSpace
      description: <p>Modifies an existing AWS re:Post Private private re:Post.</p>
      tags:
        - Update
        - Space
        - Spaces
        - Id
  /spaces/{spaceId}/admins/{adminId}:
    POST:
      summary: RegisterAdmin
      description: >-
        <p>Adds a user or group to the list of administrators of the private
        re:Post.</p>
      tags:
        - Register
        - Admin
        - Spaces
        - Id
        - Admins
        - Admin
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: >-
        <p>Removes the association of the tag with the AWS re:Post Private
        resource.</p>
      tags:
        - Untag
        - Resource
        - Spaces
        - Id
        - Admins
        - Admin
        - Arn
  /spaces/{spaceId}/invite:
    POST:
      summary: SendInvites
      description: <p>Sends an invitation email to selected users and groups.</
      tags:
        - Send
        - Invites
        - Spaces
        - Id
        - Admins
        - Admin
        - Arn
        - null
