openapi: 3.1.0
info:
  title: rolesanywhere
paths:
  /profiles:
    GET:
      summary: ListProfiles
      description: >-
        <p>Lists all profiles in the authenticated account and Amazon Web
        Services Region.</p> <p> <b>Required permissions: </b>
        <code>rolesanywhere:ListProfiles</code>. </p>
  /trustanchors:
    GET:
      summary: ListTrustAnchors
      description: >-
        <p>Lists the trust anchors in the authenticated account and Amazon Web
        Services Region.</p> <p> <b>Required permissions: </b>
        <code>rolesanywhere:ListTrustAnchors</code>. </p>
  /crl/{crlId}:
    PATCH:
      summary: UpdateCrl
      description: >-
        <p>Updates the certificate revocation list (CRL). A CRL is a list of
        certificates that have been revoked by the issuing certificate authority
        (CA). IAM Roles Anywhere validates against the CRL before issuing
        credentials.</p> <p> <b>Required permissions: </b>
        <code>rolesanywhere:UpdateCrl</code>. </p>
  /profile/{profileId}:
    PATCH:
      summary: UpdateProfile
      description: >-
        <p>Updates a <i>profile</i>, a list of the roles that IAM Roles Anywhere
        service is trusted to assume. You use profiles to intersect permissions
        with IAM managed policies.</p> <p> <b>Required permissions: </b>
        <code>rolesanywhere:UpdateProfile</code>. </p>
  /trustanchor/{trustAnchorId}:
    PATCH:
      summary: UpdateTrustAnchor
      description: >-
        <p>Updates a trust anchor. You establish trust between IAM Roles
        Anywhere and your certificate authority (CA) by configuring a trust
        anchor. You can define a trust anchor as a reference to an Private
        Certificate Authority (Private CA) or by uploading a CA certificate.
        Your Amazon Web Services workloads can authenticate with the trust
        anchor using certificates issued by the CA in exchange for temporary
        Amazon Web Services credentials.</p> <p> <b>Required permissions: </b>
        <code>rolesanywhere:UpdateTrustAnchor</code>. </p>
  /crl/{crlId}/disable:
    POST:
      summary: DisableCrl
      description: >-
        <p>Disables a certificate revocation list (CRL).</p> <p> <b>Required
        permissions: </b> <code>rolesanywhere:DisableCrl</code>. </p>
  /profile/{profileId}/disable:
    POST:
      summary: DisableProfile
      description: >-
        <p>Disables a profile. When disabled, temporary credential requests with
        this profile fail.</p> <p> <b>Required permissions: </b>
        <code>rolesanywhere:DisableProfile</code>. </p>
  /trustanchor/{trustAnchorId}/disable:
    POST:
      summary: DisableTrustAnchor
      description: >-
        <p>Disables a trust anchor. When disabled, temporary credential requests
        specifying this trust anchor are unauthorized.</p> <p> <b>Required
        permissions: </b> <code>rolesanywhere:DisableTrustAnchor</code>. </p>
  /crl/{crlId}/enable:
    POST:
      summary: EnableCrl
      description: >-
        <p>Enables a certificate revocation list (CRL). When enabled,
        certificates stored in the CRL are unauthorized to receive session
        credentials.</p> <p> <b>Required permissions: </b>
        <code>rolesanywhere:EnableCrl</code>. </p>
  /profile/{profileId}/enable:
    POST:
      summary: EnableProfile
      description: >-
        <p>Enables temporary credential requests for a profile. </p> <p>
        <b>Required permissions: </b> <code>rolesanywhere:EnableProfile</code>.
        </p>
  /trustanchor/{trustAnchorId}/enable:
    POST:
      summary: EnableTrustAnchor
      description: >-
        <p>Enables a trust anchor. When enabled, certificates in the trust
        anchor chain are authorized for trust validation. </p> <p> <b>Required
        permissions: </b> <code>rolesanywhere:EnableTrustAnchor</code>. </p>
  /subject/{subjectId}:
    GET:
      summary: GetSubject
      description: >-
        <p>Gets a <i>subject</i>, which associates a certificate identity with
        authentication attempts. The subject stores auditing information such as
        the status of the last authentication attempt, the certificate data used
        in the attempt, and the last time the associated identity attempted
        authentication. </p> <p> <b>Required permissions: </b>
        <code>rolesanywhere:GetSubject</code>. </p>
  /crls:
    GET:
      summary: ListCrls
      description: >-
        <p>Lists all certificate revocation lists (CRL) in the authenticated
        account and Amazon Web Services Region.</p> <p> <b>Required permissions:
        </b> <code>rolesanywhere:ListCrls</code>. </p>
  /subjects:
    GET:
      summary: ListSubjects
      description: >-
        <p>Lists the subjects in the authenticated account and Amazon Web
        Services Region.</p> <p> <b>Required permissions: </b>
        <code>rolesanywhere:ListSubjects</code>. </p>
  /ListTagsForResource:
    GET:
      summary: ListTagsForResource
      description: >-
        <p>Lists the tags attached to the resource.</p> <p> <b>Required
        permissions: </b> <code>rolesanywhere:ListTagsForResource</code>. </p>
  /put-notifications-settings:
    PATCH:
      summary: PutNotificationSettings
      description: >-
        <p>Attaches a list of <i>notification settings</i> to a trust
        anchor.</p> <p>A notification setting includes information such as event
        name, threshold, status of the notification setting, and the channel to
        notify.</p> <p> <b>Required permissions: </b>
        <code>rolesanywhere:PutNotificationSettings</code>. </p>
  /reset-notifications-settings:
    PATCH:
      summary: ResetNotificationSettings
      description: >-
        <p>Resets the <i>custom notification setting</i> to IAM Roles Anywhere
        default setting. </p> <p> <b>Required permissions: </b>
        <code>rolesanywhere:ResetNotificationSettings</code>. </p>
  /TagResource:
    POST:
      summary: TagResource
      description: >-
        <p>Attaches tags to a resource.</p> <p> <b>Required permissions: </b>
        <code>rolesanywhere:TagResource</code>. </p>
  /UntagResource:
    POST:
      summary: UntagResource
      description: >-
        <p>Removes tags from the resource.</p> <p> <b>Required permissions: </b>
        <code>rolesanywhere:UntagResource</cod
