openapi: 3.1.0
info:
  title: route53-recovery-control-config
paths:
  /cluster:
    GET:
      summary: ListClusters
      description: <p>Returns an array of all the clusters in an account.</p>
      tags:
        - List
        - Clusters
        - Cluster
  /controlpanel:
    PUT:
      summary: UpdateControlPanel
      description: >-
        <p>Updates a control panel. The only update you can make to a control
        panel is to change the name of the control panel.</p>
      tags:
        - Update
        - Control
        - Panel
        - Cluster
        - Controlpanel
  /routingcontrol:
    PUT:
      summary: UpdateRoutingControl
      description: >-
        <p>Updates a routing control. You can only update the name of the
        routing control. To get or update the routing control state, see the
        Recovery Cluster (data plane) API actions for Amazon Route 53
        Application Recovery Controller.</p>
      tags:
        - Update
        - Routing
        - Control
        - Cluster
        - Controlpanel
        - Routingcontrol
  /safetyrule:
    PUT:
      summary: UpdateSafetyRule
      description: >-
        <p>Update a safety rule (an assertion rule or gating rule). You can only
        update the name and the waiting period for a safety rule. To make other
        updates, delete the safety rule and create a new one.</p>
      tags:
        - Update
        - Safety
        - Rule
        - Cluster
        - Controlpanel
        - Routingcontrol
        - Safetyrule
  /cluster/{ClusterArn}:
    GET:
      summary: DescribeCluster
      description: >-
        <p>Display the details about a cluster. The response includes the
        cluster name, endpoints, status, and Amazon Resource Name (ARN).</p>
      tags:
        - Describe
        - Cluster
        - Cluster
        - Controlpanel
        - Routingcontrol
        - Safetyrule
        - Arn
  /controlpanel/{ControlPanelArn}:
    GET:
      summary: DescribeControlPanel
      description: <p>Displays details about a control panel.</p>
      tags:
        - Describe
        - Control
        - Panel
        - Cluster
        - Controlpanel
        - Routingcontrol
        - Safetyrule
        - Arn
        - Control
        - Panel
  /routingcontrol/{RoutingControlArn}:
    GET:
      summary: DescribeRoutingControl
      description: >-
        <p>Displays details about a routing control. A routing control has one
        of two states: ON and OFF. You can map the routing control state to the
        state of an Amazon Route 53 health check, which can be used to control
        routing.</p> <p>To get or update the routing control state, see the
        Recovery Cluster (data plane) API actions for Amazon Route 53
        Application Recovery Controller.</p>
      tags:
        - Describe
        - Routing
        - Control
        - Cluster
        - Controlpanel
        - Routingcontrol
        - Safetyrule
        - Arn
        - Control
        - Panel
        - Routing
  /safetyrule/{SafetyRuleArn}:
    GET:
      summary: DescribeSafetyRule
      description: <p>Returns information about a safety rule.</p>
      tags:
        - Describe
        - Safety
        - Rule
        - Cluster
        - Controlpanel
        - Routingcontrol
        - Safetyrule
        - Arn
        - Control
        - Panel
        - Routing
        - Safety
        - Rule
  /resourcePolicy/{ResourceArn}:
    GET:
      summary: GetResourcePolicy
      description: <p>Get information about the resource policy for a cluster.</p>
      tags:
        - Get
        - Resource
        - Policy
        - Cluster
        - Controlpanel
        - Routingcontrol
        - Safetyrule
        - Arn
        - Control
        - Panel
        - Routing
        - Safety
        - Rule
        - Policy
        - Resource
  /routingcontrol/{RoutingControlArn}/associatedRoute53HealthChecks:
    GET:
      summary: ListAssociatedRoute53HealthChecks
      description: >-
        <p>Returns an array of all Amazon Route 53 health checks associated with
        a specific routing control.</p>
      tags:
        - List
        - Associated
        - Route53
        - Health
        - Checks
        - Cluster
        - Controlpanel
        - Routingcontrol
        - Safetyrule
        - Arn
        - Control
        - Panel
        - Routing
        - Safety
        - Rule
        - Policy
        - Resource
        - Associated
        - Route53
        - Health
        - Checks
  /controlpanels:
    GET:
      summary: ListControlPanels
      description: <p>Returns an array of control panels in an account or in a cluster.</p>
      tags:
        - List
        - Control
        - Panels
        - Cluster
        - Controlpanel
        - Routingcontrol
        - Safetyrule
        - Arn
        - Control
        - Panel
        - Routing
        - Safety
        - Rule
        - Policy
        - Resource
        - Associated
        - Route53
        - Health
        - Checks
        - Controlpanels
  /controlpanel/{ControlPanelArn}/routingcontrols:
    GET:
      summary: ListRoutingControls
      description: >-
        <p>Returns an array of routing controls for a control panel. A routing
        control is an Amazon Route 53 Application Recovery Controller construct
        that has one of two states: ON and OFF. You can map the routing control
        state to the state of an Amazon Route 53 health check, which can be used
        to control routing.</p>
      tags:
        - List
        - Routing
        - Controls
        - Cluster
        - Controlpanel
        - Routingcontrol
        - Safetyrule
        - Arn
        - Control
        - Panel
        - Routing
        - Safety
        - Rule
        - Policy
        - Resource
        - Associated
        - Route53
        - Health
        - Checks
        - Controlpanels
        - Routingcontrols
  /controlpanel/{ControlPanelArn}/safetyrules:
    GET:
      summary: ListSafetyRules
      description: >-
        <p>List the safety rules (the assertion rules and gating rules) that
        you've defined for the routing controls in a control panel.</p>
      tags:
        - List
        - Safety
        - Rules
        - Cluster
        - Controlpanel
        - Routingcontrol
        - Safetyrule
        - Arn
        - Control
        - Panel
        - Routing
        - Safety
        - Rule
        - Policy
        - Resource
        - Associated
        - Route53
        - Health
        - Checks
        - Controlpanels
        - Routingcontrols
        - Safetyrules
  /tags/{ResourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Removes a tag from a resource.</
      tags:
        - Untag
        - Resource
        - Cluster
        - Controlpanel
        - Routingcontrol
        - Safetyrule
        - Arn
        - Control
        - Panel
        - Routing
        - Safety
        - Rule
        - Policy
        - Resource
        - Associated
        - Route53
        - Health
        - Checks
        - Controlpanels
        - Routingcontrols
        - Safet
