openapi: 3.1.0
info:
  title: sagemaker-edge
paths:
  /GetDeployments:
    POST:
      summary: GetDeployments
      description: <p>Use to get the active deployments from a device.</p>
      tags:
        - Get
        - Deployments
        - Get
        - Deployments
  /GetDeviceRegistration:
    POST:
      summary: GetDeviceRegistration
      description: >-
        <p>Use to check if a device is registered with SageMaker Edge
        Manager.</p>
      tags:
        - Get
        - Device
        - Registration
        - Get
        - Deployments
        - Device
        - Registration
  /SendHeartbeat:
    POST:
      summary: SendHeartbeat
      description: >-
        <p>Use to get the current status of devices registered on SageMaker Edge
        Ma
      tags:
        - Send
        - Heartbeat
        - Get
        - Deployments
        - Device
        - Registration
        - Send
        - Heartbe
