openapi: 3.1.0
info:
  title: sagemaker-metrics
paths:
  /BatchPutMetrics:
    PUT:
      summary: BatchPutMetrics
      description: >-
        <p>Used to ingest training metrics into SageMaker. These metrics can be
        visualized in SageMaker Studio and retrieved with the
        <code>GetMetrics</code> API. </
      tags:
        - Batch
        - Put
        - Metrics
        - Batch
        - Put
        - M
