openapi: 3.1.0
info:
  title: savingsplans
paths:
  /CreateSavingsPlan:
    POST:
      summary: CreateSavingsPlan
      description: <p>Creates a Savings Plan.</p>
      tags:
        - Create
        - Savings
        - Plan
        - Create
        - Savings
        - Plan
  /DeleteQueuedSavingsPlan:
    POST:
      summary: DeleteQueuedSavingsPlan
      description: <p>Deletes the queued purchase for the specified Savings Plan.</p>
      tags:
        - Delete
        - Queued
        - Savings
        - Plan
        - Create
        - Savings
        - Plan
        - Delete
        - Queued
  /DescribeSavingsPlanRates:
    POST:
      summary: DescribeSavingsPlanRates
      description: <p>Describes the specified Savings Plans rates.</p>
      tags:
        - Describe
        - Savings
        - Plan
        - Rates
        - Create
        - Savings
        - Plan
        - Delete
        - Queued
        - Describe
        - Rates
  /DescribeSavingsPlans:
    POST:
      summary: DescribeSavingsPlans
      description: <p>Describes the specified Savings Plans.</p>
      tags:
        - Describe
        - Savings
        - Plans
        - Create
        - Savings
        - Plan
        - Delete
        - Queued
        - Describe
        - Rates
        - Plans
  /DescribeSavingsPlansOfferingRates:
    POST:
      summary: DescribeSavingsPlansOfferingRates
      description: <p>Describes the specified Savings Plans offering rates.</p>
      tags:
        - Describe
        - Savings
        - Plans
        - Offering
        - Rates
        - Create
        - Savings
        - Plan
        - Delete
        - Queued
        - Describe
        - Rates
        - Plans
        - Offering
  /DescribeSavingsPlansOfferings:
    POST:
      summary: DescribeSavingsPlansOfferings
      description: <p>Describes the specified Savings Plans offerings.</p>
      tags:
        - Describe
        - Savings
        - Plans
        - Offerings
        - Create
        - Savings
        - Plan
        - Delete
        - Queued
        - Describe
        - Rates
        - Plans
        - Offering
        - Offerings
  /ListTagsForResource:
    POST:
      summary: ListTagsForResource
      description: <p>Lists the tags for the specified resource.</p>
      tags:
        - List
        - Tags
        - For
        - Resource
        - Create
        - Savings
        - Plan
        - Delete
        - Queued
        - Describe
        - Rates
        - Plans
        - Offering
        - Offerings
        - List
        - Tags
        - For
        - Resource
  /TagResource:
    POST:
      summary: TagResource
      description: <p>Adds the specified tags to the specified resource.</p>
      tags:
        - Tag
        - Resource
        - Create
        - Savings
        - Plan
        - Delete
        - Queued
        - Describe
        - Rates
        - Plans
        - Offering
        - Offerings
        - List
        - Tags
        - For
        - Resource
        - Tag
  /UntagResource:
    POST:
      summary: UntagResource
      description: <p>Removes the specified tags from the specified resource.</
      tags:
        - Untag
        - Resource
        - Create
        - Savings
        - Plan
        - Delete
        - Queued
        - Describe
        - Rates
        - Plans
        - Offering
        - Offerings
        - List
        - Tags
        - For
        - Resource
        - Tag
        - Untag
