openapi: 3.1.0
info:
  title: savingsplans
paths:
  /CreateSavingsPlan:
    POST:
      summary: CreateSavingsPlan
      description: <p>Creates a Savings Plan.</p>
  /DeleteQueuedSavingsPlan:
    POST:
      summary: DeleteQueuedSavingsPlan
      description: <p>Deletes the queued purchase for the specified Savings Plan.</p>
  /DescribeSavingsPlanRates:
    POST:
      summary: DescribeSavingsPlanRates
      description: <p>Describes the specified Savings Plans rates.</p>
  /DescribeSavingsPlans:
    POST:
      summary: DescribeSavingsPlans
      description: <p>Describes the specified Savings Plans.</p>
  /DescribeSavingsPlansOfferingRates:
    POST:
      summary: DescribeSavingsPlansOfferingRates
      description: <p>Describes the specified Savings Plans offering rates.</p>
  /DescribeSavingsPlansOfferings:
    POST:
      summary: DescribeSavingsPlansOfferings
      description: <p>Describes the specified Savings Plans offerings.</p>
  /ListTagsForResource:
    POST:
      summary: ListTagsForResource
      description: <p>Lists the tags for the specified resource.</p>
  /TagResource:
    POST:
      summary: TagResource
      description: <p>Adds the specified tags to the specified resource.</p>
  /UntagResource:
    POST:
      summary: UntagResource
      description: <p>Removes the specified tags from the specified resou
