openapi: 3.1.0
info:
  title: scheduler
paths:
  /schedules/{Name}:
    PUT:
      summary: UpdateSchedule
      description: >-
        <p> Updates the specified schedule. When you call
        <code>UpdateSchedule</code>, EventBridge Scheduler uses all values,
        including empty values, specified in the request and overrides the
        existing schedule. This is by design. This means that if you do not set
        an optional field in your request, that field will be set to its
        system-default value after the update. </p> <p> Before calling this
        operation, we recommend that you call the <code>GetSchedule</code> API
        operation and make a note of all optional parameters for your
        <code>UpdateSchedule</code> call. </p>
      tags:
        - Update
        - Schedule
        - Name
  /schedule-groups/{Name}:
    GET:
      summary: GetScheduleGroup
      description: <p>Retrieves the specified schedule group.</p>
      tags:
        - Get
        - Schedule
        - Group
        - Name
  /schedule-groups:
    GET:
      summary: ListScheduleGroups
      description: <p>Returns a paginated list of your schedule groups.</p>
      tags:
        - List
        - Schedule
        - Groups
        - Name
        - Schedule
        - Groups
  /schedules:
    GET:
      summary: ListSchedules
      description: <p>Returns a paginated list of your EventBridge Scheduler schedules.</p>
      tags:
        - List
        - Schedules
        - Name
        - Schedule
        - Groups
        - Schedules
  /tags/{ResourceArn}:
    DELETE:
      summary: UntagResource
      description: >-
        <p>Removes one or more tags from the specified EventBridge Scheduler
        schedule group.</
      tags:
        - Untag
        - Resource
        - Name
        - Schedule
        - Groups
        - Schedules
        - Resource
        - Arn
