openapi: 3.1.0
info:
  title: serverlessrepo
paths:
  /applications:
    GET:
      summary: ListApplications
      description: <p>Lists applications owned by the requester.</p>
      tags:
        - List
        - Applications
        - Applications
  /applications/{applicationId}/versions/{semanticVersion}:
    PUT:
      summary: CreateApplicationVersion
      description: <p>Creates an application version.</p>
      tags:
        - Create
        - Application
        - Version
        - Applications
        - Id
        - Versions
        - Semantic
        - Version
  /applications/{applicationId}/changesets:
    POST:
      summary: CreateCloudFormationChangeSet
      description: >-
        <p>Creates an AWS CloudFormation change set for the given
        application.</p>
      tags:
        - Create
        - Cloud
        - Formation
        - Change
        - Set
        - Applications
        - Id
        - Versions
        - Semantic
        - Version
        - Changesets
  /applications/{applicationId}/templates:
    POST:
      summary: CreateCloudFormationTemplate
      description: <p>Creates an AWS CloudFormation template.</p>
      tags:
        - Create
        - Cloud
        - Formation
        - Template
        - Applications
        - Id
        - Versions
        - Semantic
        - Version
        - Changesets
        - Templates
  /applications/{applicationId}:
    PATCH:
      summary: UpdateApplication
      description: <p>Updates the specified application.</p>
      tags:
        - Update
        - Application
        - Applications
        - Id
        - Versions
        - Semantic
        - Version
        - Changesets
        - Templates
  /applications/{applicationId}/policy:
    PUT:
      summary: PutApplicationPolicy
      description: >-
        <p>Sets the permission policy for an application. For the list of
        actions supported for this operation, see
         <a href="https://docs.aws.amazon.com/serverlessrepo/latest/devguide/access-control-resource-based.html#application-permissions">Application 
         Permissions</a>
         .</p>
      tags:
        - Put
        - Application
        - Policy
        - Applications
        - Id
        - Versions
        - Semantic
        - Version
        - Changesets
        - Templates
        - Policy
  /applications/{applicationId}/templates/{templateId}:
    GET:
      summary: GetCloudFormationTemplate
      description: <p>Gets the specified AWS CloudFormation template.</p>
      tags:
        - Get
        - Cloud
        - Formation
        - Template
        - Applications
        - Id
        - Versions
        - Semantic
        - Version
        - Changesets
        - Templates
        - Policy
        - Template
  /applications/{applicationId}/dependencies:
    GET:
      summary: ListApplicationDependencies
      description: >-
        <p>Retrieves the list of applications nested in the containing
        application.</p>
      tags:
        - List
        - Application
        - Dependencies
        - Applications
        - Id
        - Versions
        - Semantic
        - Version
        - Changesets
        - Templates
        - Policy
        - Template
        - Dependencies
  /applications/{applicationId}/versions:
    GET:
      summary: ListApplicationVersions
      description: <p>Lists versions for the specified application.</p>
      tags:
        - List
        - Application
        - Versions
        - Applications
        - Id
        - Versions
        - Semantic
        - Version
        - Changesets
        - Templates
        - Policy
        - Template
        - Dependencies
  /applications/{applicationId}/unshare:
    POST:
      summary: UnshareApplication
      description: >-
        <p>Unshares an application from an AWS Organization.</p><p>This
        operation can be called only from the organization's master account.</
      tags:
        - Unshare
        - Application
        - Applications
        - Id
        - Versions
        - Semantic
        - Version
        - Changesets
        - Templates
        - Policy
        - Template
        - Dependencies
        - Unshare
