openapi: 3.1.0
info:
  title: servicecatalog-appregistry
paths:
  /applications/{application}/attribute-groups/{attributeGroup}:
    DELETE:
      summary: DisassociateAttributeGroup
      description: >-
        <p>Disassociates an attribute group from an application to remove the
        extra attributes contained in the attribute group from the application's
        metadata. This operation reverts
        <code>AssociateAttributeGroup</code>.</p>
      tags:
        - Disassociate
        - Attribute
        - Group
        - Group
  /applications/{application}/resources/{resourceType}/{resource}:
    GET:
      summary: GetAssociatedResource
      description: <p>Gets the resource associated with the application.</p>
      tags:
        - Get
        - Associated
        - Resource
        - Group
        - Type
        - Resource
  /applications:
    GET:
      summary: ListApplications
      description: >-
        <p>Retrieves a list of all of your applications. Results are
        paginated.</p>
      tags:
        - List
        - Applications
        - Group
        - Type
        - Resource
        - Applications
  /attribute-groups:
    GET:
      summary: ListAttributeGroups
      description: >-
        <p>Lists all attribute groups which you have access to. Results are
        paginated.</p>
      tags:
        - List
        - Attribute
        - Groups
        - Group
        - Type
        - Resource
        - Applications
        - Attribute
        - Groups
  /applications/{application}:
    PATCH:
      summary: UpdateApplication
      description: <p>Updates an existing application with new attributes.</p>
      tags:
        - Update
        - Application
        - Group
        - Type
        - Resource
        - Applications
        - Attribute
        - Groups
        - Application
  /attribute-groups/{attributeGroup}:
    PATCH:
      summary: UpdateAttributeGroup
      description: <p>Updates an existing attribute group with new details. </p>
      tags:
        - Update
        - Attribute
        - Group
        - Group
        - Type
        - Resource
        - Applications
        - Attribute
        - Groups
        - Application
  /configuration:
    PUT:
      summary: PutConfiguration
      description: <p> Associates a <code>TagKey</code> configuration to an account. </p>
      tags:
        - Put
        - Configuration
        - Group
        - Type
        - Resource
        - Applications
        - Attribute
        - Groups
        - Application
        - Configuration
  /applications/{application}/attribute-groups:
    GET:
      summary: ListAssociatedAttributeGroups
      description: >-
        <p>Lists all attribute groups that are associated with specified
        application. Results are paginated.</p>
      tags:
        - List
        - Associated
        - Attribute
        - Groups
        - Group
        - Type
        - Resource
        - Applications
        - Attribute
        - Groups
        - Application
        - Configuration
  /applications/{application}/resources:
    GET:
      summary: ListAssociatedResources
      description: >-
        <p> Lists all of the resources that are associated with the specified
        application. Results are paginated. </p> <note> <p> If you share an
        application, and a consumer account associates a tag query to the
        application, all of the users who can access the application can also
        view the tag values in all accounts that are associated with it using
        this API. </p> </note>
      tags:
        - List
        - Associated
        - Resources
        - Group
        - Type
        - Resource
        - Applications
        - Attribute
        - Groups
        - Application
        - Configuration
        - Resources
  /applications/{application}/attribute-group-details:
    GET:
      summary: ListAttributeGroupsForApplication
      description: >-
        <p>Lists the details of all attribute groups associated with a specific
        application. The results display in pages.</p>
      tags:
        - List
        - Attribute
        - Groups
        - For
        - Application
        - Group
        - Type
        - Resource
        - Applications
        - Attribute
        - Groups
        - Application
        - Configuration
        - Resources
        - Details
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: >-
        <p>Removes tags from a resource.</p> <p>This operation returns an empty
        response if the call was successful.</p>
      tags:
        - Untag
        - Resource
        - Group
        - Type
        - Resource
        - Applications
        - Attribute
        - Groups
        - Application
        - Configuration
        - Resources
        - Details
        - Arn
  /sync/{resourceType}/{resource}:
    POST:
      summary: SyncResource
      description: >-
        <p>Syncs the resource with current AppRegistry records.</p>
        <p>Specifically, the resource’s AppRegistry system tags sync with its
        associated application. We remove the resource's AppRegistry system tags
        if it does not associate with the application. The caller must have
        permissions to read and update the resource.</
      tags:
        - Sync
        - Resource
        - Group
        - Type
        - Resource
        - Applications
        - Attribute
        - Groups
        - Application
        - Configuration
        - Resources
        - Details
        - Arn
