openapi: 3.1.0
info:
  title: serverlessrepo
paths:
  /applications:
    GET:
      summary: ListApplications
      description: <p>Lists applications owned by the requester.</p>
  /applications/{applicationId}/versions/{semanticVersion}:
    PUT:
      summary: CreateApplicationVersion
      description: <p>Creates an application version.</p>
  /applications/{applicationId}/changesets:
    POST:
      summary: CreateCloudFormationChangeSet
      description: >-
        <p>Creates an AWS CloudFormation change set for the given
        application.</p>
  /applications/{applicationId}/templates:
    POST:
      summary: CreateCloudFormationTemplate
      description: <p>Creates an AWS CloudFormation template.</p>
  /applications/{applicationId}:
    PATCH:
      summary: UpdateApplication
      description: <p>Updates the specified application.</p>
  /applications/{applicationId}/policy:
    PUT:
      summary: PutApplicationPolicy
      description: >-
        <p>Sets the permission policy for an application. For the list of
        actions supported for this operation, see
         <a href="https://docs.aws.amazon.com/serverlessrepo/latest/devguide/access-control-resource-based.html#application-permissions">Application 
         Permissions</a>
         .</p>
  /applications/{applicationId}/templates/{templateId}:
    GET:
      summary: GetCloudFormationTemplate
      description: <p>Gets the specified AWS CloudFormation template.</p>
  /applications/{applicationId}/dependencies:
    GET:
      summary: ListApplicationDependencies
      description: >-
        <p>Retrieves the list of applications nested in the containing
        application.</p>
  /applications/{applicationId}/versions:
    GET:
      summary: ListApplicationVersions
      description: <p>Lists versions for the specified application.</p>
  /applications/{applicationId}/unshare:
    POST:
      summary: UnshareApplication
      description: >-
        <p>Unshares an application from an AWS Organization.</p><p>This
        operation can be called only from the organization's master acco
