openapi: 3.1.0
info:
  title: sms-voice
paths:
  /v1/sms-voice/configuration-sets:
    GET:
      summary: ListConfigurationSets
      description: >-
        List all of the configuration sets associated with your Amazon Pinpoint
        account in the current region.
      tags:
        - List
        - Configuration
        - Sets
        - V1
        - Sms
        - Voice
        - Configuration
        - Sets
  /v1/sms-voice/configuration-sets/{ConfigurationSetName}/event-destinations:
    GET:
      summary: GetConfigurationSetEventDestinations
      description: >-
        Obtain information about an event destination, including the types of
        events it reports, the Amazon Resource Name (ARN) of the destination,
        and the name of the event destination.
      tags:
        - Get
        - Configuration
        - Set
        - Event
        - Destinations
        - V1
        - Sms
        - Voice
        - Configuration
        - Sets
        - Set
        - Name
        - Event
        - Destinations
  /v1/sms-voice/configuration-sets/{ConfigurationSetName}:
    DELETE:
      summary: DeleteConfigurationSet
      description: Deletes an existing configuration set.
      tags:
        - Delete
        - Configuration
        - Set
        - V1
        - Sms
        - Voice
        - Configuration
        - Sets
        - Set
        - Name
        - Event
        - Destinations
  /v1/sms-voice/configuration-sets/{ConfigurationSetName}/event-destinations/{EventDestinationName}:
    PUT:
      summary: UpdateConfigurationSetEventDestination
      description: >-
        Update an event destination in a configuration set. An event destination
        is a location that you publish information about your voice calls to.
        For example, you can log an event to an Amazon CloudWatch destination
        when a call fails.
      tags:
        - Update
        - Configuration
        - Set
        - Event
        - Destination
        - V1
        - Sms
        - Voice
        - Configuration
        - Sets
        - Set
        - Name
        - Event
        - Destinations
        - Destination
  /v1/sms-voice/voice/message:
    POST:
      summary: SendVoiceMessage
      description: Create a new voice message and send it to a recipient's pho
      tags:
        - Send
        - Voice
        - Message
        - V1
        - Sms
        - Voice
        - Configuration
        - Sets
        - Set
        - Name
        - Event
        - Destinations
        - Destination
        - Messa
