openapi: 3.1.0
info:
  title: snowball
paths:
  /:
    POST:
      summary: UpdateLongTermPricing
      description: <p>Updates the long-term pricing type.</
      tags:
        - Update
        - Long
        - Term
        - P
