openapi: 3.1.0
info:
  title: timestream-query
paths:
  /:
    POST:
      summary: UpdateScheduledQuery
      description: <p>Update a scheduled query.</
      tags:
        - Update
        - Scheduled
        - null
