openapi: 3.1.0
info:
  title: trustedadvisor
paths:
  /v1/organization-recommendations/{organizationRecommendationIdentifier}:
    GET:
      summary: GetOrganizationRecommendation
      description: >-
        <p>Get a specific recommendation within an AWS Organizations
        organization. This API supports only prioritized recommendations. </p>
      tags:
        - Get
        - Organization
        - Recommendation
        - Recommendation
        - Identifier
  /v1/recommendations/{recommendationIdentifier}:
    GET:
      summary: GetRecommendation
      description: <p>Get a specific Recommendation</p>
      tags:
        - Get
        - Recommendation
        - Recommendation
        - Identifier
  /v1/checks:
    GET:
      summary: ListChecks
      description: <p>List a filterable set of Checks</p>
      tags:
        - List
        - Checks
        - Recommendation
        - Identifier
        - V1
        - Checks
  /v1/organization-recommendations/{organizationRecommendationIdentifier}/accounts:
    GET:
      summary: ListOrganizationRecommendationAccounts
      description: >-
        <p>Lists the accounts that own the resources for an organization
        aggregate recommendation. This API only supports prioritized
        recommendations. </p>
      tags:
        - List
        - Organization
        - Recommendation
        - Accounts
        - Recommendation
        - Identifier
        - V1
        - Checks
        - Accounts
  /v1/organization-recommendations/{organizationRecommendationIdentifier}/resources:
    GET:
      summary: ListOrganizationRecommendationResources
      description: >-
        <p>List Resources of a Recommendation within an Organization. This API
        only supports prioritized recommendations. </p>
      tags:
        - List
        - Organization
        - Recommendation
        - Resources
        - Recommendation
        - Identifier
        - V1
        - Checks
        - Accounts
        - Resources
  /v1/organization-recommendations:
    GET:
      summary: ListOrganizationRecommendations
      description: >-
        <p>List a filterable set of Recommendations within an Organization. This
        API only supports prioritized recommendations. </p>
      tags:
        - List
        - Organization
        - Recommendations
        - Recommendation
        - Identifier
        - V1
        - Checks
        - Accounts
        - Resources
        - Organization
        - Recommendations
  /v1/recommendations/{recommendationIdentifier}/resources:
    GET:
      summary: ListRecommendationResources
      description: <p>List Resources of a Recommendation</p>
      tags:
        - List
        - Recommendation
        - Resources
        - Recommendation
        - Identifier
        - V1
        - Checks
        - Accounts
        - Resources
        - Organization
        - Recommendations
  /v1/recommendations:
    GET:
      summary: ListRecommendations
      description: <p>List a filterable set of Recommendations</p>
      tags:
        - List
        - Recommendations
        - Recommendation
        - Identifier
        - V1
        - Checks
        - Accounts
        - Resources
        - Organization
        - Recommendations
  /v1/organization-recommendations/{organizationRecommendationIdentifier}/lifecycle:
    PUT:
      summary: UpdateOrganizationRecommendationLifecycle
      description: >-
        <p>Update the lifecyle of a Recommendation within an Organization. This
        API only supports prioritized recommendations. </p>
      tags:
        - Update
        - Organization
        - Recommendation
        - Lifecycle
        - Recommendation
        - Identifier
        - V1
        - Checks
        - Accounts
        - Resources
        - Organization
        - Recommendations
        - Lifecycle
  /v1/recommendations/{recommendationIdentifier}/lifecycle:
    PUT:
      summary: UpdateRecommendationLifecycle
      description: >-
        <p>Update the lifecyle of a Recommendation. This API only supports
        prioritized recommendations.</
      tags:
        - Update
        - Recommendation
        - Lifecycle
        - Recommendation
        - Identifier
        - V1
        - Checks
        - Accounts
        - Resources
        - Organization
        - Recommendations
        - Lif
