openapi: 3.1.0
info:
  title: vpc-lattice
paths:
  /services/{serviceIdentifier}/listeners/{listenerIdentifier}/rules:
    GET:
      summary: ListRules
      description: <p>Lists the rules for the listener.</p>
      tags:
        - List
        - Rules
        - Identifier
        - Listeners
        - Listener
        - Rules
  /accesslogsubscriptions:
    GET:
      summary: ListAccessLogSubscriptions
      description: >-
        <p>Lists all access log subscriptions for the specified service network
        or service.</p>
      tags:
        - List
        - Access
        - Log
        - Subscriptions
        - Identifier
        - Listeners
        - Listener
        - Rules
        - Accesslogsubscriptions
  /services/{serviceIdentifier}/listeners:
    GET:
      summary: ListListeners
      description: <p>Lists the listeners for the specified service.</p>
      tags:
        - List
        - Listeners
        - Identifier
        - Listeners
        - Listener
        - Rules
        - Accesslogsubscriptions
  /services:
    GET:
      summary: ListServices
      description: >-
        <p>Lists the services owned by the caller account or shared with the
        caller account.</p>
      tags:
        - List
        - Services
        - Identifier
        - Listeners
        - Listener
        - Rules
        - Accesslogsubscriptions
        - Services
  /servicenetworks:
    GET:
      summary: ListServiceNetworks
      description: >-
        <p>Lists the service networks owned by the caller account or shared with
        the caller account. Also includes the account ID in the ARN to show
        which account owns the service network.</p>
      tags:
        - List
        - Service
        - Networks
        - Identifier
        - Listeners
        - Listener
        - Rules
        - Accesslogsubscriptions
        - Services
        - Servicenetworks
  /servicenetworkserviceassociations:
    GET:
      summary: ListServiceNetworkServiceAssociations
      description: >-
        <p>Lists the associations between the service network and the service.
        You can filter the list either by service or service network. You must
        provide either the service network identifier or the service
        identifier.</p> <p>Every association in Amazon VPC Lattice is given a
        unique Amazon Resource Name (ARN), such as when a service network is
        associated with a VPC or when a service is associated with a service
        network. If the association is for a resource that is shared with
        another account, the association will include the local account ID as
        the prefix in the ARN for each account the resource is shared with.</p>
      tags:
        - List
        - Service
        - Network
        - Associations
        - Identifier
        - Listeners
        - Listener
        - Rules
        - Accesslogsubscriptions
        - Services
        - Servicenetworks
        - Servicenetworkserviceassociations
  /servicenetworkvpcassociations:
    GET:
      summary: ListServiceNetworkVpcAssociations
      description: >-
        <p>Lists the service network and VPC associations. You can filter the
        list either by VPC or service network. You must provide either the
        service network identifier or the VPC identifier.</p>
      tags:
        - List
        - Service
        - Network
        - Vpc
        - Associations
        - Identifier
        - Listeners
        - Listener
        - Rules
        - Accesslogsubscriptions
        - Services
        - Servicenetworks
        - Servicenetworkserviceassociations
        - Servicenetworkvpcassociations
  /targetgroups:
    GET:
      summary: ListTargetGroups
      description: >-
        <p>Lists your target groups. You can narrow your search by using the
        filters below in your request.</p>
      tags:
        - List
        - Target
        - Groups
        - Identifier
        - Listeners
        - Listener
        - Rules
        - Accesslogsubscriptions
        - Services
        - Servicenetworks
        - Servicenetworkserviceassociations
        - Servicenetworkvpcassociations
        - Targetgroups
  /accesslogsubscriptions/{accessLogSubscriptionIdentifier}:
    PATCH:
      summary: UpdateAccessLogSubscription
      description: <p>Updates the specified access log subscription.</p>
      tags:
        - Update
        - Access
        - Log
        - Subscription
        - Identifier
        - Listeners
        - Listener
        - Rules
        - Accesslogsubscriptions
        - Services
        - Servicenetworks
        - Servicenetworkserviceassociations
        - Servicenetworkvpcassociations
        - Targetgroups
        - Log
        - Subscription
  /authpolicy/{resourceIdentifier}:
    PUT:
      summary: PutAuthPolicy
      description: <p>Creates or updates the auth policy.</p>
      tags:
        - Put
        - Auth
        - Policy
        - Identifier
        - Listeners
        - Listener
        - Rules
        - Accesslogsubscriptions
        - Services
        - Servicenetworks
        - Servicenetworkserviceassociations
        - Servicenetworkvpcassociations
        - Targetgroups
        - Log
        - Subscription
  /services/{serviceIdentifier}/listeners/{listenerIdentifier}:
    PATCH:
      summary: UpdateListener
      description: <p>Updates the specified listener for the specified service.</p>
      tags:
        - Update
        - Listener
        - Identifier
        - Listeners
        - Listener
        - Rules
        - Accesslogsubscriptions
        - Services
        - Servicenetworks
        - Servicenetworkserviceassociations
        - Servicenetworkvpcassociations
        - Targetgroups
        - Log
        - Subscription
  /resourcepolicy/{resourceArn}:
    PUT:
      summary: PutResourcePolicy
      description: >-
        <p>Attaches a resource-based permission policy to a service or service
        network. The policy must contain the same actions and condition
        statements as the Amazon Web Services Resource Access Manager permission
        for sharing services and service networks.</p>
      tags:
        - Put
        - Resource
        - Policy
        - Identifier
        - Listeners
        - Listener
        - Rules
        - Accesslogsubscriptions
        - Services
        - Servicenetworks
        - Servicenetworkserviceassociations
        - Servicenetworkvpcassociations
        - Targetgroups
        - Log
        - Subscription
        - Arn
  /services/{serviceIdentifier}/listeners/{listenerIdentifier}/rules/{ruleIdentifier}:
    PATCH:
      summary: UpdateRule
      description: >-
        <p>Updates a rule for the listener. You can't modify a default listener
        rule. To modify a default listener rule, use
        <code>UpdateListener</code>.</p>
      tags:
        - Update
        - Rule
        - Identifier
        - Listeners
        - Listener
        - Rules
        - Accesslogsubscriptions
        - Services
        - Servicenetworks
        - Servicenetworkserviceassociations
        - Servicenetworkvpcassociations
        - Targetgroups
        - Log
        - Subscription
        - Arn
        - Rule
  /services/{serviceIdentifier}:
    PATCH:
      summary: UpdateService
      description: <p>Updates the specified service.</p>
      tags:
        - Update
        - Service
        - Identifier
        - Listeners
        - Listener
        - Rules
        - Accesslogsubscriptions
        - Services
        - Servicenetworks
        - Servicenetworkserviceassociations
        - Servicenetworkvpcassociations
        - Targetgroups
        - Log
        - Subscription
        - Arn
        - Rule
  /servicenetworks/{serviceNetworkIdentifier}:
    PATCH:
      summary: UpdateServiceNetwork
      description: <p>Updates the specified service network.</p>
      tags:
        - Update
        - Service
        - Network
        - Identifier
        - Listeners
        - Listener
        - Rules
        - Accesslogsubscriptions
        - Services
        - Servicenetworks
        - Servicenetworkserviceassociations
        - Servicenetworkvpcassociations
        - Targetgroups
        - Log
        - Subscription
        - Arn
        - Rule
        - Network
  /servicenetworkserviceassociations/{serviceNetworkServiceAssociationIdentifier}:
    GET:
      summary: GetServiceNetworkServiceAssociation
      description: >-
        <p>Retrieves information about the specified association between a
        service network and a service.</p>
      tags:
        - Get
        - Service
        - Network
        - Association
        - Identifier
        - Listeners
        - Listener
        - Rules
        - Accesslogsubscriptions
        - Services
        - Servicenetworks
        - Servicenetworkserviceassociations
        - Servicenetworkvpcassociations
        - Targetgroups
        - Log
        - Subscription
        - Arn
        - Rule
        - Network
        - Service
        - Association
  /servicenetworkvpcassociations/{serviceNetworkVpcAssociationIdentifier}:
    PATCH:
      summary: UpdateServiceNetworkVpcAssociation
      description: >-
        <p>Updates the service network and VPC association. Once you add a
        security group, it cannot be removed.</p>
      tags:
        - Update
        - Service
        - Network
        - Vpc
        - Association
        - Identifier
        - Listeners
        - Listener
        - Rules
        - Accesslogsubscriptions
        - Services
        - Servicenetworks
        - Servicenetworkserviceassociations
        - Servicenetworkvpcassociations
        - Targetgroups
        - Log
        - Subscription
        - Arn
        - Rule
        - Network
        - Service
        - Association
        - Vpc
  /targetgroups/{targetGroupIdentifier}:
    PATCH:
      summary: UpdateTargetGroup
      description: <p>Updates the specified target group.</p>
      tags:
        - Update
        - Target
        - Group
        - Identifier
        - Listeners
        - Listener
        - Rules
        - Accesslogsubscriptions
        - Services
        - Servicenetworks
        - Servicenetworkserviceassociations
        - Servicenetworkvpcassociations
        - Targetgroups
        - Log
        - Subscription
        - Arn
        - Rule
        - Network
        - Service
        - Association
        - Vpc
        - Group
  /targetgroups/{targetGroupIdentifier}/deregistertargets:
    POST:
      summary: DeregisterTargets
      description: >-
        <p>Deregisters the specified targets from the specified target
        group.</p>
      tags:
        - Deregister
        - Targets
        - Identifier
        - Listeners
        - Listener
        - Rules
        - Accesslogsubscriptions
        - Services
        - Servicenetworks
        - Servicenetworkserviceassociations
        - Servicenetworkvpcassociations
        - Targetgroups
        - Log
        - Subscription
        - Arn
        - Rule
        - Network
        - Service
        - Association
        - Vpc
        - Group
        - Deregistertargets
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Removes the specified tags from the specified resource.</p>
      tags:
        - Untag
        - Resource
        - Identifier
        - Listeners
        - Listener
        - Rules
        - Accesslogsubscriptions
        - Services
        - Servicenetworks
        - Servicenetworkserviceassociations
        - Servicenetworkvpcassociations
        - Targetgroups
        - Log
        - Subscription
        - Arn
        - Rule
        - Network
        - Service
        - Association
        - Vpc
        - Group
        - Deregistertargets
  /targetgroups/{targetGroupIdentifier}/listtargets:
    POST:
      summary: ListTargets
      description: >-
        <p>Lists the targets for the target group. By default, all targets are
        included. You can use this API to check the health status of targets.
        You can also ﬁlter the results by target. </p>
      tags:
        - List
        - Targets
        - Identifier
        - Listeners
        - Listener
        - Rules
        - Accesslogsubscriptions
        - Services
        - Servicenetworks
        - Servicenetworkserviceassociations
        - Servicenetworkvpcassociations
        - Targetgroups
        - Log
        - Subscription
        - Arn
        - Rule
        - Network
        - Service
        - Association
        - Vpc
        - Group
        - Deregistertargets
        - Listtargets
  /targetgroups/{targetGroupIdentifier}/registertargets:
    POST:
      summary: RegisterTargets
      description: >-
        <p>Registers the targets with the target group. If it's a Lambda target,
        you can only have one target in a target group.</
      tags:
        - Register
        - Targets
        - Identifier
        - Listeners
        - Listener
        - Rules
        - Accesslogsubscriptions
        - Services
        - Servicenetworks
        - Servicenetworkserviceassociations
        - Servicenetworkvpcassociations
        - Targetgroups
        - Log
        - Subscription
        - Arn
        - Rule
        - Network
        - Service
        - Association
        - Vpc
        - Group
        - Deregistertargets
        - Listtargets
        - Registertargets
