openapi: 3.1.0
info:
  title: wisdom
paths:
  /assistants:
    GET:
      summary: ListAssistants
      description: <p>Lists information about assistants.</p>
      tags:
        - List
        - Assistants
        - Assistants
  /assistants/{assistantId}/associations:
    GET:
      summary: ListAssistantAssociations
      description: <p>Lists information about assistant associations.</p>
      tags:
        - List
        - Assistant
        - Associations
        - Assistants
        - Id
        - Associations
  /knowledgeBases/{knowledgeBaseId}/contents:
    GET:
      summary: ListContents
      description: <p>Lists the content.</p>
      tags:
        - List
        - Contents
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
  /knowledgeBases:
    GET:
      summary: ListKnowledgeBases
      description: <p>Lists the knowledge bases.</p>
      tags:
        - List
        - Knowledge
        - Bases
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
  /knowledgeBases/{knowledgeBaseId}/quickResponses:
    GET:
      summary: ListQuickResponses
      description: <p>Lists information about quick response.</p>
      tags:
        - List
        - Quick
        - Responses
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
        - Quick
        - Responses
  /assistants/{assistantId}/sessions:
    POST:
      summary: CreateSession
      description: >-
        <p>Creates a session. A session is a contextual container used for
        generating recommendations. Amazon Connect creates a new Wisdom session
        for each contact on which Wisdom is enabled.</p>
      tags:
        - Create
        - Session
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
        - Quick
        - Responses
        - Sessions
  /assistants/{assistantId}:
    GET:
      summary: GetAssistant
      description: <p>Retrieves information about an assistant.</p>
      tags:
        - Get
        - Assistant
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
        - Quick
        - Responses
        - Sessions
  /assistants/{assistantId}/associations/{assistantAssociationId}:
    GET:
      summary: GetAssistantAssociation
      description: <p>Retrieves information about an assistant association.</p>
      tags:
        - Get
        - Assistant
        - Association
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
        - Quick
        - Responses
        - Sessions
        - Assistant
        - Association
  /knowledgeBases/{knowledgeBaseId}/contents/{contentId}:
    POST:
      summary: UpdateContent
      description: <p>Updates information about the content.</p>
      tags:
        - Update
        - Content
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
        - Quick
        - Responses
        - Sessions
        - Assistant
        - Association
        - Content
  /knowledgeBases/{knowledgeBaseId}/importJobs/{importJobId}:
    GET:
      summary: GetImportJob
      description: <p>Retrieves the started import job.</p>
      tags:
        - Get
        - Import
        - Job
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
        - Quick
        - Responses
        - Sessions
        - Assistant
        - Association
        - Content
        - Import
        - Jobs
        - Job
  /knowledgeBases/{knowledgeBaseId}:
    GET:
      summary: GetKnowledgeBase
      description: <p>Retrieves information about the knowledge base.</p>
      tags:
        - Get
        - Knowledge
        - Base
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
        - Quick
        - Responses
        - Sessions
        - Assistant
        - Association
        - Content
        - Import
        - Jobs
        - Job
  /knowledgeBases/{knowledgeBaseId}/quickResponses/{quickResponseId}:
    POST:
      summary: UpdateQuickResponse
      description: <p>Updates an existing Wisdom quick response.</p>
      tags:
        - Update
        - Quick
        - Response
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
        - Quick
        - Responses
        - Sessions
        - Assistant
        - Association
        - Content
        - Import
        - Jobs
        - Job
        - Response
  /knowledgeBases/{knowledgeBaseId}/contents/{contentId}/summary:
    GET:
      summary: GetContentSummary
      description: <p>Retrieves summary information about the content.</p>
      tags:
        - Get
        - Content
        - Summary
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
        - Quick
        - Responses
        - Sessions
        - Assistant
        - Association
        - Content
        - Import
        - Jobs
        - Job
        - Response
        - Summary
  /assistants/{assistantId}/sessions/{sessionId}/recommendations:
    GET:
      summary: GetRecommendations
      description: >-
        <p>Retrieves recommendations for the specified session. To avoid
        retrieving the same recommendations in subsequent calls, use <a
        href="https://docs.aws.amazon.com/wisdom/latest/APIReference/API_NotifyRecommendationsReceived.html">NotifyRecommendationsReceived</a>.
        This API supports long-polling behavior with the
        <code>waitTimeSeconds</code> parameter. Short poll is the default
        behavior and only returns recommendations already available. To perform
        a manual query against an assistant, use <a
        href="https://docs.aws.amazon.com/wisdom/latest/APIReference/API_QueryAssistant.html">QueryAssistant</a>.</p>
      tags:
        - Get
        - Recommendations
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
        - Quick
        - Responses
        - Sessions
        - Assistant
        - Association
        - Content
        - Import
        - Jobs
        - Job
        - Response
        - Summary
        - Session
        - Recommendations
  /assistants/{assistantId}/sessions/{sessionId}:
    GET:
      summary: GetSession
      description: <p>Retrieves information for a specified session.</p>
      tags:
        - Get
        - Session
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
        - Quick
        - Responses
        - Sessions
        - Assistant
        - Association
        - Content
        - Import
        - Jobs
        - Job
        - Response
        - Summary
        - Session
        - Recommendations
  /knowledgeBases/{knowledgeBaseId}/importJobs:
    POST:
      summary: StartImportJob
      description: >-
        <p>Start an asynchronous job to import Wisdom resources from an uploaded
        source file. Before calling this API, use <a
        href="https://docs.aws.amazon.com/wisdom/latest/APIReference/API_StartContentUpload.html">StartContentUpload</a>
        to upload an asset that contains the resource data.</p> <ul> <li> <p>For
        importing Wisdom quick responses, you need to upload a csv file
        including the quick responses. For information about how to format the
        csv file for importing quick responses, see <a
        href="https://docs.aws.amazon.com/console/connect/quick-responses/add-data">Import
        quick responses</a>.</p> </li> </ul>
      tags:
        - Start
        - Import
        - Job
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
        - Quick
        - Responses
        - Sessions
        - Assistant
        - Association
        - Content
        - Import
        - Jobs
        - Job
        - Response
        - Summary
        - Session
        - Recommendations
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Removes the specified tags from the specified resource.</p>
      tags:
        - Untag
        - Resource
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
        - Quick
        - Responses
        - Sessions
        - Assistant
        - Association
        - Content
        - Import
        - Jobs
        - Job
        - Response
        - Summary
        - Session
        - Recommendations
        - Arn
  /assistants/{assistantId}/sessions/{sessionId}/recommendations/notify:
    POST:
      summary: NotifyRecommendationsReceived
      description: >-
        <p>Removes the specified recommendations from the specified assistant's
        queue of newly available recommendations. You can use this API in
        conjunction with <a
        href="https://docs.aws.amazon.com/wisdom/latest/APIReference/API_GetRecommendations.html">GetRecommendations</a>
        and a <code>waitTimeSeconds</code> input for long-polling behavior and
        avoiding duplicate recommendations.</p>
      tags:
        - Notify
        - Recommendations
        - Received
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
        - Quick
        - Responses
        - Sessions
        - Assistant
        - Association
        - Content
        - Import
        - Jobs
        - Job
        - Response
        - Summary
        - Session
        - Recommendations
        - Arn
        - Notify
  /assistants/{assistantId}/query:
    POST:
      summary: QueryAssistant
      description: >-
        <p>Performs a manual search against the specified assistant. To retrieve
        recommendations for an assistant, use <a
        href="https://docs.aws.amazon.com/wisdom/latest/APIReference/API_GetRecommendations.html">GetRecommendations</a>.
        </p>
      tags:
        - Query
        - Assistant
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
        - Quick
        - Responses
        - Sessions
        - Assistant
        - Association
        - Content
        - Import
        - Jobs
        - Job
        - Response
        - Summary
        - Session
        - Recommendations
        - Arn
        - Notify
        - Query
  /knowledgeBases/{knowledgeBaseId}/templateUri:
    POST:
      summary: UpdateKnowledgeBaseTemplateUri
      description: >-
        <p>Updates the template URI of a knowledge base. This is only supported
        for knowledge bases of type EXTERNAL. Include a single variable in
        <code>${variable}</code> format; this interpolated by Wisdom using
        ingested content. For example, if you ingest a Salesforce article, it
        has an <code>Id</code> value, and you can set the template URI to
        <code>https://myInstanceName.lightning.force.com/lightning/r/Knowledge__kav/*${Id}*/view</code>.
        </p>
      tags:
        - Update
        - Knowledge
        - Base
        - Template
        - Uri
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
        - Quick
        - Responses
        - Sessions
        - Assistant
        - Association
        - Content
        - Import
        - Jobs
        - Job
        - Response
        - Summary
        - Session
        - Recommendations
        - Arn
        - Notify
        - Query
        - Template
        - Uri
  /knowledgeBases/{knowledgeBaseId}/search:
    POST:
      summary: SearchContent
      description: >-
        <p>Searches for content in a specified knowledge base. Can be used to
        get a specific content resource by its name.</p>
      tags:
        - Search
        - Content
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
        - Quick
        - Responses
        - Sessions
        - Assistant
        - Association
        - Content
        - Import
        - Jobs
        - Job
        - Response
        - Summary
        - Session
        - Recommendations
        - Arn
        - Notify
        - Query
        - Template
        - Uri
        - Search
  /knowledgeBases/{knowledgeBaseId}/search/quickResponses:
    POST:
      summary: SearchQuickResponses
      description: >-
        <p>Searches existing Wisdom quick responses in a Wisdom knowledge
        base.</p>
      tags:
        - Search
        - Quick
        - Responses
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
        - Quick
        - Responses
        - Sessions
        - Assistant
        - Association
        - Content
        - Import
        - Jobs
        - Job
        - Response
        - Summary
        - Session
        - Recommendations
        - Arn
        - Notify
        - Query
        - Template
        - Uri
        - Search
  /assistants/{assistantId}/searchSessions:
    POST:
      summary: SearchSessions
      description: <p>Searches for sessions.</p>
      tags:
        - Search
        - Sessions
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
        - Quick
        - Responses
        - Sessions
        - Assistant
        - Association
        - Content
        - Import
        - Jobs
        - Job
        - Response
        - Summary
        - Session
        - Recommendations
        - Arn
        - Notify
        - Query
        - Template
        - Uri
        - Search
  /knowledgeBases/{knowledgeBaseId}/upload:
    POST:
      summary: StartContentUpload
      description: >-
        <p>Get a URL to upload content to a knowledge base. To upload content,
        first make a PUT request to the returned URL with your file, making sure
        to include the required headers. Then use <a
        href="https://docs.aws.amazon.com/wisdom/latest/APIReference/API_CreateContent.html">CreateContent</a>
        to finalize the content creation process or <a
        href="https://docs.aws.amazon.com/wisdom/latest/APIReference/API_UpdateContent.html">UpdateContent</a>
        to modify an existing resource. You can only upload content to a
        knowledge base of type C
      tags:
        - Start
        - Content
        - Upload
        - Assistants
        - Id
        - Associations
        - Bases
        - Knowledge
        - Base
        - Contents
        - Quick
        - Responses
        - Sessions
        - Assistant
        - Association
        - Content
        - Import
        - Jobs
        - Job
        - Response
        - Summary
        - Session
        - Recommendations
        - Arn
        - Notify
        - Query
        - Template
        - Uri
        - Search
        - Uplo
