openapi: 3.1.0
info:
  title: workspaces-thin-client
paths:
  /environments:
    GET:
      summary: ListEnvironments
      description: <p>Returns a list of environments.</p>
  /devices/{id}:
    PATCH:
      summary: UpdateDevice
      description: <p>Updates a thin client device.</p>
  /environments/{id}:
    PATCH:
      summary: UpdateEnvironment
      description: <p>Updates an environment.</p>
  /deregister-device/{id}:
    POST:
      summary: DeregisterDevice
      description: <p>Deregisters a thin client device.</p>
  /softwaresets/{id}:
    PATCH:
      summary: UpdateSoftwareSet
      description: <p>Updates a software set.</p>
  /devices:
    GET:
      summary: ListDevices
      description: <p>Returns a list of thin client devices.</p>
  /softwaresets:
    GET:
      summary: ListSoftwareSets
      description: <p>Returns a list of software sets.</p>
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Removes a tag or tags from a resou
