openapi: 3.1.0
info:
  title: Box Collections API
paths:
  /collections:
    get:
      summary: List all collections
      tags:
        - Collections
      description: |-
        Retrieves all collections for a given user.

        Currently, only the `favorites` collection
        is supported.
  /collections/{collection_id}/items:
    get:
      summary: List collection items
      tags:
        - Collections
      description: |-
        Retrieves the files and/or folders contained within
        this collectio
