openapi: 3.1.0
info:
  title: Box Enterprises API
paths:
  /enterprises/{enterprise_id}/device_pinners:
    get:
      summary: List enterprise device pins
      tags:
        - Device pinners
      description: |-
        Retrieves all the device pins within an enterprise.

        The user must have admin privileges, and the application
        needs the "manage enterprise" scope to make this cal
