openapi: 3.1.0
info:
  title: Box Group Memberships API
paths:
  /group_memberships:
    post:
      summary: Add user to group
      tags:
        - Group memberships
      description: |-
        Creates a group membership. Only users with
        admin-level permissions will be able to use this API.
  /group_memberships/{group_membership_id}:
    get:
      summary: Get group membership
      tags:
        - Group memberships
      description: |-
        Retrieves a specific group membership. Only admins of this
        group or users with admin-level permissions will be able to
        use this API.
    put:
      summary: Update group membership
      tags:
        - Group memberships
      description: |-
        Updates a user's group membership. Only admins of this
        group or users with admin-level permissions will be able to
        use this API.
    delete:
      summary: Remove user from group
      tags:
        - Group memberships
      description: |-
        Deletes a specific group membership. Only admins of this
        group or users with admin-level permissions will be able to
        use this AP
