openapi: 3.1.0
info:
  title: Box Integration Mappings API
paths:
  /integration_mappings/slack:
    get:
      summary: List Slack integration mappings
      tags:
        - Integration mappings
      description: >-
        Lists [Slack integration
        mappings](https://support.box.com/hc/en-us/articles/4415585987859-Box-as-the-Content-Layer-for-Slack)
        in a users' enterprise.


        You need Admin or Co-Admin role to

        use this endpoint.
    post:
      summary: Create Slack integration mapping
      tags:
        - Integration mappings
      description: >-
        Creates a [Slack integration
        mapping](https://support.box.com/hc/en-us/articles/4415585987859-Box-as-the-Content-Layer-for-Slack)

        by mapping a Slack channel to a Box item.


        You need Admin or Co-Admin role to

        use this endpoint.
  /integration_mappings/slack/{integration_mapping_id}:
    put:
      summary: Update Slack integration mapping
      tags:
        - Integration mappings
      description: >-
        Updates a [Slack integration
        mapping](https://support.box.com/hc/en-us/articles/4415585987859-Box-as-the-Content-Layer-for-Slack).

        Supports updating the Box folder ID and options.


        You need Admin or Co-Admin role to

        use this endpoint.
    delete:
      summary: Delete Slack integration mapping
      tags:
        - Integration mappings
      description: >-
        Deletes a [Slack integration
        mapping](https://support.box.com/hc/en-us/articles/4415585987859-Box-as-the-Content-Layer-for-Slack).



        You need Admin or Co-Admin role to

        use this endpoin
