openapi: 3.1.0
info:
  title: Box Invites API
paths:
  /invites:
    post:
      summary: Create user invite
      tags:
        - Invites
      description: |-
        Invites an existing external user to join an enterprise.

        The existing user can not be part of another enterprise and
        must already have a Box account. Once invited, the user will receive an
        email and are prompted to accept the invitation within the
        Box web application.

        This method requires the "Manage An Enterprise" scope enabled for
        the application, which can be enabled within the developer console.
  /invites/{invite_id}:
    get:
      summary: Get user invite status
      tags:
        - Invites
      description: Returns the status of a user invit
