openapi: 3.1.0
info:
  title: Box Retention Policies API
paths:
  /retention_policies:
    get:
      summary: List retention policies
      tags:
        - Retention policies
      description: Retrieves all of the retention policies for an enterprise.
    post:
      summary: Create retention policy
      tags:
        - Retention policies
      description: Creates a retention policy.
  /retention_policies/{retention_policy_id}:
    get:
      summary: Get retention policy
      tags:
        - Retention policies
      description: Retrieves a retention policy.
    put:
      summary: Update retention policy
      tags:
        - Retention policies
      description: Updates a retention policy.
    delete:
      summary: Delete retention policy
      tags:
        - Retention policies
      description: Permanently deletes a retention policy.
  /retention_policies/{retention_policy_id}/assignments:
    get:
      summary: List retention policy assignments
      tags:
        - Retention policy assignments
      description: >-
        Returns a list of all retention policy assignments associated with a
        specified

        retention polic
