openapi: 3.1.0
info:
  title: Box Shield Information Barrier Reports API
paths:
  /shield_information_barrier_reports:
    get:
      summary: List shield information barrier reports
      tags:
        - Shield information barrier reports
      description: Lists shield information barrier reports.
    post:
      summary: Create shield information barrier report
      tags:
        - Shield information barrier reports
      description: Creates a shield information barrier report for a given barrier.
  /shield_information_barrier_reports/{shield_information_barrier_report_id}:
    get:
      summary: Get shield information barrier report by ID
      tags:
        - Shield information barrier reports
      description: Retrieves a shield information barrier report by its I
