openapi: 3.1.0
info:
  title: Box Shield Information Barrier Segments API
paths:
  /shield_information_barrier_segments/{shield_information_barrier_segment_id}:
    get:
      summary: Get shield information barrier segment with specified ID
      tags:
        - Shield information barrier segments
      description: Retrieves shield information barrier segment based on provided ID..
    delete:
      summary: Delete shield information barrier segment
      tags:
        - Shield information barrier segments
      description: |-
        Deletes the shield information barrier segment
        based on provided ID.
    put:
      summary: Update shield information barrier segment with specified ID
      tags:
        - Shield information barrier segments
      description: Updates the shield information barrier segment based on provided ID..
  /shield_information_barrier_segments:
    get:
      summary: List shield information barrier segments
      tags:
        - Shield information barrier segments
      description: |-
        Retrieves a list of shield information barrier segment objects
        for the specified Information Barrier ID.
    post:
      summary: Create shield information barrier segment
      tags:
        - Shield information barrier segments
      description: Creates a shield information barrier segmen
