openapi: 3.1.0
info:
  title: Box Storage Policies API
paths:
  /storage_policies:
    get:
      summary: List storage policies
      tags:
        - Standard and Zones Storage Policies
      description: Fetches all the storage policies in the enterprise.
  /storage_policies/{storage_policy_id}:
    get:
      summary: Get storage policy
      tags:
        - Standard and Zones Storage Policies
      description: Fetches a specific storage polic
