openapi: 3.1.0
info:
  title: Box Terms Of Services API
paths:
  /terms_of_services:
    get:
      summary: List terms of services
      tags:
        - Terms of service
      description: |-
        Returns the current terms of service text and settings
        for the enterprise.
    post:
      tags:
        - Terms of service
      summary: Create terms of service
      description: |-
        Creates a terms of service for a given enterprise
        and type of user.
  /terms_of_services/{terms_of_service_id}:
    get:
      summary: Get terms of service
      tags:
        - Terms of service
      description: Fetches a specific terms of service.
    put:
      summary: Update terms of service
      tags:
        - Terms of service
      description: Updates a specific terms of servic
