openapi: 3.0.1
info:
  title: Twilio - Accounts
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: AccountsV1AuthTokenPromotion
  - name: AccountsV1Aws
  - name: AccountsV1PublicKey
  - name: AccountsV1Safelist
  - name: AccountsV1SecondaryAuthToken
x-maturity:
  - name: GA
    description: This product is Generally Available.
  - name: Beta
    description: >-
      PLEASE NOTE that this is a Beta product that is subject to change. Use it
      with caution.
paths:
  /v1/AuthTokens/Promote:
    description: Auth Token promotion
    post:
      description: >-
        Promote the secondary Auth Token to primary. After promoting the new
        token, all requests to Twilio using your old primary Auth Token will
        result in an error.
      tags:
        - AccountsV1AuthTokenPromotion
  /v1/Credentials:
    description: 'TODO: Resource-level docs'
  /v1/Credentials/AWS:
    description: User provided AWS keys
    get:
      description: >-
        Retrieves a collection of AWS Credentials belonging to the account used
        to make the request
      tags:
        - AccountsV1Aws
    post:
      description: Create a new AWS Credential
      tags:
        - AccountsV1Aws
  /v1/Credentials/AWS/{Sid}:
    description: User provided AWS keys
    get:
      description: Fetch the AWS credentials specified by the provided Credential Sid
      tags:
        - AccountsV1Aws
    post:
      description: Modify the properties of a given Account
      tags:
        - AccountsV1Aws
    delete:
      description: Delete a Credential from your account
      tags:
        - AccountsV1Aws
  /v1/Credentials/PublicKeys:
    description: User provided public keys
    get:
      description: >-
        Retrieves a collection of Public Key Credentials belonging to the
        account used to make the request
      tags:
        - AccountsV1PublicKey
    post:
      description: Create a new Public Key Credential
      tags:
        - AccountsV1PublicKey
  /v1/Credentials/PublicKeys/{Sid}:
    description: User provided public keys
    get:
      description: Fetch the public key specified by the provided Credential Sid
      tags:
        - AccountsV1PublicKey
    post:
      description: Modify the properties of a given Account
      tags:
        - AccountsV1PublicKey
    delete:
      description: Delete a Credential from your account
      tags:
        - AccountsV1PublicKey
  /v1/SafeList/Numbers:
    description: 'TODO: Resource-level docs'
    post:
      description: Add a new phone number to SafeList.
      tags:
        - AccountsV1Safelist
    get:
      description: Check if a phone number exists in SafeList.
      tags:
        - AccountsV1Safelist
    delete:
      description: Remove a phone number from SafeList.
      tags:
        - AccountsV1Safelist
  /v1/AuthTokens/Secondary:
    description: Secondary Auth Token
    post:
      description: Create a new secondary Auth Token
      tags:
        - AccountsV1SecondaryAuthToken
    delete:
      description: Delete the secondary Auth Token from your account
      tags:
        - AccountsV1SecondaryA
