info:
  title: Assistants
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /understand/Assistants/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
    post:
      description: ''
      tags:
        - Assistants
    delete:
      description: ''
      tags:
        - Assistants
  /understand/Assistants/{AssistantSid}/FallbackActions:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Actions
    post:
      description: ''
      tags:
        - Actions
  /understand/Assistants/{AssistantSid}/InitiationActions:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Actions
    post:
      description: ''
      tags:
        - Actions
  /understand/Assistants/{AssistantSid}/Dialogues/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - PreviewUnderstandDialogue
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Fields/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - PreviewUnderstandField
    delete:
      description: ''
      tags:
        - PreviewUnderstandField
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Fields:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - PreviewUnderstandField
    post:
      description: ''
      tags:
        - PreviewUnderstandField
  /understand/Assistants/{AssistantSid}/FieldTypes/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - PreviewUnderstandFieldType
    post:
      description: ''
      tags:
        - PreviewUnderstandFieldType
    delete:
      description: ''
      tags:
        - PreviewUnderstandFieldType
  /understand/Assistants/{AssistantSid}/FieldTypes:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - PreviewUnderstandFieldType
    post:
      description: ''
      tags:
        - PreviewUnderstandFieldType
  /understand/Assistants/{AssistantSid}/FieldTypes/{FieldTypeSid}/FieldValues/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - PreviewUnderstandFieldValue
    delete:
      description: ''
      tags:
        - PreviewUnderstandFieldValue
  /understand/Assistants/{AssistantSid}/FieldTypes/{FieldTypeSid}/FieldValues:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - PreviewUnderstandFieldValue
    post:
      description: ''
      tags:
        - PreviewUnderstandFieldValue
  /understand/Assistants/{AssistantSid}/ModelBuilds/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - PreviewUnderstandModelBuild
    post:
      description: ''
      tags:
        - PreviewUnderstandModelBuild
    delete:
      description: ''
      tags:
        - PreviewUnderstandModelBuild
  /understand/Assistants/{AssistantSid}/ModelBuilds:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - PreviewUnderstandModelBuild
    post:
      description: ''
      tags:
        - PreviewUnderstandModelBuild
  /understand/Assistants/{AssistantSid}/Queries/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - PreviewUnderstandQuery
    post:
      description: ''
      tags:
        - PreviewUnderstandQuery
    delete:
      description: ''
      tags:
        - PreviewUnderstandQuery
  /understand/Assistants/{AssistantSid}/Queries:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - PreviewUnderstandQuery
    post:
      description: ''
      tags:
        - PreviewUnderstandQuery
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Samples/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - PreviewUnderstandSample
    post:
      description: ''
      tags:
        - PreviewUnderstandSample
    delete:
      description: ''
      tags:
        - PreviewUnderstandSample
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Samples:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - PreviewUnderstandSample
    post:
      description: ''
      tags:
        - PreviewUnderstandSample
  /understand/Assistants/{AssistantSid}/StyleSheet:
    description: 'TODO: Resource-level docs'
    get:
      description: Returns Style sheet JSON object for this Assistant
      tags:
        - PreviewUnderstandStyleSheet
    post:
      description: >-
        Updates the style sheet for an assistant identified by {AssistantSid} or
        {AssistantUniqueName}.
      tags:
        - PreviewUnderstandStyleSheet
  /understand/Assistants/{AssistantSid}/Tasks/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - PreviewUnderstandTask
    post:
      description: ''
      tags:
        - PreviewUnderstandTask
    delete:
      description: ''
      tags:
        - PreviewUnderstandTask
  /understand/Assistants/{AssistantSid}/Tasks:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - PreviewUnderstandTask
    post:
      description: ''
      tags:
        - PreviewUnderstandTask
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Actions:
    description: 'TODO: Resource-level docs'
    get:
      description: Returns JSON actions for this Task.
      tags:
        - PreviewUnderstandTaskActions
    post:
      description: >-
        Updates the actions of an Task identified by {TaskSid} or
        {TaskUniqueName}.
      tags:
        - PreviewUnderstandTaskActions
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Statistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - PreviewUnderstandTaskStatistics
tags:
  - name: PreviewDeployedDevicesCertificate
  - name: PreviewDeployedDevicesDeployment
  - name: PreviewDeployedDevicesDevice
  - name: PreviewDeployedDevicesFleet
  - name: PreviewDeployedDevicesKey
  - name: PreviewHostedNumbersAuthorizationDocument
  - name: PreviewHostedNumbersDependentHostedNumberOrder
  - name: PreviewHostedNumbersHostedNumberOrder
  - null
  - null
  - null
  - null
  - name: PreviewSyncDocument
  - name: PreviewSyncDocumentPermission
  - name: PreviewSyncService
  - name: PreviewSyncSyncList
  - name: PreviewSyncSyncListItem
  - name: PreviewSyncSyncListPermission
  - name: PreviewSyncSyncMap
  - name: PreviewSyncSyncMapItem
  - name: PreviewSyncSyncMapPermission
  - name: Assistants
  - name: Actions
  - name: Actions
  - name: PreviewUnderstandDialogue
  - name: PreviewUnderstandField
  - name: PreviewUnderstandFieldType
  - name: PreviewUnderstandFieldValue
  - name: PreviewUnderstandModelBuild
  - name: PreviewUnderstandQuery
  - name: PreviewUnderstandSample
  - name: PreviewUnderstandStyleSheet
  - name: PreviewUnderstandTask
  - name: PreviewUnderstandTaskActions
  - name: PreviewUnderstandTaskStatistics
  - name: PreviewWirelessCommand
  - name: PreviewWirelessRatePlan
  - name: PreviewWirelessSim
  - name: PreviewWirelessUsage
x-maturity:
  - name: Preview
    description: >-
      PLEASE NOTE that this is a Preview product that is subject to change. Use
      it with caution. If you currently do not have developer preview access,
      please contact https://www.twilio.com/help/
