info:
  title: Twilio - Autopilot
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Assistants/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - AutopilotV1Assistant
    post:
      description: ''
      tags:
        - AutopilotV1Assistant
    delete:
      description: ''
      tags:
        - AutopilotV1Assistant
  /v1/Assistants:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - AutopilotV1Assistant
    post:
      description: ''
      tags:
        - AutopilotV1Assistant
  /v1/Assistants/{AssistantSid}/Defaults:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - AutopilotV1Defaults
    post:
      description: ''
      tags:
        - AutopilotV1Defaults
  /v1/Assistants/{AssistantSid}/Dialogues/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - AutopilotV1Dialogue
  /v1/Assistants/{AssistantSid}/Dialogues:
    description: 'TODO: Resource-level docs'
  /v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Fields/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - AutopilotV1Field
    delete:
      description: ''
      tags:
        - AutopilotV1Field
  /v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Fields:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - AutopilotV1Field
    post:
      description: ''
      tags:
        - AutopilotV1Field
  /v1/Assistants/{AssistantSid}/FieldTypes/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - AutopilotV1FieldType
    post:
      description: ''
      tags:
        - AutopilotV1FieldType
    delete:
      description: ''
      tags:
        - AutopilotV1FieldType
  /v1/Assistants/{AssistantSid}/FieldTypes:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - AutopilotV1FieldType
    post:
      description: ''
      tags:
        - AutopilotV1FieldType
  /v1/Assistants/{AssistantSid}/FieldTypes/{FieldTypeSid}/FieldValues/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - AutopilotV1FieldValue
    delete:
      description: ''
      tags:
        - AutopilotV1FieldValue
  /v1/Assistants/{AssistantSid}/FieldTypes/{FieldTypeSid}/FieldValues:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - AutopilotV1FieldValue
    post:
      description: ''
      tags:
        - AutopilotV1FieldValue
  /v1/Assistants/{AssistantSid}/ModelBuilds/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - AutopilotV1ModelBuild
    post:
      description: ''
      tags:
        - AutopilotV1ModelBuild
    delete:
      description: ''
      tags:
        - AutopilotV1ModelBuild
  /v1/Assistants/{AssistantSid}/ModelBuilds:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - AutopilotV1ModelBuild
    post:
      description: ''
      tags:
        - AutopilotV1ModelBuild
  /v1/Assistants/{AssistantSid}/Queries/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - AutopilotV1Query
    post:
      description: ''
      tags:
        - AutopilotV1Query
    delete:
      description: ''
      tags:
        - AutopilotV1Query
  /v1/Assistants/{AssistantSid}/Queries:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - AutopilotV1Query
    post:
      description: ''
      tags:
        - AutopilotV1Query
  /v1/Assistants/Restore:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - AutopilotV1RestoreAssistant
  /v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Samples/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - AutopilotV1Sample
    post:
      description: ''
      tags:
        - AutopilotV1Sample
    delete:
      description: ''
      tags:
        - AutopilotV1Sample
  /v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Samples:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - AutopilotV1Sample
    post:
      description: ''
      tags:
        - AutopilotV1Sample
  /v1/Assistants/{AssistantSid}/StyleSheet:
    description: 'TODO: Resource-level docs'
    get:
      description: Returns Style sheet JSON object for the Assistant
      tags:
        - AutopilotV1StyleSheet
    post:
      description: Updates the style sheet for an Assistant identified by `assistant_sid`.
      tags:
        - AutopilotV1StyleSheet
  /v1/Assistants/{AssistantSid}/Tasks/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - AutopilotV1Task
    post:
      description: ''
      tags:
        - AutopilotV1Task
    delete:
      description: ''
      tags:
        - AutopilotV1Task
  /v1/Assistants/{AssistantSid}/Tasks:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - AutopilotV1Task
    post:
      description: ''
      tags:
        - AutopilotV1Task
  /v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Actions:
    description: 'TODO: Resource-level docs'
    get:
      description: Returns JSON actions for the Task.
      tags:
        - AutopilotV1TaskActions
    post:
      description: >-
        Updates the actions of an Task identified by {TaskSid} or
        {TaskUniqueName}.
      tags:
        - AutopilotV1TaskActions
  /v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Statistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - AutopilotV1TaskStatistics
  /v1/Assistants/{AssistantSid}/Webhooks/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - AutopilotV1Webhook
    post:
      description: ''
      tags:
        - AutopilotV1Webhook
    delete:
      description: ''
      tags:
        - AutopilotV1Webhook
  /v1/Assistants/{AssistantSid}/Webhooks:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - AutopilotV1Webhook
    post:
      description: ''
      tags:
        - AutopilotV1Webhook
tags:
  - name: AutopilotV1Assistant
  - name: AutopilotV1Defaults
  - name: AutopilotV1Dialogue
  - name: AutopilotV1Field
  - name: AutopilotV1FieldType
  - name: AutopilotV1FieldValue
  - name: AutopilotV1ModelBuild
  - name: AutopilotV1Query
  - name: AutopilotV1RestoreAssistant
  - name: AutopilotV1Sample
  - name: AutopilotV1StyleSheet
  - name: AutopilotV1Task
  - name: AutopilotV1TaskActions
  - name: AutopilotV1TaskStatistics
  - name: AutopilotV1Webhook
x-maturity:
  - name: Preview
    description: >-
      PLEASE NOTE that this is a Preview product that is subject to change. Use
      it with caution. If you currently do not have developer preview access,
      please contact https://www.twilio.com/help/
