info:
  title: Twilio Frontline API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Users/{Sid}:
    description: A User resource represents a frontline user.
    get:
      description: Fetch a frontline user
      tags:
        - Retrieve
        - User
        - Users
        - Sid
      summary: Retrieve User
    post:
      description: Update an existing frontline user
      tags:
        - Update
        - User
        - Users
        - Sid
      summary: Update User
tags:
  - name: Frontline
    description: Needs a description.
  - name: Sales
    description: Needs a description.
  - name: ' Relationships'
    description: Needs a description.
  - name: ' Users'
    description: Needs a description.
x-maturity:
  - name: Beta
    description: >-
      PLEASE NOTE that this is a Beta product that is subject to change. Use it
      with ca
