info:
  title: Twilio Insights API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Voice/Settings:
    description: 'TODO: Resource-level docs'
    get:
      description: Get the Voice Insights Settings.
      tags:
        - Retrieve
        - Voice
        - Settings
        - Voice
        - Settings
      summary: Retrieve Voice Settings
    post:
      description: Update a specific Voice Insights Setting.
      tags:
        - Update
        - Voice
        - Settings
        - Voice
        - Settings
      summary: Update Voice Settings
  /v1/Voice/{CallSid}/Annotation:
    description: 'TODO: Resource-level docs'
    post:
      description: Update an Annotation for a specific Call.
      tags:
        - Update
        - Voice
        - Annotation
        - Voice
        - Settings
        - Call
        - Sid
        - Annotation
      summary: Update Voice Annotation
    get:
      description: Get the Annotation for a specific Call.
      tags:
        - Retrieve
        - Voice
        - Annotation
        - Voice
        - Settings
        - Call
        - Sid
        - Annotation
      summary: Retrieve Voice Annotation
  /v1/Voice/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Retrieve
        - Voice
        - Voice
        - Settings
        - Call
        - Sid
        - Annotation
      summary: Retrieve Voice
  /v1/Voice/Summaries:
    description: 'TODO: Resource-level docs'
    get:
      description: Get a list of Call Summaries.
      tags:
        - Retrieve
        - Voice
        - Summaries
        - Voice
        - Settings
        - Call
        - Sid
        - Annotation
        - Summaries
      summary: Retrieve Voice Summaries
  /v1/Conferences/{ConferenceSid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Get a specific Conference Summary.
      tags:
        - Retrieve
        - Conference
        - Voice
        - Settings
        - Call
        - Sid
        - Annotation
        - Summaries
        - Conferences
        - Conference
      summary: Retrieve Conference
  /v1/Conferences:
    description: 'TODO: Resource-level docs'
    get:
      description: Get a list of Conference Summaries.
      tags:
        - Retrieve
        - Conferences
        - Voice
        - Settings
        - Call
        - Sid
        - Annotation
        - Summaries
        - Conferences
        - Conference
      summary: Retrieve Conferences
  /v1/Conferences/{ConferenceSid}/Participants/{ParticipantSid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Get a specific Conference Participant Summary for a Conference.
      tags:
        - Retrieve
        - Conference
        - Participant
        - Voice
        - Settings
        - Call
        - Sid
        - Annotation
        - Summaries
        - Conferences
        - Conference
        - Participants
        - Participant
      summary: Retrieve Conference Participant
  /v1/Conferences/{ConferenceSid}/Participants:
    description: 'TODO: Resource-level docs'
    get:
      description: Get a list of Conference Participants Summaries for a Conference.
      tags:
        - Retrieve
        - Conference
        - Participants
        - Voice
        - Settings
        - Call
        - Sid
        - Annotation
        - Summaries
        - Conferences
        - Conference
        - Participants
        - Participant
      summary: Retrieve Conference Participants
  /v1/Voice/{CallSid}/Events:
    description: 'TODO: Resource-level docs'
    get:
      description: Get a list of Call Insight Events for a Call.
      tags:
        - Retrieve
        - Voice
        - Events
        - Voice
        - Settings
        - Call
        - Sid
        - Annotation
        - Summaries
        - Conferences
        - Conference
        - Participants
        - Participant
        - Events
      summary: Retrieve Voice Events
  /v1/Voice/{CallSid}/Metrics:
    description: 'TODO: Resource-level docs'
    get:
      description: Get a list of Call Metrics for a Call.
      tags:
        - Retrieve
        - Voice
        - Metrics
        - Voice
        - Settings
        - Call
        - Sid
        - Annotation
        - Summaries
        - Conferences
        - Conference
        - Participants
        - Participant
        - Events
        - Metrics
      summary: Retrieve Voice Metrics
  /v1/Voice/{CallSid}/Summary:
    description: 'TODO: Resource-level docs'
    get:
      description: Get a specific Call Summary.
      tags:
        - Retrieve
        - Voice
        - Summary
        - Voice
        - Settings
        - Call
        - Sid
        - Annotation
        - Summaries
        - Conferences
        - Conference
        - Participants
        - Participant
        - Events
        - Metrics
        - Summary
      summary: Retrieve Voice Summary
  /v1/Video/Rooms/{RoomSid}/Participants/{ParticipantSid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Get Video Log Analyzer data for a Room Participant.
      tags:
        - Retrieve
        - Video
        - Room
        - Participant
        - Voice
        - Settings
        - Call
        - Sid
        - Annotation
        - Summaries
        - Conferences
        - Conference
        - Participants
        - Participant
        - Events
        - Metrics
        - Summary
        - Video
        - Rooms
        - Room
      summary: Retrieve Video Room Participant
  /v1/Video/Rooms/{RoomSid}/Participants:
    description: 'TODO: Resource-level docs'
    get:
      description: Get a list of room participants.
      tags:
        - Retrieve
        - Video
        - Room
        - Participants
        - Voice
        - Settings
        - Call
        - Sid
        - Annotation
        - Summaries
        - Conferences
        - Conference
        - Participants
        - Participant
        - Events
        - Metrics
        - Summary
        - Video
        - Rooms
        - Room
      summary: Retrieve Video Room Participants
  /v1/Video/Rooms/{RoomSid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Get Video Log Analyzer data for a Room.
      tags:
        - Retrieve
        - Video
        - Room
        - Voice
        - Settings
        - Call
        - Sid
        - Annotation
        - Summaries
        - Conferences
        - Conference
        - Participants
        - Participant
        - Events
        - Metrics
        - Summary
        - Video
        - Rooms
        - Room
      summary: Retrieve Video Room
  /v1/Video/Rooms:
    description: 'TODO: Resource-level docs'
    get:
      description: Get a list of Programmable Video Rooms.
      tags:
        - Retrieve
        - Video
        - Rooms
        - Voice
        - Settings
        - Call
        - Sid
        - Annotation
        - Summaries
        - Conferences
        - Conference
        - Participants
        - Participant
        - Events
        - Metrics
        - Summary
        - Video
        - Rooms
        - Room
      summary: Retrieve Video Rooms
tags:
  - name: Insights
    description: Needs a description.
  - name: Voice
    description: Needs a description.
  - name: Settings
    description: Needs a description.
  - name: Annotations
    description: Needs a description.
  - name: Summaries
    description: Needs a description.
  - name: Conferences
    description: Needs a description.
  - name: Participants
    description: Needs a description.
  - name: Events
    description: Needs a description.
  - name: Metrics
    description: Needs a description.
  - name: Videos
    description: Needs a description.
  - name: Rooms
    description: Needs a description.
  - name: Retrieve
    description: Needs a description.
  - name: Retriev
    description: Needs a description.
x-maturity:
  - name: GA
    description: This product is Generally Available.
  - name: Beta
    description: >-
      PLEASE NOTE that this is a Beta product that is subject to change. Use it
      with caution.
  - name: Preview
    description: >-
      PLEASE NOTE that this is a Preview product that is subject to change. Use
      it with caution. If you currently do not have developer preview access,
      please contact https://www.twilio.com/help/co
