info:
  title: Twilio - Intelligence
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v2/Transcripts/{Sid}/Media:
    description: 'TODO: Resource-level docs'
    get:
      description: Get download URLs for media if possible
      tags:
        - IntelligenceV2Media
  /v2/Transcripts/{TranscriptSid}/OperatorResults:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of Operator Results for the given Transcript.
      tags:
        - IntelligenceV2OperatorResult
  /v2/Transcripts/{TranscriptSid}/OperatorResults/{OperatorSid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Operator Result for the given Transcript.
      tags:
        - IntelligenceV2OperatorResult
  /v2/Transcripts/{TranscriptSid}/Sentences:
    description: 'TODO: Resource-level docs'
    get:
      description: Get all Transcript Sentences by TranscriptSid
      tags:
        - IntelligenceV2Sentence
  /v2/Services:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Service for the given Account
      tags:
        - IntelligenceV2Service
    get:
      description: Retrieves a list of all Services for an account.
      tags:
        - IntelligenceV2Service
  /v2/Services/{Sid}:
    description: 'TODO: Resource-level docs'
    delete:
      description: Delete a specific Service.
      tags:
        - IntelligenceV2Service
    get:
      description: Fetch a specific Service.
      tags:
        - IntelligenceV2Service
    post:
      description: Update a specific Service.
      tags:
        - IntelligenceV2Service
  /v2/Transcripts:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Transcript for the service
      tags:
        - IntelligenceV2Transcript
    get:
      description: Retrieve a list of Transcripts for a given service.
      tags:
        - IntelligenceV2Transcript
  /v2/Transcripts/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Transcript.
      tags:
        - IntelligenceV2Transcript
    delete:
      description: Delete a specific Transcript.
      tags:
        - IntelligenceV2Transcript
tags:
  - name: IntelligenceV2Media
  - name: IntelligenceV2OperatorResult
  - name: IntelligenceV2Sentence
  - name: IntelligenceV2Service
  - name: IntelligenceV2Transcript
x-maturity:
  - name: Beta
    description: >-
      PLEASE NOTE that this is a Beta product that is subject to change. Use it
      with 
