info:
  title: Twilio - Ip_messaging
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v2/Services/{ServiceSid}/Bindings:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IpMessagingV2Binding
  /v2/Services/{ServiceSid}/Bindings/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IpMessagingV2Binding
    delete:
      description: ''
      tags:
        - IpMessagingV2Binding
  /v2/Services/{ServiceSid}/Channels/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IpMessagingV2Channel
    delete:
      description: ''
      tags:
        - IpMessagingV2Channel
    post:
      description: ''
      tags:
        - IpMessagingV2Channel
  /v2/Services/{ServiceSid}/Channels:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - IpMessagingV2Channel
    get:
      description: ''
      tags:
        - IpMessagingV2Channel
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Webhooks:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IpMessagingV2Webhook
    post:
      description: ''
      tags:
        - IpMessagingV2Webhook
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Webhooks/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IpMessagingV2Webhook
    post:
      description: ''
      tags:
        - IpMessagingV2Webhook
    delete:
      description: ''
      tags:
        - IpMessagingV2Webhook
  /v2/Credentials:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IpMessagingV2Credential
    post:
      description: ''
      tags:
        - IpMessagingV2Credential
  /v2/Credentials/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IpMessagingV2Credential
    post:
      description: ''
      tags:
        - IpMessagingV2Credential
    delete:
      description: ''
      tags:
        - IpMessagingV2Credential
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Invites/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IpMessagingV2Invite
    delete:
      description: ''
      tags:
        - IpMessagingV2Invite
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Invites:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - IpMessagingV2Invite
    get:
      description: ''
      tags:
        - IpMessagingV2Invite
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Members/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IpMessagingV2Member
    delete:
      description: ''
      tags:
        - IpMessagingV2Member
    post:
      description: ''
      tags:
        - IpMessagingV2Member
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Members:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - IpMessagingV2Member
    get:
      description: ''
      tags:
        - IpMessagingV2Member
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Messages/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IpMessagingV2Message
    delete:
      description: ''
      tags:
        - IpMessagingV2Message
    post:
      description: ''
      tags:
        - IpMessagingV2Message
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Messages:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - IpMessagingV2Message
    get:
      description: ''
      tags:
        - IpMessagingV2Message
  /v2/Services/{ServiceSid}/Roles/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IpMessagingV2Role
    delete:
      description: ''
      tags:
        - IpMessagingV2Role
    post:
      description: ''
      tags:
        - IpMessagingV2Role
  /v2/Services/{ServiceSid}/Roles:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - IpMessagingV2Role
    get:
      description: ''
      tags:
        - IpMessagingV2Role
  /v2/Services/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IpMessagingV2Service
    delete:
      description: ''
      tags:
        - IpMessagingV2Service
    post:
      description: ''
      tags:
        - IpMessagingV2Service
  /v2/Services:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - IpMessagingV2Service
    get:
      description: ''
      tags:
        - IpMessagingV2Service
  /v2/Services/{ServiceSid}/Users/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IpMessagingV2User
    delete:
      description: ''
      tags:
        - IpMessagingV2User
    post:
      description: ''
      tags:
        - IpMessagingV2User
  /v2/Services/{ServiceSid}/Users:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - IpMessagingV2User
    get:
      description: ''
      tags:
        - IpMessagingV2User
  /v2/Services/{ServiceSid}/Users/{UserSid}/Bindings:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IpMessagingV2UserBinding
  /v2/Services/{ServiceSid}/Users/{UserSid}/Bindings/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IpMessagingV2UserBinding
    delete:
      description: ''
      tags:
        - IpMessagingV2UserBinding
  /v2/Services/{ServiceSid}/Users/{UserSid}/Channels:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IpMessagingV2UserChannel
  /v2/Services/{ServiceSid}/Users/{UserSid}/Channels/{ChannelSid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - IpMessagingV2UserChannel
    delete:
      description: ''
      tags:
        - IpMessagingV2UserChannel
    post:
      description: ''
      tags:
        - IpMessagingV2UserChannel
tags:
  - name: IpMessagingV2Binding
  - name: IpMessagingV2Channel
  - name: IpMessagingV2Credential
  - name: IpMessagingV2Invite
  - name: IpMessagingV2Member
  - name: IpMessagingV2Message
  - name: IpMessagingV2Role
  - name: IpMessagingV2Service
  - name: IpMessagingV2User
  - name: IpMessagingV2UserBinding
  - name: IpMessagingV2UserChannel
  - name: IpMessagingV2Webhook
x-maturity:
  - name: GA
    description: This product is Generally Av
