info:
  title: Marketplace API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /marketplace/AvailableAddOns/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch an instance of an Add-on currently available to be installed.
      tags:
        - PreviewMarketplaceAvailableAddOn
  /marketplace/AvailableAddOns:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of Add-ons currently available to be installed.
      tags:
        - PreviewMarketplaceAvailableAddOn
  /marketplace/AvailableAddOns/{AvailableAddOnSid}/Extensions/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch an instance of an Extension for the Available Add-on.
      tags:
        - PreviewMarketplaceAvailableAddOnExtension
  /marketplace/AvailableAddOns/{AvailableAddOnSid}/Extensions:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of Extensions for the Available Add-on.
      tags:
        - PreviewMarketplaceAvailableAddOnExtension
  /marketplace/InstalledAddOns:
    description: 'TODO: Resource-level docs'
    post:
      description: Install an Add-on for the Account specified.
      tags:
        - PreviewMarketplaceInstalledAddOn
    get:
      description: Retrieve a list of Add-ons currently installed on this Account.
      tags:
        - PreviewMarketplaceInstalledAddOn
  /marketplace/InstalledAddOns/{Sid}:
    description: 'TODO: Resource-level docs'
    delete:
      description: Remove an Add-on installation from your account
      tags:
        - PreviewMarketplaceInstalledAddOn
    get:
      description: Fetch an instance of an Add-on currently installed on this Account.
      tags:
        - PreviewMarketplaceInstalledAddOn
    post:
      description: Update an Add-on installation for the Account specified.
      tags:
        - PreviewMarketplaceInstalledAddOn
  /marketplace/InstalledAddOns/{InstalledAddOnSid}/Extensions/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch an instance of an Extension for the Installed Add-on.
      tags:
        - PreviewMarketplaceInstalledAddOnExtension
    post:
      description: Update an Extension for an Add-on installation.
      tags:
        - PreviewMarketplaceInstalledAddOnExtension
  /marketplace/InstalledAddOns/{InstalledAddOnSid}/Extensions:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of Extensions for the Installed Add-on.
      tags:
        - PreviewMarketplaceInstalledAddOnExtension
tags:
  - null
  - null
  - null
  - null
x-maturity:
  - name: Preview
    description: >-
      PLEASE NOTE that this is a Preview product that is subject to change. Use
      it with caution. If you currently do not have developer preview access,
      please contact https://www.twilio.com/help/c
