info:
  title: Twilio - Microvisor
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Configs:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Configs for an Account.
      tags:
        - MicrovisorV1AccountConfig
    post:
      description: Create a config for an Account.
      tags:
        - MicrovisorV1AccountConfig
  /v1/Configs/{Key}:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a Config for an Account.
      tags:
        - MicrovisorV1AccountConfig
    post:
      description: Update a config for an Account.
      tags:
        - MicrovisorV1AccountConfig
    delete:
      description: Delete a config for an Account.
      tags:
        - MicrovisorV1AccountConfig
  /v1/Secrets:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Secrets for an Account.
      tags:
        - MicrovisorV1AccountSecret
    post:
      description: Create a secret for an Account.
      tags:
        - MicrovisorV1AccountSecret
  /v1/Secrets/{Key}:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a Secret for an Account.
      tags:
        - MicrovisorV1AccountSecret
    post:
      description: Update a secret for an Account.
      tags:
        - MicrovisorV1AccountSecret
    delete:
      description: Delete a secret for an Account.
      tags:
        - MicrovisorV1AccountSecret
  /v1/Apps:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Apps for an Account.
      tags:
        - MicrovisorV1App
  /v1/Apps/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific App.
      tags:
        - MicrovisorV1App
    delete:
      description: Delete a specific App.
      tags:
        - MicrovisorV1App
  /v1/Apps/{AppSid}/Manifest:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve the Manifest for an App.
      tags:
        - MicrovisorV1AppManifest
  /v1/Devices:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Devices registered with the Account.
      tags:
        - MicrovisorV1Device
  /v1/Devices/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Device.
      tags:
        - MicrovisorV1Device
    post:
      description: Update a specific Device.
      tags:
        - MicrovisorV1Device
  /v1/Devices/{DeviceSid}/Configs:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Configs for a Device.
      tags:
        - MicrovisorV1DeviceConfig
    post:
      description: Create a config for a Microvisor Device.
      tags:
        - MicrovisorV1DeviceConfig
  /v1/Devices/{DeviceSid}/Configs/{Key}:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a Config for a Device.
      tags:
        - MicrovisorV1DeviceConfig
    post:
      description: Update a config for a Microvisor Device.
      tags:
        - MicrovisorV1DeviceConfig
    delete:
      description: Delete a config for a Microvisor Device.
      tags:
        - MicrovisorV1DeviceConfig
  /v1/Devices/{DeviceSid}/Secrets:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Secrets for a Device.
      tags:
        - MicrovisorV1DeviceSecret
    post:
      description: Create a secret for a Microvisor Device.
      tags:
        - MicrovisorV1DeviceSecret
  /v1/Devices/{DeviceSid}/Secrets/{Key}:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a Secret for a Device.
      tags:
        - MicrovisorV1DeviceSecret
    post:
      description: Update a secret for a Microvisor Device.
      tags:
        - MicrovisorV1DeviceSecret
    delete:
      description: Delete a secret for a Microvisor Device.
      tags:
        - MicrovisorV1DeviceSecret
tags:
  - name: MicrovisorV1AccountConfig
  - name: MicrovisorV1AccountSecret
  - name: MicrovisorV1App
  - name: MicrovisorV1AppManifest
  - name: MicrovisorV1Device
  - name: MicrovisorV1DeviceConfig
  - name: MicrovisorV1DeviceSecret
x-maturity:
  - name: Preview
    description: >-
      PLEASE NOTE that this is a Preview product that is subject to change. Use
      it with caution. If you currently do not have developer preview access,
      please contact https://www.twilio.com/help/
