info:
  title: Twilio Monitor API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Alerts/{Sid}:
    description: Debugger alerts
    get:
      description: ''
      tags:
        - Retrieve
        - Alert
        - Alerts
        - Sid
      summary: Retrieve Alert
  /v1/Alerts:
    description: Debugger alerts
    get:
      description: ''
      tags:
        - Retrieve
        - Alerts
        - Alerts
        - Sid
      summary: Retrieve Alerts
  /v1/Events/{Sid}:
    description: Debugger events
    get:
      description: ''
      tags:
        - Retrieve
        - Event
        - Alerts
        - Sid
        - Events
      summary: Retrieve Event
  /v1/Events:
    description: Debugger events
    get:
      description: Returns a list of events in the account, sorted by event-date.
      tags:
        - Retrieve
        - Events
        - Alerts
        - Sid
        - Events
      summary: Retrieve Events
tags:
  - name: Tag
  - name: Monitors
    description: Needs a description.
  - name: Alerts
    description: Needs a description.
  - name: Events
    description: Needs a description.
x-maturity:
  - name: GA
    description: This product is Generally Avai
