info:
  title: Twilio Notify API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Services/{ServiceSid}/Bindings/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Notifications
        - Services
        - Bindings
      summary: Retrieve Service Binding
    delete:
      description: ''
      tags:
        - Notifications
        - Services
        - Bindings
      summary: Delete Service Binding
  /v1/Services/{ServiceSid}/Bindings:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Notifications
        - Services
        - Bindings
      summary: Create Service Binding
    get:
      description: ''
      tags:
        - Notifications
        - Services
        - Bindings
      summary: Retrieve Service Bindings
  /v1/Credentials:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Notifications
        - Credentials
      summary: Retrieve Credentials
    post:
      description: ''
      tags:
        - Notifications
        - Credentials
      summary: Create Credential
  /v1/Credentials/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Notifications
        - Credentials
      summary: Retrieve Credential
    post:
      description: ''
      tags:
        - Notifications
        - Credentials
      summary: Update Credential
    delete:
      description: ''
      tags:
        - Notifications
        - Credentials
      summary: Delete Credential
  /v1/Services/{ServiceSid}/Notifications:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Notifications
        - Services
      summary: Create Service Notification
  /v1/Services:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Notifications
        - Services
      summary: Create Service
    get:
      description: ''
      tags:
        - Notifications
        - Services
      summary: Retrieve Services
  /v1/Services/{Sid}:
    description: 'TODO: Resource-level docs'
    delete:
      description: ''
      tags:
        - Notifications
        - Services
      summary: Delete Service
    get:
      description: ''
      tags:
        - Notifications
        - Services
      summary: Retrieve Service
    post:
      description: ''
      tags:
        - Notifications
        - Services
      summary: Update Service
tags:
  - name: Tag
  - name: Notifications
    description: Needs a description.
  - name: Services
    description: Needs a description.
  - name: Bindings
    description: Needs a description.
  - name: Credentials
    description: Needs a description.
x-maturity:
  - name: Beta
    description: >-
      PLEASE NOTE that this is a Beta product that is subject to change. Use it
      with caution.
