info:
  title: Twilio - Notify
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Services/{ServiceSid}/Bindings/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - NotifyV1Binding
    delete:
      description: ''
      tags:
        - NotifyV1Binding
  /v1/Services/{ServiceSid}/Bindings:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - NotifyV1Binding
    get:
      description: ''
      tags:
        - NotifyV1Binding
  /v1/Credentials:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - NotifyV1Credential
    post:
      description: ''
      tags:
        - NotifyV1Credential
  /v1/Credentials/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - NotifyV1Credential
    post:
      description: ''
      tags:
        - NotifyV1Credential
    delete:
      description: ''
      tags:
        - NotifyV1Credential
  /v1/Services/{ServiceSid}/Notifications:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - NotifyV1Notification
  /v1/Services:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - NotifyV1Service
    get:
      description: ''
      tags:
        - NotifyV1Service
  /v1/Services/{Sid}:
    description: 'TODO: Resource-level docs'
    delete:
      description: ''
      tags:
        - NotifyV1Service
    get:
      description: ''
      tags:
        - NotifyV1Service
    post:
      description: ''
      tags:
        - NotifyV1Service
tags:
  - name: NotifyV1Binding
  - name: NotifyV1Credential
  - name: NotifyV1Notification
  - name: NotifyV1Service
x-maturity:
  - name: Beta
    description: >-
      PLEASE NOTE that this is a Beta product that is subject to change. Use it
      with 
