info:
  title: Twilio - Numbers
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v2/HostedNumber/AuthorizationDocuments/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific AuthorizationDocument.
      tags:
        - NumbersV2AuthorizationDocument
    delete:
      description: Cancel the AuthorizationDocument request.
      tags:
        - NumbersV2AuthorizationDocument
  /v2/HostedNumber/AuthorizationDocuments:
    description: 'TODO: Resource-level docs'
    get:
      description: >-
        Retrieve a list of AuthorizationDocuments belonging to the account
        initiating the request.
      tags:
        - NumbersV2AuthorizationDocument
    post:
      description: >-
        Create an AuthorizationDocument for authorizing the hosting of phone
        number capabilities on Twilio's platform.
      tags:
        - NumbersV2AuthorizationDocument
  /v2/HostedNumber/Orders/Bulk/{BulkHostingSid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific BulkHostedNumberOrder.
      tags:
        - NumbersV2BulkHostedNumberOrder
  /v2/HostedNumber/Orders/Bulk:
    description: 'TODO: Resource-level docs'
  /v2/RegulatoryCompliance/Bundles:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Bundle.
      tags:
        - NumbersV2Bundle
    get:
      description: Retrieve a list of all Bundles for an account.
      tags:
        - NumbersV2Bundle
  /v2/RegulatoryCompliance/Bundles/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Bundle instance.
      tags:
        - NumbersV2Bundle
    post:
      description: Updates a Bundle in an account.
      tags:
        - NumbersV2Bundle
    delete:
      description: Delete a specific Bundle.
      tags:
        - NumbersV2Bundle
  /v2/RegulatoryCompliance/Bundles/{BundleSid}/Copies:
    description: 'TODO: Resource-level docs'
    post:
      description: >-
        Creates a new copy of a Bundle. It will internally create copies of all
        the bundle items (identities and documents) of the original bundle
      tags:
        - NumbersV2BundleCopy
    get:
      description: Retrieve a list of all Bundles Copies for a Bundle.
      tags:
        - NumbersV2BundleCopy
  /v2/HostedNumber/AuthorizationDocuments/{SigningDocumentSid}/DependentHostedNumberOrders:
    description: 'TODO: Resource-level docs'
    get:
      description: >-
        Retrieve a list of dependent HostedNumberOrders belonging to the
        AuthorizationDocument.
      tags:
        - NumbersV2DependentHostedNumberOrder
  /v2/RegulatoryCompliance/EndUsers:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new End User.
      tags:
        - NumbersV2EndUser
    get:
      description: Retrieve a list of all End User for an account.
      tags:
        - NumbersV2EndUser
  /v2/RegulatoryCompliance/EndUsers/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific End User Instance.
      tags:
        - NumbersV2EndUser
    post:
      description: Update an existing End User.
      tags:
        - NumbersV2EndUser
    delete:
      description: Delete a specific End User.
      tags:
        - NumbersV2EndUser
  /v2/RegulatoryCompliance/EndUserTypes:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all End-User Types.
      tags:
        - NumbersV2EndUserType
  /v2/RegulatoryCompliance/EndUserTypes/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific End-User Type Instance.
      tags:
        - NumbersV2EndUserType
  /v2/RegulatoryCompliance/Bundles/{BundleSid}/Evaluations:
    description: 'TODO: Resource-level docs'
    post:
      description: Creates an evaluation for a bundle
      tags:
        - NumbersV2Evaluation
    get:
      description: Retrieve a list of Evaluations associated to the Bundle resource.
      tags:
        - NumbersV2Evaluation
  /v2/RegulatoryCompliance/Bundles/{BundleSid}/Evaluations/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Evaluation Instance.
      tags:
        - NumbersV2Evaluation
  /v2/HostedNumber/Orders/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific HostedNumberOrder.
      tags:
        - NumbersV2HostedNumberOrder
    delete:
      description: >-
        Cancel the HostedNumberOrder (only available when the status is in
        `received`).
      tags:
        - NumbersV2HostedNumberOrder
  /v2/HostedNumber/Orders:
    description: 'TODO: Resource-level docs'
    get:
      description: >-
        Retrieve a list of HostedNumberOrders belonging to the account
        initiating the request.
      tags:
        - NumbersV2HostedNumberOrder
    post:
      description: Host a phone number's capability on Twilio's platform.
      tags:
        - NumbersV2HostedNumberOrder
  /v2/RegulatoryCompliance/Bundles/{BundleSid}/ItemAssignments:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Assigned Item.
      tags:
        - NumbersV2ItemAssignment
    get:
      description: Retrieve a list of all Assigned Items for an account.
      tags:
        - NumbersV2ItemAssignment
  /v2/RegulatoryCompliance/Bundles/{BundleSid}/ItemAssignments/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Assigned Item Instance.
      tags:
        - NumbersV2ItemAssignment
    delete:
      description: Remove an Assignment Item Instance.
      tags:
        - NumbersV2ItemAssignment
  /v2/RegulatoryCompliance/Regulations:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Regulations.
      tags:
        - NumbersV2Regulation
  /v2/RegulatoryCompliance/Regulations/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Regulation Instance.
      tags:
        - NumbersV2Regulation
  /v2/RegulatoryCompliance:
    description: 'TODO: Resource-level docs'
  /v2/RegulatoryCompliance/Bundles/{BundleSid}/ReplaceItems:
    description: 'TODO: Resource-level docs'
    post:
      description: >-
        Replaces all bundle items in the target bundle (specified in the path)
        with all the bundle items of the source bundle (specified by the
        from_bundle_sid body param)
      tags:
        - NumbersV2ReplaceItems
  /v2/RegulatoryCompliance/SupportingDocuments:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Supporting Document.
      tags:
        - NumbersV2SupportingDocument
    get:
      description: Retrieve a list of all Supporting Document for an account.
      tags:
        - NumbersV2SupportingDocument
  /v2/RegulatoryCompliance/SupportingDocuments/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Supporting Document Instance.
      tags:
        - NumbersV2SupportingDocument
    post:
      description: Update an existing Supporting Document.
      tags:
        - NumbersV2SupportingDocument
    delete:
      description: Delete a specific Supporting Document.
      tags:
        - NumbersV2SupportingDocument
  /v2/RegulatoryCompliance/SupportingDocumentTypes:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Supporting Document Types.
      tags:
        - NumbersV2SupportingDocumentType
  /v2/RegulatoryCompliance/SupportingDocumentTypes/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Supporting Document Type Instance.
      tags:
        - NumbersV2SupportingDocumentType
tags:
  - name: NumbersV2AuthorizationDocument
  - name: NumbersV2BulkHostedNumberOrder
  - name: NumbersV2Bundle
  - name: NumbersV2BundleCopy
  - name: NumbersV2DependentHostedNumberOrder
  - name: NumbersV2EndUser
  - name: NumbersV2EndUserType
  - name: NumbersV2Evaluation
  - name: NumbersV2HostedNumberOrder
  - name: NumbersV2ItemAssignment
  - name: NumbersV2Regulation
  - name: NumbersV2ReplaceItems
  - name: NumbersV2SupportingDocument
  - name: NumbersV2SupportingDocumentType
x-maturity:
  - name: GA
    description: This product is Generally Available.
  - name: Beta
    description: >-
      PLEASE NOTE that this is a Beta product that is subject to change. Use it
      with 
