info:
  title: Twilio Numbers API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v2/HostedNumber/AuthorizationDocuments/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific AuthorizationDocument.
      tags:
        - Numbers
        - Hosted Numbers
        - Hosted
        - Numbers
        - Authorization
        - Documents
      summary: Retrieve Hosted Number Authorization Document
    delete:
      description: Cancel the AuthorizationDocument request.
      tags:
        - Numbers
        - Hosted Numbers
        - Hosted
        - Numbers
        - Authorization
        - Documents
      summary: Delete Hosted Number Authorization Document
  /v2/HostedNumber/AuthorizationDocuments:
    description: 'TODO: Resource-level docs'
    get:
      description: >-
        Retrieve a list of AuthorizationDocuments belonging to the account
        initiating the request.
      tags:
        - Numbers
        - Hosted Numbers
        - Hosted
        - Numbers
        - Authorization
        - Documents
      summary: Retrieve Hosted Number Authorization Documents
    post:
      description: >-
        Create an AuthorizationDocument for authorizing the hosting of phone
        number capabilities on Twilio's platform.
      tags:
        - Numbers
        - Hosted Numbers
        - Hosted
        - Numbers
        - Authorization
        - Documents
      summary: Create Hosted Number Authorization Document
  /v2/HostedNumber/Orders/Bulk/{BulkHostingSid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific BulkHostedNumberOrder.
      tags:
        - Numbers
        - Hosted Numbers
        - Orders
        - Bulk
        - Bulk Hosting
        - Hosted
      summary: Retrieve Hosted Number Orders Bulk
  /v2/HostedNumber/Orders/Bulk:
    description: 'TODO: Resource-level docs'
  /v2/RegulatoryCompliance/Bundles:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Bundle.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Bundles
      summary: Create Regulatory Compliance Bundle
    get:
      description: Retrieve a list of all Bundles for an account.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Bundles
      summary: Retrieve Regulatory Compliance Bundles
  /v2/RegulatoryCompliance/Bundles/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Bundle instance.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Bundles
      summary: Retrieve Regulatory Compliance Bundle
    post:
      description: Updates a Bundle in an account.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Bundles
      summary: Update Regulatory Compliance Bundle
    delete:
      description: Delete a specific Bundle.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Bundles
      summary: Delete Regulatory Compliance Bundle
  /v2/RegulatoryCompliance/Bundles/{BundleSid}/Copies:
    description: 'TODO: Resource-level docs'
    post:
      description: >-
        Creates a new copy of a Bundle. It will internally create copies of all
        the bundle items (identities and documents) of the original bundle
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Bundles
        - Copies
      summary: Create Regulatory Compliance Bundle Copy
    get:
      description: Retrieve a list of all Bundles Copies for a Bundle.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Bundles
        - Copies
      summary: Retrieve Regulatory Compliance Bundle Copy
  /v2/HostedNumber/AuthorizationDocuments/{SigningDocumentSid}/DependentHostedNumberOrders:
    description: 'TODO: Resource-level docs'
    get:
      description: >-
        Retrieve a list of dependent HostedNumberOrders belonging to the
        AuthorizationDocument.
      tags:
        - Numbers
        - Hosted Numbers
        - Signing
        - Dependent
        - Hosted
        - Authorization
        - Documents
        - Orders
      summary: Retrieve Hosted Number Authorization Documents Orders
  /v2/RegulatoryCompliance/EndUsers:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new End User.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - User
      summary: Create Regulatory Compliance End User
    get:
      description: Retrieve a list of all End User for an account.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - User
      summary: Retrieve Regulatory Compliance End Users
  /v2/RegulatoryCompliance/EndUsers/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific End User Instance.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Users
      summary: Retrieve Regulatory Compliance End User
    post:
      description: Update an existing End User.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Users
      summary: Update Regulatory Compliance End User
    delete:
      description: Delete a specific End User.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Users
      summary: Delete Regulatory Compliance End User
  /v2/RegulatoryCompliance/EndUserTypes:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all End-User Types.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Users
        - Types
        - User Types
      summary: Retrieve Regulatory Compliance End User Types
  /v2/RegulatoryCompliance/EndUserTypes/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific End-User Type Instance.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Users
        - Types
        - User Types
      summary: Retrieve Regulatory Compliance End User Type
  /v2/RegulatoryCompliance/Bundles/{BundleSid}/Evaluations:
    description: 'TODO: Resource-level docs'
    post:
      description: Creates an evaluation for a bundle
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Bundles
        - Evaluations
      summary: Create Regulatory Compliance Bundle Evaluation
    get:
      description: Retrieve a list of Evaluations associated to the Bundle resource.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Bundles
        - Evaluations
      summary: Retrieve Regulatory Compliance Bundle Evaluations
  /v2/RegulatoryCompliance/Bundles/{BundleSid}/Evaluations/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Evaluation Instance.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Bundles
        - Evaluations
      summary: Retrieve Regulatory Compliance Bundle Evaluation
  /v2/HostedNumber/Orders/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific HostedNumberOrder.
      tags:
        - Numbers
        - Hosted Numbers
        - Orders
        - Hosted
      summary: Retrieve Hosted Number Order
    delete:
      description: >-
        Cancel the HostedNumberOrder (only available when the status is in
        `received`).
      tags:
        - Numbers
        - Hosted Numbers
        - Orders
        - Hosted
      summary: Delete Hosted Number Order
  /v2/HostedNumber/Orders:
    description: 'TODO: Resource-level docs'
    get:
      description: >-
        Retrieve a list of HostedNumberOrders belonging to the account
        initiating the request.
      tags:
        - Numbers
        - Hosted Numbers
        - Orders
        - Hosted
      summary: Retrieve Hosted Number Orders
    post:
      description: Host a phone number's capability on Twilio's platform.
      tags:
        - Numbers
        - Hosted Numbers
        - Orders
        - Hosted
      summary: Create Hosted Number Order
  /v2/RegulatoryCompliance/Bundles/{BundleSid}/ItemAssignments:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Assigned Item.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Bundles
        - Items
        - Assignments
      summary: Create Regulatory Compliance Bundle Item Assignment
    get:
      description: Retrieve a list of all Assigned Items for an account.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Bundles
        - Items
        - Assignments
      summary: Retrieve Regulatory Compliance Bundle Item Assignments
  /v2/RegulatoryCompliance/Bundles/{BundleSid}/ItemAssignments/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Assigned Item Instance.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Bundles
        - Items
        - Assignments
      summary: Retrieve Regulatory Compliance Bundle Item Assignment
    delete:
      description: Remove an Assignment Item Instance.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Bundles
        - Items
        - Assignments
      summary: Delete Regulatory Compliance Bundle Item Assignment
  /v2/RegulatoryCompliance/Regulations:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Regulations.
      tags:
        - Numbers
        - Regulations
        - Compliance
      summary: Retrieve Regulatory Compliance Regulations
  /v2/RegulatoryCompliance/Regulations/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Regulation Instance.
      tags:
        - Numbers
        - Regulations
        - Compliance
      summary: Retrieve Regulatory Compliance Regulation
  /v2/RegulatoryCompliance:
    description: 'TODO: Resource-level docs'
  /v2/RegulatoryCompliance/Bundles/{BundleSid}/ReplaceItems:
    description: 'TODO: Resource-level docs'
    post:
      description: >-
        Replaces all bundle items in the target bundle (specified in the path)
        with all the bundle items of the source bundle (specified by the
        from_bundle_sid body param)
      tags:
        - Numbers
        - Regulations
        - Compliance
        - ' Bundles'
        - Items
      summary: Create Regulatory Compliance Bundle Replace Items
  /v2/RegulatoryCompliance/SupportingDocuments:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Supporting Document.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Supporting
        - Documents
      summary: Create Regulatory Compliance Supporting Document
    get:
      description: Retrieve a list of all Supporting Document for an account.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Supporting
        - Documents
      summary: Retrieve Regulatory Compliance Supporting Documents
  /v2/RegulatoryCompliance/SupportingDocuments/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Supporting Document Instance.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Supporting
        - Documents
      summary: Retrieve Regulatory Compliance Supporting Document
    post:
      description: Update an existing Supporting Document.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Supporting
        - Documents
      summary: Update Regulatory Compliance Supporting Document
    delete:
      description: Delete a specific Supporting Document.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Supporting
        - Documents
      summary: Delete Regulatory Compliance Supporting Document
  /v2/RegulatoryCompliance/SupportingDocumentTypes:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Supporting Document Types.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Supporting
        - Documents
        - Types
        - ' Document Types'
      summary: Retrieve Regulatory Compliance Supporting Document Types
  /v2/RegulatoryCompliance/SupportingDocumentTypes/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Supporting Document Type Instance.
      tags:
        - Numbers
        - Regulations
        - Compliance
        - Supporting
        - Documents
        - Types
        - ' Document Types'
      summary: Retrieve Regulatory Compliance Supporting Document Type
tags:
  - name: Tag
  - name: Numbers
    description: Needs a description.
  - name: Hosted Numbers
    description: Needs a description.
  - name: Hosted
    description: Needs a description.
  - name: Authorization
    description: Needs a description.
  - name: Documents
    description: Needs a description.
  - name: Orders
    description: Needs a description.
  - name: Bulk
    description: Needs a description.
  - name: Bulk Hosting
    description: Needs a description.
  - name: Regulation
    description: Needs a description.
  - name: Compliance
    description: Needs a description.
  - name: Bundles
    description: Needs a description.
  - name: Copies
    description: Needs a description.
  - name: Signing
    description: Needs a description.
  - name: Dependent
    description: Needs a description.
  - name: Regulations
    description: Needs a description.
  - name: User
    description: Needs a description.
  - name: Regulatory
    description: Needs a description.
  - name: End
    description: Needs a description.
  - name: Users
    description: Needs a description.
  - name: Types
    description: Needs a description.
  - name: User Types
    description: Needs a description.
  - name: Bunldes
    description: Needs a description.
  - name: Evaluations
    description: Needs a description.
  - name: Items
    description: Needs a description.
  - name: Assignments
    description: Needs a description.
  - name: Supporting
    description: Needs a description.
  - name: ' Bundles'
    description: Needs a description.
  - name: ' Document Types'
    description: Needs a description.
x-maturity:
  - name: GA
    description: This product is Generally Available.
  - name: Beta
    description: >-
      PLEASE NOTE that this is a Beta product that is subject to change. Use it
      with caution.
