rules: null
info:
  title: Twilio Pricing API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v2/Trunking/Countries:
    description: Trunking pricing by country
    get:
      description: ''
      tags:
        - Pricing
        - Trunking
        - Countries
      summary: Retrieve Trunking Countries
  /v2/Trunking/Countries/{IsoCountry}:
    description: Trunking pricing by country
    get:
      description: Fetch a specific Country.
      tags:
        - Pricing
        - Trunking
        - Countries
      summary: Retrieve Trunking Country
  /v2/Trunking/Numbers/{DestinationNumber}:
    description: Trunking pricing for a specific phone number
    get:
      description: >-
        Fetch pricing information for a specific destination and, optionally,
        origination phone number.
      tags:
        - Pricing
        - Trunking
        - Numbers
      summary: Retrieve Trunking Number
  /v2/Trunking/Numbers:
    description: Trunking pricing for a specific phone number
  /v2/Voice:
    description: Voice pricing
  /v2/Voice/Countries:
    description: Voice pricing by country
    get:
      description: ''
      tags:
        - Pricing
        - Voice
        - Countries
      summary: Retrieve Voice Countries
  /v2/Voice/Countries/{IsoCountry}:
    description: Voice pricing by country
    get:
      description: Fetch a specific Country.
      tags:
        - Pricing
        - Voice
        - Countries
      summary: Retrieve Voice Country
  /v2/Voice/Numbers/{DestinationNumber}:
    description: Voice pricing for a specific phone number
    get:
      description: >-
        Fetch pricing information for a specific destination and, optionally,
        origination phone number.
      tags:
        - Pricing
        - Voice
        - Numbers
      summary: Retrieve Voice Number
  /v2/Voice/Numbers:
    description: Voice pricing for a specific phone number
tags:
  - name: Pricing
    description: Needs a description.
  - name: Trunking
    description: Needs a description.
  - name: Countries
    description: Needs a description.
  - name: Numbers
    description: Needs a description.
  - name: Voice
    description: Needs a description.
x-maturity:
  - name: GA
    description: This product is Generally Available.
