info:
  title: Twilio - Proxy
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Services/{ServiceSid}/Sessions/{SessionSid}/Interactions/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: >-
        Retrieve a list of Interactions for a given
        [Session](https://www.twilio.com/docs/proxy/api/session).
      tags:
        - ProxyV1Interaction
    delete:
      description: Delete a specific Interaction.
      tags:
        - ProxyV1Interaction
  /v1/Services/{ServiceSid}/Sessions/{SessionSid}/Interactions:
    description: 'TODO: Resource-level docs'
    get:
      description: >-
        Retrieve a list of all Interactions for a Session. A maximum of 100
        records will be returned per page.
      tags:
        - ProxyV1Interaction
  /v1/Services/{ServiceSid}/Sessions/{SessionSid}/Participants/{ParticipantSid}/MessageInteractions:
    description: 'TODO: Resource-level docs'
    post:
      description: >-
        Create a new message Interaction to send directly from your system to
        one [Participant](https://www.twilio.com/docs/proxy/api/participant). 
        The `inbound` properties for the Interaction will always be empty.
      tags:
        - ProxyV1MessageInteraction
    get:
      description: ''
      tags:
        - ProxyV1MessageInteraction
  /v1/Services/{ServiceSid}/Sessions/{SessionSid}/Participants/{ParticipantSid}/MessageInteractions/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - ProxyV1MessageInteraction
  /v1/Services/{ServiceSid}/Sessions/{SessionSid}/Participants/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Participant.
      tags:
        - ProxyV1Participant
    delete:
      description: >-
        Delete a specific Participant. This is a soft-delete. The participant
        remains associated with the session and cannot be re-added. Participants
        are only permanently deleted when the
        [Session](https://www.twilio.com/docs/proxy/api/session) is deleted.
      tags:
        - ProxyV1Participant
  /v1/Services/{ServiceSid}/Sessions/{SessionSid}/Participants:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Participants in a Session.
      tags:
        - ProxyV1Participant
    post:
      description: Add a new Participant to the Session
      tags:
        - ProxyV1Participant
  /v1/Services/{ServiceSid}/PhoneNumbers:
    description: 'TODO: Resource-level docs'
    post:
      description: Add a Phone Number to a Service's Proxy Number Pool.
      tags:
        - ProxyV1PhoneNumber
    get:
      description: >-
        Retrieve a list of all Phone Numbers in the Proxy Number Pool for a
        Service. A maximum of 100 records will be returned per page.
      tags:
        - ProxyV1PhoneNumber
  /v1/Services/{ServiceSid}/PhoneNumbers/{Sid}:
    description: 'TODO: Resource-level docs'
    delete:
      description: Delete a specific Phone Number from a Service.
      tags:
        - ProxyV1PhoneNumber
    get:
      description: Fetch a specific Phone Number.
      tags:
        - ProxyV1PhoneNumber
    post:
      description: Update a specific Proxy Number.
      tags:
        - ProxyV1PhoneNumber
  /v1/Services/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Service.
      tags:
        - ProxyV1Service
    delete:
      description: Delete a specific Service.
      tags:
        - ProxyV1Service
    post:
      description: Update a specific Service.
      tags:
        - ProxyV1Service
  /v1/Services:
    description: 'TODO: Resource-level docs'
    get:
      description: >-
        Retrieve a list of all Services for Twilio Proxy. A maximum of 100
        records will be returned per page.
      tags:
        - ProxyV1Service
    post:
      description: Create a new Service for Twilio Proxy
      tags:
        - ProxyV1Service
  /v1/Services/{ServiceSid}/Sessions/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Session.
      tags:
        - ProxyV1Session
    delete:
      description: Delete a specific Session.
      tags:
        - ProxyV1Session
    post:
      description: Update a specific Session.
      tags:
        - ProxyV1Session
  /v1/Services/{ServiceSid}/Sessions:
    description: 'TODO: Resource-level docs'
    get:
      description: >-
        Retrieve a list of all Sessions for the Service. A maximum of 100
        records will be returned per page.
      tags:
        - ProxyV1Session
    post:
      description: Create a new Session
      tags:
        - ProxyV1Session
  /v1/Services/{ServiceSid}/ShortCodes:
    description: 'TODO: Resource-level docs'
    post:
      description: Add a Short Code to the Proxy Number Pool for the Service.
      tags:
        - ProxyV1ShortCode
    get:
      description: >-
        Retrieve a list of all Short Codes in the Proxy Number Pool for the
        Service. A maximum of 100 records will be returned per page.
      tags:
        - ProxyV1ShortCode
  /v1/Services/{ServiceSid}/ShortCodes/{Sid}:
    description: 'TODO: Resource-level docs'
    delete:
      description: Delete a specific Short Code from a Service.
      tags:
        - ProxyV1ShortCode
    get:
      description: Fetch a specific Short Code.
      tags:
        - ProxyV1ShortCode
    post:
      description: Update a specific Short Code.
      tags:
        - ProxyV1ShortCode
tags:
  - name: ProxyV1Interaction
  - name: ProxyV1MessageInteraction
  - name: ProxyV1Participant
  - name: ProxyV1PhoneNumber
  - name: ProxyV1Service
  - name: ProxyV1Session
  - name: ProxyV1ShortCode
x-maturity:
  - name: Beta
    description: >-
      PLEASE NOTE that this is a Beta product that is subject to change. Use it
      with 
