info:
  title: Twilio Routes API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v2/PhoneNumbers/{PhoneNumber}:
    description: 'TODO: Resource-level docs'
    post:
      description: Assign an Inbound Processing Region to a phone number.
      tags:
        - Routes
        - Phone Numbers
        - Numbers
      summary: Create Phone Number
    get:
      description: Fetch the Inbound Processing Region assigned to a phone number.
      tags:
        - Routes
        - Phone Numbers
        - Numbers
      summary: Retrieve Phone Number
  /v2/SipDomains/{SipDomain}:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Routes
        - SIP Domains
        - SIP
        - Domains
      summary: Create SIP Domain
    get:
      description: ''
      tags:
        - Routes
        - SIP Domains
        - SIP
        - Domains
      summary: Retrieve SIP Domain
  /v2/Trunks/{SipTrunkDomain}:
    description: 'TODO: Resource-level docs'
    post:
      description: Assign an Inbound Processing Region to a SIP Trunk
      tags:
        - Routes
        - Trunks
        - SIP Trunk
        - Domain
        - Trunks
      summary: Create Trunk
    get:
      description: Fetch the Inbound Processing Region assigned to a SIP Trunk.
      tags:
        - Routes
        - Trunks
        - SIP Trunk
        - Domain
        - Trunks
      summary: Retrieve Trunks
tags:
  - name: Tag
  - name: Routes
    description: Needs a description.
  - name: Phone Numbers
    description: Needs a description.
  - name: Numbers
    description: Needs a description.
  - name: SIP Domains
    description: Needs a description.
  - name: SIP
    description: Needs a description.
  - name: Domains
    description: Needs a description.
  - name: Trunks
    description: Needs a description.
  - name: SIP Trunk
    description: Needs a description.
  - name: Domain
    description: Needs a description.
x-maturity:
  - name: GA
    description: This product is Generally Available.
