info:
  title: Twilio - Serverless
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Services/{ServiceSid}/Assets:
    description: >-
      A wrapper that represents a static file and groups the different Versions
      of the static file.
    get:
      description: Retrieve a list of all Assets.
      tags:
        - ServerlessV1Asset
    post:
      description: Create a new Asset resource.
      tags:
        - ServerlessV1Asset
  /v1/Services/{ServiceSid}/Assets/{Sid}:
    description: >-
      A wrapper that represents a static file and groups the different Versions
      of the static file.
    get:
      description: Retrieve a specific Asset resource.
      tags:
        - ServerlessV1Asset
    delete:
      description: Delete an Asset resource.
      tags:
        - ServerlessV1Asset
    post:
      description: Update a specific Asset resource.
      tags:
        - ServerlessV1Asset
  /v1/Services/{ServiceSid}/Assets/{AssetSid}/Versions:
    description: The content of an Asset.
    get:
      description: Retrieve a list of all Asset Versions.
      tags:
        - ServerlessV1AssetVersion
  /v1/Services/{ServiceSid}/Assets/{AssetSid}/Versions/{Sid}:
    description: The content of an Asset.
    get:
      description: Retrieve a specific Asset Version.
      tags:
        - ServerlessV1AssetVersion
  /v1/Services/{ServiceSid}/Builds:
    description: >-
      A collection of Function Versions, Asset Versions, Dependencies, and a
      Runtime that form a deployable unit.
    get:
      description: Retrieve a list of all Builds.
      tags:
        - ServerlessV1Build
    post:
      description: >-
        Create a new Build resource. At least one function version or asset
        version is required.
      tags:
        - ServerlessV1Build
  /v1/Services/{ServiceSid}/Builds/{Sid}:
    description: >-
      A collection of Function Versions, Asset Versions, Dependencies, and a
      Runtime that form a deployable unit.
    get:
      description: Retrieve a specific Build resource.
      tags:
        - ServerlessV1Build
    delete:
      description: Delete a Build resource.
      tags:
        - ServerlessV1Build
  /v1/Services/{ServiceSid}/Builds/{Sid}/Status:
    description: The status of a Build resource.
    get:
      description: Retrieve a specific Build resource.
      tags:
        - ServerlessV1BuildStatus
  /v1/Services/{ServiceSid}/Environments/{EnvironmentSid}/Deployments:
    description: >-
      An association of a Build with an Environment so that the Build is
      published in the Environment.
    get:
      description: Retrieve a list of all Deployments.
      tags:
        - ServerlessV1Deployment
    post:
      description: Create a new Deployment.
      tags:
        - ServerlessV1Deployment
  /v1/Services/{ServiceSid}/Environments/{EnvironmentSid}/Deployments/{Sid}:
    description: >-
      An association of a Build with an Environment so that the Build is
      published in the Environment.
    get:
      description: Retrieve a specific Deployment.
      tags:
        - ServerlessV1Deployment
  /v1/Services/{ServiceSid}/Environments:
    description: >-
      Represents a deployed build of a given set of Functions and/or Assets at a
      specific URL.
    get:
      description: Retrieve a list of all environments.
      tags:
        - ServerlessV1Environment
    post:
      description: Create a new environment.
      tags:
        - ServerlessV1Environment
  /v1/Services/{ServiceSid}/Environments/{Sid}:
    description: >-
      Represents a deployed build of a given set of Functions and/or Assets at a
      specific URL.
    get:
      description: Retrieve a specific environment.
      tags:
        - ServerlessV1Environment
    delete:
      description: Delete a specific environment.
      tags:
        - ServerlessV1Environment
  /v1/Services/{ServiceSid}/Functions:
    description: >-
      A wrapper that represents a Serverless JavaScript function and groups the
      different  and groups the different Versions of this code.
    get:
      description: Retrieve a list of all Functions.
      tags:
        - ServerlessV1Function
    post:
      description: Create a new Function resource.
      tags:
        - ServerlessV1Function
  /v1/Services/{ServiceSid}/Functions/{Sid}:
    description: >-
      A wrapper that represents a Serverless JavaScript function and groups the
      different  and groups the different Versions of this code.
    get:
      description: Retrieve a specific Function resource.
      tags:
        - ServerlessV1Function
    delete:
      description: Delete a Function resource.
      tags:
        - ServerlessV1Function
    post:
      description: Update a specific Function resource.
      tags:
        - ServerlessV1Function
  /v1/Services/{ServiceSid}/Functions/{FunctionSid}/Versions:
    description: The content of a Function.
    get:
      description: Retrieve a list of all Function Version resources.
      tags:
        - ServerlessV1FunctionVersion
  /v1/Services/{ServiceSid}/Functions/{FunctionSid}/Versions/{Sid}:
    description: The content of a Function.
    get:
      description: Retrieve a specific Function Version resource.
      tags:
        - ServerlessV1FunctionVersion
  /v1/Services/{ServiceSid}/Functions/{FunctionSid}/Versions/{Sid}/Content:
    description: The code of a Function Version.
    get:
      description: Retrieve a the content of a specific Function Version resource.
      tags:
        - ServerlessV1FunctionVersionContent
  /v1/Services/{ServiceSid}/Environments/{EnvironmentSid}/Logs:
    description: A record of an event that occurred related to a function invocation.
    get:
      description: Retrieve a list of all logs.
      tags:
        - ServerlessV1Log
  /v1/Services/{ServiceSid}/Environments/{EnvironmentSid}/Logs/{Sid}:
    description: A record of an event that occurred related to a function invocation.
    get:
      description: Retrieve a specific log.
      tags:
        - ServerlessV1Log
  /v1/Services:
    description: >-
      The top-level resource for a Serverless application, which serves as a
      container for the application environments.
    get:
      description: Retrieve a list of all Services.
      tags:
        - ServerlessV1Service
    post:
      description: Create a new Service resource.
      tags:
        - ServerlessV1Service
  /v1/Services/{Sid}:
    description: >-
      The top-level resource for a Serverless application, which serves as a
      container for the application environments.
    get:
      description: Retrieve a specific Service resource.
      tags:
        - ServerlessV1Service
    delete:
      description: Delete a Service resource.
      tags:
        - ServerlessV1Service
    post:
      description: Update a specific Service resource.
      tags:
        - ServerlessV1Service
  /v1/Services/{ServiceSid}/Environments/{EnvironmentSid}/Variables:
    description: A key and value pair that is specific to an Environment.
    get:
      description: Retrieve a list of all Variables.
      tags:
        - ServerlessV1Variable
    post:
      description: Create a new Variable.
      tags:
        - ServerlessV1Variable
  /v1/Services/{ServiceSid}/Environments/{EnvironmentSid}/Variables/{Sid}:
    description: A key and value pair that is specific to an Environment.
    get:
      description: Retrieve a specific Variable.
      tags:
        - ServerlessV1Variable
    post:
      description: Update a specific Variable.
      tags:
        - ServerlessV1Variable
    delete:
      description: Delete a specific Variable.
      tags:
        - ServerlessV1Variable
tags:
  - name: ServerlessV1Asset
  - name: ServerlessV1AssetVersion
  - name: ServerlessV1Build
  - name: ServerlessV1BuildStatus
  - name: ServerlessV1Deployment
  - name: ServerlessV1Environment
  - name: ServerlessV1Function
  - name: ServerlessV1FunctionVersion
  - name: ServerlessV1FunctionVersionContent
  - name: ServerlessV1Log
  - name: ServerlessV1Service
  - name: ServerlessV1Variable
x-maturity:
  - name: Beta
    description: >-
      PLEASE NOTE that this is a Beta product that is subject to change. Use it
      with 
