info:
  title: Twilio Serverless API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Services/{ServiceSid}/Assets:
    description: >-
      A wrapper that represents a static file and groups the different Versions
      of the static file.
    get:
      description: Retrieve a list of all Assets.
      tags:
        - Serverless
        - Services
        - Assets
      summary: Retrieve Service Assets
    post:
      description: Create a new Asset resource.
      tags:
        - Serverless
        - Services
        - Assets
      summary: Create Service Asset
  /v1/Services/{ServiceSid}/Assets/{Sid}:
    description: >-
      A wrapper that represents a static file and groups the different Versions
      of the static file.
    get:
      description: Retrieve a specific Asset resource.
      tags:
        - Serverless
        - Services
        - Assets
      summary: Retrieve Service Asset
    delete:
      description: Delete an Asset resource.
      tags:
        - Serverless
        - Services
        - Assets
      summary: Delete Service Asset
    post:
      description: Update a specific Asset resource.
      tags:
        - Serverless
        - Services
        - Assets
      summary: Update Service Asset
  /v1/Services/{ServiceSid}/Assets/{AssetSid}/Versions:
    description: The content of an Asset.
    get:
      description: Retrieve a list of all Asset Versions.
      tags:
        - Serverless
        - Services
        - Assets
        - Versions
      summary: Retrieve Service Asset Versions
  /v1/Services/{ServiceSid}/Assets/{AssetSid}/Versions/{Sid}:
    description: The content of an Asset.
    get:
      description: Retrieve a specific Asset Version.
      tags:
        - Serverless
        - Services
        - Assets
        - Versions
      summary: Retrieve Service Asset Version
  /v1/Services/{ServiceSid}/Builds:
    description: >-
      A collection of Function Versions, Asset Versions, Dependencies, and a
      Runtime that form a deployable unit.
    get:
      description: Retrieve a list of all Builds.
      tags:
        - Serverless
        - Services
        - Builds
      summary: Retrieve Service Builds
    post:
      description: >-
        Create a new Build resource. At least one function version or asset
        version is required.
      tags:
        - Serverless
        - Services
        - Builds
      summary: Create Service Build
  /v1/Services/{ServiceSid}/Builds/{Sid}:
    description: >-
      A collection of Function Versions, Asset Versions, Dependencies, and a
      Runtime that form a deployable unit.
    get:
      description: Retrieve a specific Build resource.
      tags:
        - Serverless
        - Services
        - Builds
      summary: Retrieve Service Build
    delete:
      description: Delete a Build resource.
      tags:
        - Serverless
        - Services
        - Builds
      summary: Delete Service Build
  /v1/Services/{ServiceSid}/Builds/{Sid}/Status:
    description: The status of a Build resource.
    get:
      description: Retrieve a specific Build resource.
      tags:
        - Serverless
        - Services
        - Builds
        - Status
      summary: Retrieve Service Build Status
  /v1/Services/{ServiceSid}/Environments/{EnvironmentSid}/Deployments:
    description: >-
      An association of a Build with an Environment so that the Build is
      published in the Environment.
    get:
      description: Retrieve a list of all Deployments.
      tags:
        - Serverless
        - Services
        - Builds
        - Status
      summary: Retrieve Service Environment Deployments
    post:
      description: Create a new Deployment.
      tags:
        - Serverless
        - Services
        - Builds
        - Status
      summary: Create Service Environment Deployment
  /v1/Services/{ServiceSid}/Environments/{EnvironmentSid}/Deployments/{Sid}:
    description: >-
      An association of a Build with an Environment so that the Build is
      published in the Environment.
    get:
      description: Retrieve a specific Deployment.
      tags:
        - Serverless
        - Services
        - Environments
        - Deployments
      summary: Retrieve Service Environment Deployment
  /v1/Services/{ServiceSid}/Environments:
    description: >-
      Represents a deployed build of a given set of Functions and/or Assets at a
      specific URL.
    get:
      description: Retrieve a list of all environments.
      tags:
        - Serverless
        - Services
        - Environments
        - Deployments
      summary: Retrieve Service Environments
    post:
      description: Create a new environment.
      tags:
        - Serverless
        - Services
        - Environments
        - Deployments
      summary: Create Service Environment
  /v1/Services/{ServiceSid}/Environments/{Sid}:
    description: >-
      Represents a deployed build of a given set of Functions and/or Assets at a
      specific URL.
    get:
      description: Retrieve a specific environment.
      tags:
        - Serverless
        - Services
        - Environments
        - Deployments
      summary: Retrieve Service Environment
    delete:
      description: Delete a specific environment.
      tags:
        - Serverless
        - Services
        - Environments
        - Deployments
      summary: Delete Service Environment
  /v1/Services/{ServiceSid}/Functions:
    description: >-
      A wrapper that represents a Serverless JavaScript function and groups the
      different  and groups the different Versions of this code.
    get:
      description: Retrieve a list of all Functions.
      tags:
        - Serverless
        - Services
        - Functions
      summary: Retrieve Service Functions
    post:
      description: Create a new Function resource.
      tags:
        - Serverless
        - Services
        - Functions
      summary: Create Service Functions
  /v1/Services/{ServiceSid}/Functions/{Sid}:
    description: >-
      A wrapper that represents a Serverless JavaScript function and groups the
      different  and groups the different Versions of this code.
    get:
      description: Retrieve a specific Function resource.
      tags:
        - Serverless
        - Services
        - Functions
      summary: Retrieve Service Function
    delete:
      description: Delete a Function resource.
      tags:
        - Serverless
        - Services
        - Functions
      summary: Delete Service Function
    post:
      description: Update a specific Function resource.
      tags:
        - Serverless
        - Services
        - Functions
      summary: Update Service Function
  /v1/Services/{ServiceSid}/Functions/{FunctionSid}/Versions:
    description: The content of a Function.
    get:
      description: Retrieve a list of all Function Version resources.
      tags:
        - Serverless
        - Services
        - Functions
        - Versions
      summary: Retrieve Service Function Versions
  /v1/Services/{ServiceSid}/Functions/{FunctionSid}/Versions/{Sid}:
    description: The content of a Function.
    get:
      description: Retrieve a specific Function Version resource.
      tags:
        - Serverless
        - Services
        - Functions
        - Versions
      summary: Retrieve Service Function Version
  /v1/Services/{ServiceSid}/Functions/{FunctionSid}/Versions/{Sid}/Content:
    description: The code of a Function Version.
    get:
      description: Retrieve a the content of a specific Function Version resource.
      tags:
        - Serverless
        - Services
        - Functions
        - Versions
        - Contents
      summary: Retrieve Service Function Version Contents
  /v1/Services/{ServiceSid}/Environments/{EnvironmentSid}/Logs:
    description: A record of an event that occurred related to a function invocation.
    get:
      description: Retrieve a list of all logs.
      tags:
        - Serverless
        - Services
        - Environments
        - Logs
      summary: Retrieve Service Environment Logs
  /v1/Services/{ServiceSid}/Environments/{EnvironmentSid}/Logs/{Sid}:
    description: A record of an event that occurred related to a function invocation.
    get:
      description: Retrieve a specific log.
      tags:
        - Serverless
        - Services
        - Environments
        - Logs
      summary: Retrieve Service Environment Log
  /v1/Services:
    description: >-
      The top-level resource for a Serverless application, which serves as a
      container for the application environments.
    get:
      description: Retrieve a list of all Services.
      tags:
        - Serverless
        - Services
      summary: Retrieve Services
    post:
      description: Create a new Service resource.
      tags:
        - Serverless
        - Services
      summary: Create Service
  /v1/Services/{Sid}:
    description: >-
      The top-level resource for a Serverless application, which serves as a
      container for the application environments.
    get:
      description: Retrieve a specific Service resource.
      tags:
        - Serverless
        - Services
      summary: Retrieve Service
    delete:
      description: Delete a Service resource.
      tags:
        - Serverless
        - Services
      summary: Retrieve Service
    post:
      description: Update a specific Service resource.
      tags:
        - Serverless
        - Services
      summary: Update Service
  /v1/Services/{ServiceSid}/Environments/{EnvironmentSid}/Variables:
    description: A key and value pair that is specific to an Environment.
    get:
      description: Retrieve a list of all Variables.
      tags:
        - Serverless
        - Services
        - Environments
        - Variables
      summary: Retrieve Service Environment Variables
    post:
      description: Create a new Variable.
      tags:
        - Serverless
        - Services
        - Environments
        - Variables
      summary: Create Service Environment Variable
  /v1/Services/{ServiceSid}/Environments/{EnvironmentSid}/Variables/{Sid}:
    description: A key and value pair that is specific to an Environment.
    get:
      description: Retrieve a specific Variable.
      tags:
        - Serverless
        - Services
        - Environments
        - Variables
      summary: Retrieve Service Environment Variable
    post:
      description: Update a specific Variable.
      tags:
        - Serverless
        - Services
        - Environments
        - Variables
      summary: Update Service Environment Variable
    delete:
      description: Delete a specific Variable.
      tags:
        - Serverless
        - Services
        - Environments
        - Variables
      summary: Delete Service Environment Variable
tags:
  - name: Tag
  - name: Serverless
    description: Needs a description.
  - name: Services
    description: Needs a description.
  - name: Assets
    description: Needs a description.
  - name: Versions
    description: Needs a description.
  - name: Builds
    description: Needs a description.
  - name: Status
    description: Needs a description.
  - name: Environments
    description: Needs a description.
  - name: Deployments
    description: Needs a description.
  - name: Functions
    description: Needs a description.
  - name: Contents
    description: Needs a description.
  - name: Logs
    description: Needs a description.
  - name: Variables
    description: Needs a description.
x-maturity:
  - name: Beta
    description: >-
      PLEASE NOTE that this is a Beta product that is subject to change. Use it
      with caution.
