info:
  title: Twilio Super SIM API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Sims/{SimSid}/BillingPeriods:
    description: Billing Period for an IoT Super SIM
    get:
      description: Retrieve a list of Billing Periods for a Super SIM.
      tags:
        - Retrieve
        - Billing
        - Periods
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
      summary: Retrieve SIM Billing Periods
  /v1/ESimProfiles:
    description: eSIM Profiles that can be loaded onto consumer eUICC SIMs
    post:
      description: Order an eSIM Profile.
      tags:
        - Create
        - Profile
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
      summary: Create ESIM Profile
    get:
      description: Retrieve a list of eSIM Profiles.
      tags:
        - Retrieve
        - Profiles
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
      summary: Retrieve ESIM Profiles
  /v1/ESimProfiles/{Sid}:
    description: eSIM Profiles that can be loaded onto consumer eUICC SIMs
    get:
      description: Fetch an eSIM Profile.
      tags:
        - Retrieve
        - Profile
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
      summary: Retrieve ESIM Profile
  /v1/Fleets:
    description: >-
      Configure shared settings inherited by all Super SIMs assigned to the
      Fleet
    post:
      description: Create a Fleet
      tags:
        - Create
        - Fleets
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
      summary: Create Fleets
    get:
      description: Retrieve a list of Fleets from your account.
      tags:
        - Retrieve
        - Fleets
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
      summary: Retrieve Fleets
  /v1/Fleets/{Sid}:
    description: >-
      Configure shared settings inherited by all Super SIMs assigned to the
      Fleet
    get:
      description: Fetch a Fleet instance from your account.
      tags:
        - Retrieve
        - Fleet
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
      summary: Retrieve Fleet
    post:
      description: >-
        Updates the given properties of a Super SIM Fleet instance from your
        account.
      tags:
        - Update
        - Fleet
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
      summary: Update Fleet
  /v1/IpCommands:
    description: Machine-to-machine IP Commands sent to/from Super SIMs
    post:
      description: Send an IP Command to a Super SIM.
      tags:
        - Create
        - Command
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
      summary: Create IP Command
    get:
      description: Retrieve a list of IP Commands from your account.
      tags:
        - Retrieve
        - Commands
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
      summary: Retrieve IP Commands
  /v1/IpCommands/{Sid}:
    description: Machine-to-machine IP Commands sent to/from Super SIMs
    get:
      description: Fetch IP Command instance from your account.
      tags:
        - Retrieve
        - Command
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
      summary: Retrieve IP Command
  /v1/Networks/{Sid}:
    description: Mobile operator networks to which Super SIMs can connect
    get:
      description: Fetch a Network resource.
      tags:
        - Retrieve
        - Network
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
        - Networks
      summary: Retrieve Network
  /v1/Networks:
    description: Mobile operator networks to which Super SIMs can connect
    get:
      description: Retrieve a list of Network resources.
      tags:
        - Retrieve
        - Networks
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
        - Networks
      summary: Retrieve Networks
  /v1/NetworkAccessProfiles:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Network Access Profile
      tags:
        - Create
        - Network
        - Access
        - Profile
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
        - Networks
        - Network
        - Access
      summary: Create Network Access Profile
    get:
      description: Retrieve a list of Network Access Profiles from your account.
      tags:
        - Retrieve
        - Network
        - Access
        - Profiles
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
        - Networks
        - Network
        - Access
      summary: Retrieve Network Access Profiles
  /v1/NetworkAccessProfiles/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a Network Access Profile instance from your account.
      tags:
        - Retrieve
        - Network
        - Access
        - Profiles
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
        - Networks
        - Network
        - Access
      summary: Retrieve Network Access Profiles
    post:
      description: >-
        Updates the given properties of a Network Access Profile in your
        account.
      tags:
        - Create
        - Network
        - Access
        - Profile
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
        - Networks
        - Network
        - Access
      summary: Create Network Access Profile
  /v1/NetworkAccessProfiles/{NetworkAccessProfileSid}/Networks:
    description: Mobile operator networks which Network Access Profiles allow access to
    get:
      description: Retrieve a list of Network Access Profile resource's Network resource.
      tags:
        - Retrieve
        - Network
        - Access
        - Profile
        - Networks
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
        - Networks
        - Network
        - Access
        - Profile
      summary: Retrieve Network Access Profile Networks
    post:
      description: Add a Network resource to the Network Access Profile resource.
      tags:
        - Create
        - Network
        - Access
        - Profile
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
        - Networks
        - Network
        - Access
        - Profile
      summary: Create Network Access Profile Network
  /v1/NetworkAccessProfiles/{NetworkAccessProfileSid}/Networks/{Sid}:
    description: Mobile operator networks which Network Access Profiles allow access to
    delete:
      description: Remove a Network resource from the Network Access Profile resource's.
      tags:
        - Delete
        - Network
        - Access
        - Profile
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
        - Networks
        - Network
        - Access
        - Profile
      summary: Delete Network Access Profile Network
    get:
      description: Fetch a Network Access Profile resource's Network resource.
      tags:
        - Retrieve
        - Network
        - Access
        - Profile
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
        - Networks
        - Network
        - Access
        - Profile
      summary: Retrieve Network Access Profile Network
  /v1/SettingsUpdates:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of Settings Updates.
      tags:
        - Retrieve
        - Settings
        - Update
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
        - Networks
        - Network
        - Access
        - Profile
        - Settings
        - Updates
      summary: Retrieve Settings Update
  /v1/Sims:
    description: Individual IoT Super SIMs
    post:
      description: Register a Super SIM to your Account
      tags:
        - Create
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
        - Networks
        - Network
        - Access
        - Profile
        - Settings
        - Updates
      summary: Create SIM
    get:
      description: Retrieve a list of Super SIMs from your account.
      tags:
        - Retrieve
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
        - Networks
        - Network
        - Access
        - Profile
        - Settings
        - Updates
      summary: Retrieve SIM
  /v1/Sims/{Sid}:
    description: Individual IoT Super SIMs
    get:
      description: Fetch a Super SIM instance from your account.
      tags:
        - Retrieve
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
        - Networks
        - Network
        - Access
        - Profile
        - Settings
        - Updates
      summary: Retrieve SIM
    post:
      description: Updates the given properties of a Super SIM instance from your account.
      tags:
        - Update
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
        - Networks
        - Network
        - Access
        - Profile
        - Settings
        - Updates
      summary: Update SIM
  /v1/Sims/{SimSid}/IpAddresses:
    description: IP Addresses for a Super SIM configured to use a VPN connection
    get:
      description: Retrieve a list of IP Addresses for the given Super SIM.
      tags:
        - Retrieve
        - Ddress
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
        - Networks
        - Network
        - Access
        - Profile
        - Settings
        - Updates
        - Addresses
      summary: Retrieve SIM IP ADdress
  /v1/SmsCommands:
    description: Machine-to-machine SMS Commands sent to/from SIMs
    post:
      description: Send SMS Command to a Sim.
      tags:
        - Create
        - Command
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
        - Networks
        - Network
        - Access
        - Profile
        - Settings
        - Updates
        - Addresses
        - Sms
      summary: Create SMS Command
    get:
      description: Retrieve a list of SMS Commands from your account.
      tags:
        - Retrieve
        - Commands
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
        - Networks
        - Network
        - Access
        - Profile
        - Settings
        - Updates
        - Addresses
        - Sms
      summary: Retrieve SMS Commands
  /v1/SmsCommands/{Sid}:
    description: Machine-to-machine SMS Commands sent to/from SIMs
    get:
      description: Fetch SMS Command instance from your account.
      tags:
        - Retrieve
        - Command
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
        - Networks
        - Network
        - Access
        - Profile
        - Settings
        - Updates
        - Addresses
        - Sms
      summary: Retrieve SMS Command
  /v1/UsageRecords:
    description: Usage information for Sim resources
    get:
      description: List UsageRecords
      tags:
        - Retrieve
        - Usage
        - Records
        - Sims
        - Sim
        - Sid
        - Billing
        - Periods
        - Profiles
        - Fleets
        - Ip
        - Commands
        - Networks
        - Network
        - Access
        - Profile
        - Settings
        - Updates
        - Addresses
        - Sms
        - Usage
        - Records
      summary: Retrieve Usage Records
tags:
  - name: Tag
  - name: SIM
    description: Needs a description.
  - name: Billing
    description: Needs a description.
  - name: Periods
    description: Needs a description.
  - name: ESIM
    description: Needs a description.
  - name: Profiles
    description: Needs a description.
  - name: Fleets
    description: Needs a description.
  - name: IP Commands
    description: Needs a description.
  - name: Network
    description: Needs a description.
  - name: Networks
    description: Needs a description.
  - name: Access
    description: Needs a description.
  - name: Settings
    description: Needs a description.
  - name: Update
    description: Needs a description.
  - name: IP Addresses
    description: Needs a description.
  - name: SMS
    description: Needs a description.
  - name: Commands
    description: Needs a description.
  - name: Usage
    description: Needs a description.
  - name: Records
    description: Needs a description.
x-maturity:
  - name: GA
    description: This product is Generally Available.
  - name: Beta
    description: >-
      PLEASE NOTE that this is a Beta product that is subject to change. Use it
      with ca
