info:
  title: Twilio - Sync
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Services/{ServiceSid}/Documents/{Sid}:
    description: Sync Document objects
    get:
      description: ''
      tags:
        - SyncV1Document
    delete:
      description: ''
      tags:
        - SyncV1Document
    post:
      description: ''
      tags:
        - SyncV1Document
  /v1/Services/{ServiceSid}/Documents:
    description: Sync Document objects
    post:
      description: ''
      tags:
        - SyncV1Document
    get:
      description: ''
      tags:
        - SyncV1Document
  /v1/Services/{ServiceSid}/Documents/{DocumentSid}/Permissions/{Identity}:
    description: Sync document permissions
    get:
      description: Fetch a specific Sync Document Permission.
      tags:
        - SyncV1DocumentPermission
    delete:
      description: Delete a specific Sync Document Permission.
      tags:
        - SyncV1DocumentPermission
    post:
      description: Update an identity's access to a specific Sync Document.
      tags:
        - SyncV1DocumentPermission
  /v1/Services/{ServiceSid}/Documents/{DocumentSid}/Permissions:
    description: Sync document permissions
    get:
      description: Retrieve a list of all Permissions applying to a Sync Document.
      tags:
        - SyncV1DocumentPermission
  /v1/Services/{Sid}:
    description: Containers for sync objects
    get:
      description: ''
      tags:
        - SyncV1Service
    delete:
      description: ''
      tags:
        - SyncV1Service
    post:
      description: ''
      tags:
        - SyncV1Service
  /v1/Services:
    description: Containers for sync objects
    post:
      description: ''
      tags:
        - SyncV1Service
    get:
      description: ''
      tags:
        - SyncV1Service
  /v1/Services/{ServiceSid}/Streams/{StreamSid}/Messages:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Stream Message.
      tags:
        - SyncV1StreamMessage
  /v1/Services/{ServiceSid}/Lists/{Sid}:
    description: Sync list objects
    get:
      description: ''
      tags:
        - SyncV1SyncList
    delete:
      description: ''
      tags:
        - SyncV1SyncList
    post:
      description: ''
      tags:
        - SyncV1SyncList
  /v1/Services/{ServiceSid}/Lists:
    description: Sync list objects
    post:
      description: ''
      tags:
        - SyncV1SyncList
    get:
      description: ''
      tags:
        - SyncV1SyncList
  /v1/Services/{ServiceSid}/Lists/{ListSid}/Items/{Index}:
    description: Items in a sync list
    get:
      description: ''
      tags:
        - SyncV1SyncListItem
    delete:
      description: ''
      tags:
        - SyncV1SyncListItem
    post:
      description: ''
      tags:
        - SyncV1SyncListItem
  /v1/Services/{ServiceSid}/Lists/{ListSid}/Items:
    description: Items in a sync list
    post:
      description: ''
      tags:
        - SyncV1SyncListItem
    get:
      description: ''
      tags:
        - SyncV1SyncListItem
  /v1/Services/{ServiceSid}/Lists/{ListSid}/Permissions/{Identity}:
    description: Permissions for Sync list items
    get:
      description: Fetch a specific Sync List Permission.
      tags:
        - SyncV1SyncListPermission
    delete:
      description: Delete a specific Sync List Permission.
      tags:
        - SyncV1SyncListPermission
    post:
      description: Update an identity's access to a specific Sync List.
      tags:
        - SyncV1SyncListPermission
  /v1/Services/{ServiceSid}/Lists/{ListSid}/Permissions:
    description: Permissions for Sync list items
    get:
      description: Retrieve a list of all Permissions applying to a Sync List.
      tags:
        - SyncV1SyncListPermission
  /v1/Services/{ServiceSid}/Maps/{Sid}:
    description: Sync map objects
    get:
      description: ''
      tags:
        - SyncV1SyncMap
    delete:
      description: ''
      tags:
        - SyncV1SyncMap
    post:
      description: ''
      tags:
        - SyncV1SyncMap
  /v1/Services/{ServiceSid}/Maps:
    description: Sync map objects
    post:
      description: ''
      tags:
        - SyncV1SyncMap
    get:
      description: ''
      tags:
        - SyncV1SyncMap
  /v1/Services/{ServiceSid}/Maps/{MapSid}/Items/{Key}:
    description: Keys in a sync map
    get:
      description: ''
      tags:
        - SyncV1SyncMapItem
    delete:
      description: ''
      tags:
        - SyncV1SyncMapItem
    post:
      description: ''
      tags:
        - SyncV1SyncMapItem
  /v1/Services/{ServiceSid}/Maps/{MapSid}/Items:
    description: Keys in a sync map
    post:
      description: ''
      tags:
        - SyncV1SyncMapItem
    get:
      description: ''
      tags:
        - SyncV1SyncMapItem
  /v1/Services/{ServiceSid}/Maps/{MapSid}/Permissions/{Identity}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Sync Map Permission.
      tags:
        - SyncV1SyncMapPermission
    delete:
      description: Delete a specific Sync Map Permission.
      tags:
        - SyncV1SyncMapPermission
    post:
      description: Update an identity's access to a specific Sync Map.
      tags:
        - SyncV1SyncMapPermission
  /v1/Services/{ServiceSid}/Maps/{MapSid}/Permissions:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Permissions applying to a Sync Map.
      tags:
        - SyncV1SyncMapPermission
  /v1/Services/{ServiceSid}/Streams/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Stream.
      tags:
        - SyncV1SyncStream
    delete:
      description: Delete a specific Stream.
      tags:
        - SyncV1SyncStream
    post:
      description: Update a specific Stream.
      tags:
        - SyncV1SyncStream
  /v1/Services/{ServiceSid}/Streams:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Stream.
      tags:
        - SyncV1SyncStream
    get:
      description: Retrieve a list of all Streams in a Service Instance.
      tags:
        - SyncV1SyncStream
tags:
  - name: SyncV1Document
  - name: SyncV1DocumentPermission
  - name: SyncV1Service
  - name: SyncV1StreamMessage
  - name: SyncV1SyncList
  - name: SyncV1SyncListItem
  - name: SyncV1SyncListPermission
  - name: SyncV1SyncMap
  - name: SyncV1SyncMapItem
  - name: SyncV1SyncMapPermission
  - name: SyncV1SyncStream
x-maturity:
  - name: GA
    description: This product is Generally Av
