info:
  title: Twilio - Taskrouter
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Workspaces/{WorkspaceSid}/Activities/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1Activity
    post:
      description: ''
      tags:
        - TaskrouterV1Activity
    delete:
      description: ''
      tags:
        - TaskrouterV1Activity
  /v1/Workspaces/{WorkspaceSid}/Activities:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1Activity
    post:
      description: ''
      tags:
        - TaskrouterV1Activity
  /v1/Workspaces/{WorkspaceSid}/Events/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1Event
  /v1/Workspaces/{WorkspaceSid}/Events:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1Event
  /v1/Workspaces/{WorkspaceSid}/Tasks/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1Task
    post:
      description: ''
      tags:
        - TaskrouterV1Task
    delete:
      description: ''
      tags:
        - TaskrouterV1Task
  /v1/Workspaces/{WorkspaceSid}/Tasks:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1Task
    post:
      description: ''
      tags:
        - TaskrouterV1Task
  /v1/Workspaces/{WorkspaceSid}/TaskChannels/{Sid}:
    description: Types of tasks
    get:
      description: ''
      tags:
        - TaskrouterV1TaskChannel
    post:
      description: ''
      tags:
        - TaskrouterV1TaskChannel
    delete:
      description: ''
      tags:
        - TaskrouterV1TaskChannel
  /v1/Workspaces/{WorkspaceSid}/TaskChannels:
    description: Types of tasks
    get:
      description: ''
      tags:
        - TaskrouterV1TaskChannel
    post:
      description: ''
      tags:
        - TaskrouterV1TaskChannel
  /v1/Workspaces/{WorkspaceSid}/TaskQueues/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1TaskQueue
    post:
      description: ''
      tags:
        - TaskrouterV1TaskQueue
    delete:
      description: ''
      tags:
        - TaskrouterV1TaskQueue
  /v1/Workspaces/{WorkspaceSid}/TaskQueues:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1TaskQueue
    post:
      description: ''
      tags:
        - TaskrouterV1TaskQueue
  /v1/Workspaces/{WorkspaceSid}/TaskQueues/RealTimeStatistics:
    description: 'TODO: Resource-level docs'
  /v1/Workspaces/{WorkspaceSid}/TaskQueues/{TaskQueueSid}/CumulativeStatistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1TaskQueueCumulativeStatistics
  /v1/Workspaces/{WorkspaceSid}/TaskQueues/{TaskQueueSid}/RealTimeStatistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1TaskQueueRealTimeStatistics
  /v1/Workspaces/{WorkspaceSid}/TaskQueues/{TaskQueueSid}/Statistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1TaskQueueStatistics
  /v1/Workspaces/{WorkspaceSid}/TaskQueues/Statistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1TaskQueuesStatistics
  /v1/Workspaces/{WorkspaceSid}/Tasks/{TaskSid}/Reservations:
    description: Tasks reserved for workers
    get:
      description: ''
      tags:
        - TaskrouterV1Reservation
  /v1/Workspaces/{WorkspaceSid}/Tasks/{TaskSid}/Reservations/{Sid}:
    description: Tasks reserved for workers
    get:
      description: ''
      tags:
        - TaskrouterV1Reservation
    post:
      description: ''
      tags:
        - TaskrouterV1Reservation
  /v1/Workspaces/{WorkspaceSid}/Workers:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1Worker
    post:
      description: ''
      tags:
        - TaskrouterV1Worker
  /v1/Workspaces/{WorkspaceSid}/Workers/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1Worker
    post:
      description: ''
      tags:
        - TaskrouterV1Worker
    delete:
      description: ''
      tags:
        - TaskrouterV1Worker
  /v1/Workspaces/{WorkspaceSid}/Workers/{WorkerSid}/Channels:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1WorkerChannel
  /v1/Workspaces/{WorkspaceSid}/Workers/{WorkerSid}/Channels/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1WorkerChannel
    post:
      description: ''
      tags:
        - TaskrouterV1WorkerChannel
  /v1/Workspaces/{WorkspaceSid}/Workers/{WorkerSid}/Statistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1WorkerStatistics
  /v1/Workspaces/{WorkspaceSid}/Workers/{WorkerSid}/Reservations:
    description: Current and past reservations for a worker
    get:
      description: ''
      tags:
        - TaskrouterV1Reservation
  /v1/Workspaces/{WorkspaceSid}/Workers/{WorkerSid}/Reservations/{Sid}:
    description: Current and past reservations for a worker
    get:
      description: ''
      tags:
        - TaskrouterV1Reservation
    post:
      description: ''
      tags:
        - TaskrouterV1Reservation
  /v1/Workspaces/{WorkspaceSid}/Workers/Statistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1WorkersStatistics
  /v1/Workspaces/{WorkspaceSid}/Workers/CumulativeStatistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1WorkersCumulativeStatistics
  /v1/Workspaces/{WorkspaceSid}/Workers/RealTimeStatistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1WorkersRealTimeStatistics
  /v1/Workspaces/{WorkspaceSid}/Workflows/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1Workflow
    post:
      description: ''
      tags:
        - TaskrouterV1Workflow
    delete:
      description: ''
      tags:
        - TaskrouterV1Workflow
  /v1/Workspaces/{WorkspaceSid}/Workflows:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1Workflow
    post:
      description: ''
      tags:
        - TaskrouterV1Workflow
  /v1/Workspaces/{WorkspaceSid}/Workflows/{WorkflowSid}/CumulativeStatistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1WorkflowCumulativeStatistics
  /v1/Workspaces/{WorkspaceSid}/Workflows/{WorkflowSid}/RealTimeStatistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1WorkflowRealTimeStatistics
  /v1/Workspaces/{WorkspaceSid}/Workflows/{WorkflowSid}/Statistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1WorkflowStatistics
  /v1/Workspaces/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1Workspace
    post:
      description: ''
      tags:
        - TaskrouterV1Workspace
    delete:
      description: ''
      tags:
        - TaskrouterV1Workspace
  /v1/Workspaces:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1Workspace
    post:
      description: ''
      tags:
        - TaskrouterV1Workspace
  /v1/Workspaces/{WorkspaceSid}/CumulativeStatistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1WorkspaceCumulativeStatistics
  /v1/Workspaces/{WorkspaceSid}/RealTimeStatistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1WorkspaceRealTimeStatistics
  /v1/Workspaces/{WorkspaceSid}/Statistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - TaskrouterV1WorkspaceStatistics
tags:
  - name: TaskrouterV1Activity
  - name: TaskrouterV1Event
  - name: TaskrouterV1Reservation
  - name: TaskrouterV1Task
  - name: TaskrouterV1TaskChannel
  - name: TaskrouterV1TaskQueue
  - name: TaskrouterV1TaskQueueCumulativeStatistics
  - name: TaskrouterV1TaskQueueRealTimeStatistics
  - name: TaskrouterV1TaskQueueStatistics
  - name: TaskrouterV1TaskQueuesStatistics
  - name: TaskrouterV1Worker
  - name: TaskrouterV1WorkerChannel
  - name: TaskrouterV1WorkerStatistics
  - name: TaskrouterV1WorkersCumulativeStatistics
  - name: TaskrouterV1WorkersRealTimeStatistics
  - name: TaskrouterV1WorkersStatistics
  - name: TaskrouterV1Workflow
  - name: TaskrouterV1WorkflowCumulativeStatistics
  - name: TaskrouterV1WorkflowRealTimeStatistics
  - name: TaskrouterV1WorkflowStatistics
  - name: TaskrouterV1Workspace
  - name: TaskrouterV1WorkspaceCumulativeStatistics
  - name: TaskrouterV1WorkspaceRealTimeStatistics
  - name: TaskrouterV1WorkspaceStatistics
x-maturity:
  - name: GA
    description: This product is Generally Av
