info:
  title: Twilio Trunking API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Trunks/{TrunkSid}/CredentialLists/{Sid}:
    description: List of credentials for accessing a trunk
    get:
      description: ''
      tags:
        - Retrieve
        - Trunk
        - Credential
        - List
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
      summary: Retrieve Trunk Credential List
    delete:
      description: ''
      tags:
        - Delete
        - Trunk
        - Credential
        - List
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
      summary: Delete Trunk Credential List
  /v1/Trunks/{TrunkSid}/CredentialLists:
    description: List of credentials for accessing a trunk
    post:
      description: ''
      tags:
        - Retrieve
        - Trunk
        - Credential
        - Lists
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
      summary: Retrieve Trunk Credential Lists
    get:
      description: ''
      tags:
        - Retrieve
        - Trunk
        - Credential
        - List
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
      summary: Retrieve Trunk Credential List
  /v1/Trunks/{TrunkSid}/IpAccessControlLists/{Sid}:
    description: List of IP addresses for accessing a trunk
    get:
      description: ''
      tags:
        - Retrieve
        - Trunk
        - Access
        - Control
        - List
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
      summary: Retrieve Trunk IP Access Control List
    delete:
      description: Remove an associated IP Access Control List from a Trunk
      tags:
        - Delete
        - Trunk
        - Access
        - Control
        - List
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
      summary: Delete Trunk IP Access Control List
  /v1/Trunks/{TrunkSid}/IpAccessControlLists:
    description: List of IP addresses for accessing a trunk
    post:
      description: Associate an IP Access Control List with a Trunk
      tags:
        - Create
        - Trunk
        - Access
        - Control
        - List
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
      summary: Create Trunk IP Access Control List
    get:
      description: List all IP Access Control Lists for a Trunk
      tags:
        - Retrieve
        - Trunk
        - Access
        - Control
        - List
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
      summary: Retrieve Trunk IP Access Control List
  /v1/Trunks/{TrunkSid}/OriginationUrls/{Sid}:
    description: Network element entry points into your communications infrastructure
    get:
      description: ''
      tags:
        - Retrieve
        - Trunk
        - Origination
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
      summary: Retrieve Trunk Origination URL
    delete:
      description: ''
      tags:
        - Delete
        - Trunk
        - Origination
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
      summary: Delete Trunk Origination URL
    post:
      description: ''
      tags:
        - Update
        - Trunk
        - Origination
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
      summary: Update Trunk Origination URL
  /v1/Trunks/{TrunkSid}/OriginationUrls:
    description: Network element entry points into your communications infrastructure
    post:
      description: ''
      tags:
        - Create
        - Trunk
        - Origination
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
      summary: Create Trunk Origination URL
    get:
      description: ''
      tags:
        - Retrieve
        - Trunk
        - Origination
        - Ls
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
      summary: Retrieve Trunk Origination URLs
  /v1/Trunks/{TrunkSid}/PhoneNumbers/{Sid}:
    description: Phone numbers associated with trunks
    get:
      description: ''
      tags:
        - Retrieve
        - Trunk
        - Phone
        - Number
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
      summary: Retrieve Trunk Phone Number
    delete:
      description: ''
      tags:
        - Delete
        - Trunk
        - Phone
        - Number
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
      summary: Delete Trunk Phone Number
  /v1/Trunks/{TrunkSid}/PhoneNumbers:
    description: Phone numbers associated with trunks
    post:
      description: ''
      tags:
        - Create
        - Trunk
        - Phone
        - Number
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
      summary: Create Trunk Phone Number
    get:
      description: ''
      tags:
        - Retrieve
        - Trunk
        - Phone
        - Numbers
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
      summary: Retrieve Trunk Phone Numbers
  /v1/Trunks/{TrunkSid}/Recording:
    description: Recording settings for a trunk
    get:
      description: ''
      tags:
        - Retrieve
        - Trunk
        - Recording
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
        - Recording
      summary: Retrieve Trunk Recording
    post:
      description: ''
      tags:
        - Create
        - Trunk
        - Recording
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
        - Recording
      summary: Create Trunk Recording
  /v1/Trunks/{Sid}:
    description: Represents a SIP trunk
    get:
      description: ''
      tags:
        - Retrieve
        - Trunk
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
        - Recording
      summary: Retrieve Trunk
    delete:
      description: ''
      tags:
        - Delete
        - Trunk
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
        - Recording
      summary: Delete Trunk
    post:
      description: ''
      tags:
        - Update
        - Trunk
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
        - Recording
      summary: Update Trunk
  /v1/Trunks:
    description: Represents a SIP trunk
    post:
      description: ''
      tags:
        - Create
        - Trunk
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
        - Recording
      summary: Create Trunk
    get:
      description: ''
      tags:
        - Retrieve
        - Trunks
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
        - Recording
      summary: Retrieve Trunks
tags:
  - name: Tag
  - name: Trunking
    description: Needs a description.
  - name: Trunks
    description: Needs a description.
  - name: Credentials
    description: Needs a description.
  - name: Lists
    description: Needs a description.
  - name: IP Addresses
    description: Needs a description.
  - name: Access Control
    description: Needs a description.
  - name: Origination
    description: Needs a description.
  - name: URL
    description: Needs a description.
  - name: Phone Number
    description: Needs a description.
  - name: Numbers
    description: Needs a description.
  - name: Recording
    description: Needs a description.
x-maturity:
  - name: GA
    description: This product is Generally Avai
