info:
  title: Twilio - Trusthub
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/ComplianceInquiries/Customers/Initialize:
    description: 'TODO: Resource-level docs'
    post:
      description: >-
        Create a new Compliance Inquiry for the authenticated account. This is
        necessary to start a new embedded session.
      tags:
        - TrusthubV1ComplianceInquiries
  /v1/ComplianceInquiries/Customers/{CustomerId}/Initialize:
    description: 'TODO: Resource-level docs'
    post:
      description: >-
        Resume a specific Compliance Inquiry that has expired, or re-open a
        rejected Compliance Inquiry for editing.
      tags:
        - TrusthubV1ComplianceInquiries
  /v1/ComplianceInquiries/Tollfree/Initialize:
    description: 'TODO: Resource-level docs'
    post:
      description: >-
        Create a new Compliance Tollfree Verification Inquiry for the
        authenticated account. This is necessary to start a new embedded
        session.
      tags:
        - TrusthubV1ComplianceTollfreeInquiries
  /v1/CustomerProfiles:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Customer-Profile.
      tags:
        - TrusthubV1CustomerProfiles
    get:
      description: Retrieve a list of all Customer-Profiles for an account.
      tags:
        - TrusthubV1CustomerProfiles
  /v1/CustomerProfiles/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Customer-Profile instance.
      tags:
        - TrusthubV1CustomerProfiles
    post:
      description: Updates a Customer-Profile in an account.
      tags:
        - TrusthubV1CustomerProfiles
    delete:
      description: Delete a specific Customer-Profile.
      tags:
        - TrusthubV1CustomerProfiles
  /v1/CustomerProfiles/{CustomerProfileSid}/ChannelEndpointAssignments:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Assigned Item.
      tags:
        - TrusthubV1CustomerProfilesChannelEndpointAssignment
    get:
      description: Retrieve a list of all Assigned Items for an account.
      tags:
        - TrusthubV1CustomerProfilesChannelEndpointAssignment
  /v1/CustomerProfiles/{CustomerProfileSid}/ChannelEndpointAssignments/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Assigned Item Instance.
      tags:
        - TrusthubV1CustomerProfilesChannelEndpointAssignment
    delete:
      description: Remove an Assignment Item Instance.
      tags:
        - TrusthubV1CustomerProfilesChannelEndpointAssignment
  /v1/CustomerProfiles/{CustomerProfileSid}/EntityAssignments:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Assigned Item.
      tags:
        - TrusthubV1CustomerProfilesEntityAssignments
    get:
      description: Retrieve a list of all Assigned Items for an account.
      tags:
        - TrusthubV1CustomerProfilesEntityAssignments
  /v1/CustomerProfiles/{CustomerProfileSid}/EntityAssignments/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Assigned Item Instance.
      tags:
        - TrusthubV1CustomerProfilesEntityAssignments
    delete:
      description: Remove an Assignment Item Instance.
      tags:
        - TrusthubV1CustomerProfilesEntityAssignments
  /v1/CustomerProfiles/{CustomerProfileSid}/Evaluations:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Evaluation
      tags:
        - TrusthubV1CustomerProfilesEvaluations
    get:
      description: >-
        Retrieve a list of Evaluations associated to the customer_profile
        resource.
      tags:
        - TrusthubV1CustomerProfilesEvaluations
  /v1/CustomerProfiles/{CustomerProfileSid}/Evaluations/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Evaluation Instance.
      tags:
        - TrusthubV1CustomerProfilesEvaluations
  /v1/EndUsers:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new End User.
      tags:
        - TrusthubV1EndUser
    get:
      description: Retrieve a list of all End User for an account.
      tags:
        - TrusthubV1EndUser
  /v1/EndUsers/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific End User Instance.
      tags:
        - TrusthubV1EndUser
    post:
      description: Update an existing End User.
      tags:
        - TrusthubV1EndUser
    delete:
      description: Delete a specific End User.
      tags:
        - TrusthubV1EndUser
  /v1/EndUserTypes:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all End-User Types.
      tags:
        - TrusthubV1EndUserType
  /v1/EndUserTypes/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific End-User Type Instance.
      tags:
        - TrusthubV1EndUserType
  /v1/Policies:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Policys.
      tags:
        - TrusthubV1Policies
  /v1/Policies/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Policy Instance.
      tags:
        - TrusthubV1Policies
  /v1/SupportingDocuments:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Supporting Document.
      tags:
        - TrusthubV1SupportingDocument
    get:
      description: Retrieve a list of all Supporting Document for an account.
      tags:
        - TrusthubV1SupportingDocument
  /v1/SupportingDocuments/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Supporting Document Instance.
      tags:
        - TrusthubV1SupportingDocument
    post:
      description: Update an existing Supporting Document.
      tags:
        - TrusthubV1SupportingDocument
    delete:
      description: Delete a specific Supporting Document.
      tags:
        - TrusthubV1SupportingDocument
  /v1/SupportingDocumentTypes:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Supporting Document Types.
      tags:
        - TrusthubV1SupportingDocumentType
  /v1/SupportingDocumentTypes/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Supporting Document Type Instance.
      tags:
        - TrusthubV1SupportingDocumentType
  /v1/TrustProducts:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Customer-Profile.
      tags:
        - TrusthubV1TrustProducts
    get:
      description: Retrieve a list of all Customer-Profiles for an account.
      tags:
        - TrusthubV1TrustProducts
  /v1/TrustProducts/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Customer-Profile instance.
      tags:
        - TrusthubV1TrustProducts
    post:
      description: Updates a Customer-Profile in an account.
      tags:
        - TrusthubV1TrustProducts
    delete:
      description: Delete a specific Customer-Profile.
      tags:
        - TrusthubV1TrustProducts
  /v1/TrustProducts/{TrustProductSid}/ChannelEndpointAssignments:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Assigned Item.
      tags:
        - TrusthubV1TrustProductsChannelEndpointAssignment
    get:
      description: Retrieve a list of all Assigned Items for an account.
      tags:
        - TrusthubV1TrustProductsChannelEndpointAssignment
  /v1/TrustProducts/{TrustProductSid}/ChannelEndpointAssignments/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Assigned Item Instance.
      tags:
        - TrusthubV1TrustProductsChannelEndpointAssignment
    delete:
      description: Remove an Assignment Item Instance.
      tags:
        - TrusthubV1TrustProductsChannelEndpointAssignment
  /v1/TrustProducts/{TrustProductSid}/EntityAssignments:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Assigned Item.
      tags:
        - TrusthubV1TrustProductsEntityAssignments
    get:
      description: Retrieve a list of all Assigned Items for an account.
      tags:
        - TrusthubV1TrustProductsEntityAssignments
  /v1/TrustProducts/{TrustProductSid}/EntityAssignments/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Assigned Item Instance.
      tags:
        - TrusthubV1TrustProductsEntityAssignments
    delete:
      description: Remove an Assignment Item Instance.
      tags:
        - TrusthubV1TrustProductsEntityAssignments
  /v1/TrustProducts/{TrustProductSid}/Evaluations:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Evaluation
      tags:
        - TrusthubV1TrustProductsEvaluations
    get:
      description: Retrieve a list of Evaluations associated to the trust_product resource.
      tags:
        - TrusthubV1TrustProductsEvaluations
  /v1/TrustProducts/{TrustProductSid}/Evaluations/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Evaluation Instance.
      tags:
        - TrusthubV1TrustProductsEvaluations
tags:
  - name: TrusthubV1ComplianceInquiries
  - name: TrusthubV1ComplianceTollfreeInquiries
  - name: TrusthubV1CustomerProfiles
  - name: TrusthubV1CustomerProfilesChannelEndpointAssignment
  - name: TrusthubV1CustomerProfilesEntityAssignments
  - name: TrusthubV1CustomerProfilesEvaluations
  - name: TrusthubV1EndUser
  - name: TrusthubV1EndUserType
  - name: TrusthubV1Policies
  - name: TrusthubV1SupportingDocument
  - name: TrusthubV1SupportingDocumentType
  - name: TrusthubV1TrustProducts
  - name: TrusthubV1TrustProductsChannelEndpointAssignment
  - name: TrusthubV1TrustProductsEntityAssignments
  - name: TrusthubV1TrustProductsEvaluations
x-maturity:
  - name: GA
    description: This product is Generally Av
