info:
  title: Twilio - Verify
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v2/Services/{ServiceSid}/AccessTokens:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new enrollment Access Token for the Entity
      tags:
        - VerifyV2AccessToken
  /v2/Services/{ServiceSid}/AccessTokens/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch an Access Token for the Entity
      tags:
        - VerifyV2AccessToken
  /v2/Services/{ServiceSid}/RateLimits/{RateLimitSid}/Buckets:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Bucket for a Rate Limit
      tags:
        - VerifyV2Bucket
    get:
      description: Retrieve a list of all Buckets for a Rate Limit.
      tags:
        - VerifyV2Bucket
  /v2/Services/{ServiceSid}/RateLimits/{RateLimitSid}/Buckets/{Sid}:
    description: 'TODO: Resource-level docs'
    post:
      description: Update a specific Bucket.
      tags:
        - VerifyV2Bucket
    get:
      description: Fetch a specific Bucket.
      tags:
        - VerifyV2Bucket
    delete:
      description: Delete a specific Bucket.
      tags:
        - VerifyV2Bucket
  /v2/Services/{ServiceSid}/Entities/{Identity}/Challenges:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Challenge for the Factor
      tags:
        - VerifyV2Challenge
    get:
      description: Retrieve a list of all Challenges for a Factor.
      tags:
        - VerifyV2Challenge
  /v2/Services/{ServiceSid}/Entities/{Identity}/Challenges/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Challenge.
      tags:
        - VerifyV2Challenge
    post:
      description: Verify a specific Challenge.
      tags:
        - VerifyV2Challenge
  /v2/Services/{ServiceSid}/Entities:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Entity for the Service
      tags:
        - VerifyV2Entity
    get:
      description: Retrieve a list of all Entities for a Service.
      tags:
        - VerifyV2Entity
  /v2/Services/{ServiceSid}/Entities/{Identity}:
    description: 'TODO: Resource-level docs'
    delete:
      description: Delete a specific Entity.
      tags:
        - VerifyV2Entity
    get:
      description: Fetch a specific Entity.
      tags:
        - VerifyV2Entity
  /v2/Services/{ServiceSid}/Entities/{Identity}/Factors/{Sid}:
    description: 'TODO: Resource-level docs'
    delete:
      description: Delete a specific Factor.
      tags:
        - VerifyV2Factor
    get:
      description: Fetch a specific Factor.
      tags:
        - VerifyV2Factor
    post:
      description: >-
        Update a specific Factor. This endpoint can be used to Verify a Factor
        if passed an `AuthPayload` param.
      tags:
        - VerifyV2Factor
  /v2/Services/{ServiceSid}/Entities/{Identity}/Factors:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Factors for an Entity.
      tags:
        - VerifyV2Factor
    post:
      description: Create a new Factor for the Entity
      tags:
        - VerifyV2NewFactor
  /v2/Forms/{FormType}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch the forms for a specific Form Type.
      tags:
        - VerifyV2Form
  /v2/Services/{ServiceSid}/MessagingConfigurations:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new MessagingConfiguration for a service.
      tags:
        - VerifyV2MessagingConfiguration
    get:
      description: Retrieve a list of all Messaging Configurations for a Service.
      tags:
        - VerifyV2MessagingConfiguration
  /v2/Services/{ServiceSid}/MessagingConfigurations/{Country}:
    description: 'TODO: Resource-level docs'
    post:
      description: Update a specific MessagingConfiguration
      tags:
        - VerifyV2MessagingConfiguration
    get:
      description: Fetch a specific MessagingConfiguration.
      tags:
        - VerifyV2MessagingConfiguration
    delete:
      description: Delete a specific MessagingConfiguration.
      tags:
        - VerifyV2MessagingConfiguration
  /v2/Services/{ServiceSid}/Entities/{Identity}/Challenges/{ChallengeSid}/Notifications:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Notification for the corresponding Challenge
      tags:
        - VerifyV2Notification
  /v2/Services/{ServiceSid}/RateLimits:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Rate Limit for a Service
      tags:
        - VerifyV2RateLimit
    get:
      description: Retrieve a list of all Rate Limits for a service.
      tags:
        - VerifyV2RateLimit
  /v2/Services/{ServiceSid}/RateLimits/{Sid}:
    description: 'TODO: Resource-level docs'
    post:
      description: Update a specific Rate Limit.
      tags:
        - VerifyV2RateLimit
    get:
      description: Fetch a specific Rate Limit.
      tags:
        - VerifyV2RateLimit
    delete:
      description: Delete a specific Rate Limit.
      tags:
        - VerifyV2RateLimit
  /v2/SafeList/Numbers:
    description: 'TODO: Resource-level docs'
    post:
      description: Add a new phone number to SafeList.
      tags:
        - VerifyV2Safelist
  /v2/SafeList/Numbers/{PhoneNumber}:
    description: 'TODO: Resource-level docs'
    get:
      description: Check if a phone number exists in SafeList.
      tags:
        - VerifyV2Safelist
    delete:
      description: Remove a phone number from SafeList.
      tags:
        - VerifyV2Safelist
  /v2/Services:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Verification Service.
      tags:
        - VerifyV2Service
    get:
      description: Retrieve a list of all Verification Services for an account.
      tags:
        - VerifyV2Service
  /v2/Services/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Verification Service Instance.
      tags:
        - VerifyV2Service
    delete:
      description: Delete a specific Verification Service Instance.
      tags:
        - VerifyV2Service
    post:
      description: Update a specific Verification Service.
      tags:
        - VerifyV2Service
  /v2/Services/{ServiceSid}/Verifications:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Verification using a Service
      tags:
        - VerifyV2Verification
  /v2/Services/{ServiceSid}/Verifications/{Sid}:
    description: 'TODO: Resource-level docs'
    post:
      description: Update a Verification status
      tags:
        - VerifyV2Verification
    get:
      description: Fetch a specific Verification
      tags:
        - VerifyV2Verification
  /v2/Attempts:
    description: 'TODO: Resource-level docs'
    get:
      description: List all the verification attempts for a given Account.
      tags:
        - VerifyV2VerificationAttempt
  /v2/Attempts/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific verification attempt.
      tags:
        - VerifyV2VerificationAttempt
  /v2/Attempts/Summary:
    description: 'TODO: Resource-level docs'
    get:
      description: >-
        Get a summary of how many attempts were made and how many were
        converted.
      tags:
        - VerifyV2VerificationAttemptsSummary
  /v2/Services/{ServiceSid}/VerificationCheck:
    description: 'TODO: Resource-level docs'
    post:
      description: challenge a specific Verification Check.
      tags:
        - VerifyV2VerificationCheck
  /v2/Templates:
    description: 'TODO: Resource-level docs'
    get:
      description: List all the available templates for a given Account.
      tags:
        - VerifyV2Template
  /v2/Services/{ServiceSid}/Webhooks:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Webhook for the Service
      tags:
        - VerifyV2Webhook
    get:
      description: Retrieve a list of all Webhooks for a Service.
      tags:
        - VerifyV2Webhook
  /v2/Services/{ServiceSid}/Webhooks/{Sid}:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - VerifyV2Webhook
    delete:
      description: Delete a specific Webhook.
      tags:
        - VerifyV2Webhook
    get:
      description: Fetch a specific Webhook.
      tags:
        - VerifyV2Webhook
tags:
  - name: VerifyV2AccessToken
  - name: VerifyV2Bucket
  - name: VerifyV2Challenge
  - name: VerifyV2Entity
  - name: VerifyV2Factor
  - name: VerifyV2Form
  - name: VerifyV2MessagingConfiguration
  - name: VerifyV2NewFactor
  - name: VerifyV2Notification
  - name: VerifyV2RateLimit
  - name: VerifyV2Safelist
  - name: VerifyV2Service
  - name: VerifyV2Template
  - name: VerifyV2Verification
  - name: VerifyV2VerificationAttempt
  - name: VerifyV2VerificationAttemptsSummary
  - name: VerifyV2VerificationCheck
  - name: VerifyV2Webhook
x-maturity:
  - name: GA
    description: This product is Generally Available.
  - name: Beta
    description: >-
      PLEASE NOTE that this is a Beta product that is subject to change. Use it
      with 
