info:
  title: Twilio Wireless API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/UsageRecords:
    description: Aggregated Usage information for all SIMs on an Account
    get:
      description: ''
      tags:
        - Wireless
        - Usage
        - Records
      summary: Retrieve Usage Records
  /v1/Commands/{Sid}:
    description: Machine-to-machine commands sent to/from devices
    get:
      description: Fetch a Command instance from your account.
      tags:
        - Wireless
        - Commands
      summary: Retrieve Command
    delete:
      description: Delete a Command instance from your account.
      tags:
        - Wireless
        - Commands
      summary: Delete Command
  /v1/Commands:
    description: Machine-to-machine commands sent to/from devices
    get:
      description: Retrieve a list of Commands from your account.
      tags:
        - Wireless
        - Commands
      summary: Retrieve Commands
    post:
      description: Send a Command to a Sim.
      tags:
        - Wireless
        - Commands
      summary: Create Command
  /v1/Sims/{SimSid}/DataSessions:
    description: Data session information for SIMs
    get:
      description: ''
      tags:
        - Wireless
        - SIM
        - Data
        - Sessions
      summary: Retrieve SIMS Data Sessions
  /v1/RatePlans:
    description: Capabilities and restrictions for SIMs
    get:
      description: ''
      tags:
        - Wireless
        - Rate Plans
      summary: Retrieve Rate Plans
    post:
      description: ''
      tags:
        - Wireless
        - Rate Plans
      summary: Create Rate Plan
  /v1/RatePlans/{Sid}:
    description: Capabilities and restrictions for SIMs
    get:
      description: ''
      tags:
        - Wireless
        - Rate Plans
      summary: Retrieve Rate Plan
    post:
      description: ''
      tags:
        - Wireless
        - Rate Plans
      summary: Update Rate Plan
    delete:
      description: ''
      tags:
        - Wireless
        - Rate Plans
      summary: Delete Rate Plan
  /v1/Sims/{Sid}:
    description: A resource representing a Programmable Wireless SIM
    get:
      description: Fetch a Sim resource on your Account.
      tags:
        - Wireless
        - SIM
      summary: Retrieve SIM
    post:
      description: Updates the given properties of a Sim resource on your Account.
      tags:
        - Wireless
        - SIM
      summary: Update SIM
    delete:
      description: Delete a Sim resource on your Account.
      tags:
        - Wireless
        - SIM
      summary: Delete SIM
  /v1/Sims:
    description: A resource representing a Programmable Wireless SIM
    get:
      description: Retrieve a list of Sim resources on your Account.
      tags:
        - Wireless
        - SIM
      summary: Retrieve SIMs
  /v1/Sims/{SimSid}/UsageRecords:
    description: Usage information for SIMs
    get:
      description: ''
      tags:
        - Wireless
        - SIM
      summary: Retrieve SIM Usage Records
tags:
  - name: Tag
  - name: Wireless
    description: Needs a description.
  - name: Usage
    description: Needs a description.
  - name: Records
    description: Needs a description.
  - name: Commands
    description: Needs a description.
  - name: SIMS
    description: Needs a description.
  - name: Data
    description: Needs a description.
  - name: Sessions
    description: Needs a description.
  - name: Rate Plans
    description: Needs a description.
  - name: SIM
    description: Needs a description.
x-maturity:
  - name: GA
    description: This product is Generally Available.
