openapi: 3.0.0
info:
  title: CTS Data Dictionary API
paths:
  /navigator/products:
    get:
      tags:
        - navigator
      summary: Get the list of products for Navigator.
  /navigator/data_items/{Product_id}:
    get:
      tags:
        - navigator
      summary: Get the list of data items associated with a product for Navigator.
  /navigator/sources/{DataItem_id}:
    get:
      tags:
        - navigator
      summary: >-
        Get a list of sources where the specified data item can be found, for
        each delivery method, filtered to the appearances of the given data item
        within the specified product.
  /navigator/sources:
    get:
      tags:
        - navigator
      summary: Get a list of sources by delivery method for the given product_id
  /navigator/table_fields/{Table_id}:
    get:
      tags:
        - navigator
      summary: >-
        Get the list of fields associated with a table for Navigator, and the
        code information for the specified data item, if applicable.
  /navigator/basic_search:
    post:
      tags:
        - navigator
      summary: >-
        Returns the data items (along with the products they belong to) that
        contain at least one of the search terms as a substring of either their
        name or description.
      requestBody:
        description: A list of search terms (each term must be at least two characters).
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BasicSearchRequest'
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicSearchResponse'
        '400':
          description: The request body was not formatted properly.
        '401':
          description: You are not authorized to view this page.
ary: >-
        Returns the data items (along with the products they belong to) that
        contain at least one of the search terms as a substring of either their
        name or description.
      requestBody:
        description: A list of search terms (each term must be at least two characters).
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BasicSearchRequest'
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicSearchResponse'
        '400':
          description: The request body was not formatted properly.
        '401':
          description: You are not authorized to view this page.
: A list of search terms (each term must be at least two characters).
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BasicSearchRequest'
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicSearchResponse'
        '400':
          description: The request body was not formatted properly.
        '401':
          description: You are not authorized to view this page.
g with the products they belong to) that
        contain at least one of the search terms as a substring of either their
        name or description.
      requestBody:
        description: A list of search terms (each term must be at least two characters).
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BasicSearchRequest'
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicSearchResponse'
        '400':
          description: The request body was not formatted properly.
        '401':
          description: You are not authorized to view this page.
requestBody:
        description: A list of search terms (each term must be at least two characters).
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BasicSearchRequest'
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicSearchResponse'
        '400':
          description: The request body was not formatted properly.
        '401':
          description: You are not authorized to view this page.
