openapi: 3.0.1
info:
  title: FactSet Digital Cards API
  description: ''
paths:
  /v1/company/{component}/adaptive-card:
    parameters:
      - name: component
        in: path
        required: true
        description: Card name
        schema:
          type: string
          enum:
            - profile
            - event-calendar
      - name: ids
        in: query
        required: true
        description: Public company tickers (comma delimited)
        schema:
          type: string
          default: FDS-US
      - name: format
        in: query
        description: >-
          Return data in different format. By default adaptive cards will be
          returned in key (ticker) value (adaptive card) pairs in a object.
          Table option would return adaptive cards in an array
        schema:
          type: string
          enum:
            - table
      - name: thumbnail
        in: query
        description: Whether or not to include a thumbnail card in the return data
        schema:
          type: boolean
          enum:
            - true
            - false
    get:
      tags:
        - Digital Card
      summary: Retrieve Multiple Digital Cards in Microsoft Adaptive Card Format.
  /v1/company/{component}/adaptive-card/{id}:
    parameters:
      - name: component
        in: path
        required: true
        description: Card name
        schema:
          type: string
          enum:
            - profile
            - event-calendar
      - name: id
        in: path
        required: true
        description: Public company ticker
        schema:
          type: string
          default: FDS-US
    get:
      tags:
        - Digital Card
      summary: Retrieve One Digital Card in Microsoft Adaptive Card Format.
      responses:
        '200':
          description: Digital Card JSON received.
          headers:
            Content-Encoding:
              description: >-
                Standard HTTP header. Header value based on Accept-Encoding
                Request header.
              schema:
                type: string
            Content-Type:
              description: Standard HTTP header.
              schema:
                type: string
          content:
            application/json:
              examples:
                objectExample1:
                  $ref: '#/components/examples/OneProfileCard'
                objectExample2:
                  $ref: '#/components/examples/OneEventCalendarCard'
        '400':
          description: >-
            Bad Request. For further assistance, file an issue under "Workflow &
            Throttling - 400 or 429 Response" using `Report Issue` at the top of
            this page, including the X-DataDirect-Request-Key from the header to
            assist in troubleshooting.
          headers:
            X-DataDirect-Request-Key:
              schema:
                type: string
              description: FactSet request ID
            Api-Supported-Versions:
              schema:
                type: string
              description: Supported API major versions
            Api-Version:
              schema:
                type: string
              description: API version (semantic versioning)
        '401':
          description: >-
            Missing or invalid authentication. Ensure you are logged in and have
            successfully generated an API KEY for the IP range you are
            connecting from. For further assistance, file an issue under
            "Connectivty - 401 or 403 Responses" using `Report Issue` at the top
            of this page, including the X-DataDirect-Request-Key from the header
            to assist in troubleshooting.
          headers:
            X-DataDirect-Request-Key:
              schema:
                type: string
              description: FactSet request ID
        '404':
          description: >-
            Not found. For further assistance, file an issue under "Performance
            - 404 and 500 Responses" using `Report Issue` at the top of this
            page, including the X-DataDirect-Request-Key from the header to
            assist in troubleshooting.
          headers:
            X-DataDirect-Request-Key:
              schema:
                type: string
              description: FactSet request ID
        '429':
          description: >-
            Too many requests - this API is rate-limited to 20 requests per
            second. For further assistance, file an issue under "Workflow &
            Throttling - 400 or 429 Response" using `Report Issue` at the top of
            this page, including the X-DataDirect-Request-Key from the header to
            assist in troubleshooting.
          headers:
            X-DataDirect-Request-Key:
              schema:
                type: string
              description: FactSet request ID
        '500':
          description: >-
            Server error. For further assistance, file an issue under
            "Performance - 404 and 500 Responses" using `Report Issue` at the
            top of this page, including the X-DataDirect-Request-Key from the
            header to assist in troubleshooting
          headers:
            X-DataDirect-Request-Key:
              schema:
                type: string
              description: FactSet request ID
        '503':
          description: >-
            Service unavailable. Typically a timeout, or result of a rejected
            request to prevent service overload. For further assistance, file an
            issue under "Performance - 404 and 500 Responses" using `Report
            Issue` at the top of this page, including the
            X-DataDirect-Request-Key from the header to assist in
            troubleshooting.
          headers:
            X-DataDirect-Request-Key:
              schema:
                type: string
              description: FactSet request ID
