openapi: 3.0.0
info:
  title: FactSet Entity API
tags:
  - name: Entity Reference
    description: >-
      Retrieve Entity Reference information for a list of securities, such as
      Parent Equity and Business Descriptions.
  - name: Entity Securities
    description: >-
      Retrieve the related equity or fixed income securities for a given list of
      ids
  - name: Entity Structure
    description: >-
      Retrieve the Entities corporate structure, its subsidiaries and related
      entity ids.
  - name: Entity Reference Chinese
  - name: Historical Credit Parent
paths:
  /factset-entity/v1/entity-references:
    get:
      summary: Returns an entity reference profiles for an individual entity
      description: >
        Returns an Entity reference profile for the requested Entity Id(s). Data
        points include - Ultimate Parent Id, Credit Parent Id, Headquarters
        location details, Website URL, and Business Description.
      tags:
        - Entity Reference
    post:
      summary: Returns an entity reference data for a list of ids.
      description: >
        Returns an entity reference object for the requested entity ids. Data
        points include - ultimate parent id, headquarters location details,
        credit parent id, website, and business description.
      tags:
        - Entity Reference
  /factset-entity/v1/entity-securities:
    get:
      summary: >-
        Returns all Equity Exchange Listings and all debt instruments issued for
        the requested entity.
      description: >
        Returns all Equity Exchange Listings (ticker-exchange) and all debt
        instruments (cusips) issued for the requested entity.
      tags:
        - Entity Securities
    post:
      summary: >-
        Returns all Equity Exchange Listings and all debt instruments issued for
        the requested entity.
      description: >
        Returns all Equity Exchange Listings (ticker-exchange) and all debt
        instruments (cusips) issued for the requested entity.
      tags:
        - Entity Securities
  /factset-entity/v1/entity-structures:
    get:
      summary: >-
        Returns all active or inactive entities and respective levels below the
        requested entity id.
      description: |
        Returns all active or inactive entities below the requested entity id.
      tags:
        - Entity Structure
    post:
      summary: Returns all active or inactive entities below the requested entity id.
      description: >
        Returns all active or inactive entities and respective levels below the
        requested entity id.
      tags:
        - Entity Structure
  /factset-entity/v1/ultimate-entity-structures:
    get:
      summary: >-
        Returns the full ultimate parent entity hiearachy. Control levels and
        active status of underlying entities.
      description: >
        Returns full ultimate entity structure including ultimate parent and all
        subordinates. Will accept entity from any level of entity structure or
        active vs. inactive status of entity.
      tags:
        - Entity Structure
    post:
      summary: >-
        Returns all active or inactive entities and respective levels below the
        requested entity id.
      description: >
        Returns all active or inactive entities and respective levels below the
        requested entity id.
      tags:
        - Entity Structure
  /factset-entity/v1/entity-reference-chi:
    get:
      summary: Returns entity reference data in Chinese for an individual entity.
      description: >
        Returns entity reference data in Chinese for the requested Id(s). Data
        points include Business Description and Entity Name in both simplified
        and traditional Chinese.
      tags:
        - Entity Reference Chinese
    post:
      summary: Returns entity reference data in Chinese for an individual entity.
      description: >
        Returns entity reference data in Chinese for the requested Id(s). Data
        points include Business Description and Entity Name in both simplified
        and traditional Chinese.
      tags:
        - Entity Reference Chinese
  /factset-entity/v1/hist-credit-parent:
    get:
      summary: Returns historical credit parents for the requested id(s).
      description: >
        Returns the credit parent for requested fixed income ids. Point in time
        credit parent retrieval is

        also available if an asOfDate is provided. The full credit parent
        history of a security is returned if

        no asOfDate is provided.


        This endpoint uses a seven day calendar to account for changes that
        occur on all seven days of the week.
      tags:
        - Historical Credit Parent
    post:
      summary: Returns historical credit parents for the requested id(s).
      description: >
        Returns the credit parent for requested fixed income ids. Point in time
        credit parent retrieval is

        also available if an asOfDate is provided. The full credit parent
        history of a security is returned if

        no asOfDate is provided.


        This endpoint uses a seven day calendar to account for changes that
        occur on all seven days of the week.
      tags:
        - Historical Credit Parent
