openapi: 3.0.3
info:
  title: FactSet Estimates Report Builder
  description: ''
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
externalDocs:
  description: Read more about STACH 2.0's row organized schema
  url: https://factset.github.io/stachschema/#/v2/RowOrganized
tags:
  - name: All Estimates
  - name: Estimate Tables
paths:
  /income-statement:
    get:
      tags:
        - All Estimates
      summary: Income Statement
      description: >-
        Returns historical and future period broker estimate consensus in a
        statement format for Income Statement line items.
  /balance-sheet:
    get:
      tags:
        - All Estimates
      summary: Balance Sheet
      description: >-
        Returns historical and future period broker estimate consensus in a
        statement format for Balance Sheet line items.
  /cash-flow:
    get:
      tags:
        - All Estimates
      summary: Cash Flow
      description: >-
        Returns historical and future period broker estimate consensus in a
        statement format for Cash Flow line items.
  /per-share:
    get:
      tags:
        - All Estimates
      operationId: getEstimatesPerShare
      summary: Per Share
      description: >-
        Returns historical and future period broker estimate consensus in a
        statement format for Per Share line items.
      parameters:
        - $ref: '#/components/parameters/idParameter'
        - $ref: '#/components/parameters/periodicityParameter'
        - $ref: '#/components/parameters/schemaParameter'
      responses:
        '200':
          $ref: '#/components/responses/200OKStach'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
        '503':
          $ref: '#/components/responses/503ServiceUnavailable'
  /industry-metrics:
    get:
      tags:
        - All Estimates
      operationId: getEstimatesIndustryMetrics
      summary: Industry Metrics
      description: >-
        Returns historical and future period broker estimate consensus in a
        statement format for industry-specific metrics.
      parameters:
        - $ref: '#/components/parameters/idParameter'
        - $ref: '#/components/parameters/periodicityParameter'
        - $ref: '#/components/parameters/schemaParameter'
      responses:
        '200':
          $ref: '#/components/responses/200OKStach'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
        '503':
          $ref: '#/components/responses/503ServiceUnavailable'
  /product-segments:
    get:
      tags:
        - All Estimates
      operationId: getEstimatesProductSegments
      summary: Product Segments
      description: >-
        Returns historical and future period broker estimate consensus in a
        statement format for line items broken down by product and business.
      parameters:
        - $ref: '#/components/parameters/idParameter'
        - $ref: '#/components/parameters/periodicityParameter'
        - $ref: '#/components/parameters/schemaParameter'
      responses:
        '200':
          $ref: '#/components/responses/200OKStach'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
        '503':
          $ref: '#/components/responses/503ServiceUnavailable'
  /geographic-segments:
    get:
      tags:
        - All Estimates
      operationId: getEstimatesGeographicSegments
      summary: Geographic Segments
      description: >-
        Returns historical and future period broker estimate consensus in a
        statement format for line items broken down geographically.
      parameters:
        - $ref: '#/components/parameters/idParameter'
        - $ref: '#/components/parameters/periodicityParameter'
        - $ref: '#/components/parameters/schemaParameter'
      responses:
        '200':
          $ref: '#/components/responses/200OKStach'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
        '503':
          $ref: '#/components/responses/503ServiceUnavailable'
  /valuation:
    get:
      tags:
        - All Estimates
      operationId: getEstimatesValuation
      summary: Valuation
      description: >-
        Returns valuation ratios in a statement format calculated from
        historical and future period broker estimate consensus.
      parameters:
        - $ref: '#/components/parameters/idParameter'
        - $ref: '#/components/parameters/periodicityParameter'
        - $ref: '#/components/parameters/schemaParameter'
      responses:
        '200':
          $ref: '#/components/responses/200OKStach'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
        '503':
          $ref: '#/components/responses/503ServiceUnavailable'
  /table:
    get:
      tags:
        - Estimate Tables
      operationId: getEstimateTablesTable
      summary: Interim/Annual Estimate Table
      description: >-
        Returns a timeseries grid of Interim and Annual data for a single line
        item
      parameters:
        - $ref: '#/components/parameters/idParameter'
        - $ref: '#/components/parameters/metricParameter'
      responses:
        '200':
          $ref: '#/components/responses/200OKStachTable'
        '400':
          $ref: '#/components/responses/400BadRequest-table'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
        '503':
          $ref: '#/components/responses/503ServiceUnavailable'
        Returns a timeseries grid of Interim and Annual data for a single line
        item
      parameters:
        - $ref: '#/components/parameters/idParameter'
        - $ref: '#/components/parameters/metricParameter'
      responses:
        '200':
          $ref: '#/components/responses/200OKStachTable'
        '400':
          $ref: '#/components/responses/400BadRequest-table'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
        '503':
          $ref: '#/components/responses/503ServiceUnavailable'
 >-
        Returns a timeseries grid of Interim and Annual data for a single line
        item
      parameters:
        - $ref: '#/components/parameters/idParameter'
        - $ref: '#/components/parameters/metricParameter'
      responses:
        '200':
          $ref: '#/components/responses/200OKStachTable'
        '400':
          $ref: '#/components/responses/400BadRequest-table'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
        '503':
          $ref: '#/components/responses/503ServiceUnavailable'
