openapi: 3.0.0
info:
  title: FactSet Exchange Traded Funds API
  license:
    name: License Information
    url: http://www.factset.com/api/license.html
paths:
  /factset-etf/v1/reference:
    get:
      summary: Return reference data for an ETF.
      description: |
        Returns reference data items for Exchange Traded Funds.
      tags:
        - Reference
    post:
      summary: Fetch Reference Data for a large list of ETF securities.
      description: |
        Returns reference data items for a list of Exchange Traded Funds.
      tags:
        - Reference
  /factset-etf/v1/metrics:
    get:
      summary: Available ETF metrics
      tags:
        - Data Items
      description: >
        Returns a list of available metrics that can be used in the `metrics`
        parameter of related endpoints. Leave _category_ blank to request all
        availa
