openapi: 3.0.0
info:
  title: Foreign Exchange Rates API
paths:
  /foreign-exchange/v1/spots:
    get:
      tags:
        - Spots
      summary: Gets spots for a list of currency pairs
      description: >
        Gets FX Spot rates for a requested currency pair, date range, and
        frequency. The WM Company calculates daily standardized spot rates for
        global foreign exchange transactions, using rates provided by Reuters.
        These rates are recognized globally as the standard by banks, fund
        managers, and index compilers; increasingly these rates are also being
        used for benchmark currency trading.
    post:
      tags:
        - Spots
      summary: Gets spots for a list of currency pairs
      description: >
        Gets FX Spot rates for a requested currency pair, date range, and
        frequency. The WM Company calculates daily standardized spot rates for
        global foreign exchange transactions, using rates provided by Reuters.
        These rates are recognized globally as the standard by banks, fund
        managers, and index compilers; increasingly these rates are also being
        used for benchmark currency trading.
  /foreign-exchange/v1/forwards:
    get:
      tags:
        - Forwards
      summary: Gets Forwards for a list of currency pairs
      description: >
        Forward rates are provided in 80+ currencies against the U.S. dollar,
        British pound, and euro. Forward quotes are provided by Reuters and
        coverage is determined by the amount of reliable currency trading in a
        particular currency. Bid, offer, and mid rates are available for 11
        `forwardPeriod` periods - Overnight, Tomorrow Next, 1 Week (Spot Week),
        1 month, 2 month, 3 month, 6 month, 9 month, 1 year, 2 year, 5 year. All
        identifiers have spot rates, but not all identifiers have forward rate
        data.
    post:
      tags:
        - Forwards
      summary: Gets Forwards for a list of currency pairs
      description: >
        Forward rates are provided in 80+ currencies against the U.S. dollar,
        British pound, and euro. Forward quotes are provided by Reuters and
        coverage is determined by the amount of reliable currency trading in a
        particular currency. Bid, offer, and mid rates are available for 11
        `forwardPeriod` periods - Overnight, Tomorrow Next, 1 Week (Spot Week),
        1 month, 2 month, 3 month, 6 month, 9 month, 1 year, 2 year, 5 year. All
        identifiers have spot rates, but not all identifiers have forward 
