openapi: 3.0.0
info:
  title: Global Filings API
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/global-filings-api
paths:
  /search:
    get:
      summary: >-
        Returns the filings documents and related metadata within FactSet
        coverage.
      tags:
        - Filings API
      description: >-
        Returns the filings documents within FactSet coverage along with other
        response fields
  /helper:
    get:
      tags:
        - Filings API
      operationId: getHelper
      summary: Returns the static values for various parameters
      description: >-
        Returns the static values for sources,formTypes,timeZones,categories
        based on the specified parameter
      parameters:
        - $ref: '#/components/parameters/report1'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseHelper'
              examples:
                sources:
                  summary: Sample 200 Response for Sources Parameter
                  value:
                    data:
                      - source: EDG
                        description: EDGAR
                      - source: EDJ
                        description: EDINET
                      - source: FBLK
                        description: Factset Blackline Report
                      - source: FFR
                        description: Factset Annuals & Interims
                      - source: HNX
                        description: Hanoi Stock Exchange - HNX News
                      - source: SDR
                        description: SEDAR
                      - source: SENS
                        description: Stock Exchange News Service
                      - source: TDT
                        description: TDnet
                      - source: TWSE
                        description: Taiwan Stock Exchange
                      - source: ASXD
                        description: ASX Company Announcements Delayed
                formTypes:
                  summary: Sample 200 Response for FormTypes Parameter
                  value:
                    data:
                      - source: EDG
                        description: Edgar
                        formType: 10-K
                      - source: EDG
                        description: Edgar
                        formType: 8-K
                timeZones:
                  summary: Sample 200 Response for TimeZones Parameter
                  value:
                    data:
                      - timezone: Africa/Malabo
                categories:
                  summary: Sample 200 Response for Categories Parameter
                  value:
                    data:
                      - subject: SB
                        category: SB:ANLCH
                        description: Analysts Revisions
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                default400ResponseExample:
                  $ref: '#/components/examples/ErrorDetails'
        '401':
          description: >-
            Unauthenticated USERNAME-SERIAL. Ensure you are logged in and have
            successfully generated an API KEY for the IP range you are
            connecting from. For more help, select the Report Issue in the top
            right corner of this Developer Portal specification card and choose
            Connectivity 401 or 403 Responses.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                default401ResponseExample:
                  $ref: '#/components/examples/AuthErrorDetails'
        '403':
          description: >-
            The USERNAME-SERIAL attempted to request the endpoint is not
            authorized to access. The request was a legal request, but the
            server is refusing to respond. Please reach out to FactSet Account
            Team for assistance with authorization.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                default403ResponseExample:
                  $ref: '#/components/examples/AuthorizationErrorDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                default500ResponseExample:
                  $ref: '#/components/examples/ServerErrorDetails'
  /count:
    get:
      tags:
        - Filings API
      operationId: getCount
      summary: Returns the count of filings for specified source
      description: Returns the count of filings documents along with other response fields.
      parameters:
        - $ref: '#/components/parameters/report2'
        - $ref: '#/components/parameters/startDate'
        - $ref: '#/components/parameters/endDate'
        - $ref: '#/components/parameters/ids'
        - $ref: '#/components/parameters/sources'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseCount'
              examples:
                default200ResponseExample:
                  $ref: '#/components/examples/sampleResponseCount'
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                default400ResponseExample:
                  $ref: '#/components/examples/ErrorDetails'
        '401':
          description: >-
            Unauthenticated USERNAME-SERIAL. Ensure you are logged in and have
            successfully generated an API KEY for the IP range you are
            connecting from. For more help, select the Report Issue in the top
            right corner of this Developer Portal specification card and choose
            Connectivity 401 or 403 Responses.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                default401ResponseExample:
                  $ref: '#/components/examples/AuthErrorDetails'
        '403':
          description: >-
            The USERNAME-SERIAL attempted to request the endpoint is not
            authorized to access. The request was a legal request, but the
            server is refusing to respond. Please reach out to FactSet Account
            Team for assistance with authorization.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                default403ResponseExample:
                  $ref: '#/components/examples/AuthorizationErrorDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                default500ResponseExample:
                  $ref: '#/components/examples/ServerErrorDetails'
tags:
  - name: Filings API
    description: >-
      API provides access to search and download filings documents from various
      sources.
