openapi: 3.0.1
info:
  title: IRN API v1
paths:
  /v1/custom-symbols:
    get:
      tags:
        - CustomSymbols
      summary: >-
        Get list of all custom symbols in your group along with some of their
        standard field and custom fields data
    post:
      tags:
        - CustomSymbols
      summary: Create a custom symbol
  /v1/custom-symbols/{customSymbolId}:
    get:
      tags:
        - CustomSymbols
      summary: >-
        Get all custom field and standard field details on a specific custom
        symbol
    patch:
      tags:
        - CustomSymbols
      summary: Edit a custom symbol’s standard field and custom field data
    delete:
      tags:
        - CustomSymbols
      summary: Delete a custom symbol
  /v1/custom-symbols/{customSymbolId}/records:
    get:
      tags:
        - CustomSymbols
      summary: >-
        Get all notes and meetings where a specific customSymbol was tagged as
        primary or related identifier
  /v1/custom-symbols/standard-symbol-metadata/{standardSymbol}:
    get:
      tags:
        - HybridSymbols
      summary: >-
        Get all custom field and standard field details on a specific standard
        symbol
  /v1/symbol-relationships/{symbolId}/relationships:
    get:
      tags:
        - CustomSymbols - Relationships
      summary: Returns a list of a symbol’s relationships
  /v1/symbol-relationships/{symbolRelationshipId}:
    get:
      tags:
        - CustomSymbols - Relationships
      summary: Get details on a specific symbol relationship
    delete:
      tags:
        - CustomSymbols - Relationships
      summary: Delete a symbol relationship
  /v1/custom-symbols/{customSymbolId}/link-standard-symbol:
    post:
      tags:
        - CustomSymbols
      summary: Link custom symbol to standard symbol
  /v1/custom-symbols/standard-symbol-metadata:
    post:
      tags:
        - HybridSymbols
      summary: Create standard symbol metadata
  /v1/symbol-relationships:
    post:
      tags:
        - CustomSymbols - Relationships
      summary: Create a symbol relationship
  /v1/symbol-relationships/{symbol}:
    put:
      tags:
        - CustomSymbols - Relationships
      summary: Edit a symbol relationship
  /v1/custom-symbols/standard-symbol-metadata/{standardSymbolId}:
    patch:
      tags:
        - HybridSymbols
      summary: Edit a standard symbol’s standard field and custom field data
tags:
  - name: CustomSymbols
  - name: CustomSymbols - Relationships
  - name: HybridSymbols
