openapi: 3.0.1
info:
  title: IRN API v1
paths:
  /v1/custom-symbols:
    get:
      tags:
        - CustomSymbols
      summary: >-
        Get list of all custom symbols in your group along with some of their
        standard field and custom fields data
    post:
      tags:
        - CustomSymbols
      summary: Create a custom symbol
  /v1/custom-symbols/{customSymbolId}:
    get:
      tags:
        - CustomSymbols
      summary: >-
        Get all custom field and standard field details on a specific custom
        symbol
    patch:
      tags:
        - CustomSymbols
      summary: Edit a custom symbol’s standard field and custom field data
    delete:
      tags:
        - CustomSymbols
      summary: Delete a custom symbol
  /v1/custom-symbols/{customSymbolId}/records:
    get:
      tags:
        - CustomSymbols
      summary: >-
        Get all notes and meetings where a specific customSymbol was tagged as
        primary or related identifier
  /v1/custom-symbols/standard-symbol-metadata/{standardSymbol}:
    get:
      tags:
        - HybridSymbols
      summary: >-
        Get all custom field and standard field details on a specific standard
        symbol
  /v1/symbol-relationships/{symbolId}/relationships:
    get:
      tags:
        - CustomSymbols - Relationships
      summary: Returns a list of a symbol’s relationships
  /v1/symbol-relationships/{symbolRelationshipId}:
    get:
      tags:
        - CustomSymbols - Relationships
      summary: Get details on a specific symbol relationship
    delete:
      tags:
        - CustomSymbols - Relationships
      summary: Delete a symbol relationship
  /v1/custom-symbols/{customSymbolId}/link-standard-symbol:
    post:
      tags:
        - CustomSymbols
      summary: Link custom symbol to standard symbol
      operationId: LinkCustomSymbolToStandardSymbol
      parameters:
        - name: customSymbolId
          in: path
          description: customSymbolId associated with custom symbol
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: standard symbol name
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/StandardSymbolDto'
          application/json:
            schema:
              $ref: '#/components/schemas/StandardSymbolDto'
          text/json:
            schema:
              $ref: '#/components/schemas/StandardSymbolDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/StandardSymbolDto'
      responses:
        '200':
          description: Success
  /v1/custom-symbols/standard-symbol-metadata:
    post:
      tags:
        - HybridSymbols
      summary: Create standard symbol metadata
      operationId: CreateStandardSymbolMetadata
      requestBody:
        description: createStandardSymbolMetadataDto object to save
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/CreateStandardSymbolMetadataDto'
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStandardSymbolMetadataDto'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateStandardSymbolMetadataDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateStandardSymbolMetadataDto'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewItemDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /v1/symbol-relationships:
    post:
      tags:
        - CustomSymbols - Relationships
      summary: Create a symbol relationship
      operationId: CreateSymbolRelationship
      requestBody:
        description: symbolRelationship object to save
        content:
          application/json-patch+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/SymbolRelationshipSaveDto'
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/SymbolRelationshipSaveDto'
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/SymbolRelationshipSaveDto'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/SymbolRelationshipSaveDto'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /v1/symbol-relationships/{symbol}:
    put:
      tags:
        - CustomSymbols - Relationships
      summary: Edit a symbol relationship
      operationId: EditAndAddSymbolRelationship
      parameters:
        - name: symbol
          in: path
          description: ''
          required: true
          schema:
            type: string
      requestBody:
        description: symbolRelationship object to save
        content:
          application/json-patch+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/SymbolRelationshipUpdateDto'
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/SymbolRelationshipUpdateDto'
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/SymbolRelationshipUpdateDto'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/SymbolRelationshipUpdateDto'
      responses:
        '200':
          description: Success
  /v1/custom-symbols/standard-symbol-metadata/{standardSymbolId}:
    patch:
      tags:
        - HybridSymbols
      summary: Edit a standard symbol’s standard field and custom field data
      operationId: PatchStandardSymbol
      parameters:
        - name: standardSymbolId
          in: path
          description: standardSymbolId to update associated standard symbol
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: updateCustomSymbolDto object to update
        content:
          application/json-patch+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Operation'
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Operation'
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Operation'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Operation'
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
tags:
  - name: CustomSymbols
  - name: CustomSymbols - Relationships
  - name: HybridSymbols
’s standard field and custom field data
      operationId: PatchStandardSymbol
      parameters:
        - name: standardSymbolId
          in: path
          description: standardSymbolId to update associated standard symbol
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: updateCustomSymbolDto object to update
        content:
          application/json-patch+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Operation'
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Operation'
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Operation'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Operation'
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
tags:
  - name: CustomSymbols
  - name: CustomSymbols - Relationships
  - name: HybridSymbols
schemas/Operation'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Operation'
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
tags:
  - name: CustomSymbols
  - name: CustomSymbols - Relationships
  - name: HybridSymbols
ray
              items:
                $ref: '#/components/schemas/Operation'
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
tags:
  - name: CustomSymbols
  - name: CustomSymbols - Relationships
  - name: HybridSymbols
onents/schemas/Operation'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Operation'
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
tags:
  - name: CustomSymbols
  - name: CustomSymbols - Relationships
  - name: HybridSymbols
: '#/components/schemas/ProblemDetails'
  /v1/symbol-relationships/{symbol}:
    put:
      tags:
        - CustomSymbols - Relationships
      summary: Edit a symbol relationship
      operationId: EditAndAddSymbolRelationship
      parameters:
        - name: symbol
          in: path
          description: ''
          required: true
          schema:
            type: string
      requestBody:
        description: symbolRelationship object to save
        content:
          application/json-patch+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/SymbolRelationshipUpdateDto'
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/SymbolRelationshipUpdateDto'
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/SymbolRelationshipUpdateDto'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/SymbolRelationshipUpdateDto'
      responses:
        '200':
          description: Success
  /v1/custom-symbols/standard-symbol-metadata/{standardSymbolId}:
    patch:
      tags:
        - HybridSymbols
      summary: Edit a standard symbol’s standard field and custom field data
      operationId: PatchStandardSymbol
      parameters:
        - name: standardSymbolId
          in: path
          description: standardSymbolId to update associated standard symbol
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: updateCustomSymbolDto object to update
        content:
          application/json-patch+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Operation'
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Operation'
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Operation'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Operation'
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
tags:
  - name: CustomSymbols
  - name: CustomSymbols - Relationships
  - name: HybridSymbols
