openapi: 3.0.0
info:
  title: Issue Tracker API
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
tags:
  - name: Issue
    description: Updating and retrieving issue data within the Issue Tracker
paths:
  /issues:
    post:
      summary: Creates a Issue Tracker issue
      tags:
        - Issue
      description: Creates a new issue in Issue Tracker
  /issues/{id}:
    get:
      summary: Get the matched issue details
      tags:
        - Issue
      description: Retrieve the information of the client with the matching issue Id.
  /issues/{id}/comments:
    post:
      summary: post comment to Issue Tracker issue
      tags:
        - Issue
      description: 'Reply to the existing matched issue '
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/issue-t
