openapi: 3.0.0
info:
  title: Issue Tracker API
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
tags:
  - name: Issue
    description: Updating and retrieving issue data within the Issue Tracker
paths:
  /issues:
    post:
      summary: Creates a Issue Tracker issue
      tags:
        - Issue
      description: Creates a new issue in Issue Tracker
  /issues/{id}:
    get:
      summary: Get the matched issue details
      tags:
        - Issue
      description: Retrieve the information of the client with the matching issue Id.
  /issues/{id}/comments:
    post:
      summary: post comment to Issue Tracker issue
      tags:
        - Issue
      operationId: postReply
      parameters:
        - schema:
            type: string
          name: id
          in: path
          required: true
          description: ID of Issue Tracker issue
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/idResponse'
              examples:
                Example 1:
                  value:
                    data:
                      id: 28d38693-3454-4e45-9825-71br87e69fe3
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
      description: 'Reply to the existing matched issue '
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/commentRequest'
            examples:
              Example 1:
                value:
                  data:
                    content: <p>this is a sample comment</p>
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/issue-tracker-api
d: postReply
      parameters:
        - schema:
            type: string
          name: id
          in: path
          required: true
          description: ID of Issue Tracker issue
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/idResponse'
              examples:
                Example 1:
                  value:
                    data:
                      id: 28d38693-3454-4e45-9825-71br87e69fe3
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
      description: 'Reply to the existing matched issue '
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/commentRequest'
            examples:
              Example 1:
                value:
                  data:
                    content: <p>this is a sample comment</p>
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/issue-tracker-api
