openapi: 3.0.3
info:
  title: Open:Risk API
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
tags:
  - name: About
  - name: Operations
paths:
  /linear/{version}/riskmodels:
    get:
      summary: Get available risk models
      description: >-
        Get the list of available risk models, including their respective model
        codes required for use with other routes.
      tags:
        - About
  /linear/{version}/riskmodels/{modelCode}:
    get:
      summary: Get risk model details
      description: >-
        Get the meta data of the risk model for the corresponding modelCode.
        modelCode can be obtained via '/linear/{version}/riskmodels/' route.
      tags:
        - About
  /linear/{version}/stats:
    get:
      summary: Get available risk statistics details
      description: >-
        All base risk statistic names and their respective support and/or
        requirement for certain name-settings statistics options (such as:
        correlated specific risk, covariance isolation method, etc.), available
        levels, and security group calculation methodology. When
        'securityGroupMethod' is 'statSpecific', please refer to statistics
        documentation service for more information.
      tags:
        - About
  /linear/{version}/stats-names-only:
    get:
      summary: Get available risk statistics names
      description: >-
        All available risk statistic names including statistics names containing
        risk statistics options such as CSR (correlated specific risk)
      tags:
        - About
  /linear/{version}/health:
    get:
      summary: Get health of service
      description: Health status of the service
      operationId: healthStatus
      tags:
        - About
      parameters:
        - $ref: '#/components/parameters/VersionPath'
      responses:
        '200':
          $ref: '#/components/responses/HealthPass'
        '401':
          $ref: '#/components/responses/MissingOrInvalidAuthentication'
        '403':
          $ref: '#/components/responses/HealthFailAuthorization'
        '404':
          $ref: '#/components/responses/HealthFailVersionNotFound'
        '429':
          $ref: '#/components/responses/RateLimitReached'
  /linear/{version}/calculate/from-holdings:
    post:
      summary: Calculate risk statistics
      description: >-
        Calculate predicted risk statistics for provided holdings using risk
        model data. Asset symbols and market values/weights are required.
      operationId: calculateFromHoldings
      tags:
        - Operations
      parameters:
        - $ref: '#/components/parameters/VersionPath'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculateFromHoldingsRequestBody'
            example:
              data:
                stats:
                  - name: ActiveVarianceToRisk
                    level: Portfolio
                  - name: ActiveVarianceToRisk
                    level: SecurityGroup
                  - name: PortfolioWeights
                    level: Security
                  - name: BenchmarkWeights
                    level: Security
                  - name: ActiveWeights
                    level: Security
                  - name: ActiveFactorVarianceToRisk
                    level: Security
                    settings:
                      correlatedSpecificRisk: true
                  - name: ActiveFactorVarianceToRiskCSR
                    level: Security
                  - name: ActiveFactorRisk
                    level: FactorGroup
                    settings:
                      covarianceTimesTwo: true
                  - name: PortfolioReturnAtRiskPercentWithContribution
                    level: Portfolio
                    settings:
                      confidenceLevel: 0.95
                      daysPerYear: 250
                      horizon: 1
                  - name: RawResidualRisk
                    level: Security
                  - name: RawSecurityFactorRisk
                    level: Security
                  - name: RawFactorExposure
                    level: FactorSecurity
                  - name: RawFactorExposure
                    level: FactorSecurity
                    settings:
                      sparse: true
                  - name: PortfolioExposure
                    level: Factor
                    settings:
                      sparse: true
                holdings:
                  portfolio:
                    ids:
                      - IBM
                      - FDS
                      - CA_ETF
                      - CASH_GBP_CFD
                      - CFD_B10RZP
                    marketValues:
                      - 60
                      - 30
                      - 30
                      - -30
                      - 30
                    grouping:
                      groups:
                        - name: USD
                          groups:
                            - name: Direct Assets
                              indices:
                                - 0
                                - 1
                            - name: Composite Assets
                              indices:
                                - 2
                        - name: GBP
                          indices:
                            - 4
                        - name: Offset Cash
                          indices:
                            - 3
                  benchmark:
                    ids:
                      - B10RZP
                      - IBM
                      - MSFT
                    marketValues:
                      - 30
                      - 40
                      - 30
                    grouping:
                      groups:
                        - name: GBP
                          indices:
                            - 0
                        - name: USD
                          groups:
                            - name: Direct Assets
                              indices:
                                - 1
                                - 2
                underlyingIds:
                  CFD_B10RZP: B10RZP
                compositeAssets:
                  CA_ETF:
                    ids:
                      - FDS
                      - IBM
                    marketValues:
                      - 10
                      - 90
                assetTypes:
                  CFD_B10RZP: OTH_CFD
                factorGrouping:
                  name: >-
                    This factor grouping is incomplete; it omits factors for the
                    sake of brevity and is not recomended for actual use.
                  nodes:
                    - name: Market
                      nodes:
                        - id: GLOBAL_MARKET
                    - name: Style
                      nodes:
                        - name: Market Factors
                          nodes:
                            - id: BETA
                            - id: LIQUIDITY
                            - id: MOMENTUM
                            - id: SIZE
                            - id: VOLATILITY
                        - name: Fundamental Factors
                          nodes:
                            - id: BOOK_TO_PRICE
                            - id: DIVIDEND_YIELD
                            - id: EARNINGS_YIELD
                            - id: GROWTH
                            - id: LEVERAGE
                factorsVisible:
                  list:
                    - FX_GBP
                    - FX_USD
                  type: Whitelist
                allowForcedRisklessAssets: true
                currency: USD
                riskModel: FDS:GLOBAL_EQUITY_M_V1
                date: '2021-05-31'
                calendar: FIVEDAY
      responses:
        '200':
          $ref: '#/components/responses/CalculateFromHoldingsSuccess'
        '400':
          $ref: '#/components/responses/BadRequestOrDataUnavailable'
        '401':
          $ref: '#/components/responses/MissingOrInvalidAuthentication'
        '403':
          $ref: '#/components/responses/AccessForbidden'
        '404':
          $ref: '#/components/responses/EndpointNotFound'
        '429':
          $ref: '#/components/responses/RateLimitReached'
        '500':
          $ref: '#/components/responses/InternalServerErrorJsonOnly'
  /linear/{version}/generate/id-mapping:
    post:
      summary: Generate risk model ID mapping
      description: >-
        Resolve all input holdings IDs against a risk model for coverage and
        provide a mapping to security indices in the model or the reason for
        exclusion
      operationId: generateIdMapping
      tags:
        - Operations
      parameters:
        - $ref: '#/components/parameters/VersionPath'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateIDMappingRequestBody'
            example:
              data:
                holdings:
                  portfolio:
                    grouping:
                      groups:
                        - name: USD
                          groups:
                            - name: Direct Assets
                              indices:
                                - 0
                                - 1
                            - name: Composite Assets
                              indices:
                                - 2
                        - name: GBP
                          indices:
                            - 4
                        - name: Offset Cash
                          indices:
                            - 3
                    ids:
                      - IBM
                      - FDS
                      - CA_ETF
                      - CASH_GBP_CFD
                      - CFD_B10RZP
                    marketValues:
                      - 60
                      - 30
                      - 30
                      - -30
                      - 30
                  benchmark:
                    grouping:
                      groups:
                        - name: GBP
                          indices:
                            - 0
                        - name: USD
                          groups:
                            - name: Direct Assets
                              indices:
                                - 1
                                - 2
                        - name: Other - Uncovered Assets
                          indices:
                            - 3
                    ids:
                      - B10RZP
                      - IBM
                      - MSFT
                      - FAKE_UNCOVERED_ASSET
                    marketValues:
                      - 30
                      - 30
                      - 30
                      - 10
                allowForcedRisklessAssets: true
                assetTypes:
                  CFD_B10RZP: OTH_CFD
                calendar: FIVEDAY
                compositeAssets:
                  CA_ETF:
                    ids:
                      - FDS
                      - IBM
                    marketValues:
                      - 10
                      - 90
                currency: USD
                date: '2021-05-31'
                riskModel: FDS:GLOBAL_EQUITY_M_V1
                underlyingIds:
                  CFD_B10RZP: B10RZP
      responses:
        '200':
          $ref: '#/components/responses/GenerateIDMappingSuccess'
        '400':
          $ref: '#/components/responses/BadRequestOrDataUnavailable'
        '403':
          $ref: '#/components/responses/AccessForbidden'
        '404':
          $ref: '#/components/responses/EndpointNotFound'
        '429':
          $ref: '#/components/responses/RateLimitReached'
        '500':
          $ref: '#/components/responses/InternalServerErrorJsonOnly'
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/openrisk-api
equestOrDataUnavailable'
        '403':
          $ref: '#/components/responses/AccessForbidden'
        '404':
          $ref: '#/components/responses/EndpointNotFound'
        '429':
          $ref: '#/components/responses/RateLimitReached'
        '500':
          $ref: '#/components/responses/InternalServerErrorJsonOnly'
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/openrisk-api
rDataUnavailable'
        '403':
          $ref: '#/components/responses/AccessForbidden'
        '404':
          $ref: '#/components/responses/EndpointNotFound'
        '429':
          $ref: '#/components/responses/RateLimitReached'
        '500':
          $ref: '#/components/responses/InternalServerErrorJsonOnly'
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/openrisk-api
onses:
        '200':
          $ref: '#/components/responses/GenerateIDMappingSuccess'
        '400':
          $ref: '#/components/responses/BadRequestOrDataUnavailable'
        '403':
          $ref: '#/components/responses/AccessForbidden'
        '404':
          $ref: '#/components/responses/EndpointNotFound'
        '429':
          $ref: '#/components/responses/RateLimitReached'
        '500':
          $ref: '#/components/responses/InternalServerErrorJsonOnly'
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/openrisk-api
