openapi: 3.0.0
info:
  title: FactSet Ownership API
paths:
  /factset-ownership/v1/fund-holdings:
    get:
      tags:
        - Fund Holdings
      summary: Get underlying holdings information for a requested fund identifer.
      description: >
        Gets holdings information for list of fund identifiers. The service
        allows you to filter by the TopN holdings and Asset Type.
    post:
      tags:
        - Fund Holdings
      summary: Get holdings for a list of funds.
      description: Gets Holding information for a long list of Fund objects.
  /factset-ownership/v1/security-holders:
    get:
      tags:
        - Security Holders
      summary: Get security ownership data for requested security identifers.
      description: >
        Gets security ownership details and activity for the requested security
        identifiers. The services allows filtering by "Topn" holders and by
        holder "type", such as Institutions, Insiders, and Stakeholders.
    post:
      tags:
        - Security Holders
      summary: Get security ownership data for a list of requested securities.
      description: >
        Gets security ownership details and activity for the requested security
        identifiers. The services allows filtering by "Topn" holders and by
        holder "type", such as Institutions, Insiders, and Stakeholders.
 Holders Response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/securityHoldersResponse'
              examples:
                Single identifier request for Top 1 holder of FDS-US securities as of 2020-06-31:
                  $ref: '#/components/examples/singleSecurityHolder'
                Top 5 Insiders and Stakeholders of TSLA-US as of 2020-02-14:
                  $ref: '#/components/examples/insiderTop5Holders'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '415':
          $ref: '#/components/responses/415'
        '500':
          $ref: '#/components/responses/500'
    post:
      tags:
        - Security Holders
      summary: Get security ownership data for a list of requested securities.
      description: >
        Gets security ownership details and activity for the requested security
        identifiers. The services allows filtering by "Topn" holders and by
        holder "type", such as Institutions, Insiders, and Stakeholders.
      operationId: postSecurityHolders
      requestBody:
        required: true
        description: Requesting Security Holders for a list of Fund Identifiers.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/securityHoldersRequest'
            examples:
              Request the Top Institutional holder of FDS-US as of 2020-06-30:
                $ref: '#/components/examples/singleSecurityHolderPostRequest'
              Request Latest Top 5 Insiders for TSLA-US:
                $ref: '#/components/examples/top5InsidersRequest'
      responses:
        '200':
          description: Security Holders Response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/securityHoldersResponse'
              examples:
                Single identifier request for Top 1 holder of FDS-US securities as of 2020-06-30:
                  $ref: '#/components/examples/singleSecurityHolder'
                Top 5 Insiders and Stakeholders of TSLA-US as of 2020-02-14:
                  $ref: '#/components/examples/insiderTop5Holders'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '415':
          $ref: '#/components/responses/415'
        '500':
          $ref: '#/components/responses/500'
