openapi: 3.0.0
info:
  title: Portfolio Reporting Batcher
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/portfolio-reporting-batcher-api
paths:
  /jobs/{type}/{name}:
    parameters:
      - schema:
          $ref: '#/components/schemas/jobTypes'
        name: type
        in: path
        required: true
        description: The jobs type
      - schema:
          type: string
        name: name
        in: path
        required: true
        description: The jobs name
    get:
      summary: Get details for the given PRB job
      tags:
        - Jobs
      description: >-
        Use this endpoint to fetch the documents, tasks, accounts, and/or runs
        for the PRB job given in the path. Please note jobs with type PD will
        not return tasks nor accounts so this will be ignored if given as part
        of the array of attributes in the request.
  /runs:
    post:
      summary: trigger PRB jobs
      description: Use this endpoint with with POST method to trigger PRB jobs.
      tags:
        - Runs
  /runs/{id}/status:
    get:
      summary: check the status for a particular run ID
      tags:
        - Runs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/idStatus'
              examples:
                ADF (With Overrides):
                  value:
                    data:
                      status: queued
                      prbStatus: pending
                      statusDescription: string
                      inputs:
                        jobName: my_adf_job
                        jobType: ADF
                        overrides:
                          dates:
                            start: '2023-12-25'
                            end: '2023-12-27'
                          frequency: daily
                          calendar: sevenDay
                          runAsSerialNumber: '894550'
                      id: '34578'
                PA (With Overrides):
                  value:
                    data:
                      status: executing
                      prbStatus: running
                      statusDescription: string
                      inputs:
                        jobName: my_pa_job
                        jobType: PA
                        overrides:
                          tasks:
                            - task_1
                            - task_2
                          runAsSerialNumber: '894550'
                      id: '123456'
                PD (With Overrides):
                  value:
                    data:
                      status: executing
                      prbStatus: running
                      statusDescription: string
                      inputs:
                        jobName: my_pd_job
                        jobType: PD
                        overrides:
                          runAsSerialNumber: '894550'
                      id: '78904'
                PI:
                  value:
                    data:
                      status: queued
                      prbStatus: pending
                      statusDescription: string
                      inputs:
                        jobName: my_pi_job
                        jobType: PI
                      id: '78904'
                PUB (With Overrides):
                  value:
                    data:
                      status: queued
                      prbStatus: pending
                      statusDescription: string
                      inputs:
                        jobName: my_pub_job
                        jobType: PUB
                        overrides:
                          runAsOfDate: '2023-02-05'
                      id: '3456789'
                Vault (No Overrides):
                  value:
                    data:
                      inputs:
                        jobName: my_vault_job
                        jobType: vault
                      status: created
                      prbStatus: success
                      statusDescription: job has completed with success
                      id: '123456'
                Vault (With Overrides):
                  value:
                    data:
                      inputs:
                        jobName: my_vault_job
                        jobType: vault
                        overrides:
                          combinations:
                            - accounts:
                                - CLIENT:/FPS/VAULTED_RETURNS/7DAYS_VLT.ACCT
                                - CLIENT:/FPS/VAULTED_RETURNS/1MONTH.ACCT
                              dates:
                                - '2022-12-24'
                                - '2022-12-23'
                          runAsSerialNumber: '894550'
                      status: created
                      prbStatus: success
                      statusDescription: job has completed with success
                      id: '123456'
          headers:
            X-DataDirect-Request-Key:
              $ref: '#/components/headers/X-DataDirect-Request-Key'
            X-FactSet-Api-Request-Key:
              $ref: '#/components/headers/X-FactSet-Api-Request-Key'
            X-FactSet-Api-RateLimit-Limit:
              $ref: '#/components/headers/X-FactSet-Api-RateLimit-Limit'
            X-FactSet-Api-RateLimit-Remaining:
              $ref: '#/components/headers/X-FactSet-Api-RateLimit-Remaining'
            X-FactSet-Api-RateLimit-Reset:
              $ref: '#/components/headers/X-FactSet-Api-RateLimit-Reset'
        '401':
          description: Missing or invalid authentication.
          headers:
            X-DataDirect-Request-Key:
              $ref: '#/components/headers/X-DataDirect-Request-Key'
            X-FactSet-Api-Request-Key:
              $ref: '#/components/headers/X-FactSet-Api-Request-Key'
        '403':
          description: User is forbidden with current credentials
          headers:
            X-DataDirect-Request-Key:
              $ref: '#/components/headers/X-DataDirect-Request-Key'
            X-FactSet-Api-Request-Key:
              $ref: '#/components/headers/X-FactSet-Api-Request-Key'
            X-FactSet-Api-RateLimit-Limit:
              $ref: '#/components/headers/X-FactSet-Api-RateLimit-Limit'
            X-FactSet-Api-RateLimit-Remaining:
              $ref: '#/components/headers/X-FactSet-Api-RateLimit-Remaining'
            X-FactSet-Api-RateLimit-Reset:
              $ref: '#/components/headers/X-FactSet-Api-RateLimit-Reset'
        '429':
          description: >-
            Rate limit reached. Wait till the time specified in Retry-After
            header value to make further requests.
          headers:
            X-DataDirect-Request-Key:
              $ref: '#/components/headers/X-DataDirect-Request-Key'
            X-FactSet-Api-Request-Key:
              $ref: '#/components/headers/X-FactSet-Api-Request-Key'
            Retry-After:
              description: >-
                Time to wait in seconds before making a new request as the rate
                limit has reached.
              schema:
                type: string
        '500':
          description: >-
            Server error. Log the X-DataDirect-Request-Key header to assist in
            troubleshooting.
          headers:
            X-DataDirect-Request-Key:
              $ref: '#/components/headers/X-DataDirect-Request-Key'
            X-FactSet-Api-Request-Key:
              $ref: '#/components/headers/X-FactSet-Api-Request-Key'
        '503':
          description: Request timed out. Retry the request in sometime.
          headers:
            X-DataDirect-Request-Key:
              $ref: '#/components/headers/X-DataDirect-Request-Key'
            X-FactSet-Api-Request-Key:
              $ref: '#/components/headers/X-FactSet-Api-Request-Key'
      operationId: checkRunStatus
      parameters: []
      description: >-
        Use this endpoint to check the status of a run using the id from the
        POST /runs endpoint
    parameters:
      - schema:
          type: string
          example: '1013456'
        name: id
        in: path
        required: true
        description: run id
tags:
  - name: Jobs
    description: These endpoints relate to PRB jobs
  - name: Runs
    description: These endpoints refer to specific runs for a PRB job
type" fields will uniquely identify the job
          and both must be provided. Other fields can be provided depending on
          the job's type.
      tags:
        - Runs
  /runs/{id}/status:
    get:
      summary: check the status for a particular run ID
      tags:
        - Runs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/idStatus'
              examples:
                ADF (With Overrides):
                  value:
                    data:
                      status: queued
                      prbStatus: pending
                      statusDescription: string
                      inputs:
                        jobName: my_adf_job
                        jobType: ADF
                        overrides:
                          dates:
                            start: '2023-12-25'
                            end: '2023-12-27'
                          frequency: daily
                          calendar: sevenDay
                          runAsSerialNumber: '894550'
                      id: '34578'
                PA (With Overrides):
                  value:
                    data:
                      status: executing
                      prbStatus: running
                      statusDescription: string
                      inputs:
                        jobName: my_pa_job
                        jobType: PA
                        overrides:
                          tasks:
                            - task_1
                            - task_2
                          runAsSerialNumber: '894550'
                      id: '123456'
                PD (With Overrides):
                  value:
                    data:
                      status: executing
                      prbStatus: running
                      statusDescription: string
                      inputs:
                        jobName: my_pd_job
                        jobType: PD
                        overrides:
                          runAsSerialNumber: '894550'
                      id: '78904'
                PI:
                  value:
                    data:
                      status: queued
                      prbStatus: pending
                      statusDescription: string
                      inputs:
                        jobName: my_pi_job
                        jobType: PI
                      id: '78904'
                PUB (With Overrides):
                  value:
                    data:
                      status: queued
                      prbStatus: pending
                      statusDescription: string
                      inputs:
                        jobName: my_pub_job
                        jobType: PUB
                        overrides:
                          runAsOfDate: '2023-02-05'
                      id: '3456789'
                Vault (No Overrides):
                  value:
                    data:
                      inputs:
                        jobName: my_vault_job
                        jobType: vault
                      status: created
                      prbStatus: success
                      statusDescription: job has completed with success
                      id: '123456'
                Vault (With Overrides):
                  value:
                    data:
                      inputs:
                        jobName: my_vault_job
                        jobType: vault
                        overrides:
                          combinations:
                            - accounts:
                                - CLIENT:/FPS/VAULTED_RETURNS/7DAYS_VLT.ACCT
                                - CLIENT:/FPS/VAULTED_RETURNS/1MONTH.ACCT
                              dates:
                                - '2022-12-24'
                                - '2022-12-23'
                          runAsSerialNumber: '894550'
                      status: created
                      prbStatus: success
                      statusDescription: job has completed with success
                      id: '123456'
          headers:
            X-DataDirect-Request-Key:
              $ref: '#/components/headers/X-DataDirect-Request-Key'
            X-FactSet-Api-Request-Key:
              $ref: '#/components/headers/X-FactSet-Api-Request-Key'
            X-FactSet-Api-RateLimit-Limit:
              $ref: '#/components/headers/X-FactSet-Api-RateLimit-Limit'
            X-FactSet-Api-RateLimit-Remaining:
              $ref: '#/components/headers/X-FactSet-Api-RateLimit-Remaining'
            X-FactSet-Api-RateLimit-Reset:
              $ref: '#/components/headers/X-FactSet-Api-RateLimit-Reset'
        '401':
          description: Missing or invalid authentication.
          headers:
            X-DataDirect-Request-Key:
              $ref: '#/components/headers/X-DataDirect-Request-Key'
            X-FactSet-Api-Request-Key:
              $ref: '#/components/headers/X-FactSet-Api-Request-Key'
        '403':
          description: User is forbidden with current credentials
          headers:
            X-DataDirect-Request-Key:
              $ref: '#/components/headers/X-DataDirect-Request-Key'
            X-FactSet-Api-Request-Key:
              $ref: '#/components/headers/X-FactSet-Api-Request-Key'
            X-FactSet-Api-RateLimit-Limit:
              $ref: '#/components/headers/X-FactSet-Api-RateLimit-Limit'
            X-FactSet-Api-RateLimit-Remaining:
              $ref: '#/components/headers/X-FactSet-Api-RateLimit-Remaining'
            X-FactSet-Api-RateLimit-Reset:
              $ref: '#/components/headers/X-FactSet-Api-RateLimit-Reset'
        '429':
          description: >-
            Rate limit reached. Wait till the time specified in Retry-After
            header value to make further requests.
          headers:
            X-DataDirect-Request-Key:
              $ref: '#/components/headers/X-DataDirect-Request-Key'
            X-FactSet-Api-Request-Key:
              $ref: '#/components/headers/X-FactSet-Api-Request-Key'
            Retry-After:
              description: >-
                Time to wait in seconds before making a new request as the rate
                limit has reached.
              schema:
                type: string
        '500':
          description: >-
            Server error. Log the X-DataDirect-Request-Key header to assist in
            troubleshooting.
          headers:
            X-DataDirect-Request-Key:
              $ref: '#/components/headers/X-DataDirect-Request-Key'
            X-FactSet-Api-Request-Key:
              $ref: '#/components/headers/X-FactSet-Api-Request-Key'
        '503':
          description: Request timed out. Retry the request in sometime.
          headers:
            X-DataDirect-Request-Key:
              $ref: '#/components/headers/X-DataDirect-Request-Key'
            X-FactSet-Api-Request-Key:
              $ref: '#/components/headers/X-FactSet-Api-Request-Key'
      operationId: checkRunStatus
      parameters: []
      description: >-
        Use this endpoint to check the status of a run using the id from the
        POST /runs endpoint
    parameters:
      - schema:
          type: string
          example: '1013456'
        name: id
        in: path
        required: true
        description: run id
tags:
  - name: Jobs
    description: These endpoints relate to PRB jobs
  - name: Runs
    description: These endpoints refer to specific runs for a PRB job
