openapi: 3.0.0
info:
  title: FactSet Private Markets API
tags:
  - name: Financials
    description: Retrieve Private Company Financials
  - name: Non-Periodic
    description: Retrieve Private Company Reference Data.
  - name: Data Items
    description: Retrieve available Private Company fields, metrics, and ratios.
paths:
  /factset-private-markets/v1/financials:
    get:
      summary: Returns Private Company Financials for a list of ids.
      description: |
        Returns Private Company Financials Information.
      tags:
        - Financials
    post:
      summary: Returns Private Company Financials for a list of ids.
      description: |
        Returns a private markets financials object for the requested ids.
      tags:
        - Financials
  /factset-private-markets/v1/non-periodic:
    get:
      summary: Returns Private Company reference data for a list of ids.
      description: |
        Returns Private Company reference information.
      tags:
        - Non-Periodic
    post:
      summary: Returns Private Company reference data for a list of ids.
      description: |
        Returns a private markets reference object for the requested ids.
      tags:
        - Non-Periodic
  /factset-private-markets/v1/fields:
    get:
      summary: Available private company fields, metrics, and ratios.
      operationId: getFields
      tags:
        - Data Items
      description: >
        Returns list of available Private Company fields that can be used in the
        `fields` parameter of related endpoints. These are related to FactSet
        Private Company standardized data.
      parameters:
        - $ref: '#/components/parameters/category'
      responses:
        '200':
          description: Private Company data items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fieldsResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '415':
          $ref: '#/components/responses/415'
        '500':
          $ref: '#/components/responses/500'
  /factset-private-markets/v1/universe:
    get:
      summary: Get Entity Candidates and Matches for a single name and attributes.
      description: >
        Finds the best candidate entities matching the given entity name.
        Country code can also be supplied to narrow the search. <p>**Max of 1
        Name permitted in a single GET request.** Use the POST method for
        /entity-match to fetch up to 25 names.</p><p>
      tags:
        - Universe
      operationId: getUniverse
      parameters:
        - $ref: '#/components/parameters/name'
        - $ref: '#/components/parameters/country'
      responses:
        '200':
          $ref: '#/components/responses/EntityMatchResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '415':
          $ref: '#/components/responses/415'
        '500':
          $ref: '#/components/responses/500'
    post:
      summary: >-
        Get a list of Entity Candidates and Matches for a requested list of up
        to 25 names and attributes.
      description: >
        Finds the best candidate entities matching the given entity name.
        Country code can also be supplied to narrow the search. Finds the best
        candidate entities matching the given company name. <p>**Max of 25 Names
        inputted.**</p><p>
      tags:
        - Universe
      operationId: getUniverseForList
      requestBody:
        required: true
        description: A request to match an Entity.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntityMatchRequest'
      responses:
        '200':
          $ref: '#/components/responses/EntityMatchResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '415':
          $ref: '#/components/responses/415'
        '500':
          $ref: '#/components/responses/500'
25 names.</p><p>
      tags:
        - Universe
      operationId: getUniverse
      parameters:
        - $ref: '#/components/parameters/name'
        - $ref: '#/components/parameters/country'
      responses:
        '200':
          $ref: '#/components/responses/EntityMatchResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '415':
          $ref: '#/components/responses/415'
        '500':
          $ref: '#/components/responses/500'
    post:
      summary: >-
        Get a list of Entity Candidates and Matches for a requested list of up
        to 25 names and attributes.
      description: >
        Finds the best candidate entities matching the given entity name.
        Country code can also be supplied to narrow the search. Finds the best
        candidate entities matching the given company name. <p>**Max of 25 Names
        inputted.**</p><p>
      tags:
        - Universe
      operationId: getUniverseForList
      requestBody:
        required: true
        description: A request to match an Entity.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntityMatchRequest'
      responses:
        '200':
          $ref: '#/components/responses/EntityMatchResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '415':
          $ref: '#/components/responses/415'
        '500':
          $ref: '#/components/responses/500'
