openapi: 3.0.0
info:
  title: Time Series API For Digital Portals
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /vendor/chartIQ/timeSeries/eod/list:
    post:
      tags:
        - vendor
      summary: End-of-day time series data for a notation.
      description: >-
        End-of-day time series data for a notation. The resulting time series is
        always adjusted for currency changes.<br><br>Pagination to a previous
        page is not supported and `pagination.previous` is always `null`.
  /vendor/chartIQ/timeSeries/eod/subsample/get:
    post:
      tags:
        - vendor
      summary: Single subsample end-of-day data for a notation.
      description: >-
        Single subsample end-of-day data for a notation. The sample is always
        adjusted for currency changes. The subsample may exceed the entitled
        date range, but will be based only on days that are in the entitled
        range.
  /vendor/chartIQ/timeSeries/eod/subsample/list:
    post:
      tags:
        - vendor
      summary: Subsampled end-of-day time series data for a notation.
      description: >-
        Subsampled end-of-day time series data for a notation. The resulting
        time series is always adjusted for currency changes. If a subsample's
        date range is not entirely within the maximally entitled date range, the
        subsample is excluded from the response.<br><br>Pagination to a previous
        page is not supported and `pagination.previous` is always `null`.
  /vendor/chartIQ/timeSeries/intraday/subsample/get:
    post:
      tags:
        - vendor
      summary: Single subsample intraday data for a notation.
      description: >-
        Single subsample intraday data for a notation. The subsample may exceed
        the entitled time range, but will be based only on ticks that are in the
        entitled range.
  /vendor/chartIQ/timeSeries/intraday/subsample/list:
    post:
      tags:
        - vendor
      summary: Subsampled intraday time series data for a notation.
      description: >-
        Subsampled intraday time series data for a notation. If a subsample's
        time range is not entirely within the maximally entitled time range, the
        subsample is excluded from the response.<br><br>Pagination to a previous
        page is not supported and `pagination.previous` is always `null`.
  /prices/timeSeries/eod/list:
    post:
      tags:
        - prices
      summary: End-of-day time series data for a notation.
      description: >-
        End-of-day time series data for a notation. The resulting time series is
        always adjusted for currency changes.<br><br>Pagination to a previous
        page is not supported and `pagination.previous` is always `null`.
  /prices/timeSeries/eod/subsample/get:
    post:
      tags:
        - prices
      summary: Single subsample end-of-day data for a notation.
      description: >-
        Single subsample end-of-day data for a notation. The sample is always
        adjusted for currency changes. The subsample may exceed the entitled
        date range, but will be based only on days that are in the entitled
        range.
  /prices/timeSeries/eod/subsample/list:
    post:
      tags:
        - prices
      summary: Subsampled end-of-day time series data for a notation.
      description: >-
        Subsampled end-of-day time series data for a notation. The resulting
        time series is always adjusted for currency changes. If a subsample's
        date range is not entirely within the maximally entitled date range, the
        subsample is excluded from the response.<br><br>Pagination to a previous
        page is not supported and `pagination.previous` is always `null`.
  /prices/timeSeries/intraday/list:
    post:
      tags:
        - prices
      summary: Intraday time series data for a notation.
      description: >-
        Intraday time series data for a notation.<br><br>Pagination to a
        previous page is not supported and `pagination.previous` is always
        `null`.
  /prices/timeSeries/intraday/subsample/get:
    post:
      tags:
        - prices
      summary: Single subsample intraday data for a notation.
      description: >-
        Single subsample intraday data for a notation. The subsample may exceed
        the entitled time range, but will be based only on ticks that are in the
        entitled range.
  /prices/timeSeries/intraday/subsample/list:
    post:
      tags:
        - prices
      summary: Subsampled intraday time series data for a notation.
      description: >-
        Subsampled intraday time series data for a notation. If a subsample's
        time range is not entirely within the maximally entitled time range, the
        subsample is excluded from the response.<br><br>Pagination to a previous
        page is not supported and `pagination.previous` is always `null`.
tags:
  - name: prices
    description: prices endpoints
  - name: vendor
    description: vendor endpoints
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/
x-interface-version: 2
x-documenter-version: 6.3.9
x-api-version: nu
