openapi: 3.0.2
info:
  title: FactSet Search Answers API
paths:
  /search/answers/v1/data:
    get:
      summary: Fetch FactSet answer in data format
      tags:
        - answers
      description: >-
        Returns an answer to the specified query (if a valid answer exists).
        Returns the answer data only (as JSON), without any markup information.
  /search/answers/v1/adaptive-card:
    get:
      summary: Fetch FactSet answer in Adaptive Card format
      tags:
        - answers
      description: >-
        Returns an answer to the specified query (if valid answer exists) in the
        Adaptive Card format (https://adaptivecards.io/).
      operationId: searchForAdaptiveCardAnswer
      parameters:
        - $ref: '#/components/parameters/Query'
        - $ref: '#/components/parameters/IncludeThumbnail'
        - $ref: '#/components/parameters/DisableNoAnswerResponses'
        - $ref: '#/components/parameters/Theme'
      responses:
        '200':
          description: Request was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdaptiveCardAnswerSuccessResponse'
        '400':
          description: Missing or empty query.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnswerFailureResponse'
        '401':
          description: Missing or invalid authentication.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnswerFailureResponse'
        '500':
          description: Unhandled error occurred while processing the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnswerFailureResponse'
