openapi: 3.0.1
info:
  title: Security-Modeling API
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /analytics/security-modeling/v3/securities/retrieve:
    post:
      tags:
        - SecurityModeling
      summary: Get existing securities
      description: This endpoint gets all existing securities.
  /analytics/security-modeling/v3/securities/upsert:
    post:
      tags:
        - SecurityModeling
      summary: Create or update securities
      description: This endpoint is to create or update existing securities.
  /analytics/security-modeling/v3/securities/delete:
    post:
      tags:
        - SecurityModeling
      summary: Delete existing securities
      description: This endpoint deletes existing securities.
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/
n:
            schema:
              $ref: '#/components/schemas/SMDeleteParametersRoot'
      responses:
        '200':
          description: Expected response, deletes existing securities.
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              schema:
                type: string
                description: FactSet's request key header.
            X-FactSet-Api-Request-Key:
              description: >-
                Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              schema:
                type: string
                description: >-
                  Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
            X-FactSet-Api-RateLimit-Limit:
              description: Number of allowed requests for the time window.
              schema:
                type: string
            X-FactSet-Api-RateLimit-Remaining:
              description: Number of requests left for the time window.
              schema:
                type: string
            X-FactSet-Api-RateLimit-Reset:
              description: Number of seconds remaining till rate limit resets.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SMDeleteResponseRoot'
        '401':
          description: Missing or invalid authentication.
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              schema:
                type: string
                description: FactSet's request key header.
            X-FactSet-Api-Request-Key:
              description: >-
                Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              schema:
                type: string
                description: >-
                  Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
        '403':
          description: User is forbidden with current credentials
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              schema:
                type: string
                description: FactSet's request key header.
            X-FactSet-Api-Request-Key:
              description: >-
                Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              schema:
                type: string
                description: >-
                  Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
            X-FactSet-Api-RateLimit-Limit:
              description: Number of allowed requests for the time window.
              schema:
                type: string
            X-FactSet-Api-RateLimit-Remaining:
              description: Number of requests left for the time window.
              schema:
                type: string
            X-FactSet-Api-RateLimit-Reset:
              description: Number of seconds remaining till rate limit resets.
              schema:
                type: string
        '406':
          description: >-
            Unsupported Accept header. Header needs to be set to
            application/json.
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              schema:
                type: string
                description: FactSet's request key header.
            X-FactSet-Api-Request-Key:
              description: >-
                Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              schema:
                type: string
                description: >-
                  Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
            X-FactSet-Api-RateLimit-Limit:
              description: Number of allowed requests for the time window.
              schema:
                type: string
            X-FactSet-Api-RateLimit-Remaining:
              description: Number of requests left for the time window.
              schema:
                type: string
            X-FactSet-Api-RateLimit-Reset:
              description: Number of seconds remaining till rate limit resets.
              schema:
                type: string
        '429':
          description: >-
            Rate limit reached. Wait till the time specified in Retry-After
            header value to make further requests.
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              schema:
                type: string
                description: FactSet's request key header.
            X-FactSet-Api-Request-Key:
              description: >-
                Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              schema:
                type: string
                description: >-
                  Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
            Retry-After:
              description: >-
                Time to wait in seconds before making a new request as the rate
                limit has reached.
              schema:
                type: string
        '500':
          description: >-
            Server error. Log the X-DataDirect-Request-Key header to assist in
            troubleshooting.
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              schema:
                type: string
                description: FactSet's request key header.
            X-FactSet-Api-Request-Key:
              description: >-
                Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              schema:
                type: string
                description: >-
                  Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
        '503':
          description: Request timed out. Retry the request in sometime.
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              schema:
                type: string
                description: FactSet's request key header.
            X-FactSet-Api-Request-Key:
              description: >-
                Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              schema:
                type: string
                description: >-
                  Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/
eSecurities
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SMDeleteParametersRoot'
      responses:
        '200':
          description: Expected response, deletes existing securities.
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              schema:
                type: string
                description: FactSet's request key header.
            X-FactSet-Api-Request-Key:
              description: >-
                Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              schema:
                type: string
                description: >-
                  Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
            X-FactSet-Api-RateLimit-Limit:
              description: Number of allowed requests for the time window.
              schema:
                type: string
            X-FactSet-Api-RateLimit-Remaining:
              description: Number of requests left for the time window.
              schema:
                type: string
            X-FactSet-Api-RateLimit-Reset:
              description: Number of seconds remaining till rate limit resets.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SMDeleteResponseRoot'
        '401':
          description: Missing or invalid authentication.
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              schema:
                type: string
                description: FactSet's request key header.
            X-FactSet-Api-Request-Key:
              description: >-
                Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              schema:
                type: string
                description: >-
                  Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
        '403':
          description: User is forbidden with current credentials
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              schema:
                type: string
                description: FactSet's request key header.
            X-FactSet-Api-Request-Key:
              description: >-
                Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              schema:
                type: string
                description: >-
                  Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
            X-FactSet-Api-RateLimit-Limit:
              description: Number of allowed requests for the time window.
              schema:
                type: string
            X-FactSet-Api-RateLimit-Remaining:
              description: Number of requests left for the time window.
              schema:
                type: string
            X-FactSet-Api-RateLimit-Reset:
              description: Number of seconds remaining till rate limit resets.
              schema:
                type: string
        '406':
          description: >-
            Unsupported Accept header. Header needs to be set to
            application/json.
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              schema:
                type: string
                description: FactSet's request key header.
            X-FactSet-Api-Request-Key:
              description: >-
                Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              schema:
                type: string
                description: >-
                  Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
            X-FactSet-Api-RateLimit-Limit:
              description: Number of allowed requests for the time window.
              schema:
                type: string
            X-FactSet-Api-RateLimit-Remaining:
              description: Number of requests left for the time window.
              schema:
                type: string
            X-FactSet-Api-RateLimit-Reset:
              description: Number of seconds remaining till rate limit resets.
              schema:
                type: string
        '429':
          description: >-
            Rate limit reached. Wait till the time specified in Retry-After
            header value to make further requests.
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              schema:
                type: string
                description: FactSet's request key header.
            X-FactSet-Api-Request-Key:
              description: >-
                Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              schema:
                type: string
                description: >-
                  Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
            Retry-After:
              description: >-
                Time to wait in seconds before making a new request as the rate
                limit has reached.
              schema:
                type: string
        '500':
          description: >-
            Server error. Log the X-DataDirect-Request-Key header to assist in
            troubleshooting.
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              schema:
                type: string
                description: FactSet's request key header.
            X-FactSet-Api-Request-Key:
              description: >-
                Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              schema:
                type: string
                description: >-
                  Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
        '503':
          description: Request timed out. Retry the request in sometime.
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              schema:
                type: string
                description: FactSet's request key header.
            X-FactSet-Api-Request-Key:
              description: >-
                Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              schema:
                type: string
                description: >-
                  Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/
