openapi: 3.0.0
info:
  title: SDF Download API
paths:
  /list-schemas:
    get:
      summary: schemas
      tags:
        - Schema
      description: >-
        <a
        href=https://api.factset.com/bulk-documents/sdf/v1/list-schemas>List-Schemas</a>
        helper end point provides the list of schemas subscribed by the client
        and their corresponding sequences if no query parameters are passed in
        the request.

         If schema & sequence number (version number of schema) are passed in the request, this endpoint provides a downloadable presigned url containing the schema information.
  /list-files:
    get:
      tags:
        - SDF and QFL Content Library
      operationId: get-v1-list-files
      description: >
        <a
        href=https://api.factset.com/bulk-documents/sdf/v1/list-files>List-Files</a>
        end point provides the delta & full files in a reverse chronological
        order by default for all the schemas & bundles subscribed by the client


         QFL:-
           - In case of QFL, <a href=https://api.factset.com/bulk-documents/sdf/v1/list-files>List-Files</a> end point provides the "Historical & Year to Date (YTD)" data in a reverse chronological order by default for all the factor families & groups subscribed to by the user</p> Provides "full files" only for historical bundles[data available from 1995 to previous year], "full & delta files" for YTD bundles[data available for current year]
           
           If startDate and endDate parameters are not specified in the request, this endpoint returns past 10 days data by default.
      parameters:
        - $ref: '#/components/parameters/schema'
        - $ref: '#/components/parameters/bundle'
        - $ref: '#/components/parameters/type'
        - $ref: '#/components/parameters/startDate'
        - $ref: '#/components/parameters/endDate'
        - $ref: '#/components/parameters/_paginationLimit'
        - $ref: '#/components/parameters/_paginationOffset'
        - $ref: '#/components/parameters/_sort'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list-files_200Response'
              examples:
                default200ResponseExample:
                  $ref: '#/components/examples/list-files_200ResponseExample'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list-files_400Response'
              examples:
                default400ReponseExample:
                  $ref: '#/components/examples/list-files_400ResponseExample'
tags:
  - name: Schema
  - name: SDF and QFL Content Library
