openapi: 3.0.1
info:
  title: EMS API
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /orders/create:
    post:
      tags:
        - Orders
      summary: Send orders to EMS for execution.
      description: >-
        This endpoint takes the list of orders and place them on EMS for
        execution.
  /orders/replace:
    post:
      tags:
        - Orders
      summary: Replace the orders on EMS system.
      description: This endpoint takes the list of orders to be replaced on the EMS system.
      operationId: replace
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EMSReplaceOrdersRoot'
      responses:
        '200':
          description: Expected response, returns the list of order ids.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EMSOrdersResponseRoot'
              example:
                data:
                  accepted:
                    OR123456789:
                      symbol: GOOGL
                      side: buy
                      orderType: market
                      orderQuantity: 2500
                    OR123456790:
                      symbol: MSFT
                      side: buy
                      orderType: market
                      orderQuantity: 200
                  rejected:
                    OR123456791:
                      symbol: TSLA
                      side: buy
                      orderType: market
                      orderQuantity: 500
        '400':
          description: Invalid post body parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponse'
        '401':
          description: Missing or invalid authentication.
        '403':
          description: User is forbidden with current credentials.
        '415':
          description: >-
            Missing/Invalid Content-Type header. Header needs to be set to
            application/json.
        '429':
          description: Rate limit reached. Wait before sending further requests.
        '500':
          description: >-
            Server error. Log the X-DataDirect-Request-Key header to assist in
            troubleshooting.
        '503':
          description: Request timed out. Retry the request in sometime.
  /orders/cancel:
    post:
      tags:
        - Orders
      summary: Cancel the orders on EMS system.
      description: >-
        This endpoint takes the list of orders to be cancelled on the EMS
        system.
      operationId: cancel
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EMSCancelOrdersRoot'
      responses:
        '200':
          description: Expected response, returns the list of order ids.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EMSOrdersResponseRoot'
              example:
                data:
                  accepted:
                    OR123456789:
                      symbol: GOOGL
                      side: buy
                      orderType: market
                      orderQuantity: 2500
                    OR123456790:
                      symbol: MSFT
                      side: buy
                      orderType: market
                      orderQuantity: 200
                  rejected:
                    OR123456791:
                      symbol: TSLA
                      side: buy
                      orderType: market
                      orderQuantity: 500
        '400':
          description: Invalid post body parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponse'
        '401':
          description: Missing or invalid authentication.
        '403':
          description: User is forbidden with current credentials.
        '415':
          description: >-
            Missing/Invalid Content-Type header. Header needs to be set to
            application/json.
        '429':
          description: Rate limit reached. Wait before sending further requests.
        '500':
          description: >-
            Server error. Log the X-DataDirect-Request-Key header to assist in
            troubleshooting.
        '503':
          description: Request timed out. Retry the request in sometime.
  /child-orders/create:
    post:
      tags:
        - ChildOrders
      summary: Create Child Orders
      description: This endpoint is used to create child orders.
      operationId: createChildOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EMSChildOrdersRoot'
      responses:
        '200':
          description: Expected response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EMSCreateChildOrdersResponseRoot'
              example:
                data:
                  accepted:
                    '3280015':
                      basketId: FACTSET_OMS-100823_12345
                      ticketId: RKPW.3280015
                      symbol: FDS-USA
                  rejected:
                    '3280015':
                      message: 'Ticket does not exist for ticketid: null'
                      basketId: FACTSET_OMS-100823_12345
                      ticketId: RKPW.3280015
                      symbol: FDS-USA
        '400':
          description: Invalid parameters provided.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponse'
        '401':
          description: Missing or invalid authentication.
        '403':
          description: User is forbidden with current credentials.
        '415':
          description: >-
            Missing/Invalid Content-Type header. Header needs to be set to
            application/json.
        '429':
          description: Rate limit reached. Wait before sending further requests.
        '500':
          description: >-
            Server error. Log the X-DataDirect-Request-Key header to assist in
            troubleshooting.
        '503':
          description: Request timed out. Retry the request in sometime.
  /child-orders/replace:
    post:
      tags:
        - ChildOrders
      summary: Replace the Child Orders on EMS system.
      description: This endpoint takes the child order to be replaced on the EMS system.
      operationId: replaceChildOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EMSReplaceChildOrdersRoot'
      responses:
        '200':
          description: Expected response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EMSChildOrdersResponseRoot'
              example:
                data:
                  accepted:
                    '3280015':
                      ticketId: RKPW.3280015
                      symbol: FDS-USA
                  rejected:
                    '3280015':
                      message: 'Ticket does not exist for ticketid: null'
                      ticketId: RKPW.3280015
                      symbol: FDS-USA
        '400':
          description: Invalid parameters provided.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponse'
        '401':
          description: Missing or invalid authentication.
        '403':
          description: User is forbidden with current credentials.
        '415':
          description: >-
            Missing/Invalid Content-Type header. Header needs to be set to
            application/json.
        '429':
          description: Rate limit reached. Wait before sending further requests.
        '500':
          description: >-
            Server error. Log the X-DataDirect-Request-Key header to assist in
            troubleshooting.
        '503':
          description: Request timed out. Retry the request in sometime.
  /child-orders/cancel:
    post:
      tags:
        - ChildOrders
      summary: Cancel Child Orders
      description: This endpoint is to cancel a specific child order.
      operationId: cancelChildOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EMSCancelChildOrdersRoot'
      responses:
        '200':
          description: Expected response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EMSChildOrdersResponseRoot'
              example:
                data:
                  accepted:
                    '3280015':
                      ticketId: RKPW.3280015
                      symbol: FDS-USA
                  rejected:
                    '3280015':
                      message: 'Ticket does not exist for ticketid: null'
                      ticketId: RKPW.3280015
                      symbol: FDS-USA
        '400':
          description: Invalid parameters provided.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponse'
        '401':
          description: Missing or invalid authentication.
        '403':
          description: User is forbidden with current credentials.
        '415':
          description: >-
            Missing/Invalid Content-Type header. Header needs to be set to
            application/json.
        '429':
          description: Rate limit reached. Wait before sending further requests.
        '500':
          description: >-
            Server error. Log the X-DataDirect-Request-Key header to assist in
            troubleshooting.
        '503':
          description: Request timed out. Retry the request in sometime.
tags:
  - name: Orders
    description: These endpoints relate to Order Entry.
  - name: ChildOrders
    description: These endpoints relate to Order Routing.
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/factset-trading-api
