openapi: 3.0.1
info:
  title: FactSet Digital Cards API
  description: ''
paths:
  /v1/company/{component}/adaptive-card:
    parameters:
      - null
      - null
      - null
      - null
    get:
      tags:
        - Digital Card
      summary: Retrieve Multiple Digital Cards in Microsoft Adaptive Card Format.
  /v1/company/{component}/adaptive-card/{id}:
    parameters:
      - null
      - null
    get:
      tags:
        - Digital Card
      summary: Retrieve One Digital Card in Microsoft Adaptive Ca
