openapi: 3.0.0
info:
  title: Exchange DataFeed Data Model API
paths:
  /products:
    get:
      summary: Request the enumeration table for FactSet product codes.
      tags:
        - FactSet Product codes
      description: >
        Data can be returned in CSV, JSON or XML format, use the `format`
        parameter to chnage from the default JS
