openapi: 3.0.0
info:
  title: ID Lookup API
paths:
  /v1/idsearch:
    post:
      tags:
        - FactSet ID Lookup
      summary: >-
        Search funtionality to return tickers, company names and unique
        identifiers for FactSet data
      description: >
        Service will accept request in JSON formatted request body. The request
        is sent by passing a query which is an array conitaining search query
        objects with parameters. The parameters contain search term and filters
        defined by the end user. This would display a specific set of
        identifiers based on th
