openapi: 3.0.1
info:
  title: Tick History
  license:
    name: Apache 3.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: Data Service Manual
  url: >-
    https://www.factset.com/hubfs/Website_Downloads/Exchange%20DataFeed/data%20service%20manual%202.0b.pdf
paths:
  /TickHistory/history:
    get:
      tags:
        - Tick History
      summary: >-
        Tick History service returns trade data and associated quotes for a
        client specified interval and time period
      description: >-
        When using an HTTP GET request, the seach criteria is sent via the query
        string in the URL. Please make sure that all requests contain a date
        within the past trailing year. Fields are added using ampersands, with
        enumerations seperated by commas. <p>**Try it Out** - references a
        sandbox environment to simulate live reponses. Available `id` is limited
        to
        BABA-USA,WALMEX-MX,7203-TKS,VOD-LON,NPN-JSE,MABAX,NZF,SPY-USA,AGG-USA,GLD-USA,AOR-USA,MNA-USA,UUP-USA,SP50-SPX,ESX-STX,XAO-ASX,WD-MSX,NG00-USA,GC00-USA,CC00-USA,C00-USA,FC00-USA,ER00-USA,EURUSD-FX1,USDMXN-FX1,AUDJPY-FX1,EURCZK-FX1,USDILS-FX1,USDZAR-FX1,US10YY-TU1,FDS#190621C00145000-USA,FDS#190621P00145000-USA.
        Current day data is not available.</p>
  /TickHistory/firsttrade:
    get:
      tags:
        - First Trade
      summary: >-
        Request returns data for the first trade (official and unofficial) after
        the specified time
      description: ''
  /TickHistory/lasttrade:
    get:
      tags:
        - Last Trade
      summary: >-
        Request returns data for the last trade and associated quotes before the
        specified time
      description: ''
  /TickHistory/qat:
    get:
      tags:
        - Quote at Time
      summary: Request returns a quote at the specified time
      description: ''
  /TickHistory/tradesattime:
    get:
      tags:
        - Trades at Time
      summary: >-
        Request returns the before and after trade data along with the
        associated quotes for the specified time
      description: ''
