openapi: 3.0.1
info:
  title: IRN API v1
paths:
  /v1/meetings:
    get:
      tags:
        - Meetings
      summary: >-
        Get all the meetings in the specified date range filtered on the given
        identifiers
    post:
      tags:
        - Meetings
      summary: Create a meeting
  /v1/meetings/{meetingId}:
    get:
      tags:
        - Meetings
      summary: Get details of a meeting
    put:
      tags:
        - Meetings
      summary: Update meeting
    delete:
      tags:
        - Meetings
      summary: Delete a Meeting
  /v1/meetings/{meetingId}/attachments:
    get:
      tags:
        - Attachments
      summary: Get all the attachments belonging to a meeting
    post:
      tags:
        - Attachments
      summary: Create an attachment for a existing meeting
  /v1/meetings/{meetingId}/attachments/{attachmentId}/download:
    get:
      tags:
        - Attachments
      summary: Download an attachment from a Meeting
  /v1/meetings/{meetingId}/comments:
    get:
      tags:
        - Comments
      summary: Get all comments for a meeting
    post:
      tags:
        - Comments
      summary: Create a comment to a Meeting
  /v1/meetings/{meetingId}/comments/{commentId}:
    get:
      tags:
        - Comments
      summary: Get details of a comment belonging to a meeting
    patch:
      tags:
        - Comments
      summary: Edit a comment for a meeting
    delete:
      tags:
        - Comments
      summary: Delete a Comment from a Meeting
  /v1/meetings/{meetingId}/comments/{commentId}/attachments:
    get:
      tags:
        - Comments
      summary: Get attachments summary of a comment belonging to a meeting
    post:
      tags:
        - Comments
      summary: Create a comment attachment to a Meeting
  /v1/meetings/{meetingId}/comments/{commentId}/attachments/{attachmentId}/download:
    get:
      tags:
        - Comments
      summary: Download single attachment detail of a comment belonging to a meeting
  /v1/meetings/{meetingId}/events:
    get:
      tags:
        - Events
      summary: Get all the record events that belong to a meeting
  /v1/meetings/{meetingId}/events/{recordEventId}:
    get:
      tags:
        - Events
      summary: Get details of a record event of a meeting
  /v1/meetings/{meetingId}/attachments/{attachmentId}:
    delete:
      tags:
        - Attachments
      summary: Delete attachment from meeting
tags:
  - name: Attachments
  - name: Comments
  - name: Events
  - name: nu
