openapi: 3.0.1
info:
  title: IRN API v1
paths:
  /v1/authors:
    get:
      tags:
        - Notes - Configuration
      summary: Get all Authors
  /v1/contact-custom-fields:
    get:
      tags:
        - Contacts - CustomFields
      summary: Get all the contact custom fields
    post:
      tags:
        - Contacts - CustomFields
      summary: Create a contact custom field
  /v1/contact-custom-fields/{contactCustomFieldId}:
    get:
      tags:
        - Contacts - CustomFields
      summary: Get a specific Contact custom field's details
    patch:
      tags:
        - Contacts - CustomFields
      summary: Edit a contact custom field
    delete:
      tags:
        - Contacts - CustomFields
      summary: Delete a contact custom field
  /v1/contact-roles:
    get:
      tags:
        - Contacts - Roles
      summary: Get list of the contact roles configured in your group
    post:
      tags:
        - Contacts - Roles
      summary: Create contact roles
  /v1/contact-types:
    get:
      tags:
        - Contacts - Types
      summary: Get list of the contact types configured in your group
    post:
      tags:
        - Contacts - Types
      summary: Create contact types
  /v1/custom-fields:
    get:
      tags:
        - Notes - Configuration
      summary: Get all Custom Fields
  /v1/custom-symbol-custom-fields:
    get:
      tags:
        - CustomSymbols - CustomFields
      summary: Get all the Custom symbol custom fields
    post:
      tags:
        - CustomSymbols - CustomFields
      summary: Create a Custom symbol custom field
  /v1/custom-symbol-custom-fields/{customSymbolCustomFieldId}:
    get:
      tags:
        - CustomSymbols - CustomFields
      summary: Get a specific Custom symbol custom field's details
    patch:
      tags:
        - CustomSymbols - CustomFields
      summary: Edit a Custom symbol custom field
    delete:
      tags:
        - CustomSymbols - CustomFields
      summary: Delete a Custom symbol custom field
  /v1/custom-symbol-types:
    get:
      tags:
        - CustomSymbols - Types
      summary: Get all the custom symbol types
    post:
      tags:
        - CustomSymbols - Types
      summary: Create a Custom symbol type
  /v1/custom-symbol-types/{customSymbolTypeId}:
    get:
      tags:
        - CustomSymbols - Types
      summary: Get a specific Custom symbol type's details
    put:
      tags:
        - CustomSymbols - Types
      summary: Edit a Custom symbol type
    delete:
      tags:
        - CustomSymbols - Types
      summary: Delete a Custom symbol type
  /v1/custom-symbol-types/{customSymbolTypeId}/custom-fields:
    get:
      tags:
        - CustomSymbols - Types
      summary: Get Custom fields for Custom Symbol type
  /v1/group:
    get:
      tags:
        - Notes - Configuration
      summary: Get Group details
  /v1/group/client-sales-representative:
    get:
      tags:
        - Notes - Configuration
  /v1/phone-number-types:
    get:
      tags:
        - Contacts - PhoneNumberTypes
      summary: Get list of the phone types configured in your group
    post:
      tags:
        - Contacts - PhoneNumberTypes
      summary: Create a phone type
  /v1/recommendations:
    get:
      tags:
        - Notes - Configuration
      summary: Get all Recommendations
  /v1/relationship-categories:
    get:
      tags:
        - Contacts - Relationship Category
      summary: Get list of the relationship categories configured in your group
    post:
      tags:
        - Contacts - Relationship Category
      summary: Create a relationship category
  /v1/relationships:
    get:
      tags:
        - Contacts - Relationships
      summary: Get list of the relationships configured in your group
    post:
      tags:
        - Contacts - Relationships
      summary: Create a relationship type
  /v1/sentiments:
    get:
      tags:
        - Notes - Configuration
      summary: Get all Sentiments
  /v1/subjects:
    get:
      tags:
        - Notes - Configuration
      summary: Get all Subjects
  /v1/subjects/{subjectId}:
    get:
      tags:
        - Notes - Configuration
      summary: Get Subject details for the given Id provided
  /v1/symbols-relationships:
    get:
      tags:
        - CustomSymbols - Relationships
      summary: Get all the Symbols Relationships
    post:
      tags:
        - CustomSymbols - Relationships
      summary: Create a symbol relationship
  /v1/teams:
    get:
      tags:
        - Notes - Configuration
      summary: Get all Teams
  /v1/teams/{teamId}:
    get:
      tags:
        - Notes - Configuration
      summary: Get Team details for the given Id provided
  /v1/users:
    get:
      tags:
        - Notes - Configuration
      summary: Get all assigned FactSet users
  /v1/custom-symbol-types/reorder:
    post:
      tags:
        - CustomSymbols - Types
  /v1/relationship-categories/reorder:
    post:
      tags:
        - Contacts - Relationship Category
      summary: Reorder relationship categories
  /v1/contact-roles/{contactRoleId}:
    put:
      tags:
        - Contacts - Roles
      summary: Edit a contact role
    delete:
      tags:
        - Contacts - Roles
      summary: Delete a contact role
  /v1/contact-types/{contactTypeId}:
    put:
      tags:
        - Contacts - Types
      summary: Edit a contact type
    delete:
      tags:
        - Contacts - Types
      summary: Delete a contact type
  /v1/phone-number-types/{phoneNumberTypeId}:
    put:
      tags:
        - Contacts - PhoneNumberTypes
      summary: Edit a phone type
    delete:
      tags:
        - Contacts - PhoneNumberTypes
      summary: Delete a phone type
  /v1/relationship-categories/{relationshipCategoryId}:
    put:
      tags:
        - Contacts - Relationship Category
      summary: Edit a relationship category
    delete:
      tags:
        - Contacts - Relationship Category
      summary: Delete a relationship category
  /v1/relationships/{relationshipId}:
    put:
      tags:
        - Contacts - Relationships
      summary: Edit a relationship type
    delete:
      tags:
        - Contacts - Relationships
      summary: Delete a relationship type
  /v1/symbols-relationships/{symbolsRelationshipId}:
    put:
      tags:
        - CustomSymbols - Relationships
      summary: Edit a symbol relationship
    delete:
      tags:
        - CustomSymbols - Relationships
      summary: Delete a symbol relationship
tags:
  - name: Contacts - CustomFields
  - name: Contacts - PhoneNumberTypes
  - name: Contacts - Relationship Category
  - name: Contacts - Relationships
  - name: Contacts - Roles
  - name: Contacts - Types
  - name: CustomSymbols - CustomFields
  - name: CustomSymbols - Relationships
  - name: CustomSymbols - Types
  - name: Notes - Configuration
