openapi: 3.0.1
info:
  title: IRN API v1
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/irn-notes-api#apiDocumentation
paths:
  /v1/events:
    get:
      tags:
        - Events
      summary: >-
        Get all the record events in the specified date range filtered on the
        given types
  /v1/identifiers:
    get:
      tags:
        - Identifiers
      summary: Get all the identifier details for given identifiers
  /v1/notes:
    get:
      tags:
        - Notes
      summary: >-
        Get all the notes in the specified date range filtered on the given
        identifiers
    post:
      tags:
        - Notes
      summary: Create a note
  /v1/notes/{noteId}:
    get:
      tags:
        - Notes
      summary: Get details of a note
    put:
      tags:
        - Notes
      summary: Update a note
    delete:
      tags:
        - Notes
      summary: Delete a Note
  /v1/notes/{noteId}/attachments:
    get:
      tags:
        - Attachments
      summary: Get all the attachments belonging to a note
    post:
      tags:
        - Attachments
      summary: Create an attachment for an existing note
  /v1/notes/{noteId}/attachments/{attachmentId}/download:
    get:
      tags:
        - Attachments
      summary: Download an attachment from a Note
  /v1/notes/{noteId}/comments:
    get:
      tags:
        - Comments
      summary: Get all comments for a note
    post:
      tags:
        - Comments
      summary: Create a comment to a Note
  /v1/notes/{noteId}/comments/{commentId}:
    get:
      tags:
        - Comments
      summary: Get details of a comment belonging to a note
    patch:
      tags:
        - Comments
      summary: Edit a comment for a note
    delete:
      tags:
        - Comments
      summary: Delete a Comment from a Note
  /v1/notes/{noteId}/comments/{commentId}/attachments:
    get:
      tags:
        - Comments
      summary: Get attachments summary of a comment belonging to a note
    post:
      tags:
        - Comments
      summary: Create a comment attachment to a Note
  /v1/notes/{noteId}/comments/{commentId}/attachments/{attachmentId}/download:
    get:
      tags:
        - Comments
      summary: Download single attachment detail of a comment belonging to a note
  /v1/notes/{noteId}/events:
    get:
      tags:
        - Events
      summary: Get all the record events that belong to a note
  /v1/notes/{noteId}/events/{recordEventId}:
    get:
      tags:
        - Events
      summary: Get details of a record event of a note
  /v1/notes/{noteId}/attachments/{attachmentId}:
    delete:
      tags:
        - Attachments
      summary: Delete attachment from note
tags:
  - name: Attachments
  - name: Comments
  - name: Events
  - name: Identifiers
  - name: Notes
