openapi: 3.0.1
info:
  title: Northfield Portfolio API
  license:
    name: Apache License 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.txt
paths:
  /analytics/lookups/v3/accounts/{path}:
    get:
      tags:
        - Accounts
      summary: Get accounts and sub-directories in a directory
      description: >-
        This endpoint looks up all ACCT and ACTM files and sub-directories in a
        given directory.
  /analytics/lookups/v3/currencies:
    get:
      tags:
        - Currencies
      summary: Get currencies
      description: >-
        This endpoint lists all the currencies that can be applied to any
        calculation.
  /analytics/engines/npo/v3/optimizations:
    post:
      tags:
        - NPO Optimizer
      summary: Create and Run NPO optimization
      description: "This endpoint creates and runs NPO optimization specified in the POST body parameters.\r\n            \r\nRemarks:\r\n            \r\n*\tAny settings in POST body will act as a one-time override over the settings saved in the strategy document."
  /analytics/engines/npo/v3/optimizations/{id}:
    put:
      tags:
        - NPO Optimizer
      summary: Create or Update NPO optimization and run it.
      description: >-
        This endpoint updates and run the NPO optimization specified in the PUT
        body parameters. It also allows the creation of new NPO optimization
        with custom id.
    get:
      tags:
        - NPO Optimizer
      summary: Get NPO optimization parameters by id
      description: >-
        This is the endpoint that returns the optimization parameters passed for
        an optimization.
    delete:
      tags:
        - NPO Optimizer
      summary: Cancel NPO optimization by id
      description: This is the endpoint to cancel a previously submitted optimization.
  /analytics/engines/npo/v3/optimizations/{id}/status:
    get:
      tags:
        - NPO Optimizer
      summary: Get NPO optimization status by id
      description: "This is the endpoint to check on the progress of a previously requested optimization.\r\nIf the optimization has finished computing, the body of the response will contain result in JSON.\r\nOtherwise, the optimization is still running and the X-FactSet-Api-PickUp-Progress header will contain a progress percentage."
  /analytics/engines/npo/v3/optimizations/{id}/result:
    get:
      tags:
        - NPO Optimizer
      summary: Get NPO optimization result by id
      description: >-
        This is the endpoint to get the result of a previously requested
        optimization.
  /analytics/engines/npo/v3/strategies/{path}:
    get:
      tags:
        - StrategyDocuments
      summary: Get Northfield strategy documents and sub-directories in a directory
      description: >-
        This endpoint looks up all Northfield strategy documents and
        sub-directories in a given directory.
