openapi: 3.0.0
info:
  title: Open:FactSet - Partners
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/openfactset-partners-documents
paths:
  /linkup/job-listings:
    get:
      tags:
        - LinkUp
      summary: >-
        Returns the  daily files from Open:FactSet Partner - LinkUp. The LinkUp
        API provides access to job listings dataset that is sourced directly
        from employer webistes globally delivered daily.
      description: >-
        Returns the  daily files from Open:FactSet Partner - LinkUp. The LinkUp
        API provides access to job listings dataset that is sourced directly
        from employer webistes globally delivered daily. **This API is no longer
        being sold for new clients.**
  /orbit/transcripts/daily:
    get:
      tags:
        - Orbit
      summary: Returns the daily files from Open:FactSet Partner - Orbit.
      description: Returns the daily files from Open:FactSet Partner - Orbit.
  /orbit/transcripts/history:
    get:
      tags:
        - Orbit
      summary: Returns the history files from Open:FactSet Partner - Orbit
      description: 'Returns the historical files from February 28th, 2005 to current date. '
  /ozmosi/clinical-trials/daily:
    get:
      tags:
        - Ozmosi
      summary: >-
        Returns the daily files of Clinical Trial Details from Open:FactSet
        Partner - Ozmosi.
      description: >-
        Returns the daily files of Clinical Trial Details from Open:FactSet
        Partner - Ozmosi.
  /ozmosi/diseases/daily:
    get:
      tags:
        - Ozmosi
      summary: >-
        Returns the daily files of Diseases Details from Open:FactSet Partner-
        Ozmosi.
      description: >-
        Returns the daily files of Diseases Details from Open:FactSet Partner-
        Ozmosi.
  /ozmosi/biomarkers/daily:
    get:
      tags:
        - Ozmosi
      summary: >-
        Returns the daily files of Biomarkers Details from Open:FactSet Partner
        - Ozmosi.
      description: >-
        Returns the daily files of Biomarkers Details from Open:FactSet Partner
        - Ozmosi.
  /ozmosi/beam-endpoints/daily:
    get:
      tags:
        - Ozmosi
      summary: >-
        Returns the daily files of Beam Endpoints Details from Open:FactSet
        Partner - Ozmosi.
      description: >-
        Returns the daily files of Beam Endpoints Details from Open:FactSet
        Partner - Ozmosi.
  /ozmosi/primaryoutcome/daily:
    get:
      tags:
        - Ozmosi
      summary: >-
        Returns the daily files of PrimaryOutcome Details from Open:FactSet
        Partner - Ozmosi.
      description: >-
        Returns the daily files of PrimaryOutcome Details from Open:FactSet
        Partner - Ozmosi.
  /ozmosi/orangepurple/daily:
    get:
      tags:
        - Ozmosi
      summary: >-
        Returns the daily files of OrangePurple Details from Open:FactSet
        Partner - Ozmosi.
      description: >-
        Returns the daily files of OrangePurple Details from Open:FaStset
        Partner - Ozmosi.
  /ozmosi/intervention/daily:
    get:
      tags:
        - Ozmosi
      summary: >-
        Returns the daily files of Intervention details from Open:FactSet
        Partner - Ozmosi.
      description: >-
        Returns the daily files of Intervention details from Open:FactSet
        Partner - Ozmosi.
  /ozmosi/sponsors/daily:
    get:
      tags:
        - Ozmosi
      summary: >-
        Returns the daily files of Sponsors Details from Open:FactSet Partner -
        Ozmosi.
      description: >-
        Returns the daily files of Sponsors Details from Open:FactSet Partner -
        Ozmosi.
  /ozmosi/collaborators/daily:
    get:
      tags:
        - Ozmosi
      summary: >-
        Returns the daily files of Collaborators Details from Open:FactSet
        Partner - Ozmosi.
      description: >-
        Returns the daily files of Collaborators Details from Open:FactSet
        Partner - Ozmosi.
  /ozmosi/clinical-trials/history:
    get:
      tags:
        - Ozmosi
      summary: Returns the history files from Open:FactSet Partner - Ozmosi
      description: Returns the historical files from June 23rd, 2005 to current date.
  /luxembourg/green-bonds/daily:
    get:
      tags:
        - Luxembourg
      summary: Returns daily files from Open:FactSet Partner - Luxembourg
      description: >
        Returns XML files and relevant metadata provided by Open: FactSet
        Partner – Luxembourg.
  /scripts-asia/transcripts:
    get:
      tags:
        - Scripts Asia
      summary: Returns the daily files from Open:FactSet Partner - Scripts Asia.
      description: >-
        Returns XML files and relevant metadata provided by Open: FactSet
        Partner – Scripts Asia.

        - type=delta returns the files from March 1st 2023 to current date.

        - type=full will returns the files from start of date until Feb 28th
        2023.
tags:
  - name: Luxembourg
    description: >
      <a
      href=https://go.factset.com/marketplace/catalog/product/lgx-datahub>Luxembourg</a>
      API provides access to Green Bonds data. 
  - name: Orbit
    description: >
      <a
      href=https://go.factset.com/marketplace/catalog/product/china-a-shares-transcripts>Orbit</a>
      API covers full universe of almost 4,800 companies since the early 2000's.
      Content covers 3 types, both in Chinese and English: 1) Earning Call
      Transcripts 2) Public disclosures on broker onsite research 3) Executive
      official responses on online platforms.
  - name: Ozmosi
    description: >
      <a href=https://open.factset.com/partners/ozmosi/en-us>Ozmosi</a> API
      provides access to Clinical Trials data.
  - name: Scripts Asia
    description: >-
      Scripts Asia API provides access to Asia Pacific regional collected
      transcripts.
  - name: LinkUp
    description: >
      <a
      href=https://go.factset.com/marketplace/catalog/product/linkup-raw>LinkUp</a>
      API provides access to job listings data.
