openapi: 3.0.3
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/overview-report-builder-api
info:
  title: FactSet Overview Report Builder API
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
tags:
  - name: Company
paths:
  /profile:
    get:
      tags:
        - Company
      summary: Overview Profile
  /peer-list:
    get:
      tags:
        - Company
      summary: Peer List
  /current-cap:
    get:
      tags:
        - Company
      summary: Current Capitalization
  /financial-highlights:
    get:
      tags:
        - Company
      summary: Financial / Estimate Highlights
  /transactions:
    get:
      tags:
        - Company
      summary: Transactions
  /key-stats:
    description: >-
      Returns key financial metrics for private and public companies, as well as
      ETFs and mutual funds.  This endpoint provides a quick and easy way to
      obtain fundamental financial data. These key statistics can be used to
      evaluate a company's financial health, compare it to other companies in
      the same industry, and make informed investment decisions.
    get:
      tags:
        - Company
      summary: Key Stats
