openapi: 3.0.0
info:
  title: Price Alerting API For Digital Portals
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /alerting/prices/basic/alert/get:
    get:
      tags:
        - alerting
      x-supportsOffsetBasedPaging: false
      x-supportsOffsetBasedPagingWithoutTotal: false
      x-supportsCursorBasedPaging: false
      x-supportsCursorBasedPagingWithoutTotal: false
      x-supportsPush: false
      x-requiresUser: true
      x-requiresInternalClient: false
      x-disallowUser: false
      x-no-merge: false
      x-maxSortParameterCount: 10
      x-supportsPermissionDeniedResponse: false
      description: >-
        Details of an alert. The details include the trigger definition at the
        time of alert creation.
      summary: Details of an alert.
  /alerting/prices/basic/alert/list:
    get:
      tags:
        - alerting
      x-supportsOffsetBasedPaging: false
      x-supportsOffsetBasedPagingWithoutTotal: false
      x-supportsCursorBasedPaging: true
      x-supportsCursorBasedPagingWithoutTotal: false
      x-supportsPush: true
      x-requiresUser: true
      x-requiresInternalClient: false
      x-disallowUser: false
      x-no-merge: false
      x-maxSortParameterCount: 10
      x-supportsPermissionDeniedResponse: false
      description: List of alerts in descending order of creation.
      summary: List of alerts.
  /alerting/prices/basic/trigger/get:
    get:
      tags:
        - alerting
      x-supportsOffsetBasedPaging: false
      x-supportsOffsetBasedPagingWithoutTotal: false
      x-supportsCursorBasedPaging: false
      x-supportsCursorBasedPagingWithoutTotal: false
      x-supportsPush: false
      x-requiresUser: true
      x-requiresInternalClient: false
      x-disallowUser: false
      x-no-merge: false
      x-maxSortParameterCount: 10
      x-supportsPermissionDeniedResponse: false
      description: Details of a trigger.
      summary: Details of a trigger.
  /alerting/prices/basic/trigger/list:
    post:
      tags:
        - alerting
      x-supportsOffsetBasedPaging: false
      x-supportsOffsetBasedPagingWithoutTotal: false
      x-supportsCursorBasedPaging: true
      x-supportsCursorBasedPagingWithoutTotal: false
      x-supportsPush: false
      x-requiresUser: true
      x-requiresInternalClient: false
      x-disallowUser: false
      x-no-merge: false
      x-maxSortParameterCount: 10
      x-supportsPermissionDeniedResponse: false
      description: Returns a list of triggers sorted in descending order of creation.
      summary: List of triggers.
tags:
  - name: alerting
    description: alerting endpoints
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/
x-interface-version: 2
x-documenter-version: 6.3.9
x-api-version: 4.4.0
