openapi: 3.0.0
info:
  title: News API For Digital Portals
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /news/article/get:
    get:
      tags:
        - news
      x-supportsOffsetBasedPaging: false
      x-supportsOffsetBasedPagingWithoutTotal: false
      x-supportsCursorBasedPaging: false
      x-supportsCursorBasedPagingWithoutTotal: false
      x-supportsPush: false
      x-requiresUser: false
      x-requiresInternalClient: false
      x-disallowUser: false
      x-no-merge: false
      x-maxSortParameterCount: 10
      x-supportsPermissionDeniedResponse: false
      summary: Details for a news article.
      description: Details for a news article.
  /news/article/list:
    post:
      tags:
        - news
      x-supportsOffsetBasedPaging: false
      x-supportsOffsetBasedPagingWithoutTotal: false
      x-supportsCursorBasedPaging: false
      x-supportsCursorBasedPagingWithoutTotal: true
      x-supportsPush: true
      x-requiresUser: false
      x-requiresInternalClient: false
      x-disallowUser: false
      x-no-merge: false
      x-maxSortParameterCount: 10
      x-supportsPermissionDeniedResponse: false
      summary: List of news articles.
      description: List of news articles.
  /news/article/listByChain:
    post:
      tags:
        - news
      x-supportsOffsetBasedPaging: false
      x-supportsOffsetBasedPagingWithoutTotal: false
      x-supportsCursorBasedPaging: false
      x-supportsCursorBasedPagingWithoutTotal: true
      x-supportsPush: true
      x-requiresUser: false
      x-requiresInternalClient: false
      x-disallowUser: false
      x-no-merge: false
      x-maxSortParameterCount: 10
      x-supportsPermissionDeniedResponse: false
      summary: List news articles of an article chain.
      description: List news articles of an article chain.
  /news/article/listByIndex:
    post:
      tags:
        - news
      x-supportsOffsetBasedPaging: false
      x-supportsOffsetBasedPagingWithoutTotal: false
      x-supportsCursorBasedPaging: false
      x-supportsCursorBasedPagingWithoutTotal: true
      x-supportsPush: true
      x-requiresUser: false
      x-requiresInternalClient: false
      x-disallowUser: false
      x-no-merge: false
      x-maxSortParameterCount: 10
      x-supportsPermissionDeniedResponse: false
      summary: >-
        News articles for instruments that are constituents of the given
        indices.
      description: >-
        News articles for instruments that are constituents of the given
        indices.
  /news/article/listByInstrument:
    post:
      tags:
        - news
      x-supportsOffsetBasedPaging: false
      x-supportsOffsetBasedPagingWithoutTotal: false
      x-supportsCursorBasedPaging: false
      x-supportsCursorBasedPagingWithoutTotal: true
      x-supportsPush: true
      x-requiresUser: false
      x-requiresInternalClient: false
      x-disallowUser: false
      x-no-merge: false
      x-maxSortParameterCount: 10
      x-supportsPermissionDeniedResponse: false
      summary: News articles for instruments.
      description: News articles for instruments.
  /news/article/listByMediaKind:
    post:
      tags:
        - news
      x-supportsOffsetBasedPaging: false
      x-supportsOffsetBasedPagingWithoutTotal: false
      x-supportsCursorBasedPaging: false
      x-supportsCursorBasedPagingWithoutTotal: true
      x-supportsPush: true
      x-requiresUser: false
      x-requiresInternalClient: false
      x-disallowUser: false
      x-no-merge: false
      x-maxSortParameterCount: 10
      x-supportsPermissionDeniedResponse: false
      summary: List news articles which contain media of specific media kinds.
      description: List news articles which contain media of specific media kinds.
  /news/article/searchByText:
    post:
      tags:
        - news
      x-supportsOffsetBasedPaging: false
      x-supportsOffsetBasedPagingWithoutTotal: false
      x-supportsCursorBasedPaging: false
      x-supportsCursorBasedPagingWithoutTotal: true
      x-supportsPush: true
      x-requiresUser: false
      x-requiresInternalClient: false
      x-disallowUser: false
      x-no-merge: false
      x-maxSortParameterCount: 10
      x-supportsPermissionDeniedResponse: false
      summary: Search for news articles using a fulltext search.
      description: >-
        Search for news articles using a fulltext search. All specified criteria
        need to be fulfilled for an article to match. Each criterion is handled
        according to its selectionType; "include" requires the criterion to
        evaluate to true, "exclude" requires the criterion to evaluate to false.
        A criterion is fulfilled when at least one of its values is found.
  /news/article/type/get:
    get:
      tags:
        - news
      x-supportsOffsetBasedPaging: false
      x-supportsOffsetBasedPagingWithoutTotal: false
      x-supportsCursorBasedPaging: false
      x-supportsCursorBasedPagingWithoutTotal: false
      x-supportsPush: false
      x-requiresUser: false
      x-requiresInternalClient: false
      x-disallowUser: false
      x-no-merge: false
      x-maxSortParameterCount: 10
      x-supportsPermissionDeniedResponse: false
      summary: Details for a news article type.
      description: Details for a news article type.
  /news/article/type/list:
    get:
      tags:
        - news
      x-supportsOffsetBasedPaging: false
      x-supportsOffsetBasedPagingWithoutTotal: false
      x-supportsCursorBasedPaging: false
      x-supportsCursorBasedPagingWithoutTotal: false
      x-supportsPush: false
      x-requiresUser: false
      x-requiresInternalClient: false
      x-disallowUser: false
      x-no-merge: false
      x-maxSortParameterCount: 10
      x-supportsPermissionDeniedResponse: false
      summary: List of news article types.
      description: List of news article types.
  /news/distributor/get:
    get:
      tags:
        - news
      x-supportsOffsetBasedPaging: false
      x-supportsOffsetBasedPagingWithoutTotal: false
      x-supportsCursorBasedPaging: false
      x-supportsCursorBasedPagingWithoutTotal: false
      x-supportsPush: false
      x-requiresUser: false
      x-requiresInternalClient: false
      x-disallowUser: false
      x-no-merge: false
      x-maxSortParameterCount: 10
      x-supportsPermissionDeniedResponse: false
      summary: Details of a distributor.
      description: Details of a distributor.
  /news/distributor/list:
    get:
      tags:
        - news
      x-supportsOffsetBasedPaging: false
      x-supportsOffsetBasedPagingWithoutTotal: false
      x-supportsCursorBasedPaging: false
      x-supportsCursorBasedPagingWithoutTotal: false
      x-supportsPush: false
      x-requiresUser: false
      x-requiresInternalClient: false
      x-disallowUser: false
      x-no-merge: false
      x-maxSortParameterCount: 1
      x-supportsPermissionDeniedResponse: false
      summary: List of distributors.
      description: List of distributors.
  /news/publisher/get:
    get:
      tags:
        - news
      x-supportsOffsetBasedPaging: false
      x-supportsOffsetBasedPagingWithoutTotal: false
      x-supportsCursorBasedPaging: false
      x-supportsCursorBasedPagingWithoutTotal: false
      x-supportsPush: false
      x-requiresUser: false
      x-requiresInternalClient: false
      x-disallowUser: false
      x-no-merge: false
      x-maxSortParameterCount: 10
      x-supportsPermissionDeniedResponse: false
      summary: Details of a publisher.
      description: Details of a publisher.
  /news/publisher/list:
    get:
      tags:
        - news
      x-supportsOffsetBasedPaging: false
      x-supportsOffsetBasedPagingWithoutTotal: true
      x-supportsCursorBasedPaging: false
      x-supportsCursorBasedPagingWithoutTotal: false
      x-supportsPush: false
      x-requiresUser: false
      x-requiresInternalClient: false
      x-disallowUser: false
      x-no-merge: false
      x-maxSortParameterCount: 1
      x-supportsPermissionDeniedResponse: false
      summary: List of publishers.
      description: List of publishers.
  /news/publisher/listByDistributor:
    get:
      tags:
        - news
      x-supportsOffsetBasedPaging: false
      x-supportsOffsetBasedPagingWithoutTotal: false
      x-supportsCursorBasedPaging: false
      x-supportsCursorBasedPagingWithoutTotal: false
      x-supportsPush: false
      x-requiresUser: false
      x-requiresInternalClient: false
      x-disallowUser: false
      x-no-merge: false
      x-maxSortParameterCount: 1
      x-supportsPermissionDeniedResponse: false
      summary: List of publishers provided by the given distributor.
      description: List of publishers provided by the given distributor.
  /news/publisher/searchByName:
    post:
      tags:
        - news
      x-supportsOffsetBasedPaging: false
      x-supportsOffsetBasedPagingWithoutTotal: false
      x-supportsCursorBasedPaging: false
      x-supportsCursorBasedPagingWithoutTotal: false
      x-supportsPush: false
      x-requiresUser: false
      x-requiresInternalClient: false
      x-disallowUser: false
      x-no-merge: false
      x-maxSortParameterCount: 1
      x-supportsPermissionDeniedResponse: false
      summary: Search for publishers.
      description: Search for publishers by the name of the publisher.
tags:
  - name: news
    description: news endpoints
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/
x-interface-version: 2
x-documenter-version: 6.3.9
x-api-version: 4.4.0
