openapi: 3.0.1
info:
  title: Vault API
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /analytics/engines/vault/v3/components:
    get:
      tags:
        - Components
      summary: Get Vault components
      description: >-
        This endpoint returns the list of Vault components in a given Vault
        document.
  /analytics/engines/vault/v3/components/{id}:
    get:
      tags:
        - Components
      summary: Get Vault component by id
      description: This endpoint returns the default settings of a Vault component.
  /analytics/engines/vault/v3/configurations:
    get:
      tags:
        - Configurations
      summary: Get Vault configurations
      description: >-
        This endpoint returns all the Vault configurations saved in the provided
        account.
  /analytics/engines/vault/v3/configurations/{id}:
    get:
      tags:
        - Configurations
      summary: Get Vault configuration by id
      description: >-
        This endpoint returns details for a Vault configuration as well as a
        list of accounts it is used in.
  /analytics/engines/vault/v3/dates:
    get:
      tags:
        - Dates
      summary: Convert Vault dates to absolute format
      description: >-
        This endpoint converts the given start and end dates in FactSet date
        format to yyyymmdd format for a Vault calculation. For more information
        on FactSet date format, please refer to the Vault API documentation
        under the 'API Documentation' section in the developer portal.
  /analytics/engines/vault/v3/documents/{path}:
    get:
      tags:
        - Documents
      summary: Get Vault documents and sub-directories in a directory
      description: >-
        This endpoint looks up all Vault documents and sub-directories in a
        given directory.
  /analytics/engines/vault/v3/frequencies:
    get:
      tags:
        - Frequencies
      summary: Get Vault frequencies
      description: >-
        This endpoint lists all the frequencies that can be applied to a Vault
        calculation.
  /analytics/engines/vault/v3/calculations:
    post:
      tags:
        - VaultCalculations
      summary: Create and Run Vault calculation
      description: "This endpoint runs the Vault calculation specified in the POST body parameters.\r\nIt can take one or more units as input.\r\n\r\nRemarks:\r\n\r\n*   Start and and end date must be within the configuration's min and max date range"
    get:
      tags:
        - VaultCalculations
      summary: Get all calculations
      description: This endpoints returns all calculation requests.
  /analytics/engines/vault/v3/calculations/{id}:
    put:
      tags:
        - VaultCalculations
      summary: Create or Update Vault calculation and run it.
      description: "This endpoint updates and run the Vault calculation specified in the PUT body parameters. This also allows creating new Vault calculations with custom ids.\r\nIt can take one or more units as input.\r\n\r\nRemarks:\r\n\r\n*   Start and and end date must be within the configuration's min and max date range"
    get:
      tags:
        - VaultCalculations
      summary: Get Vault calculation parameters by id
      description: >-
        This is the endpoint that returns the calculation parameters passed for
        a calculation.
    delete:
      tags:
        - VaultCalculations
      summary: Cancel Vault calculation by id
      description: This is the endpoint to cancel a previously submitted calculation.
  /analytics/engines/vault/v3/calculations/{id}/status:
    get:
      tags:
        - VaultCalculations
      summary: Get Vault calculation status by id
      description: "This is the endpoint to check on the progress of a previously requested calculation.\r\nIf the calculation has finished computing, the location header will point to the result url."
  /analytics/engines/vault/v3/calculations/{id}/units/{unitId}/result:
    get:
      tags:
        - VaultCalculations
      summary: Get Vault calculation result by id
      description: "This is the endpoint to get the result of a previously requested calculation.\r\nIf the calculation has finished computing, the body of the response will contain the requested document in JSON."
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/vault-api
