info:
  title: Adyen Balance Control API
paths:
  /balanceTransfer:
    post:
      tags:
        - General
      summary: Start a balance transfer
      description: >
        Starts a balance transfer request between merchant accounts. The
        following conditions must be met before you can successfully transfer
        balances:


        * The source and destination merchant accounts must be under the same
        company account and legal entity.


        * The source merchant account must have sufficient funds.


        * The source and destination merchant accounts must have at least one
        common processing currency.


        When sending multiple API requests with the same source and destination
        merchant accounts, send the requests sequentially and *not* in parallel.
        Some requests may not be processed if the requests are sent in parallel.
components: {}
