openapi: 3.1.0
info:
  x-publicVersion: true
  title: Configuration API
tags:
  - name: Platform
  - name: Account holders
  - name: Balance accounts
  - name: Payment instruments
  - name: Payment instrument groups
  - name: Transaction rules
  - name: Bank account validation
  - name: Network tokens
  - name: Grant accounts
  - name: Grant offers
  - name: PIN functionality
  - name: Card orders
  - name: Transfer routes
paths:
  /accountHolders:
    post:
      tags:
        - Account holders
      summary: Create an account holder
      description: >+
        Creates an account holder linked to a [legal
        entity](https://docs.adyen.com/api-explorer/#/legalentity/latest/post/legalEntities).

      x-addedInVersion: '1'
      x-sortIndex: 1
      x-methodName: createAccountHolder
  /accountHolders/{id}:
    get:
      tags:
        - Account holders
      summary: Get an account holder
      description: Returns an account holder.
      x-addedInVersion: '1'
      x-sortIndex: 3
      x-methodName: getAccountHolder
    patch:
      tags:
        - Account holders
      summary: Update an account holder
      description: >-
        Updates an account holder. When updating an account holder resource, if
        a parameter is not provided in the request, it is left unchanged.
      x-addedInVersion: '1'
      x-sortIndex: 2
      x-methodName: updateAccountHolder
  /accountHolders/{id}/balanceAccounts:
    get:
      tags:
        - Account holders
      summary: Get all balance accounts of an account holder
      description: >-
        Returns a paginated list of the balance accounts associated with an
        account holder. To fetch multiple pages, use the query parameters. 


        For example, to limit the page to 5 balance accounts and skip the first
        10, use `/accountHolders/{id}/balanceAccounts?limit=5&offset=10`.
      x-addedInVersion: '1'
      x-sortIndex: 4
      x-methodName: getAllBalanceAccountsOfAccountHolder
  /accountHolders/{id}/taxForms:
    get:
      tags:
        - Account holders
      summary: Get a tax form
      description: >-
        Generates a tax form for account holders operating in the US. For more
        information, refer to [Providing tax
        forms](https://docs.adyen.com/marketplaces-and-platforms/us-tax-forms/).
      x-addedInVersion: '2'
      x-sortIndex: 5
      x-methodName: getTaxForm
  /balanceAccounts:
    post:
      tags:
        - Balance accounts
      summary: Create a balance account
      description: >-
        Creates a balance account that holds the funds of the associated account
        holder.
      x-addedInVersion: '1'
      x-sortIndex: 1
      x-methodName: createBalanceAccount
  /balanceAccounts/{balanceAccountId}/sweeps:
    get:
      tags:
        - Balance accounts
      summary: Get all sweeps for a balance account
      description: >-
        Returns a list of the sweeps configured for a balance account.


        To fetch multiple pages, use the query parameters. For example, to limit
        the page to 5 sweeps and to skip the first 10, use
        `/balanceAccounts/{balanceAccountId}/sweeps?limit=5&offset=10`.
      x-addedInVersion: '2'
      x-sortIndex: 7
      x-methodName: getAllSweepsForBalanceAccount
    post:
      tags:
        - Balance accounts
      summary: Create a sweep
      description: >-
        Creates a sweep that results in moving funds from or to a balance
        account.


        A sweep pulls in or pushes out funds based on a defined schedule,
        amount, currency, and a source or a destination.
      x-addedInVersion: '2'
      x-sortIndex: 5
      x-methodName: createSweep
  /balanceAccounts/{balanceAccountId}/sweeps/{sweepId}:
    delete:
      tags:
        - Balance accounts
      summary: Delete a sweep
      description: Deletes a sweep for a balance account.
      x-addedInVersion: '2'
      x-sortIndex: 9
      x-methodName: deleteSweep
    get:
      tags:
        - Balance accounts
      summary: Get a sweep
      description: Returns a sweep.
      x-addedInVersion: '2'
      x-sortIndex: 8
      x-methodName: getSweep
    patch:
      tags:
        - Balance accounts
      summary: Update a sweep
      description: >-
        Updates a sweep. When updating a sweep resource, note that if a request
        parameter is not provided, the parameter is left unchanged.
      x-addedInVersion: '2'
      x-sortIndex: 6
      x-methodName: updateSweep
  /balanceAccounts/{id}:
    get:
      tags:
        - Balance accounts
      summary: Get a balance account
      description: >-
        Returns a balance account and its balances for the default currency and
        other currencies with a non-zero balance.
      x-addedInVersion: '1'
      x-sortIndex: 3
      x-methodName: getBalanceAccount
    patch:
      tags:
        - Balance accounts
      summary: Update a balance account
      description: Updates a balance account.
      x-addedInVersion: '1'
      x-sortIndex: 2
      x-methodName: updateBalanceAccount
  /balanceAccounts/{id}/paymentInstruments:
    get:
      tags:
        - Balance accounts
      summary: Get payment instruments linked to a balance account
      description: >-
        Returns a paginated list of the payment instruments associated with a
        balance account. 


        To fetch multiple pages, use the query parameters.For example, to limit
        the page to 3 payment instruments which are in active status and to skip
        the first 6, use
        `/balanceAccounts/{id}/paymentInstruments?limit=3&offset=6&status=active`.
      x-addedInVersion: '1'
      x-sortIndex: 4
      x-methodName: getPaymentInstrumentsLinkedToBalanceAccount
  /balancePlatforms/{id}:
    get:
      tags:
        - Platform
      summary: Get a balance platform
      description: Returns a balance platform.
      x-addedInVersion: '1'
      x-sortIndex: 1
      x-methodName: getBalancePlatform
  /balancePlatforms/{id}/accountHolders:
    get:
      tags:
        - Platform
      summary: Get all account holders under a balance platform
      description: >-
        Returns a paginated list of all the account holders that belong to the
        balance platform. To fetch multiple pages, use the query parameters. 


        For example, to limit the page to 5 account holders and to skip the
        first 20, use `/balancePlatforms/{id}/accountHolders?limit=5&offset=20`.
      x-addedInVersion: '1'
      x-sortIndex: 2
      x-methodName: getAllAccountHoldersUnderBalancePlatform
  /cardorders:
    get:
      tags:
        - Card orders
      summary: Get a list of card orders
      description: Returns a paginated list of card orders.
      x-addedInVersion: '1'
      x-sortIndex: 1
      x-methodName: listCardOrders
  /cardorders/{id}/items:
    get:
      tags:
        - Card orders
      summary: Get card order items
      description: Returns the item list of a specific card order.
      x-addedInVersion: '1'
      x-sortIndex: 2
      x-methodName: getCardOrderItems
  /grantAccounts/{id}:
    get:
      tags:
        - Grant accounts
      summary: Get a grant account
      description: >-
        Returns the details of the [grant
        account](https://docs.adyen.com/marketplaces-and-platforms/capital#grant-account).
      x-addedInVersion: '1'
      x-sortIndex: 1
      x-methodName: getGrantAccount
  /grantOffers:
    get:
      tags:
        - Grant offers
      summary: Get all available grant offers
      description: >-
        Returns a list of all [grant
        offers](https://docs.adyen.com/marketplaces-and-platforms/capital#grant-offers)
        available for `accountHolderId` specified as a query parameter.
      x-addedInVersion: '2'
      x-sortIndex: 1
      x-methodName: getAllAvailableGrantOffers
  /grantOffers/{grantOfferId}:
    get:
      tags:
        - Grant offers
      summary: Get a grant offer
      description: Returns the details of a single grant offer.
      x-addedInVersion: '2'
      x-sortIndex: 1
      x-methodName: getGrantOffer
  /networkTokens/{networkTokenId}:
    get:
      tags:
        - Network tokens
      summary: Get a network token
      description: Returns the details of a network token.
      x-addedInVersion: '1'
      x-sortIndex: 1
      x-methodName: getNetworkToken
    patch:
      tags:
        - Network tokens
      summary: Update a network token
      description: Updates the status of the network token.
      x-addedInVersion: '1'
      x-sortIndex: 2
      x-methodName: updateNetworkToken
  /paymentInstrumentGroups:
    post:
      tags:
        - Payment instrument groups
      summary: Create a payment instrument group
      description: >-
        Creates a payment instrument group to associate and group payment
        instrument resources together. You can apply a transaction rule to a
        payment instrument group.
      x-addedInVersion: '1'
      x-sortIndex: 1
      x-methodName: createPaymentInstrumentGroup
  /paymentInstrumentGroups/{id}:
    get:
      tags:
        - Payment instrument groups
      summary: Get a payment instrument group
      description: Returns the details of a payment instrument group.
      x-addedInVersion: '1'
      x-sortIndex: 2
      x-methodName: getPaymentInstrumentGroup
  /paymentInstrumentGroups/{id}/transactionRules:
    get:
      tags:
        - Payment instrument groups
      summary: Get all transaction rules for a payment instrument group
      description: >-
        Returns a list of all the transaction rules associated with a payment
        instrument group.
      x-addedInVersion: '1'
      x-sortIndex: 3
      x-methodName: getAllTransactionRulesForPaymentInstrumentGroup
  /paymentInstruments:
    post:
      tags:
        - Payment instruments
      summary: Create a payment instrument
      description: >-
        Creates a payment instrument to issue a physical card, a virtual card,
        or a business account to your user.

         For more information, refer to [Issue cards](https://docs.adyen.com/issuing/create-cards) or [Issue business accounts](https://docs.adyen.com/marketplaces-and-platforms/business-accounts).
      x-addedInVersion: '1'
      x-sortIndex: 11
      x-methodName: createPaymentInstrument
  /paymentInstruments/{id}:
    get:
      tags:
        - Payment instruments
      summary: Get a payment instrument
      description: Returns the details of a payment instrument.
      x-addedInVersion: '1'
      x-sortIndex: 13
      x-methodName: getPaymentInstrument
    patch:
      tags:
        - Payment instruments
      summary: Update a payment instrument
      description: >-
        Updates a payment instrument. Once a payment instrument is already
        active, you can only update its status. However, for cards created with
        **inactive** status, you can still update the balance account associated
        with the card.
      x-addedInVersion: '1'
      x-sortIndex: 12
      x-methodName: updatePaymentInstrument
  /paymentInstruments/{id}/networkTokens:
    get:
      tags:
        - Payment instruments
      summary: List network tokens
      description: List the network tokens connected to a payment instrument.
      x-addedInVersion: '1'
      x-sortIndex: 15
      x-methodName: listNetworkTokens
  /paymentInstruments/{id}/reveal:
    get:
      tags:
        - Payment instruments
      summary: Get the PAN of a payment instrument
      description: >-
        Returns the primary account number (PAN) of a payment instrument.


        To make this request, your API credential must have the following
        [role](https://docs.adyen.com/issuing/manage-access/api-credentials-web-service#api-permissions):


        * Balance Platform BCL PCI role
      x-addedInVersion: '1'
      x-sortIndex: 14
      x-methodName: getPanOfPaymentInstrument
  /paymentInstruments/{id}/transactionRules:
    get:
      tags:
        - Payment instruments
      summary: Get all transaction rules for a payment instrument
      description: >-
        Returns a list of transaction rules associated with a payment
        instrument.
      x-addedInVersion: '1'
      x-sortIndex: 14
      x-methodName: getAllTransactionRulesForPaymentInstrument
  /pins/change:
    post:
      tags:
        - PIN functionality
      summary: Change Pin
      description: Change Pin
      x-addedInVersion: '1'
      x-sortIndex: 2
      x-methodName: changePin
  /pins/publicKey:
    get:
      tags:
        - PIN functionality
      summary: Get RSA publicKey
      description: Get RSA publicKey
      x-addedInVersion: '1'
      x-sortIndex: 1
      x-methodName: getRsaPublickey
  /pins/reveal:
    post:
      tags:
        - PIN functionality
      summary: Reveal Pin
      description: Reveal Pin
      x-addedInVersion: '1'
      x-sortIndex: 2
      x-methodName: revealPin
  /transactionRules:
    post:
      tags:
        - Transaction rules
      summary: Create a transaction rule
      description: >-
        Creates a [transaction
        rule](https://docs.adyen.com/issuing/transaction-rules). When your user
        makes a transaction with their Adyen-issued card, the transaction is
        allowed or declined based on the conditions and outcome defined in the
        transaction rule. You can apply the transaction rule to several cards,
        such as all the cards in your platform, or to a specific card. For use
        cases, see
        [examples](https://docs.adyen.com/issuing/transaction-rules/examples).
      x-addedInVersion: '1'
      x-sortIndex: 1
      x-methodName: createTransactionRule
  /transactionRules/{transactionRuleId}:
    delete:
      tags:
        - Transaction rules
      summary: Delete a transaction rule
      description: Deletes a transaction rule.
      x-addedInVersion: '1'
      x-sortIndex: 5
      x-methodName: deleteTransactionRule
    get:
      tags:
        - Transaction rules
      summary: Get a transaction rule
      description: Returns the details of a transaction rule.
      x-addedInVersion: '1'
      x-sortIndex: 2
      x-methodName: getTransactionRule
    patch:
      tags:
        - Transaction rules
      summary: Update a transaction rule
      description: >-
        Updates a transaction rule. 


        * To update only the status of a transaction rule, send only the
        `status` parameter. All other parameters not provided in the request are
        left unchanged.


        * When updating any other parameter, you need to send all existing
        resource parameters. If you omit a parameter in the request, that
        parameter is removed from the resource.
      x-addedInVersion: '1'
      x-sortIndex: 3
      x-methodName: updateTransactionRule
  /transferRoutes/calculate:
    post:
      tags:
        - Transfer routes
      summary: Calculate transfer routes
      description: >-
        Returns available transfer routes based on a combination of transfer
        `country`, `currency`, `counterparty`, and `priorities`. Use this
        endpoint to find optimal transfer priorities and associated requirements
        before you [make a
        transfer](https://docs.adyen.com/api-explorer/transfers/latest/post/transfers).
      x-addedInVersion: '1'
      x-sortIndex: 1
      x-methodName: calculateTransferRoutes
  /validateBankAccountIdentification:
    post:
      tags:
        - Bank account validation
      summary: Validate a bank account
      description: >-
        Validates bank account identification details. You can use this endpoint
        to validate bank account details before you [make a
        transfer](https://docs.adyen.com/api-explorer/transfers/latest/post/transfers)
        or [create a transfer
        instrument](https://docs.adyen.com/api-explorer/legalentity/latest/post/transferInstruments).
      x-addedInVersion: '1'
      x-sortIndex: 1
      x-methodName: validateBankAccountIdentification
