info:
  title: Adyen Data Protection API
paths:
  /requestSubjectErasure:
    post:
      tags:
        - Submit
        - Subject
        - Erasure
        - Request.
        - Subject
        - Erasure
      summary: Submit a Subject Erasure Request.
      description: >-
        Sends the PSP reference containing the shopper data that should be
        deleted.
components: null
