info:
  title: Disputes API
paths:
  /acceptDispute:
    post:
      tags:
        - General
      summary: Accept a dispute
      description: Accepts a specific dispute.
  /defendDispute:
    post:
      tags:
        - General
      summary: Defend a dispute
      description: Defends a specific dispute.
  /deleteDisputeDefenseDocument:
    post:
      tags:
        - General
      summary: Delete a defense document
      description: Deletes a specific dispute defense document that was supplied earlier.
  /retrieveApplicableDefenseReasons:
    post:
      tags:
        - General
      summary: Get applicable defense reasons
      description: >-
        Returns a list of all applicable defense reasons to defend a specific
        dispute.
  /supplyDefenseDocument:
    post:
      tags:
        - General
      summary: Supply a defense document
      description: Supplies a specific dispute defense document.
components: {}
