info:
  title: Disputes API
paths:
  /acceptDispute:
    post:
      tags:
        - Accept
        - Dispute
        - Dispute
      summary: Accept a dispute
      description: Accepts a specific dispute.
  /defendDispute:
    post:
      tags:
        - Defend
        - Dispute
        - Dispute
      summary: Defend a dispute
      description: Defends a specific dispute.
  /deleteDisputeDefenseDocument:
    post:
      tags:
        - Delete
        - Defense
        - Document
        - Dispute
        - Defense
        - Document
      summary: Delete a defense document
      description: Deletes a specific dispute defense document that was supplied earlier.
  /retrieveApplicableDefenseReasons:
    post:
      tags:
        - Get
        - Applicable
        - Defense
        - Reasons
        - Dispute
        - Defense
        - Document
        - Applicable
        - Reasons
      summary: Get applicable defense reasons
      description: >-
        Returns a list of all applicable defense reasons to defend a specific
        dispute.
  /supplyDefenseDocument:
    post:
      tags:
        - Supply
        - Defense
        - Document
        - Dispute
        - Defense
        - Document
        - Applicable
        - Reasons
      summary: Supply a defense document
      description: Supplies a specific dispute defense document.
components: null
