openapi: 3.1.0
info:
  x-publicVersion: true
  title: Disputes API
tags:
  - name: General
paths:
  /acceptDispute:
    post:
      tags:
        - General
      summary: Accept a dispute
      description: Accepts a specific dispute.
      x-addedInVersion: '1'
      x-sortIndex: 1
      x-methodName: acceptDispute
  /defendDispute:
    post:
      tags:
        - General
      summary: Defend a dispute
      description: Defends a specific dispute.
      x-addedInVersion: '1'
      x-sortIndex: 1
      x-methodName: defendDispute
  /deleteDisputeDefenseDocument:
    post:
      tags:
        - General
      summary: Delete a defense document
      description: Deletes a specific dispute defense document that was supplied earlier.
      x-addedInVersion: '1'
      x-sortIndex: 1
      x-methodName: deleteDisputeDefenseDocument
  /retrieveApplicableDefenseReasons:
    post:
      tags:
        - General
      summary: Get applicable defense reasons
      description: >-
        Returns a list of all applicable defense reasons to defend a specific
        dispute.
      x-addedInVersion: '1'
      x-sortIndex: 1
      x-methodName: retrieveApplicableDefenseReasons
  /supplyDefenseDocument:
    post:
      tags:
        - General
      summary: Supply a defense document
      description: Supplies a specific dispute defense document.
      x-addedInVersion: '1'
      x-sortIndex: 1
      x-methodName: supplyDefenseDocument
