openapi: 3.1.0
info:
  x-publicVersion: true
  title: Fund API
  x-timestamp: '2023-05-30T15:27:19Z'
x-groups:
  - General
  - Migration
tags:
  - name: General
paths:
  /accountHolderBalance:
    post:
      tags:
        - Get
        - The
        - Balances
        - Of
        - An
        - Account
        - Holder
        - Holder
        - Balance
      summary: Get the balances of an account holder
      description: >-
        Returns the account balances of an account holder. An account's balances
        are organized according by currencies. This mean that an account may
        have multiple balances: one for each currency.
  /accountHolderTransactionList:
    post:
      tags:
        - Get
        - List
        - Of
        - Transactions
        - Holder
        - Balance
        - Transaction
        - List
      summary: Get a list of transactions
      description: >-
        Returns a list of transactions for an account holder's accounts. You can
        specify the accounts and transaction statuses to be included on the
        list. The call returns a maximum of 50 transactions for each account. To
        retrieve all transactions, you must make another call with the 'page'
        value incremented. Transactions are listed in chronological order, with
        the most recent transaction first.
  /debitAccountHolder:
    post:
      tags:
        - Send
        - Direct
        - Debit
        - Request
        - Holder
        - Balance
        - Transaction
        - List
        - Account
      summary: Send a direct debit request
      description: >-
        Sends a direct debit request to an account holder's bank account. If the
        direct debit is successful, the funds are settled in the accounts
        specified in the split instructions. Adyen sends the result of the
        direct debit in a
        [`DIRECT_DEBIT_INITIATED`](https://docs.adyen.com/api-explorer/#/NotificationService/latest/post/DIRECT_DEBIT_INITIATED)
        notification webhook.

         To learn more about direct debits, see [Top up accounts](https://docs.adyen.com/marketplaces-and-platforms/classic/top-up-accounts).
  /payoutAccountHolder:
    post:
      tags:
        - Pay
        - Out
        - From
        - An
        - Account
        - To
        - The
        - Holder
        - Holder
        - Balance
        - Transaction
        - List
        - Account
      summary: Pay out from an account to the account holder
      description: >-
        Pays out a specified amount from an account to the bank account of
        account holder.
  /refundFundsTransfer:
    post:
      tags:
        - Refund
        - Funds
        - Transfer
        - Holder
        - Balance
        - Transaction
        - List
        - Account
        - Funds
        - Transfer
      summary: Refund a funds transfer
      description: >-
        Refunds funds transferred from one account to another. Both accounts
        must be in the same platform, but can have different account holders. 
  /refundNotPaidOutTransfers:
    post:
      tags:
        - Refund
        - All
        - Transactions
        - Of
        - An
        - Account
        - Since
        - The
        - Most
        - Recent
        - Payout
        - Holder
        - Balance
        - Transaction
        - List
        - Account
        - Funds
        - Transfer
        - Not
        - Paid
        - Out
        - Transfers
      summary: Refund all transactions of an account since the most recent payout
      description: >-
        Refunds all the transactions of an account that have taken place since
        the most recent payout. This request is on a account basis (as opposed
        to a payment basis), so only the portion of the payment that was made to
        the specified account is refunded. The commissions, fees, and payments
        to other accounts remain in the accounts to which they were sent as
        designated by the original payment's split details.
  /setupBeneficiary:
    post:
      tags:
        - Designate
        - Beneficiary
        - Account
        - And
        - Transfer
        - The
        - Benefactor's
        - Current
        - Balance
        - Holder
        - Balance
        - Transaction
        - List
        - Account
        - Funds
        - Transfer
        - Not
        - Paid
        - Out
        - Transfers
        - Beneficiary
      summary: >-
        Designate a beneficiary account and transfer the benefactor's current
        balance
      description: >-
        Defines a benefactor and a beneficiary relationship between two
        accounts. At the time of benefactor/beneficiary setup, the funds in the
        benefactor account are transferred to the beneficiary account, and any
        further payments to the benefactor account are automatically sent to the
        beneficiary account. A series of benefactor/beneficiaries may not exceed
        four beneficiaries and may not have a cycle in it.
  /transferFunds:
    post:
      tags:
        - Transfer
        - Funds
        - Between
        - Platform
        - Accounts
        - Holder
        - Balance
        - Transaction
        - List
        - Account
        - Funds
        - Transfer
        - Not
        - Paid
        - Out
        - Transfers
        - Beneficiary
      summary: Transfer funds between platform accounts
      description: >-
        Transfers funds from one account to another account. Both accounts must
        be in the same platform, but can have different account holders. The
        transfer must include a transfer code, which should be determined by the
        platform, in compliance
