openapi: 3.1.0
info:
  x-publicVersion: true
  title: Notification Configuration API
  x-timestamp: '2023-05-30T15:27:19Z'
x-groups:
  - General
tags:
  - name: General
paths:
  /createNotificationConfiguration:
    post:
      tags:
        - General
      summary: Subscribe to notifications
      description: >-
        Creates a subscription to notifications informing you of events on your
        platform. After the subscription is created, the events specified in the
        configuration will be sent to the URL specified in the configuration.
        Subscriptions must be configured on a per-event basis (as opposed to,
        for example, a per-account holder basis), so all event notifications of
        a marketplace and of a given type will be sent to the same endpoint(s).
        A marketplace may have multiple endpoints if desired; an event
        notification may be sent to as many or as few different endpoints as
        configured.
      x-groupName: General
      x-sortIndex: 1
      x-methodName: createNotificationConfiguration
  /deleteNotificationConfigurations:
    post:
      tags:
        - General
      summary: Delete a notification subscription configuration
      description: >-
        Deletes an existing notification subscription configuration. After the
        subscription is deleted, no further event notifications will be sent to
        the URL defined in the subscription.
      x-groupName: General
      x-sortIndex: 6
      x-methodName: deleteNotificationConfigurations
  /getNotificationConfiguration:
    post:
      tags:
        - General
      summary: Get a notification subscription configuration
      description: Returns the details of the configuration of a notification subscription.
      x-groupName: General
      x-sortIndex: 2
      x-methodName: getNotificationConfiguration
  /getNotificationConfigurationList:
    post:
      tags:
        - General
      summary: Get a list of notification subscription configurations
      description: >-
        Returns the details of the configurations of all of the notification
        subscriptions in the platform of the executing user.
      x-groupName: General
      x-sortIndex: 3
      x-methodName: getNotificationConfigurationList
  /testNotificationConfiguration:
    post:
      tags:
        - General
      summary: Test a notification configuration
      description: >-
        Tests an existing notification subscription configuration. For each
        event type specified, a test notification will be generated and sent to
        the URL configured in the subscription specified.
      x-groupName: General
      x-sortIndex: 4
      x-methodName: testNotificationConfiguration
  /updateNotificationConfiguration:
    post:
      tags:
        - General
      summary: Update a notification subscription configuration
      description: >-
        Updates an existing notification subscription configuration. If you are
        updating the event types, you must provide all event types, otherwise
        the previous event type configuration will be overwritten.
      x-groupName: General
      x-sortIndex: 5
      x-methodName: updateNotificationConfiguration
