info:
  title: Adyen Recurring API
paths:
  /createPermit:
    post:
      tags:
        - General
      summary: Create new permits linked to a recurring contract.
      description: >-
        Create permits for a recurring contract, including support for defining
        restrictions.
  /disable:
    post:
      tags:
        - General
      summary: Disable stored payment details
      description: >-
        Disables stored payment details to stop charging a shopper with this
        particular recurring detail ID.


        For more information, refer to [Disable stored
        details](https://docs.adyen.com/classic-integration/recurring-payments/disable-stored-details/).
  /disablePermit:
    post:
      tags:
        - General
      summary: Disable an existing permit.
      description: >-
        Disable a permit that was previously linked to a
        recurringDetailReference.
  /listRecurringDetails:
    post:
      tags:
        - General
      summary: Get stored payment details
      description: >-
        Lists the stored payment details for a shopper, if there are any
        available. The recurring detail ID can be used with a regular
        authorisation request to charge the shopper. A summary of the payment
        detail is returned for presentation to the shopper.


        For more information, refer to [Retrieve stored
        details](https://docs.adyen.com/classic-integration/recurring-payments/retrieve-stored-details/).
  /notifyShopper:
    post:
      tags:
        - General
      summary: Ask issuer to notify the shopper
      description: >-
        Sends a request to the issuer so they can inform the shopper about the
        upcoming recurring payment. This endpoint is used only for local
        acquiring in India. For more information, refer to [Recurring card
        payments in
        India](https://docs.adyen.com/payment-methods/cards/cards-recurring-india).
  /scheduleAccountUpdater:
    post:
      tags:
        - General
      summary: Schedule running the Account Updater
      description: >-
        When making the API call, you can submit either the credit card
        information, or the recurring detail reference and the shopper
        reference:

        * If the card information is provided, all the sub-fields for `card` are
        mandatory.

        * If the recurring detail reference is provided, the fields for
        `shopperReference` and `selectedRecurringDetailReference` are mandatory.
components: {}
