info:
  title: Adyen Stored Value API
paths:
  /changeStatus:
    post:
      tags:
        - Changes
        - The
        - Status
        - Of
        - Payment
        - Method.
        - Status
      summary: Changes the status of the payment method.
      description: >-
        Changes the status of the provided payment method to the specified
        status.
  /checkBalance:
    post:
      tags:
        - Checks
        - The
        - Balance.
        - Status
        - Balance
      summary: Checks the balance.
      description: Checks the balance of the provided payment method.
  /issue:
    post:
      tags:
        - Issues
        - New
        - Card.
        - Status
        - Balance
        - Issue
      summary: Issues a new card.
      description: Issues a new card of the given payment method.
  /load:
    post:
      tags:
        - Loads
        - The
        - Payment
        - Method.
        - Status
        - Balance
        - Issue
        - Load
      summary: Loads the payment method.
      description: Loads the payment method with the specified funds.
  /mergeBalance:
    post:
      tags:
        - Merge
        - The
        - Balance
        - Of
        - Two
        - Cards.
        - Status
        - Balance
        - Issue
        - Load
      summary: Merge the balance of two cards.
      description: >-
        Increases the balance of the paymentmethod by the full amount left on
        the source paymentmethod
  /voidTransaction:
    post:
      tags:
        - Voids
        - Transaction.
        - Status
        - Balance
        - Issue
        - Load
        - Transaction
      summary: Voids a transaction.
      description: Voids the referenced stored value transaction.
components: null
