openapi: 3.1.0
info:
  x-publicVersion: true
  title: Adyen Stored Value API
x-groups:
  - General
tags:
  - name: General
paths:
  /changeStatus:
    post:
      tags:
        - General
      summary: Changes the status of the payment method.
      description: >-
        Changes the status of the provided payment method to the specified
        status.
      x-groupName: General
      x-sortIndex: 0
      x-methodName: changeStatus
  /checkBalance:
    post:
      tags:
        - General
      summary: Checks the balance.
      description: Checks the balance of the provided payment method.
      x-groupName: General
      x-sortIndex: 0
      x-methodName: checkBalance
  /issue:
    post:
      tags:
        - General
      summary: Issues a new card.
      description: Issues a new card of the given payment method.
      x-groupName: General
      x-sortIndex: 0
      x-methodName: issue
  /load:
    post:
      tags:
        - General
      summary: Loads the payment method.
      description: Loads the payment method with the specified funds.
      x-groupName: General
      x-sortIndex: 0
      x-methodName: load
  /mergeBalance:
    post:
      tags:
        - General
      summary: Merge the balance of two cards.
      description: >-
        Increases the balance of the paymentmethod by the full amount left on
        the source paymentmethod
      x-groupName: General
      x-sortIndex: 0
      x-methodName: mergeBalance
  /voidTransaction:
    post:
      tags:
        - General
      summary: Voids a transaction.
      description: Voids the referenced stored value transaction.
      x-groupName: General
      x-sortIndex: 0
      x-methodName: voidTransaction
