info:
  title: Adyen Stored Value API
paths:
  /changeStatus:
    post:
      tags:
        - General
      summary: Changes the status of the payment method.
      description: >-
        Changes the status of the provided payment method to the specified
        status.
  /checkBalance:
    post:
      tags:
        - General
      summary: Checks the balance.
      description: Checks the balance of the provided payment method.
  /issue:
    post:
      tags:
        - General
      summary: Issues a new card.
      description: Issues a new card of the given payment method.
  /load:
    post:
      tags:
        - General
      summary: Loads the payment method.
      description: Loads the payment method with the specified funds.
  /mergeBalance:
    post:
      tags:
        - General
      summary: Merge the balance of two cards.
      description: >-
        Increases the balance of the paymentmethod by the full amount left on
        the source paymentmethod
  /voidTransaction:
    post:
      tags:
        - General
      summary: Voids a transaction.
      description: Voids the referenced stored value transaction.
components: {}
