info:
  title: Adyen Test Cards API
paths:
  /createTestCardRanges:
    post:
      tags:
        - General
      summary: Creates one or more test card ranges.
      description: Creates one or more test card ranges.
components: {}
