name: Netlify
description: >-
  Netlify is a remote-first cloud computing company that offers a development
  platform that includes build, deploy, and serverless backend services for web
  applications and dynamic websites.
url: https://raw.githubusercontent.com/apis-json/artisanal/main/apis/netlify.yml
created: 2024/04/14
modified: 2024/04/14
specificationVersion: '0.16'
tags: []
apis:
  - name: Netlify API
    description: >-
      Netlify is a hosting service for the programmable web. It understands your
      documents and provides an API to handle atomic deploys of websites, manage
      form submissions, inject JavaScript snippets, and much more. This is a
      REST-style API that uses JSON for serialization and OAuth 2 for
      authentication.
    tags: []
    overlays:
      - type: APIs.io Search
        url: >-
          overlays/https://open-api.netlify.com/6dac5474-6daf-41e6-8a14-6d9bcb8aca52-openapi-search.yml
    aid: netlify:netlify-api
maintainers:
  - FN: API Evangelist
    url: http://apievangelist.com
    email: info@apievangelist.com
aid: netlify
