openapi: 3.0.0
info:
  title: Abandoned Cart Emails
tags:
  - name: Abandoned Cart Emails
  - name: Template settings
paths:
  /marketing/abandoned-cart-emails:
    get:
      description: An array of abandoned cart emails pertaining to a store.
      tags:
        - Abandoned Cart Emails
      summary: Get all abandoned cart email templates
    post:
      summary: Create abandoned cart email template
      tags:
        - Abandoned Cart Emails
      description: Create an Abandoned Cart Email template.
    parameters:
      - null
  /marketing/abandoned-cart-emails/{id}:
    get:
      summary: Get an email template
      description: Get a single Abandoned Cart Email template.
      tags:
        - Abandoned Cart Emails
    put:
      summary: Update an email template
      description: Update an email template.
      tags:
        - Abandoned Cart Emails
    delete:
      tags:
        - Abandoned Cart Emails
      description: Delete Abandoned Cart Email template.
      summary: Delete email template
    parameters:
      - null
      - null
  /marketing/abandoned-cart-emails/default:
    get:
      summary: Get default email template
      description: Return default Abandoned Cart Email template.
      tags:
        - Abandoned Cart Emails
    parameters:
      - null
  /marketing/abandoned-cart-emails/settings:
    get:
      summary: Get email template settings
      tags:
        - Template settings
      description: Read Abandoned Cart Email Template settings.
    put:
      summary: Update email template settings
      tags:
        - Template settings
      description: Update Abandoned Cart Email template settings.
    parameters:
      - nu
