openapi: 3.0.3
info:
  title: Catalog - Category Trees
  version: ''
tags:
  - name: Category Trees
  - name: Categories
paths:
  /catalog/trees/categories:
    get:
      summary: Get All Categories
      description: |-
        Returns a list of categories. 

        To get a specific category in a tree, provide a category ID.
      tags:
        - Categories
    post:
      summary: Create Categories
      description: |-
        Creates new categories. 

        Creating a category requires:
         - `name`
         - `tree_id` or `parent_id` 
      tags:
        - Categories
    put:
      summary: Update Categories
      description: |-
        Updates existing categories. 

         To update a specific category in a tree, provide a category id.
      tags:
        - Categories
    delete:
      summary: Delete Categories
      description: |-
        Deletes categories. 

        To delete a specific category in a tree, provide a category ID.
      tags:
        - Categories
    parameters:
      - null
  /catalog/trees:
    get:
      summary: Get All Category Trees
      description: Returns a list of *Category Trees*.
      tags:
        - Category Trees
    put:
      summary: Upsert Category Trees
      description: >
        Upserts *Category Trees*. 


        This single endpoint updates and creates category trees. If a tree
        object contains an ID, it is processed as an update operation using that
        ID. If you do not provide an ID, a new tree is created. The category
        tree `name` field is required to create trees, but is not required on
        the update.


        **Usage Notes**

        * `channel_id` is required to create a *Category Tree*. You can assign
        one `channel_id` to one category tree.
      tags:
        - Category Trees
    delete:
      summary: Delete Category Trees
      description: Deletes *Category Trees*. A filter must be supplied with the endpoint.
      tags:
        - Category Trees
    parameters:
      - null
  /catalog/trees/{tree_id}/categories:
    get:
      summary: Get a Category Tree
      description: Returns a *Category Tree*.
      tags:
        - Category Trees
    parameters:
      - null
      - nu
