openapi: 3.0.3
info:
  title: Catalog - Product Variants
  version: ''
tags:
  - name: Batch metafields
  - name: Product Variants
  - name: Variants (Batch)
  - name: Metafields
  - name: Images
paths:
  /catalog/products/{product_id}/variants:
    get:
      tags:
        - Product Variants
      summary: Get All Product Variants
      description: >-
        Returns a list of product *Variants*. Optional parameters can be passed
        in.
    post:
      tags:
        - Product Variants
      summary: Create a Product Variant
      description: >-
        Creates a *Product Variant*.


        **Required Fields**

        * sku

        * option_values


        **Read-Only Fields**

        * id


        **Limits**

        * 600 SKUs per product limit.

        * 255 characters SKU length limit.


        Variants need to be created one at a time using this endpoint. To use a
        variant array, create products, and variants in the same call use the
        [Create Products](/docs/rest-catalog/products#create-a-product) endpoint
        during the initial product creation.
    parameters:
      - null
      - null
  /catalog/products/{product_id}/variants/{variant_id}:
    get:
      tags:
        - Product Variants
      summary: Get a Product Variant
      description: >-
        Returns a single product *Variant*. Optional parameters can be passed
        in.
    put:
      tags:
        - Product Variants
      summary: Update a Product Variant
      description: Updates a product *Variant*.
    delete:
      tags:
        - Product Variants
      summary: Delete a Product Variant
      description: Deletes a product *Variant*.
    parameters:
      - null
      - null
      - null
  /catalog/products/{product_id}/variants/{variant_id}/metafields:
    get:
      tags:
        - Metafields
      summary: Get Product Variant Metafields
      description: >-
        Returns a list of product variant *Metafields*. Optional parameters can
        be passed in.
    post:
      tags:
        - Metafields
      summary: Create a Product Variant Metafield
      description: >-
        Creates a product variant *Metafield*.


        **Required Fields:**

        * permission_set

        * namespace

        * key

        * value


        **Read-Only Fields**

        * id


        **Note:** The maxiumum number of metafields allowed on each order,
        product, category, variant, or brand is 250 per client ID. For more
        information, see [Platform
        Limits](https://support.bigcommerce.com/s/article/Platform-Limits) in
        the Help Center.
    parameters:
      - null
      - null
      - null
  /catalog/products/{product_id}/variants/{variant_id}/metafields/{metafield_id}:
    get:
      tags:
        - Metafields
      summary: Get a Product Variant Metafields
      description: >-
        Returns a single product variant *Metafield*. Optional parameters can be
        passed in.
    put:
      tags:
        - Metafields
      summary: Update Product Variant Metafields
      description: "Updates a product variant *Metafield*.\n\n**Required Fields:**\n* none\n\n**Read-Only Fields**\n* id\n* These fields can only be modified by the app (API credentials) that created the metafield:\n\t* namespace\n\t* key\n\t* permission_set\n\n**Usage Notes**\n* Attempting to modify `namespace`, `key`, and `permission_set` fields using a client ID different from the one used to create those metafields will result in a 403 error message. "
    delete:
      tags:
        - Metafields
      summary: Delete a Product Variant Metafield
      description: Deletes a product variant *Metafield*.
    parameters:
      - null
      - null
      - null
      - null
  /catalog/products/{product_id}/variants/{variant_id}/image:
    post:
      tags:
        - Images
      summary: Create a Product Variant Image
      description: >-
        Creates a *Variant Image*.


        Only one image can be explicitly associated with a Variant. If the
        Variant already has an associated image, overwrites the existing Variant
        Image.


        The image displays on the storefront when the Variant is selected.

         **Required Fields**
        - image_file: Form posts. Files larger than 1 MB are not accepted

        - image_url: Any publicly available URL
    parameters:
      - null
      - null
      - null
  /catalog/variants:
    get:
      tags:
        - Variants (Batch)
      summary: Get All Variants
      description: >-
        Returns a list of all variants in your catalog. Optional parameters can
        be passed in.
    put:
      tags:
        - Variants (Batch)
      summary: Update Variants (Batch)
      description: >-
        Updates a batch of `variant` objects. Currently the limit is 50 variants
        however this is subject to change.


        **Required Fields**


        To update an existing variant:

        * id (variant ID)


        To create a new variant:

        * product_id

        * sku

        * option_values
          - id (option_value ID - Example: 146)
          - option_id (Option ID - Example: 151)
    parameters:
      - null
  /catalog/variants/metafields:
    get:
      summary: Get All Product Variant Metafields
      tags:
        - Batch metafields
      description: Get all variant metafields.
    post:
      summary: Create multiple Metafields
      tags:
        - Batch metafields
      description: Create multiple metafields.
    put:
      summary: Update multiple Metafields
      tags:
        - Batch metafields
      description: Create multiple metafields.
    delete:
      summary: Delete All Metafields
      tags:
        - Batch metafields
      description: Delete all variant metafield
