openapi: 3.0.1
info:
  title: Price Lists
  version: ''
tags:
  - name: Price Lists
  - name: Price Lists Assignments
  - name: Price Lists Records
paths:
  /pricelists:
    parameters:
      - null
    get:
      tags:
        - Price Lists
      summary: Get All Price Lists
      description: Returns a list of *Price Lists*. Optional parameters can be passed in.
    post:
      tags:
        - Price Lists
      summary: Create a Price List
      description: |-
        Creates a *Price List*.

        **Required Fields**
        * name
    delete:
      tags:
        - Price Lists
      summary: Delete All Price Lists
      description: >-
        Deletes a *Price List*. All associated price records are also removed.
        Optional parameters can be passed in.
  /pricelists/{price_list_id}:
    parameters:
      - null
    get:
      tags:
        - Price Lists
      summary: Get a Price List
      description: ' Returns a single *Price List*.'
    put:
      tags:
        - Price Lists
      summary: Update a Price List
      description: Updates a *Price List*.
    delete:
      tags:
        - Price Lists
      summary: Delete a Price List
      description: |-
        Deletes a *Price List*. All associated price records are also removed.
        **Limits**
        * Limit of 1 concurrent request.
  /pricelists/records:
    parameters:
      - null
    put:
      tags:
        - Price Lists Records
      summary: Create Batch of Price Lists Records
      description: >-
        Creates a batch of `Price Lists Records`; may include price list records
        from more than one price list.  Concurrency limit of 1.
  /pricelists/{price_list_id}/records:
    parameters:
      - null
    get:
      tags:
        - Price Lists Records
      summary: Get All Price List Records
      description: >-
        Returns a list of *Price List Records* associated with a *Price List*.


        **Notes**

        * Supports up to 10 simultaneous GET requests. Running more than the
        allowed number of requests concurrently on the same store will result in
        a `429` status error and your additional requests will fail.

        * Store Pricelist Records data to reduce the number of calls and
        maximize performance.
    put:
      tags:
        - Price Lists Records
      summary: Upsert Price List Records
      description: >-
        Creates or updates *Price List Records*. 


        **Required Fields**

        * currency


        **Notes**

        * Batch requests support up to 1,000 items per request.

        * Up to 2 concurrent batch upsert requests are supported with this API.
        Running more than the allowed concurrent requests in parallel on the
        **same store** will cause a `429` error, and your additional requests
        will fail. You are encouraged to run requests sequentially with as many
        records per request as possible to maximize performance.

        * When updating a product with variants, or multiple SKUs, don't include
        records for the parent product SKU.
    delete:
      tags:
        - Price Lists Records
      summary: Delete a Price List Record
      description: >-
        Deletes a *Price List Record*. Deleting the records does not delete the
        Price List. Optional parameters can be passed in.
  /pricelists/{price_list_id}/records/{variant_id}:
    parameters:
      - null
    get:
      tags:
        - Price Lists Records
      summary: Get Price Records by Variant
      description: >
        Returns *Price List Records* using the variant ID. Will also contain
        currency records.


        **Notes**

        * Supports up to 40 simultaneous GET requests. Running more than the
        allowed number of requests concurrently on the same store will result in
        a `429` status error, and your additional requests will fail.

        * Store Pricelist Records data to reduce the number of calls and
        maximize performance.
  /pricelists/{price_list_id}/records/{variant_id}/{currency_code}:
    parameters:
      - null
    get:
      tags:
        - Price Lists Records
      summary: Get a Price Record by Currency Code
      description: >-
        Returns a *Price List Record* using the currency code. You can use
        optional parameters.

        **Notes**

        * Supports up to 50 simultaneous GET requests. Running more than the
        allowed number of requests concurrently on the same store will result in
        a `429` status error, and your additional requests will fail.
    put:
      tags:
        - Price Lists Records
      summary: Set Price List Record by Currency Code
      description: >-
        Creates or updates a *Price List Record* using the currency code.

        **Notes**

        * Supports up to 40 simultaneous PUT requests. Running more than the
        allowed number of requests concurrently on the same store will result in
        a `429` status error, and your additional requests will fail.
    delete:
      tags:
        - Price Lists Records
      summary: Delete a Price Record by Currency Code
      description: >-
        Deletes a *Price List Record* using the currency code.

        **Note:**

        * Supports up to 25 simultaneous DELETE requests. Running more than the
        allowed number of requests concurrently on the same store will result in
        a `429` status error, and your additional requests will fail.
  /pricelists/assignments:
    parameters:
      - null
    get:
      tags:
        - Price Lists Assignments
      summary: Get Price List Assignments
      description: >-
        Fetches an array of `Price List Assignments` matching a particular
        Customer Group and Price List and Channel.
    post:
      tags:
        - Price Lists Assignments
      description: |-
        Creates a batch of `Price List Assignments`. 
        **Note:** The batch limit for `Price List Assignments` is 25.
      summary: Create Price List Assignments
    delete:
      tags:
        - Price Lists Assignments
      summary: Delete Price List Assignments
      description: >-
        Deletes one or more `Price List Assignments` objects from BigCommerce
        using a query parameter. You must use at least one query parameter. 
  /pricelists/{price_list_id}/assignments:
    parameters:
      - null
    put:
      tags:
        - Price Lists Assignments
      description: >-
        Upsert a single `Price List Assignment` for a `Price List`.

        **Note:**

        * Supports up to 25 simultaneous PUT requests. Running more than the
        allowed number of requests concurrently on the same store will result in
        a `429` status error and your additional requests will fail.        
      summary: Upsert Price List Assignme
