openapi: 3.0.0
info:
  version: ''
  title: Shipping Providers
tags:
  - name: Shipping Provider
paths:
  /rate:
    post:
      description: >-
        Request shipping rates. BigCommerce sends a request for shipping quotes
        to the shipping provider URL. The shipping provider responds with
        shipping quotes.


        > #### Note

        > * Substitute the host and path specific to the shipping provider for
        `your_app.example.com` and `rate`. 

        > * The Send a Test Request feature is not currently supported for this
        endpoint.  
      summary: Request shipping rates
      tags:
        - Shipping Provider
  /check_connection_options:
    post:
      description: >-
        Validate connection options. BigCommerce sends a request to the shipping
        provider URL to check a merchantÊ¼s connection credentials. The shipping
        provider sends a response indicating whether a merchant has valid
        credentials. 


        > #### Note

        > * Substitute the host and path specific to the shipping provider for
        `your_app.example.com` and `check_connection_options`.  

        > * The Send a Test Request feature is not currently supported for this
        endpoint.
      summary: Validate connection options
      tags:
        - Shipping Provid
