openapi: 3.0.0
info:
  title: Store Logs V3 API
  version: ''
paths:
  /store/systemlogs:
    get:
      summary: Get System Logs
      description: 'Get system logs '
      tags:
        - System Logs
    parameters: []
tags:
  - name: System Lo
