openapi: 3.0.1
info:
  title: Subscribers
  license:
    name: ''
  version: ''
tags:
  - name: Subscribers
    description: BigCommerce Customers API Definition.
paths:
  /customers/subscribers:
    parameters:
      - null
    get:
      tags:
        - Subscribers
      summary: Get Subscribers
      description: >-
        Returns a list of *Subscribers*. Optional filter parameters can be
        passed in.
    post:
      tags:
        - Subscribers
      summary: Create a Subscriber
      description: |-
        Creates a *Subscriber*.

        **Required Fields**
        * email

        **Read Only Fields**
        * id
    delete:
      tags:
        - Subscribers
      summary: Delete Subscribers
      description: >-
        By default, it deletes all *Subscribers*. A filter should be added to
        avoid deleting all subscribers in a store.
  /customers/subscribers/{subscriber_id}:
    parameters:
      - null
    get:
      tags:
        - Subscribers
      summary: Get a Subscriber
      description: Returns a *Subscriber*.
    put:
      tags:
        - Subscribers
      summary: Update a Subscriber
      description: |-
        Updates a *Subscriber*.

        **Read Only Fields**
        * id
    delete:
      tags:
        - Subscribers
      summary: Delete a Subscriber
      description: Deletes a *Subscriber
