openapi: 3.0.0
info:
  title: Tax Settings
  version: ''
tags:
  - name: Tax Settings
paths:
  /tax/settings:
    get:
      tags:
        - Tax Settings
      summary: Get Tax Settings
      description: Retrieves global-level tax settings.
    put:
      tags:
        - Tax Settings
      summary: Update Tax Settings
      description: Updates global-level tax settings.
    parameters:
      - nu
