openapi: 3.0.0
info:
  title: Tax Properties
  version: ''
tags:
  - name: Tax Properties
  - name: Product Tax Properties
paths:
  /tax/properties:
    parameters:
      - null
    get:
      tags:
        - Tax Properties
      summary: Get Tax Properties
      description: Retrieve all tax properties defined in this store.
    put:
      tags:
        - Tax Properties
      summary: Update Tax Properties
      description: >-
        Update one or more tax properties. Only fields specified will be
        adjusted.
    post:
      tags:
        - Tax Properties
      summary: Create Tax Properties
      description: >-
        Create one or more tax properties. A **code** and a **display name**
        must be included when creating tax properties.
    delete:
      tags:
        - Tax Properties
      summary: Delete Tax Properties
      description: >-
        Delete one or multiple tax properties. A tax property must have zero
        usages within product tax properties before you can delete it.
  /tax/products/properties:
    parameters:
      - null
    get:
      tags:
        - Product Tax Properties
      summary: Get Product Tax Properties
      description: >-
        Retrieve the tax properties that are associated with one or more
        products.
    put:
      tags:
        - Product Tax Properties
      summary: Update Product Tax Properties
      description: >-
        Update the tax properties associated with one or more products. This
        operation will be additive to any tax property values already associated
        with the product, overwriting any existing tax property values.
    delete:
      tags:
        - Product Tax Properties
      summary: Delete Product Tax Properties
      description: Delete tax properties that are associated with one or more product
