openapi: 3.0.0
info:
  title: Tax Zone Check
  version: ''
tags:
  - name: Tax Zone Check
paths:
  /tax/zonecheck:
    parameters:
      - null
    post:
      tags:
        - Tax Zone Check
      summary: Check zone given an address.
      description: Check the applicable tax zone for a given address and customer grou
